== Part I.

[.heading-continuation-blurb]
Of the Faith of the Primitive Christians, and the Apostasy From it,
Traced in Some of its Successive Steps,
Until that Part of the World called Christendom was Almost Totally
Overspread with a Midnight of Darkness and Superstition.

When I consider the efficacy of faith as recorded in the Holy Scriptures,
whether among the elders who had not yet received the promises,
but seen them afar off as described in the eleventh of the Hebrews;
or among those who believed in Christ actually come in the flesh,
as recorded in the New Testament, in the following (among many other) places,
John 1:12, "`To as many as received him gave he power to become the sons of God,
even to them that believe on his name.`"
Mark 9:23, "`All things are possible to him that believeth.`"
Acts 15:9 and 26:18,
"`The hearts of both Jews and Gentiles were purified by faith;`"
and 1 John 5:4. "`This is the victory that overcometh the world,
even our faith.`"
James 2:18, "`I will shew thee my faith by my works.`"
Eph. 6:16, "`The shield of faith,
wherewith they were able to quench all the fiery darts of the wicked:`"--I
say when I consider this Scripture account of faith,
I see clearly that it was a lively operative one,
and such as professed Christians of ungodly lives have no claim to;
for a dead faith may be reckoned either no faith at all,
or (in some respect) to fall short of that of devils
mentioned by the above-cited apostle James,
of whom he says, that they not only believe but tremble,
a disposition which many professing faith in Christ, are strangers to.

Now in my small reading I find also the accounts given of the early Christians,
not only during the lives of the apostles, but for some time afterwards,
to be such as imply that their faith also was of the same lively
operative kind as that above described from the New Testament,
and superior in efficacy to the dictates of mere reason.

// lint-disable invalid-characters "œ"
"`There appears,`" says Stillingfleet, 1. 2. c. 9. of his Origines sacrœ,
"`to have been a divine efficacy in the first preaching of the gospel,
far beyond that of the mere dictates of philosophy,
which was not suited to all capacities, but to the few only,
and even where it was suited to the capacities of men,
did indeed render them more knowing, but rarely more good;
whereas the gospel did not only change men`'s opinions and way of worship,
but shewed its superior power, in turning them from their lusts, sensualities,
and habitual sins.`"

"`We do indeed,`" continues he,
// lint-disable invalid-characters "æ"
"`read of one Phædon and one Polemon brought off
from their debaucheries by Socrates and Xenocrates;
but what are these to the multitudes which by the mean and contemptible
language of the apostles were converted from intemperance to sobriety,
from injustice to fair dealing: from cowardice to the highest constancy;
yea so great as to lay down their lives for the sake of virtue?
and this is what Origen, in his books against Celfus, triumphs in,
as the most signal evidence of a divine power in the doctrine of Christ.`"

Agreeably to this, I find that, "`the primitive Christians placed their religion,
not in talking finely, but in living well,
nor did they esteem any Christians that merely professed,
but such as lived as Christ commanded;
and Tertullian openly declares that when men depart from the discipline of the gospel,
they so far cease amongst us to be accounted Christians.`"^
footnote:[Cave`'s Primitive Christianity]

But alas, how was the face of things changed, in process of time,
and that faith which was once delivered to the saints
cast off in the sense of the apostle, 1 Tim. 5:12.
In short, an apostasy from the primitive purity and simplicity did creep in,
and from small beginnings prevail at length so far as to
render many parts of the Christian world as corrupt,
and in some cases more so than the heathen.

Of such an apostasy befalling the Christian churches it hath seemed fit
to the divine wisdom to forewarn us in the Revelation of John the divine,
and several other places of the New Testament,
of which it shall suffice at present to mention but two, viz. 1 John 4,
"`Many false prophets are gone out into the world,
that spirit of Antichrist whereof you have heard that it should come, and even,
now already is it in the world,`" and 2 Thess. 2:1-4. "`We beseech you,
that ye be not soon shaken in mind, or troubled, neither by spirit, nor by word,
nor by letter, as from us, as that the day of Christ is at hand:
let no man deceive you by any means,
for that day shall not come except there come a falling away first,
and that man of sin be revealed, the son of perdition;
who opposeth and exalteth himself above all that is called God, or that is worshipped;
so that he as God sitteth in the temple of God, shewing himself that he is God.
"`

Accordingly when we come to consider by whose means
it chiefly happened that the primitive beauty,
purity and simplicity above hinted at, came to suffer an eclipse,
we shall find that it was not by aliens and open adversaries, but by professed brethren:
that the greatest enemies of the church were those of her own house,
even as was said of Judas, John 13:18.
"`He that eateth bread with me hath
lift up his heel against me,`" Who kissed,
and at the same time betrayed his Lord and Master:
for indeed when we come to trace the origin and progress of the apostasy,
we shall find that the great corrupters of Christianity have been the pretended disciples,
apostles, and vicars of Christ Jesus,
who by their conduct have brought infamy upon the Christian name and profession,
and exposed it to that contempt with which it hath sometimes been treated.

Now in order that this may appear,
I shall show that the practices of those men have been the
most barefaced contradictions to the precepts of their Lord;
that from the humility, meekness, and love by him exemplified and recommended,
they have degenerated into the most enormous degree of pride and cruelty,
from a heavenly disposition of mind and contempt of worldly riches,
into the most sordid and most oppressive covetousness; and that,
as corruption of manners is commonly accompanied by that of judgment also,
they have egregiously corrupted the primitive doctrine as well as discipline.

The true origin of this woeful apostasy seems to have been pretty deeply seated,
viz. in the corruption of human nature:
we are told that pride found admittance even among the angels,
and degraded them from their heavenly stations.
It also, through the insinuation of the serpent, sound entrance into Paradise,
and appears to have been one principal cause of the fall of our first parents.
See Gen. 3:5-6. And if the wise man`'s maxim,
Prov. 13:10 viz. "`Only by pride cometh contention,`" be of universal extent,
it seems to have possessed some of the Christians even of the early ages,
and even so far as to have introduced among them the persecution, one of another:
for what was it else that caused Victor, bishop of Rome, in the second century,
to raise so many broils in support of his opinion,
upon a question of no more importance than this,
on what day the Passover ought to be celebrated,
and even to excommunicate all the churches of the lesser Asia,
because they celebrated that festival on the 14th day of the First Month,
and not on the First-day of the week following, as he would have had it?

And again, upon the same principle, what else but pride,
was the origin of those great contentions we read of,
that the Christians in the fourth century fell into about their creeds?

And moreover,
certain external accidents attending the church seem to have had no small
share in fostering this pride incident to some of her members,
that is to say, outward ease, liberty and an affluence of the riches of this world.
When the church`'s fortune grew better, her sons grew worse, and some of her fathers,
(as a learned author observes) worst of all: and indeed, as far as I have learned,
the most memorable era from whence we may date the corruption of Christians was,
when the church, through the favour of Emperors, became endowed with lands, possessions,
and patrimonies, so that
(in the words of Fox, in his Acts and Monuments, Vol. I. p. 716.)
"`the bishops thereof, feeling the smack of wealth, ease, and prosperity,
began to swell in pomp and pride,`" where I also read,
that about this time a voice was heard, as it were from Heaven,
over the city of Constantinople, saying,
"`This day is poison poured forth into the churches.`"

That lordly imposing spirit,
which I have hinted at as creeping in among some of the leading men,
even in the early times, grew much more flagrant in succeeding ages;
and to such a degree, that in process of time,
upon the growing pride of the prelates and corruption of the people,
a spiritual sovereignty was erected,
a separate jurisdiction was established and tyrannically
exercised over the rest of mankind.
Thus the word Church, which, in Scripture language,
signifies any number of persons who embraced the doctrine of the gospel,
and worshipped God in the name of Jesus Christ,
was in process of time wrested from the people, and appropriated,
together with the power thereto belonging,
to a certain set of men who called themselves the clergy.
Now this was a mere novelty, and utterly inconsistent with the primitive example.
For, "`in the apostolic age,
the laity bore a part in the most solemn deliberations which
concerned the interest and government of the church.
The whole number of believers was consulted in the choice
of a fit person to succeed in the apostleship after Judas.
The apostles, elders, and brethren,
or as it is otherwise expressed in the 15th chapter of the Acts of the Apostles,
the church,
or all the multitude assembled at Jerusalem to deliberate on the great question,
how far the gentile converts were obliged to submit to the law of Moses:
and after the assembly had proceeded, not by apostolic authority,
but in the way of a rational and free debate, they came to a resolution,
which they communicated to the churches, convened in the name of the whole body.
Nor indeed did any of the bishops of the first three hundred years after Christ
claim any separate exclusive powers for the exercise of church discipline,
but left these matters to the provincial and diocesan consistories, which,
in the purer ages of the church, were composed of bishops, clergy, and laity.`"^
footnote:[Examination of the bishop of London`'s Codex Juris Ecclesiastici Anglicani,
published in London, 1735.]

Hence, in the laws of the Anglo Saxons,
we find a perpetual mixture of ecclesiastical and civil laws;^
footnote:[Rapin`'s History of England.]
nor was it until the papal power grew to a monstrous height, under the Norman kings,
that the clergy claimed a privilege of debating apart all matters,
that in any wise related to religion, in ecclesiastical assemblies or synods.
Even in the time of king Henry I. we meet with plain proofs of the civil
court retaining their ancient jurisdiction in ecclesiastical causes;
but in the time of king Henry II. the two courts, ecclesiastical and civil,
are constantly spoken of as distinct, and enjoying separate jurisdictions:
and herein the clergy had the countenance and authority
of pope Innocent II. (who began his reign A. D. 1130,
and died 1143),
who at this very juncture excluded the laity from all pontifical assemblies at Rome.^
footnote:[See the place before cited.]

And here it seems worthy of observation,
that the celibacy of the clergy was not established until this time, or pretty near it;
for in the New Testament,
(1 Tim. 4:1,3) the prohibition of marriage is reckoned
among the marks of apostasy and doctrines of devils,
and even in the year of our Lord 601,
marriage was allowed to priests that could not live continently; but in the year 1102,
in the reign of king Henry I. a national synod was held,
of which the fourth canon forbids the clergy to marry,
or to live with their wives already married^
footnote:[Rapin`'s History of England, Vol.
II.]
and this point once gained was a great step towards
putting in execution the project the pope had formed,
of rendering the clergy independent of the civil power,
and incorporating them into a society apart, which should be governed by its own laws:
and indeed whilst the priests had children of their own,
it was a hard matter to prevent them from having some dependence on their princes,
whose favour has so great an influence on the fortune of private persons;
but being without families,
and consequently in expectation of no great matters from their sovereign,
they were more at liberty to stick by the pope,
who would be looked upon as the sovereign of the clergy.^
footnote:[Ibid.
Vol. II.]

This however he did not attain to,
till after a series of ages of growing darkness and ignorance.
For the bishop of Rome at first had no more authority than others,
nor was Rome deemed a mother church until the time of Boniface III.
who did not begin to preside till after the year of our Lord 600,
and obtained from the emperor Phocas,
that the see of Rome should be acknowledged the head of all other churches:
for before that, the Constantinopolitan church was accounted the highest,
as Jerusalem was before:
nor did the church of Rome remarkably exercise her
sway over England until the 7th or 8th century.
The ancient Britons had been converted to Christianity by the apostles,
or some of their disciples,^
footnote:["`The first springing of Christ`'s gospel
in England was in the time of king Lucius,
in the year of our Lord 180,
and the continuance of it from thence to the entrance of the Infidel Saxons,
was 301 years.
The decay of the same, to the entrance of Austin the monk, was 143 years.`"
Fox`'s Acts and Monuments, Vol. I. p.104.]
and adhered to the rites prescribed to them by their first teachers:
and when Austin the monk came into England, being sent by pope Gregory I,
chiefly urging this one point, that they should submit to the authority of the pope,
the church of Rome having made several innovations in the celebrating divine service,
to which they pretended all other churches ought to conform,
the British bishops refused to submit to any alterations,
professing that they owed no more deference to the
bishop of Rome than to any other Christian bishop:
however, by and by, they submitted their necks to the yoke, for A. D. 669, Theodore,
archbishop of Canterbury, as soon as he came into England,
made a visit to all the churches in his jurisdiction,
and brought the people to a thorough conformity to the usages of the church of Rome;
and A. D. 735, the English, archbishops went to Rome to receive the pall.^
footnote:[Rapin`'s History of England, Vol.
I.]

Besides the celibacy of the clergy, there was yet another stratagem,
by which the dominion of this mighty prince was extended far and near;
of which Puffendorf, in his Spiritual Monarchy of the Church of Rome,
give us the following account:

The popes claimed the supreme direction over the universities,
whereby these were rendered mainly instrumental in maintaining the popish sovereignty.
For, in the universities,
men are first tinctured with such opinions as they
are afterwards make use of during their whole life,
and instill them into others; and it was for this reason,
that the sciences there to be taught were sure to be accommodated to the pope`'s interest.
Here the professors of divinity, those of the canon law, and even the philosophers,
were the creatures and slaves of the pope;
and indeed the divinity and philosophy profited in these universities,
were not taught with an intention to make the young students more learned and understanding,
but that the ingenious, by confused and idle terms,
might be diverted from thoroughly canvassing those matters which
would have led them to the whole discovery of the popish intrigues;
for their school-divinity is not employed in searching the Holy Scripture,
but for the most part entangled in useless questions, invented chiefly by Peter Lombard,
Thomas Aquinas, Scotus, and other patriarchs of pedantry;
and what they call philosophy is nothing else but a collection of foolish chimeras,
empty terms, and very bad Latin,
the knowledge of which is rather hurtful than profitable.
So that all their aim was,
to take care that the sciences should not be fundamentally taught;
and above all the rest, the most useful of all,
the doctrine of morality is much misinterpreted, and entangled in an endless labyrinth,
that the fathers confessors may not want means to domineer over layman`'s consciences,
and the these may be rendered incapable to examine
and rule their actions according to solid principles,
but be obliged to be guided blindfold, at the pleasure of their fathers confessors.

So far Puffendorf.

Agreeable to all this was one singular master-stroke
of insolence which deserves particular notice.
It so happened,
that many of the popish institutions were directly contrary
to the precepts and examples recorded in the New Testament:
one thing therefore was necessary,
which once admitted obviates entirely this difficulty to their reception,
and that was to decree, as pope Nicholas did about the year 870,
that the pope`'s laws and letters should be of equal authority with the Scriptures.

And again,
whereas the security of the kingdom of this spiritual
sovereign stood in darkness and ignorance,
he and his adherents finding it necessary,
in order to maintain themselves in the peaceable possession of this their kingdom,
did arrogate unto themselves a right of censuring and licensing all sorts of books whatsoever;
by which means, they were effectually empowered to hinder any thing from coming to light,
which might be prejudicial to their own interest.

But it was not sufficient for this mighty prince,
thus to have established to himself an empire over
the consciences of men in spiritual matters,
but he must exercise it also in temporals, and over kings and emperors.

Indeed the example of him who was Lord of all,
who was the most perfect pattern of humility and meekness, stood in his way,
as did also that express declaration of his to his disciples;
(Mark 10) "`Ye know that they which are accounted to rule
over the Gentiles exercise lordship over them,
and their great ones exercise authority upon them; but so it shall not be among you;
but whosoever will be great among you, shall be your minister,
and whosoever will be the chiefest shall be servant
of all;`" and therefore it seemed to him but decent,
to put on the cloak of humility, and call himself Servus Servorum;
but if one were to judge from his conduct,
he were in reality King of kings and Lord of lords,
viz. When he took upon him the disposal of kingdoms and empires,
as is well known of pope Adrian IV. who gave this
kingdom of Ireland unto Henry II. king of England,
and of pope Innocent III.
who A. D. 1195, crowned Otho the emperor, and afterwards deposed him again, saying,
"`It lies in my power for set up and pluck down emperors, kings, and princes,
at my pleasure, for all power is given unto me both in heaven and in earth.`"
And by the same pope was the kingdom of England interdicted, king John excommunicated,
and his subjects absolved from their oaths of allegiance;
and in the year of our Lord 1212, the king was deposed,
and the kingdom of England and lordship of Ireland, by him resigned unto the pope:
and the same king did thenceforward acknowledge himself a vassal to the holy see,
and as such bound himself to pay the yearly tribute of one thousand marks,
viz. seven hundred for England and three hundred for Ireland.^
footnote:[Rapin`'s History of England.]
That the popes did really, in some of the most essential concerns,
invade the rights of princes to a great degree, may appear from hence,
that pope John 22. by his sole authority published a truce between England and Scotland,
against the consent of one of the parties,
and empowered his legates to conclude a peace between the two kingdoms,
upon what terms they pleased,
with orders to compel the two kings and their subjects punctually to keep it,
under pain of excommunication.^
footnote:[Ibid.
Vol. IV.]

Next to the pope`'s pride, it remains that I give some account of his cruelty.

The great and glorious event of the birth of our Lord Jesus Christ,
was introduced by that angelic acclamation, (Luke 11:14) "`Glory to God in the highest,
on earth peace and good-will to men;`" and Christ
himself was the author of the new commandment,
(John 13:34-35),
"`Love one another,`" and laid down this as a standing
characteristic by which his disciples should be distinguished,
viz. that they loved one another.

Now, if war, bloodshed,
and the destruction of one another (even among the professors of faith in the
same Jesus) be instances of peace and marks of love and good-will to men,
then the pretended vicar of Christ Jesus had them;
but if these things be marks of hatred,
he wants the distinguishing badge of a disciple of Christ; and since,
in the language of the apostle John, (1 John 4:20) "`If a man say, I love God,
and hateth his brother, he is a liar,`" this appellation suits him better, whilst,
under the profession of being a representative of the Lamb of God,
he is spreading desolation and destruction among men.

Again the apostle saith, (2 Tim. 2:24,28) "`The servant of the Lord must not strive,
but be gentle unto, all men, apt to teach, patient,
in meekness instructing those that oppose themselves; if God,
peradventure will give them repentance to the acknowledging of the Truth.`"
And the weapons of the warfare of the primitive Christians were not carnal:
but the weapons and methods the pope usually had recourse
to for the overcoming of those who opposed him were carnal,
and the reverse of gentleness, patience, and meekness; for whereas it is notorious,
that especially from the year 1160, to the year 1170,
divers were by God`'s good Providence raised up to bear a public testimony
against the many gross corruptions that had crept into the church,
these were sure to do this with the hazard of their lives and liberties,
among whom were the followers of Wickliff, called Lollards in England,
and the Waldenses in France, many of whom were burned to death,
and others scattered into divers countries by persecution;
and a few years after those rose the Albigenses in the city of Tholouse,
against whom the pope incensed sent Dominic,
with several missionaries called inquisitors, into the county of Tholouse,
and employed armies against them,
and destroyed above two hundred thousand in the face of some months.
^
footnote:[Sermons Against Popery, A. D. 1735]

In the massacre of Paris, A. D. 1572,
the number destroyed is computed at one hundred thousand, the new whereof,
as Thuanus tells us, they received at Rome with transports of pleasure,
and the pope and cardinals instantly repaired to St. Mark`'s to
thank God for so great a favour conferred on the see of Rome,
and appointed a Jubilee over the whole Christian world for
this slaughter of those called heretics in France.

In the Irish massacre one hundred fifty thousand Protestants,
according to the most moderate computation, were murdered in cold blood.^
footnote:[The Life of Oliver Cromwell]
Nor are there wanting later instances of the continuance of the same cruel disposition,
particularly the persecution in France under Lewis XIV.,
the cruelties at Thorn in Poland,
and on the poor Saltzburghers stripped of all they had and driven from their habitations,
and still more recent examples might be produced to the same purpose.

In short,
we are assured from good authority that far more
blood has been shed by the papal empire and its agents,
than ever was shed by Rome heathen:
and indeed perhaps it may with too much truth be observed,
that when ecclesiastical men once become corrupt,
they seem zealous to outstrip not only laymen, but even heathens and infidels,
and to have exercised far more cruelty in inflicting
their punishments than either of these:
for,
in some of the courts of inquisition (erected first
in the kingdom of him called the Catholic king,
about the year 1479) any one not convicted, but barely suspected of heresy,
is by various tortures tempted to accuse himself (contrary to common
law) and his goods are confiscated (not after conviction,
but) when they first apprehend him;
and whatever process is carried on against him no person knoweth,
but only the holy fathers and the tormentors who are sworn to execute the torments.
The accusation is secret, the crime is secret, and so is the witness;
and even the prisoner in his examination swears inviolably
to keep secret the affairs of the inquisition,
a method of procedure which the ancient heathens would undoubtedly have abhorred,
as we may learn from the 24, 25 and 26 chapters of the Acts.
And although Christ Jesus expressly forbids his disciples to call
for fire from heaven to consume such as would not receive him,
yet his professed representative hath (by his agents) frequently called for and actually
applied fire to the consuming the bodies of such as would not receive his impositions;
and with respect to the torments of the inquisition,
it is observed that the final execution is not by common burning, but by a flow fire;
and moreover, if the supposed heretic has been dead, though many years,
the process is carried on against him as if he were alive,
and he is burnt in effigy with his bones,
even as were the bones of that eminent reformer John Wickliff,
after he had been dead forty-one years,
taken out of the grave by a decree of the synod of Constance, and publicly burnt,
and the ashes thrown into the river.^
footnote:[See the History of the Inquisition at Goa,
and the History of the English Martyrs.]

And when John Hus, another reformer, was condemned to be burnt by the synod of Constance,
seven bishops degraded him, and then a proper mitre was put on his head,
etc. and the prelates delivered his body to be burnt, adding these words:
"`And we devote thy soul to the devil in Hell.`"
Such was the cruelty peculiar to ecclesiastics,
whereas when our temporal judges pronounce sentence against the worst malefactors,
they pray, "`The Lord have mercy on thy soul.`"^
footnote:[Sermons Against Popery, A. D. 1735]

These and the above mentioned may suffice as short
specimens of the pope`'s pride and cruelty.
Let us next take a view of the temper of his mind with regard to earthly treasure,
and see what title he has to the appellation of a
representative of Christ on this account also.

Now we find by the history of the New Testament that Christ Jesus,
who was greater than Moses,
who promised to the obedient an increase of outward substance, as of corn and cattle,
Duet. 28 (the factions of his laws being, for the most part,
outward rewards and punishments), ever directed the desires of his disciples,
not to the riches of this world, but to the spiritual ones,
expressly enjoining them not to "`Lay up treasures on earth,
where moth and rust do corrupt and thieves break through and steal, but in heaven.`"
(Matt. 6:19-20) Nor do I find in the catalogue
of blessings pronounced by our Lord on the Mount,
or elsewhere in the New Testament, one blessing on rich men as such,
but on those who were possessed of a heavenly disposition of mind: on the contrary,
I find woes denounced on the rich and full, but blessings to the poor, in Luke 6,
and consistently with this the apostle Paul, in his first epistle to Timothy, chap.
6 says, "`Having food and raiment let us be therewith content;
but they that will be rich, fall into temptation and a snare,
and into many foolish and hurtful lusts, which drown men in destruction and perdition;
for the love of money is the root of all evil,
which while some coveted after they have erred from the faith,
and pierced themselves through with many sorrows.
But thou O man of God, flee these things, and follow after righteousness, godliness,
faith, love, patience, meekness.`"

Such was the sense of the apostle Paul concerning the disposition of mind that
ought to prevail in a Christian bishop with regard to the riches of this world.
Let us see how consistently with this the bishops of succeeding times have acted.

After the Christian religion became modish, the liberality,
partly of certain piously disposed persons, and partly of some deluded ones,
who vainly imagined that by donations of this sort
they might purchase the remission of their sins,
became great, and in process of time increased to an enormous degree,
even so far as to corrupt the minds of the receivers;
for with the acquisition of riches the desire of them also by and by increased,
even as commonly happens to mere carnal men;
and truly to a greater degree in those apostatizing Christians than in heathens.

Property and power entering into Christian (even as in other) societies,
created parties and factions.
To accept of the office of a bishop became, in process of time,
no longer an instance of self-denial nor a post of labour and vigilance as at first,
but a desirable bait to sensual men;
and whereas their professed Lord and Master testifieth
of himself that though the foxes had holes,
and the birds of the air nests, yet he had not where to lay his head,
nothing less than stately palaces at length would satisfy these his professed representatives.
In short, the gospel-motive of love to the souls of men, gave way to,
and was supplanted by views merely carnal and human;
Christ was followed for the loaves and fishes, preaching the gospel became a trade,
and a very gainful one too.

A few instances shall suffice to shew what an advantageous
trade the pope and his agents did follow,
and how the spirit of avarice at length prevailed so far
as to render the trade of priestcraft bare-faced,
and that this was driven on to that extremity as at length to threaten, in some sort,
the ruin of those that were exercised therein.

The office of a bishop or other minister was originally
such as required a constant and assiduous residence;
and indeed many severe canons and decrees of councils
were made against pluralists and non residents;
as likewise against the translations of bishops from one city or bishopric to another.
But what did these canons avail?
Truly they were but like spiders`' webs, letting the great flies through,
and catching the little ones,
and so proved an effectual stratagem to bring money into the apostolical exchequer;
for by that one clause of the pope`'s dispensing power,
the richer clergy were indulged in their non-residence,
etc. whilst the poor vicars were bound by a constitution of Otho,
to take a strict oath of continual residence,
and without it their institution was declared to be null and void.^
footnote:[Dr. Ayliff`'s Parergon juris Canonici Anglicani.]

The pope, in process of time,
engrossed to himself the collation of almost all the church preferments,
and conferred the greatest part of the benefices
in England on the cardinals and their relations,
who enjoyed the profits without ever residing;
and these benefices were commonly farmed out to the English, who,
to make the most of them, got the cure served for a very small salary.
Hence divine service was neglected, the churches ran to ruin,
and the instruction of Christians was almost wholly laid aside.^
footnote:[Rapin`'s History of England.]
It appeared, however, upon a computation, made by order of king Henry III.
A+++.+++ D. 1245, that more money was carried out of England annually by the pope`'s authority,
than all the revenues of the crown put together;
and without doubt all the riches of the nation had been conveyed away through this channel,
and the ecclesiastics soon become masters of all the lands
of the kingdom (seeing they daily acquired and never alienated),
had not certain statutes, particularly that of Mortmain,
enacted in the reign of king Edward I. to check the growth of the riches of the clergy,
prevented it.^
footnote:[Rapin`'s Hist. and Sermons Against Popery.]

But to conclude, about the year 1475,
was erected the famous trade of pardons and indulgencies, i. e.
a procurement of the remission of the pains of purgatory,
which was sold for money like any other ware, in the time of Boniface IX.^
footnote:[Polydore Virgil de rer. inventoribus.]
And Thuanus says,
that the pope sent his bulls throughout Christendom to raise money for his immense expenses,
promising the expiation of all sins, and eternal life at a set price and rate,
according to the nature of the crimes; and he appointed a treasury and questors,
and preachers, to set forth the value and efficacy of those indulgencies.
"`The collectors under the authority of pope Leo X. about the year 1516,
persuaded the people that whosoever would give ten shillings,
should at his pleasure deliver one soul from the pains of purgatory, and preached,
that if it were one jot less than ten shillings, it would profit them nothing.`"^
footnote:[Fox`'s Acts and Monuments.]
Hence many were encouraged to sin, and the authority of the keys was much debased.

Behold the awakening imposition that made all men feel the bondage;
and indeed this seems to have been the ne plus ultra of Romish corruption,
or the very midnight of popish darkness, out of which, by God`'s good providence,
emerged more resplendent beams of the glorious light of the reformation.
For this kind of filthy merchandize, being, among other countries,
propagated also in Germany, by the means of Tecellus, a Dominican friar,
his scandalous sermons much moved Martin Luther the monk,
who upon this occasion published certain propositions concerning indulgencies,^
footnote:[Fox`'s Acts and Monuments]
which gave rise to a controversy,
and from these small beginnings he proceeded with great zeal and
constancy to detect many of the long established errors of popery.

That great corruptions did really prevail in the church about this time;
that there was a strong necessity and even a loud call for a reformation,
we may very safely affirm, since we have a remarkable testimony of Adrian the pope,
then reigning, in his instructions published against Luther,^
footnote:[Ibid.]
acknowledging it in these words:

We confess that God suffereth this persecution to
be inflicted on his church for the sins of men,
especially of priests and prelates of the clergy,
and the Scripture testifieth that the sins of the
people do issue out from the sins of the priests.
We know that in this holy see there have been many abominable things wrought and practised.
And no marvel if the sickness beginning at the head
have descended afterward to inferior prelates.
Wherefore, etc. in us shall be lacking no diligence of a better reformation,
first beginning with our own court,
that like as the contagion first from thence descended into all the inferior parts,
so reformation and amendment of all that is amiss from the same place,
again shall take its beginning: whereunto they shall find us so much the more ready,
for that we see the whole world so desirous of the same.

So far Pope Adrian.

Now, that under the influence of such directors as those above described,
novelties and corruptions of the primitive discipline and doctrine should creep in,
we need not wonder; some instances whereof have been occasionally mentioned already,
viz. their prohibition of marriage to the clergy,
their excluding the laity from the assemblies for church discipline,
and the setting up the authority of the church of Rome above all other churches:
a few more examples to the like purpose now follow, viz.

I+++.+++ The veneration paid by the Papists to their images (contrary to the
practice of the primitive Christians within four hundred years after Christ,
among whom no images were worshipped or used in their churches^
footnote:[Cave`'s Primitive Christianity]) and to their saints;
to whom they erect temples and chapels, confess their sins, pray and give praises,
thus robbing the one supreme God of his honour.
Now this their worship of saints is a practice borrowed from the heathenish theology,
and particularly from the worship of demons among the Pagans;
and accordingly they have a variety of saints and fairnesses
to answer the gods and goddesses in the heathen world;
and as the several kingdoms of the earth were formerly supposed
to be under the protection of different gods,
in like manner are they now consigned over to the guardianship of several Roman saints,
as St. Dennis for France, George for England, Andrew for Scotland, etc.

In some other instances they corrupted the simplicity of
the gospel by the introduction of divers Jewish rites.
Thus the use of holy water, or the water of purifying,
was a Jewish rite mentioned in the Eighth chapter of Numbers,
where God commands the water of purifying to be sprinkled on the Levites;
and hence Alexander I. bishop of Rome^
footnote:[Polyd. Virg. de rer. inventorib. i. v. c. 8.]
is said to have been the author of consecrating such cleansing water,
ordering it to be kept in temples and houses to drive away devils.
Whether the bishop last mentioned, who presided in the beginning of the Second century,
was really the introducer of this custom, I shall not take upon me to determine; however,
its origin is plainly Jewish, and the continuance of it in the Christian church,
a voluntary relapse from gospel-liberty into Jewish bondage.

II. The priests`' vestments are derived from the Hebrews,
as the last cited author shews in the mitre, surplice, girdle, etc. from Exodus 28 etc.

III.
The payment of tithes is another Jewish rite,
void of all support by precept or example in the New Testament,
and which was not established until about the same era as divers other popish corruptions.
For as father Paul, in his Treatise of Ecclesiastical Benefices and Revenues, observes,
the "`Law of tithes was a divine Mosaical law, and as such,
binding only to the Jewish people.--All right whatsoever of tithes is merely human;
and about the year 1170, Alexander III.
ordered proceedings by censures to enforce the payment of tithes,
under pain of excommunication.`"^
footnote:[Father Paul`'s Treatise of Ecclesiatcal Revenues, etc. chap.
28.]

IV. Auricular confession does not appear to have
been absolutely enjoined to be practised once a year,
earlier than the 4th Lateran council in 1215.^
footnote:[Sermons Against Popery, A. D. 1735]

I shall subjoin but a few words of their corruptions of the Christian doctrines,
and first, in their doctrine of purgatory,
which is expressly contrary to the sense of the catholic church in the four first centuries;
and is moreover acknowledged by an eminent popish author, and an opponent of Luther,
to have been but lately received into the universal church.^
footnote:[Ibid.]

Secondly.
The doctrine of transubstantiation is also another novelty,
not broached until the Eighth century,
and even about that time warmly opposed by the most learned men,
particularly Johannes Scotus.
In the year 1214, Pope Honorius III.
commanded that the missal-bread should be lifted
up above the priest`'s head at a certain time,
and that all the people should fall down and worship it;
and though the new-found device and term of Transubstantiation
was hatched in the Lateran council,
A+++.+++ D. 1059,
the doctrine of transubstantiation was not decreed or established
by any general council but the council of Trent,
A+++.+++ D. 1551.^
footnote:[Sermons Against Popery, A. D. 1735]

To conclude; that divers of the novel order of Jesuits,
of whom Ignatius Loyala the founder was not canonized until 1622,
did corrupt the great doctrines of Christianity,
and represent the Christian morality as far short of the purity of the heathenish,
the reader may see in a treatise written by the Abbe de Berthier, published in Dublin,
1726,
entitled The Parallel of the Doctrine of the Pagans with the Doctrine of the Jesuits,
and That of the Constitution Unigenitus,
Issued by Pope Clement XL. Out of several instances therein
mentioned of the nature of the doctrines of these fathers,
it shall suffice here to transcribe one as a specimen of the rest, viz.

Father Rhodes, in his scholastic theology, says, "`if any one commits adultery or murder,
and at the same time considers the malignancy and heinous nature of these
actions but in such a manner as is very imperfect and superficial,
though the matter of it is very gross, yet his sin is venial.`"
To which I shall subjoin one instance more of the Christian morality
being represented even by the professed vicar of Christ Jesus himself,
as far short of the heathenish, viz. "`in a bull of Pope Clement VI. in the year 1351,
a dispensation was granted to John, king of France, and to queen Joan, his second wife,
giving to the king and queen`'s confessor a power to absolve them
both for the past and future from all engagements and contracts,
though backed by an oath, if they could not keep them without some inconveniency.
Thus is perjury authorized; whereas among the ancient Romans,
it was an opinion generally received that rather than break one`'s oath,
one ought to be ready to brave all that is dreadful in banishment,
imprisonment and torment.`"^
footnote:[Letter from a Librarian at Geneva, published in the London Magazine, 1751]

Now surely it must have been in a time of deep sleep that those tares were sown,
that these gross corruptions in doctrine and practice,
these flat contradictions to the precepts laid down by the
author of the Christian religion in the New Testament,
were broached;
and indeed the broachers of them seem to have been well aware of their being such,
and therefore, consistently enough,
ordered that book to be locked up from the use of the vulgar;
and that ignorance was the mother of devotion became an established maxim among them;
and (dismal to relate!) the prayers of the church were to be muttered in a language
which most as those that were therein exercised did not understand;
for even in queen Mary`'s time, in the year 1557,
it was deemed a crime for any clergyman to perform divine service in English:^
footnote:[Fox`'s Ecclesiastical History.]
and indeed an universal ignorance, extending to human as well as divine things,
did reign for divers centuries preceding the grand era of
the midnight of popish darkness above hinted at: v. g. king Alfred who died in 900,
complained bitterly that from the Humber to the Thames there was
not a priest that understood the liturgy in his mother tongue;
and that from the Thames to the sea there was not a man
that knew how to translate the easiest piece of Latin.^
footnote:[Rapin`'s History of England, Vol. 1]

And in the 15th century, the state of learning was very deplorable,
viz. real learning was then scarce so much as heard of.
School divinity and skill in the canon law were all
the ecclesiastics valued themselves upon,
and it was the only road by which they could hope to arrive at church dignities.
On the other hand,
the monks who had crept into most of the professorships in the universities
had over-run divinity and philosophy with such a heap of jargon as served
only to give their disciples false notions of learning,
and to teach them to wrangle.^
footnote:[Rapin`'s History of England, Vol.
6]

But with the reformation in religion, a more solid and useful learning did also revive;
and here it seems well worthy of notice,
as a singular providence greatly favouring the progress and establishment of the reformation,
that about the year 1450, the mystery of printing was first discovered;
and is said to have been brought into England, A. D. 1471, in the reign of Henry VI;
which, as Fox observes, proved a forcible engine to batter popery,
and a means of spreading knowledge among the people,
who had with great care been kept in ignorance by the prevailing power.
But now, as the poet says, by means of this excellent invention,

"`Learning revives, nor fears again t`'expire Midst papal ignorance and Gothic fire:`"

And it is humbly hoped that the same thing may justly
now also be applicable to the reformed religion.

Thus have I, for the sake of those who may have been less conversant in these matters,
given a brief portraiture of the apostasy of the professors of Christianity,
those especially who affected the title of vicars and representatives of Christ Jesus;
of whom as it is supposed to have been prophesied
that his visage was more marred than any man`'s,
these men have taken care that this should be amply fulfilled in the representation
they have given of Christ and his religion to the world:
a religion,
although calculated to promote the temporal as well as eternal happiness of mankind, yet,
if one were to frame his idea of it from their conduct as above described would
appear to be no better than a stratagem to enrich and aggrandize a few men,
called ecclesiastics at the cost of impoverishing and enslaving the rest;
from whence I cease to wonder at the contempt with which the profession of Christianity,
without the power and Spirit of it, hath been sometimes treated.
