== Advertisement.

I+++.+++ The Reader is desired to excuse the diversity
of style that occurs in different parts of this work;
for which it is hoped the following reasons will sufficiently apologize.
1st. The foregoing part of the history to the year 1700,
having been compiled for the most part by the person mentioned in the title-page,
it was deemed most expedient to publish it in his own words; and 2ndly,
in order that the genuine sense of the authors of divers narrations and epistles,
might be faithfully conveyed to posterity,
their own words are also retained in their native simplicity.

II. Order of time,
with respect to the accounts of the convincement
and services of many eminent ministers and elders,
hath not been always observed,
because of the compiler`'s design to place these things together in one view,
with the testimonies, or characters given of them at their decease, where this could,
be conveniently done.

III.
It is but doing justice to many other worthy ministers and elders,
of whom nothing in particular is related in the following history,
to acknowledge that their memoirs are as honourable
as those of whom particular accounts have been given,
and their services oftentimes were as great,
although partly through the great modesty of the persons concerned,
and partly through the neglect of others, no record was preserved of them.
