== Chapter III.

From the end of the troubles under King James the Second,
to the passing the Act of Parliament for registering the meetinghouses of Friends,
in common with those of other dissenters, under the reign of King George the First,
in the year 1719.
Great plenty succeeding the late times of devastation and scarcity,
faithful warnings are given against the spiritual danger thereon attending.
The eminent zeal of faithful Friends of those days
against the inordinate pursuit of worldly riches.
Their zeal and prudence in the prosecution of Christian discipline.
Some progress in propagating the gospel in the province of Connaught.
The characters of divers ministers and elders, deceased.

It is observable, that whereas this year, 1692,
there had been some application made to the parliament in England,
in order that the solemn declaration of the people
called Quakers might be accepted instead of an oath,
an epistle of caution was sent in behalf of Friends
of this nation to the Meeting for Sufferings in London,
desiring that only the form of Christ`'s own words, yea and nay,
might be kept to if possible so that nothing might be accepted of,
that might bring a snare or burden upon any tender conscientious person;
and recommending patience, and to wait God`'s time,
to open a clear and free way for his true and tender-hearted people to assert the truth.

Besides other ministering Friends who visited this nation this year, 1693,
was Thomas Rudd, who travelled through most parts of the nation,
not only where Friends were settled, but also in several other parts;
and he preached repentance through the streets,
and in the public places of most towns he came into,
travelling as far as Galway and Sligo, at the first of which places he was imprisoned,
as also at Cork.

Now after the troubles, and great spoil and scarcity above-mentioned,
there suddenly succeeded a time of great plenty after a wonderful manner,
beyond what could be expected; and stock and trade increased mightily,
and the time of getting great riches came on,
as the time of great losses had been experienced before,
and many too eagerly pursued them; and too many of our society were concerned therein,
which has proved very injurious upon several accounts,
and especially to Friends`' children; who perceiving their parents`' fullness,
and relying thereupon, grew conceited and finical; many of them giving way to idleness,
and too many parents indulging them,
as also gratifying the vain mind that goes after the fashions of the world;
and for want of timely care,
some grew so hardy that their parents could not deal with them;
and these things greatly added to the exercises of the sincere,
and great endeavours were used to put a stop to this
eager pursuit after the things of this world,
in such a day of great ease as this was,
suddenly succeeding the many sufferings which Friends had formerly undergone:
and as this spirit of eagerness predominated, as though it would choke all that was good,
like the tares, and bring a damp upon the sense of truth in the hearts of Friends,
and so make them forget the eminent care and providence of God over them,
in giving them their lives for a prey, through all those calamities;
the Lord in his mercy, in order to preserve us,
and prevent this evil design of the enemy,
raised up by his Holy Spirit a fervent zeal and courage in many of his servants,
to stand against this insatiable spirit, and was mouth and wisdom to them;
and so from men and women`'s meetings many admonitions, exhortations, and warnings,
both in word and writing,
were sent forth to the body of Friends to keep close to the truth,
and within the limits thereof;
and the Lord wonderfully accompanied Friends in that service,
with his power and presence, to great satisfaction and confirmation,
and opened to them many ways to stop the progress of that spirit,
for the preservation of one another, which wrought to good effect.

In 1694, John Banks visited this nation in the work of the ministry,
and in one of his epistles recorded in his journal, is the following remark:

The Lord hath here a blessed zealous people for his name and truth,
filled with love to his servants, largely manifested to us,
in accompanying us from one meeting to another,
from ten to twenty and above in company at one time, the length of twenty five miles,
even in the time of harvest;
and three travelled from Dublin with us above one hundred miles.

It was observed at the Third month national meeting, in 1695,
that no one friend was a prisoner through the nation,
Friends having gained a pretty good esteem among those in authority.
This year, 1696, the government of England savoured Friends there,
so far as to prescribe for them a declaration to be made, or signed by them,
instead of an oath;
which although not universally satisfactory to Friends of this nation,
nor to many of the brethren in England,
by reason of the sacred name of the Lord being mentioned therein,
this dissatisfaction however never proceeded to an open division;
but the spirit of true Christian charity and mutual forbearance towards one another,
under different sentiments, shone forth, particularly in the yearly meeting of London,
and a happy harmony was established among Friends of both nations,
and an unanimous resolution taken, to solicit the government,
when Providence should open the way, for the granting an affirmation easy to all;
in which that Friends of this nation were not inactive, we shall see hereafter,
particularly in the years 1711 and 1721.

This year (1696) died Deborah Sandham of Youghall, wife of Robert Sandham,
of whom account hath been given before,
who had a sound and weighty testimony for God`'s truth;
she was a pattern of righteousness, humility and self-denial.
She survived her husband about twenty years,
and carefully trained up her children in the fear of God,
watching over them and her servants in love,
and the Lord was pleased to bless her labour and care therein.
She was of a tender spirit, not hasty to censure any hardly; was loth to hurt the good,
and yet would condemn the evil;
and if she heard of any nigh her professing truth that had done amiss,
it was her godly care to visit them in love, and admonish them;
she was a mother in the church, and her love and care over God`'s heritage was great;
she departed this natural life with sweetness and comfort,
having this testimony to bear on her deathbed, that truth had been her chief treasure.

Among other Friends who visited the nation this year was John Gratton,
an able minister of the gospel,
who in his journal has left this testimony concerning the Friends of Ireland,
that "`There was great love, peace and concord among them,
and good order and government in a careful oversight of the flock,
that Friends be careful in all respects to keep their profession without blame,
and particularly that none run inordinately after the world,
or break in other men`'s debts.`"

In 1698,
we have also a remarkable testimony concerning the zeal of Friends of this nation,
in prosecuting a strict and close discipline, from the men`'s meeting of Bristol,
in an epistle of theirs to the national meeting here, in these words:

Your love to the holy cross of our Lord Jesus,
and your zeal for promoting the way thereof, by a strict and close discipline,
is that which is much wanted in many places;
and though ignorant and malicious spirits may, (as they have done) carp at it,
and cry out against it as an imposition on conscience,
God Almighty hath blocked up their way, and spoiled the spoiler,
and manifested their folly to all,
the necessity of a holy care in the church of Christ more and more daily appearing.

This year (1698) William Penn among others visited this nation;
and some time after his arrival, John Plympton, a certain tenacious Baptist disputant,
published a paper, entitled, A Quaker No Christian:
to which William Penn replied under the title of, The Quaker a Christian;
and in order the more effectually to wipe off that adversary`'s aspersions,
he also wrote and dispersed a paper entitled,
Gospel-Truths Held by the People Called Quakers, subscribed by himself, Thomas Story,
Anthony Sharp, and George Rooke, at Dublin;
which may be seen in the second volume of William Penn`'s Works,^
footnote:[In two Vols.
Folio.
1726.]
with the bishop of Cork`'s exceptions to it, and William Penn`'s answer.
After this, he travelled to other parts of this nation in the work of the ministry,
to the edification of the churches; of which, because he has given some account,
in an epistle from hence to the yearly meeting at London,
signed by himself and his two fellow-labourers,
as likewise a remarkable testimony concerning the Friends of Ireland:
here follows a copy of it from his works, viz.

To the Yearly-Meeting at London.

Dear Friends and Brethren,

It is not the least of our exercises, that we are thus far outwardly separated from you,
at this, time of your holy and blessed solemnity;
but because we have good reason to believe it is in the will of God,
we humbly submit to his ordering hand, and with open arms of deep and tender love,
embrace you our living and loving brethren,
who are given up to serve the Lord in your generation,
and that have long preferred Jerusalem, and the peace and prosperity of her borders,
above your chiefest joy.
The salutation of our endeared brotherly love in Christ Jesus is unto you,
desiring that he may richly appear among you in power, wisdom, and love,
to guide your judgment and influence your spirits,
in this weighty and anniversary assembly;
that so nothing may appear or have place among you,
but what singly seeks the honour of the Lord, the exaltation of his truth,
and the peace and establishment of his heritage.
For this, brethren, you and we know has been the aim, end,
and practice of those whom the Lord hath made willing
to forsake and give up all for his name`'s sake;
and through various exercises and tribulations, yea, in the way of the daily cross,
and through the fight and baptism of many afflictions,
to have their conversation and sojourning here below upon the earth, in fear and love,
looking for their reward in the heavens that shall never pass away;
who have not been lifted up by good reports, nor cast down by evil report,
from their love to the Lord and his precious truth, but hold on their way;
whose hands being clean of evil things towards all men,
have waxed stronger and stronger in the Lord.
Wherefore, dear brethren, let us all be found in the same steps,
and walking the same way, not being high-minded, but fearing to the end,
that we may serve our generation in diligence and faithfulness,
and so enter into the rest that God has reserved for his
true travellers and labourers in his vineyard.

And now, dear brethren,
know that the Lord hath brought us well into this kingdom of Ireland,
and given us many large and blessed opportunities in several parts;
meetings being crowded by people of all ranks and persuasions, especially at Dublin, who,
for ought we have heard, have given the truth a good report;
and indeed the Lord has mightily appeared for his own name,
and owned us with a more than ordinary presence, suitable to the occasions,
and made very heavy and hard things easy to us, because of the glory of his power,
with which he assisted us in our needful times, for which our souls bow before him,
and bless, reverence and praise his holy and worthy name.
So that, dear brethren, we have good tidings to give you of truth`'s prosperity at large,
and more especially in the churches,
having had the comfort of the general meeting of this nation,
consisting of many weighty brethren and sisters, from all parts thereof,
which was held in the city of Dublin in much love, peace and unity for several days,
wherein we had occasion to observe their commendable
care for the prosperity of the blessed truth,
in all the branches of its holy testimony, both in the general and in the particular,
improving the good order practised among the churches of Christ in our nation.

Indeed their simplicity, gravity, and coolness, in managing their church affairs;
their diligence in meetings both for worship and business;
their dispatch in ending differences, and expedients to prevent them;
but especially their, zeal against covetousness and indifferency in truth`'s service,
and exemplary care to discourage immoderate concern in pursuit of things of this life,
and to excite Friends to do good with what they have, very greatly comforted us,
and in the sweet and blessed power of Christ Jesus the meeting ended,
and Friends departed.
The Lord grant that you may also see of the travail of your souls,
and end of your labour and service of love, who seek not your own things,
but the things of Jesus Christ in this your solemn general meeting.

And, dear brethren, we must tell you,
here is room enough for true labourers in God`'s vineyard,
and cannot well forbear to recommend the service of truth in this nation,
to your serious consideration,
if happily the Lord may put it into the hearts of any faithful and weighty brethren,
to visit it in the word of eternal life; for we can not but say,
the harvest appears to us to be great, and the labourers in comparison but a few.
So in that love which many waters cannot quench,
nor distance wear out of our remembrances,
and in which we desire to be remembered of you to the Lord of our household,
we dearly and tenderly salute you, and remain

Your loving and faithful brethren,

William Penn

John Everott

Thomas Story

Lambstowne, 2nd of the Fourth month, 1698.

William Perm also sent the following epistle to Friends of this nation,
after his return to England.

Bristol, 13th of the Eighth Month, 1698.

My Dear Friends, Brethren, and Sisters of the Nation of Ireland.

Much beloved in the Lord,
and often remembered for his name`'s sake since I saw your faces,
and though absent in body, yet present with you in spirit.

Grace, mercy, and peace, from God our Father,
and our Lord Jesus Christ be increased amongst you; and it will be increased,
my dear Friends,
amongst you as you increase in your faithfulness to that
blessed testimony which the Lord hath given you to bear;
for faithfulness is the only way to fruitfulness (and where any
are slack and short they will not be fruitful to the Lord),
wherefore, my dearly beloved in the Lord, keep close to him,
and in his blessed light walk, where you have a right judgment of yourselves and others,
and may see what is amiss or short, or contrary to the truth,
and your call and station in it; that so every one of you knowing your membership,
and place in the body, may, while you have a day and time,
answer it to the Lord and his church; for this world, my dear friends,
is but a trial and pilgrimage, in order to another;
for this is not the place of our rest,
and therefore let us not take up our rest in fading things, but let the Lord be our rest,
who is the everlasting sabbath of his ransomed people.

O my heart is overcome in the sense of his goodness to us all every way.
O how has he worked for us!
Should we not then work for him while we have day to work,
and lay ourselves out for his glory,
which is the way for us to lay up treasure in heaven for ourselves?
Wherefore, my dear friends, brethren, and sisters,
be you encouraged to double your diligence for the Lord, his truth and church,
and let the concern of its prosperity come more and more upon you,
in your respective places as abode,
that you may shine as lights and heavenly examples
amongst your neighbours and country folk,
yea to the poor dark natives; that it may appear to all that you have been with Jesus,
and that Jesus is with you; for though it be a time of peace with you, I tell you,
brethren, it is a time of great trial; your enemy is the same,
though his temptations are not, and thereby he hopes to get ground upon you,
having transformed his appearance; but my soul prayeth to the Lord,
that you may not be moved from your steadfastness by the enjoyment of those things,
the loss of which could not shake you.
Now is the time to grow strong in the Lord, and lay up store for a cold winter day,
which the Lord may yet suffer to come for the trial of his people,
and punishment of evil doers.

O, I feel my heart engaged and tenderly drawn forth to you, "`flesh of my flesh,
and bone of my bone,`" in the eternal kindred,
where I embrace you in the arms of love that is without dissimulation,
that love which knows no guile, which many waters cannot quench,
nor time or distance wear out of my remembrance; for it has an everlasting spring.
In this I salute you altogether, I hope in your national meeting, however,
it is to the family of God, wherever scattered over that country;
and the Lord reside among you, and open his secrets to you,
and make you learned in all the learning of the Israelites indeed, the redeemed of God,
which is wisdom in a mystery that the world`'s wisdom cannot reach;
so will you be truly comely and edifying to the body both of elder and younger,
fathers and children, all in the line of light, life, and love,
sweetly leading and following each other,
being fastened together by the cords of charity which
keeps the unity of the Spirit in the bond of peace,
where the Lord preserve you all.

Things here, and hereaway, are pretty well (blessed be the Lord), and go forward;
they rejoice in the good account I gave them of your love,
zeal and care (for it is pleasant to the Lord`'s people to hear well one of another).
I find and feel a dark and envious spirit secretly gathering
all its strength together to encompass the holy city,
both Gog and Magog;
but from heaven will deliverance come to all the heavenly-minded in the Lord`'s time;
and till then, and ever, his blessed will be done.
I could say no more, but a word to the wise may suffice;
so my dearly beloved in the Lord, I take my leave of you, and bid you farewell, remaining

Your faithful friend and brother, in the fellowship of the blessed truth,

William Penn.

Many Friends of the ministry from abroad, visited this nation this year 1699;
among whom was Mary Mitchel, who went into sundry public places of worship,
and preached repentance in the streets of several towns,
calling upon the people to fear the Lord, and turn from the evil of their ways,
and declaring that if they did not, the Lord would visit them with his judgments;
particularly in the streets of Drogheda,
where the mayor of the place committed her to prison, but she was soon enlarged.

A general provincial visit was performed this year; i. e.
a visit to every particular monthly meeting in each province,
in order to enquire into the state of each meeting,
and see how the wholesome admonitions and exhortations given forth had been put in practice;
and an account was returned to the national meeting,
of the great satisfaction and comfort that attended those concerned in this service,
the Lord`'s good presence attending them;
and a condescension appearing in those that were visited,
with regard to the advice given them;
and particularly Friends of Leinster province gave an account,
that many had lessened their outward concerns, and denied themselves of the offers,
of considerable gain and profit, in order to answer truth`'s requirings,
and Friends`' labour of love;
and that some who had large holdings had accommodated
others that wanted small tracts of land,
and some offered to do more on that account.

Agreeable hereunto,
was the publication of an epistle from the province of Leinster this year
(1699) which was dispersed and recommended to the observation of Friends;
an epistle shewing the spirit and disposition of the faithful elders in those days,
and the just conceptions they had of Christian simplicity, moderation, and self-denial:
not confining it to certain superfluities in habit and speech,
as some have ignorantly or maliciously surmised,
but considering it in its due latitude and extent,
being truly sensible that the cares of this life, and the deceitfulness of riches,
was as dangerous a snare to the old,
as airiness in deportment and the love of other pleasures are to the young;
or that the good seed was as effectually hindered from bringing forth fruit in the thorny,
as it was in the highway and stony ground in the parable:
with me it is also a standing evidence of the true
spiritual wisdom and foresight of these men,
with regard to the pernicious effects of the unbounded love and pursuit of worldly riches,
on the welfare of our Christian society,
the truth of which has been abundantly confirmed by the experience of succeeding times.

The epistle is here annexed, whereof two thousand were printed for public service.

=== An Epistle to Friends, Given Forth From Leinster Province Meeting, in Ireland, Held at Castledermot, the 9th, 10th, and 11th Days of the Seventh Month, 1698.

"`Love not the world, neither the things that are in the world.
If any man love the world, the love of the Father is not in him,`" 1 John 2:15.

=== The Preface.

Dear Friends,

The following epistle is recommended to be read in the fear of the Lord,
in which I doubt not but you will have a sense of the godly care and concern
which the Lord hath raised in the minds of some of his faithful elders,
for the good and preservation of his heritage.
But if there be any amongst ourselves or others,
not acquainted with our Christian discipline, who,
for want of truly seeing the great danger and hurt
that hath attended the professors of Christianity,
by unbounded desires, and pursuit after the things of this world,
shall censure our Christian care;
as if we went about to exercise lordship over one another,
or would hinder and limit such industrious and capable persons, who in the fear of God,
and in moderation, do improve the creation in general,
or their own worldly talents in particular, which God has been pleased to give them;
I say, if any shall thus judge of our godly care and endeavours,
let all such know they are mistaken, and that no such thing is intended.

But as a people whom the Lord hath made sensible of the many snares that do attend,
and the loss some have sustained,
by the insatiable desire and too eager pursuit after the lawful things of this world,
a concern came upon us, that if possible,
we might all come to be limited with the bounds of
truth that leads to moderation and content,
and to depend more upon that providential hand of the Lord,
that will afford us what we stand in need of,
than in an inordinate desire to pursue after the gain of this world`'s goods.

And now, dear friends and brethren, this brotherly caution arises in my heart for you,
who were eye-witnesses and partakers of that wonderful and
eminent bowing power and presence of the Lord God,
that appeared amongst us at that meeting,
that none who were witnesses of the power of the Lord at that time,
and thereby brought into a lively sense and sight of the great
danger attending that mind which would be going after covetousness,
may in the least give way thereto,
or enter into reasoning and consulting with flesh and blood,
by which you will lose the sense you then had of that spirit,
and be in danger of becoming monuments of God`'s displeasure.
But on the contrary, keep to the guidance and direction of God`'s Spirit in yourselves,
which will limit your desires (to the lawful things
of this world) within the bounds of truth:
which is the earnest desire of one that desires the good and preservation of all,
in that which will tend to the glory of God, and bring everlasting comfort in the end.

Thomas Trafford.

To All Our Dear Friends and Brethren in this Nation of Ireland, and Elsewhere.

The salutation of our dear love in the Lord Jesus Christ, in tender bowels,
flows forth to the whole heritage of God,
with fervent desires that all may walk worthy of his great love and fatherly kindness,
who hath blessed us in turning us from our iniquities,
and brought us to the knowledge of himself,
by the blessed light of his dear Son shining in our hearts,
and by the evidence of his Holy Spirit confirmed,
our faith in the unspeakable benefit we have,
both in his first and second coming for to suffer for us, in that prepared body,
and now in Spirit and glorious power of the Father,
to perfect our redemption and salvation, and to reconcile us unto himself,
by washing us with the water of regeneration,
and sprinkling us with the blood of his covenant, and under his daily cross,
which crucifies us to the world, and renews his heavenly image in us,
and hath preserved us in all exercises of troubles, temptations, and perils of all sorts,
inward and outward,
and fed us plentifully with the wholesome and sound doctrine of his heavenly kingdom,
and watered us abundantly from time to time,
with the distillations of the showers thereof,
flowing from the clouds that he hath prepared and filled with his Holy Spirit,
to replenish his husbandry and vineyard with the mysteries of faith and godliness,
as the former rain in its season, and the latter rain in its season;
and clothed us with religious discipline and gospel order,
that no nakedness may be amongst us,
but every member of this body which Christ is the head of,
may be covered with his righteousness in words and actions,
following him (in the daily cross and self-denial
by faith in him) as lights in the world to the praise,
and glory of God.

And in order to carry on and perfect this good work for our establishment and his honour,
he hath raised and settled, and is raising, instruments according to his blessed promise,
that he would give to his people judges as at the first,
and counsellors as at the beginning: men fearing God and hating covetousness,
gifting them for this great work with his Holy Spirit of counsel,
with a sound mind and understanding, and a concern for his honour,
and prosperity of his blessed truth amongst men,
the enlargement and exalting of the government and
kingdom of Christ with all godly diligence,
according to the ability and gift of his Holy Spirit,
given to them for this work and service for the Lord and his people,
as help-meets in government,
and overseers and door-keepers of the flock and church of Christ,
walking before them as good examples in self-denial,
not only to the unlawful things of the world, but to the lawful things;
the Lord bounding them in their getting, and ordering them in their management,
and disposing thereof, that the flock may follow by their footsteps,
as they thus follow Christ.

And, dear friends, you of this nation know, that for several years past there hath been,
and yet remains a godly care on the spirits of such whom
the Lord hath thus raised and concerned as overseers,
that all things might be well in the church of Christ,
and that he may present it to the Father as a chaste virgin, without blemish;
and on this account much labour of love hath been bestowed at opportunities and seasons,
which the Lord hath put into our hands, and have been sanctified to us,
the Lord owning his work and us in it,
and honouring our assemblies in this service with his powerful, glorious presence,
to the overcoming of our hearts with comfort and satisfaction,
opening our understandings by the enlargement of his Holy Spirit,
in many things absolutely needful to be put in practice,
for the preservation of his people out of the snares of the enemy of mankind,
which he lays in the world, and baits them with the things of this world.
And God hath wonderfully owned and blessed our labours,
to our great comfort and encouragement, and the great benefit and satisfaction of many,
who give thanks and praises to the Lord for the benefit received, on many accounts,
through those close concerns and labours of love for the good of one another,
as saviours on Mount Zion.

And now that which remains, and chiefly is before us in this service,
is to warn and admonish the church of Christ,
to beware of the snares of that unwearied enemy, which he lays in secret,
and baits with the lawful things of this world, in this time of ease and great liberty;
for his baits are suitable to the times and seasons,
to answer the inclination of people`'s minds, that go from things that are above,
after the things that are below;
and it is easy to understand the generality of people are taken in his snares,
and carried away after riches, preferment, honour, greatness,
and vain-glory in the things of this world, that are uncertain, and soon come to an end:
and he is striving to break in upon the people of our society,
whom the Lord hath called by his grace out of the world,
to obey and follow him in all things, as lights in the world to his honour.

And this enemy of all righteousness hath prevailed on many,
that are not so careful and watchful in the light of Christ as they ought to be;
and others following their examples to get riches, and be big in the world,
invade other mens properties, and fail in their purposes,
so sacrifice religion and their own credit, to their greedy desire after gain,
and give occasion for men to brand us with the character of covetousness,
which causes the truth professed by us, to be evil spoken of,
stumbles the minds of some that otherwise might join with us,
and hinders the Lord`'s work of reformation on many accounts,
and grieves his good spirit, and wounds the hearts of his faithful servants,
that are given up in heart, mind, body, and substance, that the Lord may limit, bound,
order and dispose of them and all they have, and hold as stewards under him,
that hath all power in heaven and earth, with all due reverence, subjection,
and obedience,
where our preservation is from the inroads the enemy
makes to hinder the progress of the Lord`'s people,
and to make them unfruitful to the Lord as his vineyards,
in heavenly and spiritual things; but instead thereof to bring forth wild grapes, briars,
thorns, thistles and tares, the fruits of the mind, heart, spirit,
and affections that go in their own wills into earthly things,
beyond the bounds and limits of the Lord`'s everlasting truth,
which is great provocation for the Lord to curse the ground,
and to lay his vineyard waste, which he hath bestowed great labour upon,
that it might bring forth good fruit, to the praise, honour, and glory of his great name.

Now under a due consideration of the great injury and damage
the church of Christ hath and doth sustain in our day,
by this floating spirit that leads into the lawful things of the world,
beyond the bounds of truth,
and beyond the use for which they were created and given of God,
a great concern came upon several of us in a spiritual travail,
for the honour of God and the preservation of his people, the comeliness,
beauty and credit of the unspotted religion professed by us;
and under this godly care and concern the Spirit
and power of the Lord mightily appearing with us,
and in us, in which the testimony of the Lord Jesus rose in many,
as a standard lifted up against the invasions of an enemy,
and great labours and endeavours were used to stop this
insatiable spirit that is so eager after earthly things,
and yet not willing to be called by the name of covetousness,
and to bring it within the bounds and limits of truth.
This religious concern being practised from time to time for several years,
at such opportunities as the Lord put into our hands to be concerned in church affairs,
that nothing might get in or grow which God hath not sowed nor planted,
but be plucked up and rooted out in due time;
that the Lord`'s plant and good seed that he hath planted and sowed, might grow,
flourish, and bring forth good fruits in due season,
to the honour and glory of the great Husbandman,
that the cares of this world and covetousness of riches might not choke it.

Now we being at our province meeting, before mentioned,
and a great appearance of Friends, both men and women,
and the mighty power of the Lord amongst us;
under a weighty sense thereof the affairs of the church were managed in great unity,
peace and concord: and under this heavenly canopy of the Lord`'s ancient goodness,
a weighty concern came upon our spirits, as at other times on the like occasion,
concerning the bounds and limits of getting, and the right using,
the lawful things of this world; and how far Friends might safely go into them:
and much time being spent in church affairs to good purpose and satisfaction,
the meeting adjourned till the next day;
and after the meeting for the worship of God was over, then men Friends,
and ancient concerned women, met to consider of this weighty matter;
and accordingly Friends met and sat down in great silence,
retired to the Lord for his aid and counsel, and the Lord was pleased to appear,
and his power was great through his Spirit to our comfort;
and many hearts were melted before him, because of the weight of his goodness,
which bowed all spirits; and many heavenly things were opened in the testimony of Jesus,
concerning the bounds and right use of the lawful things of this world,
and in the demonstration of the Spirit and power of Christ then abounding amongst us,
and governing our assembly, and guiding our hearts and understandings,
unanimously it was agreed and adjudged,
that a competency of the lawful things of this world is sufficient for every one,
and is the right bounds, with a due consideration of every one`'s charge, station,
place and service.
And that mind which will not be content with this, bears the character of covetousness,
and renders such unfit to rule in the church of Christ;
and there was an unanimous consent, one by one,
to offer up ourselves to the judgment of the province meeting, or other approved elders,
as the province meeting shall think fit; if in any thing we do exceed those bounds,
that Truth (i. e. Christ) may bound us that hath all power in heaven and earth:
and in a subjection one to another in our possessions, holdings, callings, trading,
and dealing amongst men, not to be our own judges, or walk in the light of our own eyes,
considering the wise man`'s saying, that every man`'s cause is good in his own eyes;
but his neighbour finds him out, and in the multitude of counsel is safety.

Not that we intend to deprive any of the moderate
and lawful use of the things of this world,
or to take from any man his possessions, or to invade and take away property,
but to bring all things into right bounds, and set them in their right places,
that so none may be guilty of the great sin of abusing the Lord`'s mercies,
but might use and enjoy them to his honour;
that in so doing they may have his peace and blessing,
which indeed is the true comfort of all enjoyments.
Thus shall we give evident testimony to the world by our moderation,
even in the lawful things, that we are true followers of the Lord Jesus Christ,
in a self-denying life.
And thus, as help-meets together in the Lord Jesus, we may be as Saviours on mount Zion,
building up one another in our most precious faith,
and in our heavenly possession in Christ Jesus, over the greedy gain, greatness,
and vain-glory of the world, and perishing, fading things thereof,
that soon come to an end; and here the rich man will not glory in his riches,
but see the danger of them, and not lay hold of opportunities to heap up more,
to make himself and posterity great in the world; but rather endeavour to lessen,
that with more ease and cheerfulness he may serve
God and his generation with what he hath,
with all his might, being glad of every opportunity that presents, that he may do good,
and be rich in good works, considering he is a steward,
and his time uncertain in what he enjoys,
and that he must be accountable to the Lord of all,
for all things he possesses under him; and, under the like consideration,
the mean man will be glad that he is free from many temptations and snares,
that the rich in this world are liable to fall into,
and pierce themselves with many sorrows and hurtful lusts,
and bless the Lord for what he enjoys, not wanting food and raiment,
with which he is well content and easy in his mind, that is towards the Lord,
and seeks not from place to place, and from one country to another,
in a covetous mind to heap up riches, but looks to the Lord with an eye of faith,
to receive counsel from him in his undertakings, and dare not go beyond his limits,
nor without his countenance; and all murmuring,
repining and unbelief is kept out of the camp.

And there will be no craving spirits where the Lord rules, but all in their stations,
according to their ability and gifts,
endeavour to serve the Lord with all their might and substance,
in their places where the lord hath raised them, or ordered them, and may be serviceable;
shaking themselves from the dust of the earth,
putting on their beautiful garments of the Lord`'s
government and shining under the discipline thereof,
rising over the earth and earthly things in the life and power of Christ,
as lights in the world in this glorious day of the Lord,
wherein he is staining the glory of the lawful things of this world,
and the goodliness thereof,
by the brightness of his coming in the glory of his Father`'s kingdom;
and is whipping buyers and sellers out of the temple,
that it may be a house for the service of God, which holiness becometh; that he may walk,
sup, and make his abode, and the offering of his people may be acceptable to him,
when he hath purged away all this dross, tin, and reprobate silver.

Our hearts are deeply affected with the care and kindness of the Lord,
for our preservation from the snares of the enemy,
which he lays for us in the lawful things of this world, far more dangerous,
and we more liable to be taken in them in this time of great ease and liberty,
than in the time of persecution and sufferings,
to be frighted from our steadfastness in our faith and principles.

And, dear friends, we may well understand that as to our Society,
self-denial stands mostly in the lawful things, hoping,
by this time of this glorious day, you have overcome the base and unlawful things,
and your hearts and minds are cleansed from them by the blood of
Christ that sprinkles our hearts from an evil conscience,
and washes our bodies with the clean water of regeneration,
and renewing of his Holy Spirit.
And he that hath done this for us is perfecting what is lacking,
that he may present us to God the Father faultless to whom be praises forever.
Amen.

Subscribed, in behalf of the meeting, by

John Pim,

William Edmundson,

George Rooke,

Thomas Trafford,

Thomas Wilson,

Roger Roberts.

Postscript.--

At the first, when the Lord called and gathered us to be a people,
and opened the eyes of our understandings, then we saw the exceeding sinfulness of sin,
and the wickedness that was in the world;
and a perfect abhorrence was fixed in our hearts against all the wicked, unjust, vain,
ungodly, unlawful part of the world in all respects;
and we saw the goodly and most glorious lawful things of the world to be abused:
and that many snares and temptations lay in them,
and many troubles and dangers of divers kinds; and we felt the load of them,
and that we could not carry them and run the race the Lord had set before us so cheerfully,
as to win the prize of our salvation;
so that our care was to cast off this great load and burden
of our great and gainful ways of getting riches,
and to lessen our concerns therein,
to the compass that we might not be chargeable to
any in our stations and services required of us,
and be ready to answer Christ Jesus our Captain,
that called us to follow him in a spiritual warfare,
under the discipline of his daily cross and self-denial;
and then the things of this world were of small value with us,
so that we might win Christ, and the goodliest things of the world were not near us,
so that we might be near the Lord, and the Lord`'s truth outbalanced all the world,
even the most glorious part of it.
Then great trading was a burden, and great concerns a great trouble; all needless things,
fine houses, rich furniture, and gaudy apparel, was an eye-sore;
our eye being single to the Lord, and the inshining of his light in our hearts,
which gave us the sight of the knowledge of the glory of God,
which so affected our minds, that it stained the glory of all earthly things,
and they bore no mastery with us, either in dwelling, eating, drinking, buying, selling,
marrying, or giving in marriage; the Lord was the object of our eye,
and we all humble and low before him, and self of small repute;
ministers and elders in all such cases walking as good examples,
that the flock might follow their footsteps as they followed
Christ in the daily cross and self-denial in their dwellings,
callings, eating, drinking, buying, selling, marrying, and giving in marriage;
and this answered the Lord`'s witness in all consciences, and gave us credit amongst men.

And as our number increased, it happened that such a spirit came in amongst us,
as was amongst the Jews when they came out of Egypt,
and this began to look back into the world,
and traded with the credit which was not of its own purchasing,
and striving to be great in the riches and possessions of this world; and then,
great fair buildings in city and country, fine and fashionable furniture,
and apparel equivalent, with dainty and voluptuous provision,
with rich matches in marriage, with excessive customary uncomely smoking of tobacco,
under colour of lawful and serviceable,
far wide from the footsteps of the ministers and elders the Lord
raised and sent forth into his work and service at the beginning;
and far short of the example our Lord and Master Christ Jesus left us,
when he was tempted in the wilderness with the offer of all the kingdoms of the world,
and the glory of them, and despised them:
and Moses that refused to be called the son of Pharaoh`'s daughter,
and rather chose affliction with the Lord`'s people,
having a regard to the recompense of reward.
And the holy apostle writes to the church of Christ, both fathers, young men,
and the children, and advises against the love of the world, and the fashions thereof:
and it is working as the old leaven at this very time, to corrupt the heritage of God,
and to fill it with briars, thorns, thistles, and tares,
and the grapes of the earth to make the Lord reject it, and lay it waste.

But the Lord of all our mercies,
whose eye hath been over us for good since he gathered us to be a people,
and entered into covenant with us, according to his ancient promise,
is lifting up his Spirit as a standard against the invasion of this enemy,
and is raising up his living word and testimony in the hearts of many,
to stand in the gap which this floating, high, worldly, libertine spirit hath made,
and that is gone from the footsteps of them that follow Christ as at first,
and know him to bound them, and to keep in his bounds;
and not in their own will and time lay hold on presentations
and opportunities that may offer to get riches,
which many have had and refused for truth`'s sake,
and the Lord hath accepted as an offering, and rewarded to their great comfort,
and to the praise of his great name.

William Edmundson.

In the Sixth and Seventh month this year, 1669,
W+++.+++ Edmundson and George Rooke performed a visit to the North, and to Connaught,
accompanied by Abel Strettell, Richard Guy, and Henry Ridgeway.

Their first visit was to Friends in Ulster,
at their Province meeting at Richard Boyes`'s. Then visiting
some particular meetings of Friends in that province,
they went to preach the gospel in the following places.
Near Salter`'s town at Francis Parfons`'s they had a large meeting,
and many sober people came to hear truth declared there,
and seemed to be pretty well satisfied; then at Dungiven was another meeting;
these places are both in the county of Londonderry,
and there was some convincement about the latter place:
then they went into the county of Donegal and coming to a place called Raphoe,
a bishop`'s see, and being desirous to have a meeting with the people there,
they were much averse to it, and none of them would suffer a meeting in their house,
so the meeting was appointed at the market-cross; and the people gathered,
and George Rooke stood upon the cross, and declared the way of life to them;
and then the priests called the high constable to break up the meeting;
but understanding they acted of themselves, and not by any order from the government,
the meeting continued about two hours,
most of which time was spent in preaching the free gospel of Christ Jesus,
and the people were so well affected with truth,
that they got a large quiet meeting in the inn where they lodged that evening;
and William Edmundson set the power of truth over all hirelings,
and the free gospel of Christ Jesus above the tithing priests.
The next day they had a meeting in the morning about four miles from thence,
and in the afternoon a meeting at Letterkenny, both which were quiet,
and in the morning following a parting meeting,
where the sweet presence of God was richly enjoyed;
and there being three Friends that lived about eight miles north of that place,
they were advised to keep a meeting there (they being far from Friends)
the promise of Christ being where two or three meet in his name,
that his presence shall be with them;
and so a meeting was settled there for the worship of God.

Soon after, they took their journey for Sligo,
and came thither the seventh day of the week,
and got leave to keep a meeting in the market-house,
where many people came the next day and were sober;
and then they had a meeting six miles from Sligo at Killoony,
where the priest did what he could to hinder and frighten the people from coming,
but all in vain, for the meeting was kept to satisfaction;
and they not being clear of Sligo went back and had another meeting there,
where was a justice of peace, and many sober people,
and the way of eternal life was clearly opened to them,
and so they were left without excuse.
The next meeting they had was at a place called Carrickdrumrusk,
they being mostly British people that lived there,
and were very ready to come to the meeting, which was kept in an inn,
and a good satisfactory time Friends had with them.
Then they travelled to Longford, but none would permit a meeting there,
so they passed on to the Province meeting at Moat of Granoge,
where meeting with Friends from several parts, they were comforted in the Lord,
and one in another, giving account of their service,
and that a door was opened in those remote places to receive truth,
and the messengers of it, and the peace and satisfaction they enjoyed from God,
the rewarder of his faithful labourers.^
footnote:[See a further account of this journey in William Edmundson`'s Journal.]

This year (1700) also,
William Edmundson and George Rooke performed another
visit to several parts of the province of Connaught,
being a journey of about 342 miles,
of which a particular account may be seen in W. Edmundson`'s journal.

Barclay`'s Apology, printed in London,
was this year ordered to be distributed among strangers.

This year died James Greenwood and Ann his wife, of Grange in the county of Antrim,
a faithful couple,
being of one spirit (as well as joined together in the covenant
of marriage) wherein they were true help-meets to one another,
being endowed with many spiritual gifts and graces, which they as good stewards,
faithfully improved to the honour of the great Giver
and the benefit and comfort of his people.
They were of such a just and upright conversation, fearing the Lord and eschewing evil,
that the truth they professed was honoured by them;
their hearts being seasoned by the heavenly grace, so that they were as the savoury salt,
among those with whom they were conversant, being of a grave and weighty deportment,
aiming at the glory of God, and the good of souls in their concerns.
They were great lovers of peace and concord in the church,
and much concerned for keeping the unity of the spirit in the bond of peace.
They were strict observers of the apostles exhortation,
not to forget to entertain strangers,
their house and hearts being open to receive the travelling servants of the Lord:
for which service they were well qualified,
administering to them spiritual help and assistance, as well as outward entertainment.
James being for many years infirm in body, was unable to travel much abroad;
but Ann being healthy, both in body and mind,
was frequently serviceable at the general meetings of Friends,
where she appeared in such sweetness and evenness of temper, so savoury, grave,
deliberate, and reaching in her expressions,
that such as were in the service with her were much strengthened and encouraged,
by the excellent fruits of the Divine Spirit that appeared through her, both in doctrine,
discipline, and conversation.
Her words in her testimony were but few, and not forwardly expressed,
she being careful not to run before her guide, but to observe divine conduct,
under which her example was a check to forward, and rash appearances;
yet she was a nursing mother to the young and tender, a refresher of the weary,
an encourager of the distressed, and was so endued with heavenly wisdom,
and a taking way of expression and gesture in conference,
that even disorderly and obstinate persons were often times won upon by her.
They both died in the same year, in great resignation and assurance of peace with God.

The latter end of this year (1701) king William died who, during his whole reign,
allowed a Christian liberty to tender consciences,
the ever memorable act of toleration being passed in his reign,
and continued and confirmed in the reign of queen Ann,
by which the several dissenters were exempted from
divers penalties to which they had been before liable;
and now Friends throughout the nation peaceably enjoyed
their meetings for the worship of God.

Friends of Dublin suffered little this year (1702) for their
testimony against the superstitious observation of days,
Thomas Bell, mayor of that city,
having put forth a proclamation some time before the day called Christmas-day,
forbidding the tumultuous meetings of any men, boys, or apprentices,
under pretence of shutting down Friends`' shops;
also the seneschal of Thomas-Court and Donore did the like, both which proclamations had,
in a great measure, the desired effect of preventing the meeting of the wicked rabble,
their hurting Friends, breaking windows, etc. as had been usual in former years.

This year a chosen number of Friends in Ulster performed
a general visit through that province.

This year (1703) also John Page, mayor of the city of Dublin, counsellor William Neave,
seneschal of the Liberty of Thomas-Court and Donore, and counsellor Grace,
seneschal of Sepulchre`'s Liberty, by seasonably issuing proclamations as aforesaid,
as also lieutenant-general Earl, taking care that the soldiers should not be abusive,
protected Friends of the city from the usual insolence of the rabble,
so that they suffered little or nothing for opening their shops,
and following their lawful trades and employments,
in testimony against the superstitious observation of days;
and now little sufferings attended Friends,
except for their Christian testimony against tithes.

This year (1704), and in the fifty-sixth of his age, died Gershon Boate,
having been convinced about 1670, and the twenty-second of his age;
and the Lord was pleased to bestow upon him a gift in the ministry,
in the exercise of which he was many times fresh and lively,
and sometimes travelled both in this nation and some parts of England, Scotland,
and Wales.
He was ready and willing to serve truth and Friends with all his might,
both in travelling with Friends in the ministry,
and in seeking relief for such as were under sufferings;
and he was a man of such parts and interest,
that he seldom missed effecting the matter he took in hand.
He was of a quick apprehension, great abilities and courage,
and very serviceable to the country on several accounts,
and particularly with regard to the Rapparees that infested it;
and was wonderfully preserved through many imminent dangers,
from those blood-thirsty men who lay in wait for mischief.
By this means he became acceptable to the government, and had an interest among,
and a ready access to, persons in power,
which however he did not apply to his own promotion,
in the profits or honours of this world,
but to the advancement of truth and its testimony, and the good of his brethren.
He was a true servant of the church, and in its service contracted his last illness,
and died in great peace and resignation to the will of God.

Faithful Friends at this time (1705) were in good esteem, the government favourable,
and magistrates generally moderate.

This year several Friends, appointed by a province-meeting in Ulster,
performed a general visit through that province.

It seems not unseasonable here to observe,
that whereas for several preceding years repeated advices were given,
and earnestly recommended, from sundry half-year`'s meetings,
that Friends mold refrain from the too eager pursuit
of great concerns and encumbrances of the world,
in order that all might be restrained, if possible,
from those things that would hurt them inwardly or outwardly;
although it was a time wherein opportunities seemed to offer for getting riches,
by great trades, stocking of farms,
etc. yet several disappointments happened to those that took liberty herein,
particularly on occasion of a great decay of trade which ensued on the wars abroad,
so that some who flighted and rejected the timely advice and warning given them,
suffered great loss, both as to their inward condition and outward affairs;
but such who complied were sensible of the benefit thereof,
both with respect to their ease in the things of this world,
and their inward peace and satisfaction.

This year died John Clibborn of Moate Granoge,
a patient and faithful sufferer for truth`'s testimony,
an open-hearted man to entertain Friends and serve truth with his outward substance,
and very charitable to the poor.

Besides other ministering Friends who visited the nation this year (1706),
Thomas Rudd from England, landed at Dublin in the Sixth month,
and after being at Friends`' meeting there the Sixth day of the week,
on the day following, accompanied by our friends Robert Bradshaw and Joseph Gill,
both dwellers in the said city, he passed through four or five streets thereof,
uttering the following words,
viz. "`Oh the dreadful and Almighty God will dreadfully plead because
of sin;`" but before he was clear of that service,
some officers, by an order from alderman William Gibbons, mayor of the city,
brought him before the said mayor, and several other aldermen,
and the said two Friends went along with him thither; so a mittimus was written,
and they all three were sent to the Wheat-sheaf prison,
where they remained close prisoners three days,
and then were set at liberty by means of Friends`' application to the mayor, recorder,
and some of the aldermen; and Thomas, being unhealthy of body, went into the country,
thereby expecting some benefit, respecting his distemper; and passing Northward,
visited Friends`' meetings in Ulster province, and returned to Dublin; where,
being accompanied by the said two Friends,
he passed again through the same streets as before, declaring the former words,
and met with no opposition or molestation from the magistrates,
and afterwards went into other parts of the country where he had not been.
He visited most of Friends`' meetings in the nation,
and also had service in the streets of many towns
and public places in divers parts thereof.

This year died Anthony Sharp, who was born in Gloucestershire in England,
in the year 1642.
He was convinced about the year 1665, by the ministry of William Dewsbury,
at a meeting in prison at Warwick.
He came to settle in Dublin in 1669,
and some time after was concerned in a public testimony;
and Friends in Dublin then being but few,
and those exposed to sufferings on the account of tithes,
etc. he was very serviceable to them by advice,
and appearing before rulers and magistrates on their behalf,
wherein his endeavours were often blessed with success,
as also by entertaining Friends cheerfully at his house.
He was an industrious man in the concerns of this life,
and having justly acquired the reputation of a wise and honest dealer,
his credit among men, and outward substance daily increased,
which however did not prove a means of choking the good seed in his heart,
he being both a large contributor to the poor,
and devoted to serve truth and Friends in his generation,
both with his substance and understanding.

He was a man of an honest, sober, and clean conversation;
for although he had occasion to converse with people of various persuasions and tempers,
and temptations of divers kinds attended;
yet through the goodness of God he was so preserved,
that there was no just cause to reproach truth on his behalf,
being very careful to avoid needless company keeping, and being leavened^
footnote:[i. e. Conformed to the Dispositions.]
into the spirits of those he conversed with, by too much familiarity;
but would take occasion to discourse of the principles of truth,
or some religious subject whereby they might be diverted from those
vain discourses that are too frequent in many companies.
In his public testimony he was many times zealously
concerned for the convincement of strangers,
being gifted for that service, having a good understanding, a ready utterance,
and a clear way of delivery; and indeed his labour of love in that respect did,
through the blessing of God, prove effectual to several.
He has left in manuscript several pieces written in defence of truth,
against priests and others; particularly on immediate revelation,
on the call of a gospel minister, on women`'s preaching, baptism, the Lord`'s supper, etc.
He travelled several times through this nation and in England; and in the year 1695,
visited Holland, some parts of Germany, and Denmark, and some time after, Scotland,
in the work of the ministry; and at length,
having been very serviceable among Friends for many years, and finished his course,
he laid down his head in peace.

This year (1706) several Friends, by appointment of the Province meeting,
made a general visit through the province of Ulster,
and returned satisfactory accounts of their service.

This year (1707) also several Friends, appointed by the Quarterly meeting of Leinster,
performed a visit to the several Monthly meetings of that province to good satisfaction.
And in the year 1708,
a like general visit was made through the meetings in the province of Munster,
with good effect.

This year (1708) Joseph Pike published a Treatise on Baptism and the Lord`'s Supper,
which, though ordered to be printed at a national charge,
the author chose to do at his own cost.

N+++.+++ B. It is no new thing, that the church of Christ should flourish under persecution,
and, on the other hand, suffer in a time of outward ease and tranquillity;
for this has been usually her lot.
Accordingly,
the former part of this history is pretty much made up of accounts of the zeal,
piety and fervent charity that prevailed among the brethren in times of persecution;
on the contrary, the remaining parts of this narrative of the state of the church,
in the days of tranquillity and cessation from persecution,
will afford but too many instances of the decay of love towards God and one another;
and it were doing injustice to the present time to pass by the following observation,
viz. That in the year 1708,
complaint was made from divers parts of the nation to the Half-year`'s meeting,
of a lukewarm spirit among the professors of truth,
and particularly of the want of that true concern
and travail of spirit which ought to prevail,
in the meetings for the worship of Almighty God;
and it appeared to Friends at their National meeting,
upon a serious consideration of this complaint and grievance,
that it might be very much occasioned through the too great love of,
and too eager pursuit after, the things of this world;
for which reason the cautions formerly given forth against this evil, in divers minutes,
were revived, and the more diligent observance thereof recommended.

About the same time I find there was a weighty concern among Friends,
for the regulation of men`'s and women`'s meetings,
that none might be admitted members thereof,
but such who were well inclined and concerned for the prosperity of truth,
according to the first institution;^
footnote:[See the Treatise of Christian Discipline.]
and William Edmundson wrote an epistle this year on this head,
which was approved and recommended by the National meeting,
and may be seen at the end of his journal.
Among other ministering Friends who visited this nation this year (1709) was James Dickinson,
who had a particular warning to Friends and others,
of a day of great mortality approaching.

This year John Exham, a Friend, aged about eighty years,
came from his dwelling at Charleville, in the county of Cork,
and visited Friends in their families through most parts of the nation.
See a further account of him in the year 1721.

This year, (1710) and in the sixtieth of his age,
died John Watson of Kilconner in the county of Catherlough.
He was convinced about the year 1673, by the ministry of John Burnyeat;
when he took up a resolution to be faithful,
according to the then present manifestation of his duty given him,
not withstanding its exposing him to some difficulties,
and sufferings from his parents and relations,
for refusing to join with them in their way of worship, for using the plain language,
etc. which was hard to be borne by his father, who with the archdeacon, John Plummer,
used their endeavours to reduce him to a compliance
with their church-ordinances by persuasion,
which proving ineffectual, the archdeacon threatened him with a prison;
to which he answered, "`I do not fear it,
but will make ready for one,`" and accordingly he
disposed of some of the land which he held,
that he might have less rent and encumbrance lying on him.

In the year 1678, a meeting was settled at his house,
which caused the said archdeacon Plummer, and Richard Boyle,
bishop of Leighlin and Femes, to be angry, and soon after he was sued in their court,
and taken by a writ de excomunicato capiendo,
for refusing to pay one pound sixteen shillings,
demanded towards the repairs of the worship house at Fenagh;
but before he was taken to prison, the said Plummer meeting him,
spoke with seeming kindness to him, saying, if he would submit to them,
and not suffer meetings to be at his house, all should be passed by and forgiven him;
which he, for conscience sake refusing to comply with, the said Plummer being enraged,
said, "`Take him away to prison; there he shall lie till he rots;`" and then going away,
John Watson called him back,
and said he was to tell him that he should not prosper in what he intended, against him,
which accordingly came to pass; for although John was sent to prison that day,
and closely confined for about six months, he after that,
by the favour of John Tench the sheriff, obtained some liberty to go home to his family;
whereat the said Plummer being much displeased,
went the week before the ensuing assizes to consult with the bishop,
in order to sue the sheriff for granting him that liberty;
but in returning home he was suddenly smote with the loss of the use of his limbs,
and continued in that condition for some time before he died,
where upon the suit dropped for that assize,
and he lived not to see his design accomplished on the said John Watson,
who however continued a prisoner above two years.

He received a gift in the ministry in the year 1676,
in the exercise of which he approved himself a faithful steward,
and a diligent and zealous labourer,
often visiting the meetings of Friends in this nation, as also in England;
and besides attending the meetings in the province of Leinster, to which he belonged,
he usually once a year, whilst of ability to travel,
visited the meetings of Friends in the other two provinces of Ulster and Munster,
and the Lord was pleased to bless his concern and labour of love therein,
to the convincement of some, and edification and comfort of many.^
footnote:[Robert Lecky of Kilmainham, accompanying him and Anthony Sharp,
in a journey to the north, was convinced, and became a serviceable man to the Society.]
He was also serviceable in discipline, being zealous to keep up good order,
and that all might walk as becometh the gospel, in an holy and blameless conversation,
wherein he was a good example, and careful to rule well his own house.
He died in great peace of conscience, and resignation to the will of God,
with the comfort of an assurance that he had finished his day`'s work in his day.

A general visit was performed, (1711) by Friends appointed by the Province meeting,
through the province of Leinster, in order to stir up Friends effectually,
to put in practice the several advices that had been from time to time given forth,
from national and other meetings.

This year the following Friends were appointed to go over to London,
in order to join Friends in England in soliciting the English parliament,
for further ease with respect to the affirmation,
(see the year 1696 above) and accordingly they went over on that account,
viz. Alexander Seaton, John Barcroft, Thomas Ducket, John Boles,
Nicholas Harris and Gershon Boate, son of the late Gershon Boate.

And in the year 171 2, a treatise concerning oaths,
formerly printed at London in the year 1675, was, by order of the Half-year`'s meeting,
reprinted here for a general service, to the number of one thousand.

Among other ministering Friends from abroad, who visited this nation this year,
was James Hoskins, who having been here last year,
and upon some extraordinary occasion returned to England, landed a second time in Dublin,
went from thence northwards,
and had meetings among strangers in the counties of Derry and Donnegal.
At Londonderry he was handled roughly, and put out of the city,
nor would they suffer him to have a meeting,
yet he had good service in several places thereaway.
Afterwards he went into Connaught, accompanied by several Friends from Dublin,
and had several meetings in that province among strangers, and without molestation,
except at Castlebar,
where the people were intimidated from going to the meeting by sir Henry Bingham,
the chief man of that place, and justice of the peace,
who threatened to send them to the house of correction if they went to the meeting,
and by his authority the said James Hoskins was haled out of the meeting,
put into bridewell, and kept prisoner there about two days.

This year died that eminent and faithful minister and elder William Edmundson,
of whose labours in doctrine and discipline a particular
account hath been given in the foregoing part of this history.
It seems however not to be superfluous, in this place,
to give a short sketch of his distinguishing talents and character.

About the year 1650 he went into the army,
and continued a soldier some time under the parliament,
in the civil wars in England and Scotland,
but being religiously inclined he grew weary of that way of life,
the Lord leading him from a carnal to a spiritual warfare;
and in the year 1652 he quitted the army and came to Ireland.
In the year 1655 he became first concerned to speak a few words in meetings,
in fear and humility,
being under a jealousy lest a wrong spirit might get entrance to deceive him,
under the likeness of an angel of light; but as he abode faithful,
he grew in the exercise of his gift, and became an able minister of the gospel,
and an instrument in the Lord`'s hand of converting many to righteousness,
in this nation, as also in England and America.
He had a great share of natural parts, though but of a mean education,
was sound in doctrine, plain in preaching, and free from affectation,
and was often times wonderfully enlarged in declaring
the mysteries of the kingdom of Christ,
as well as the mysterious workings of Satan;
he had a singular gift in opening and applying the typical part of the law,
to the substance in the gospel; he was sharp in his testimony against transgressors,
yet tender to the dejected and penitent;
he was very often zealously concerned to exhort Friends to beware of the love,
and too eager pursuit of the riches and greatness of the world,
as being the chief engine the enemy of truth had to hurt us a people;
a truth of great importance,
which as it has been abundantly verified among the succeeding professors of the same way,
it may be worth while to give a specimen of his sentiments on this head,
as a hint not useless to many of us:

I know, (says he, in a letter to a friend,
recorded in his journal) that the eagerness after the lawful things of this world,
at this time, hinders many Friends`' growth in the precious truth,
and their service to it in their day,
though otherwise of great parts and abilities to do much service for truth on many accounts,
as instruments in the hand of God; but they cannot serve God as they ought to do,
and as the day requires,
nor please the Captain of our spiritual warfare as good soldiers,
whilst they cumber themselves with the things of this world;
and this is the great failure and stumbling-block at this day,
and too many of our society are hurt thereby, who have in measure escaped the unclean,
unjust and unlawful things of this world,
and washed their garments from the spots thereof, and so bear the name of virgins,
but sit down in the dust, in the lawful things of this world,
without a due consideration and true regard of the
right use and service of them in the creation,
and to the bounds and limits of truth,
in the getting and using of them in their places and services,
and so (as the foolish virgins) want the oil that
would make their lamps burn and their lights shine;
on which account great danger doth appear, that many, as the foolish virgins,
will be shut out of the bridegroom`'s chamber, when those that are ready,
who have shaken themselves from the dust and put on their beautiful garments,
having oil in their lamps,
and arising in the brightness of this glorious day of the Lord,
having their affections set on things above, where Christ is,
and not on things that be upon the earth, enter with Christ into the wedding chamber.

He was a most zealous and faithful labourer in the exercise of his gift,
for the edification of the churches both at home and abroad;
he went to America on this account three times (where
he pursued his journey and the work before him,
oftentimes in imminent danger of his natural life,
committing it to God that gave it) first in the year 1671,
in company with George Fox and others, then in 1675, and lastly in 1683,
where he had great and good service both in the ministry of the word,
and in settling meetings for Christian discipline; of which meetings,
as well as those for worship, he was a most constant attender,
and frequently had meetings among Friends and strangers,
in divers remote parts of this kingdom, and in England;
often travelling in the service of the gospel in great bodily weakness and pain,
supported by faith, when natural ability failed, even to extreme old age;
so that in the 83rd year of his age he travelled on this account.
He had an excellent gift in prayer and supplication, so that his appearance,
when under the performance of that part of divine worship,
was with that dread and awfulness upon his spirit,
that it made a great impression on the spirit of Friends,
causing tenderness many times to come over the meeting.

It is hard to say, whether he was more eminent in doctrine or in discipline:
for the latter he was eminently gifted, gladly joining with George Fox and others,
in settling men`'s and women`'s meetings through this nation, and when settled,
he was a zealous labourer in them; a faithful elder, worthy of double honour,
the care of the churches being much upon him; particularly,
he was greatly concerned that none should be admitted members of such meetings,
but those who were of clean and orderly conversations, walking as examples to the flock,
having a concern upon their minds for the promotion
of truth and righteousness in the earth;
and many times he had good service in such meetings,
in clearly declaring the necessary qualifications of such;
beginning at those whom the Lord put his spirit upon to assist Moses,
who were men fearing God and hating covetousness;
and going through the law and the prophets, and the doctrines delivered by Christ,
as also the discipline and order of the primitive church coming out of the wilderness;
that the authority of truth might be kept up in these meetings,
and the members thereof be faithful men,
so that justice and true judgment might be maintained
in all those meetings without respect of persons,
and judgment be placed upon all disorderly and unruly persons;
that God`'s house might be kept clean, which holiness becomes forever.

He had a great share in bearing the burden in the heat of the day,
which he cheerfully underwent, and was endued with valour and courage,
suitable to the work it pleased God to call him unto,
in the times of the sufferings of Friends in this nation.

He was of a solid and grave countenance and deportment, striking an awe over the wicked,
light and airy; a reprover of and terror to evil doers,
yet an encourager of those who did well, but with prudence,
so that none might be lifted up thereby.
He did not seek after popularity, but was rather shy,
not intimate with any he had not trial and true knowledge of,
nor willing to lay hands suddenly on any but those he found to be faithful.

He was temperate in eating and drinking, his discourse weighty,
and mostly on the things of God, tending to edification and instruction;
a careful and tender father, +++[+++if he erred on either hand,
it was rather on that of austerity than indulgence]
a firm friend and kind neighbour, given to hospitality;
and notwithstanding the great charge he was frequently at,
in his travels in the work of the ministry,
yet he was exemplarily liberal in collections for the poor; etc. and,
although it was often his lot to be separated from
those dear enjoyments of wife and children,
for the gospel`'s sake, he ordered his temporal affairs with discretion,
so that there might be no want in his family, in his absence,
of either commendable employment or necessaries.
A man of a truly public, Christian spirit,
frequently and successfully concerned in applying to those in authority,
for the relief of suffering brethren, as well as other suffering Protestants,
in the time of the troubles in Ireland, A. D. 1689;
being zealous to make use of the influence he had with the government,
for the public good.

He has left behind him a journal of his own life, to which are annexed several epistles,
and a letter of examination to all such who have assumed the place of shepherds,
herdsmen and overseers of the flocks, of people of all sorts, in Christendom,
to see if their accounts be ready, and what order their flocks are in,
with a few lines of good news to the several flocks, dated from Jamaica, A. D. 1672,
as also a paper concerning offerings to God in prayer and supplication,
which is here inserted from his journal,
and recommended to the observation of those whom it concerns, viz.

The offerings, that are acceptable to God, must be offered in righteousness,
and with clean hearts and lips, for the Lord is pure and holy,
and will be sanctified of all that come near him,
and his worship is in spirit and in truth; wherefore prayer, supplication,
and addresses to God being a special part of his worship,
must be performed in spirit and truth, with a right understanding, seasoned with grace,
and with the word of God,
even as the sacrifices under the old covenant were
to be brought and offered in clean vessels,
seasoned with salt and with fire: so all, now under the new covenant,
who approach so nigh to God, as to offer an offering in prayer,
must have their hearts sprinkled from an evil conscience,
and their bodies washed in clean water, and sanctified with the word of God,
and their senses seasoned with his grace and spirit in divine understanding,
and must offer that which is sound and pertinent,
which the spirit makes known to be needful, whose intercession is acceptable,
as a sweet smelling sacrifice in the nostrils of God, and a savour of life unto life,
and of death unto death, though in sighs, groans, or few words, being sound, pithy,
and fervent.
For the Lord knows the mind of the spirit, that makes intercession to him,
who hears and graciously answers.^
footnote:[Lev. 21:22-6:20,
32+++.+++ Duet. 33:19. Ps. 73:13. Mark 9:49-50. Lev. 2:13.
Heb. 10:22. Rom. 8:26-27.]

And now all are to be careful, both what and how they offer to God,
who will be sanctified of all that come near him, and is a consuming fire,
who consumed Nadab and Abihu that offered strange fire,
though they were of the high priest`'s line.
And there may be now offerings in prayer and supplication,
in long repetitions of many words, in the openings of some divine illuminations,
with a mixture of heat and passion of the mind, and zeal beyond knowledge,
and in this heat, passion and forward zeal,
run on into many needless words and long repetitions,
and sometimes out of supplication into declaration,
as though the Lord wanted information; such want the divine understanding,
and go from the bounds and limits of the spirit, and will of God,
offer what comes to hand, (like that forced offering of king Saul,
which Samuel called foolish,
and the strange fire and forced offering,) and lavish all out,
as if there were no treasury to hold the Lord`'s treasures,
that may open and present to view at times, for their own benefit;
so such in the end coming to poverty and want, sit down in the dry and barren ground:
wherefore all are to know their treasury, and treasure up the Lord`'s openings,
and try the spirit by which they offer, that they may know the Lord`'s tried gold,
and not mix it with dross or tin, and know his stamp, heavenly image and superscription;
and not counterfeit, waste, or lavish it out, but mind the Lord`'s directions,
who will call all to an account, and give to every one according to their deeds,
and all the churches shall know, that he searches the heart and tries the reins.^
footnote:[Duet. 4:24. Lev. 10:1-2. Heb. 12:29. 1 Cor. 14:17. 1 Sam. 13:12-13.
Isa. 50:11. Matt. 12:35. Rev. 3:18-2:23.]

As under the old covenant, there was the Lord`'s fire,
that was to burn continually on the altar, and received the acceptable offerings:
so there was strange fire, which was rejected, and the offering that was offered therein.
And now in the new covenant there is a true fervency, heat, and zeal,
according to the true knowledge of God, in the spirit and word of life,
that dies not out, in which God receives the acceptable offerings:
so there is also a wrong heat of spirit, and zeal without true knowledge,
that with violence, through the passion of the mind and forwardness of desire,
runs into a multitude of needless words and long repetitions,
thinking to be heard for much speaking, but is rejected, and is a grief,
burden and trouble to sensible weighty Friends,
who sit in a divine sense of the teachings and movings of the Lord`'s good spirit,
in which they have salt to savour withal, though the affectionate part in some,
who are not so settled in that divine sense, as to distinguish between spirit and spirit,
is raised with the flashes of this wrong heat and long repetitions,
which augments the trouble of the faithful and sensible,
who are concerned for the good and preservation of all. Lev. 6:13.

We read that the priests of Baal in their offerings were earnest, hot, and fierce,
and cut themselves, making "`long repetitions from morning until evening,
so kept the people in expectation to small purpose;`" 1 Kings 18:26,28,29,
but Elijah having repaired the Lord`'s altar, and prepared his offering,
in a few sensible words +++[+++pertinent to the matter and service of the day and time]
prayed thus in the spirit and power of God, "`Lord God of Abraham, Isaac, and of Israel,
let it be known this day, that thou art God in Israel, and that I am thy servant,
and that I have done all these things at thy word.
Hear me, O Lord! hear me, that this people may know, that thou art the Lord God,
and that thou hast turned their hearts back again,
which the Lord heard and answered.`" 1 Kings 18:36-38.
So here a few sensible words,
with a good under standing pertinent to the matter +++[+++without needless repetitions]
were prevalent with God.

And our Saviour Christ Jesus, when he taught his disciples to pray, bade them,
"`not be like the hypocrites, or heathen, who used many repetitions,
and thought to be heard for their much speaking.
Therefore,`" saith he, "`be not ye like unto them,
for your Father knoweth what things you have need of, before ye ask him.`" Matt. 6:7-8.
And the prayer which he taught, is full of matter, and to the purpose,
though comprehended in few words, and all his disciples and apostles are to learn of him,
and observe his directions, and not the manner or customs of the heathens and hypocrites,
in this weighty matter of approaching nigh unto God with offerings,
in prayer and supplication.

Our Saviour also left us a good example, written for our learning,
when he was under the sense of drinking that cup of sufferings for the sins of all mankind,
and to offer to God that great offering for their ransom, he prayed in these words:
"`O my Father, if thou be willing, remove this cup from me, nevertheless not my will,
but thine be done.`" Luke 22:41-42.
And in giving thanks in these words, "`I thank thee, O Father!
Lord of heaven and earth, because thou hast hid these things from the wise and prudent,
and hast revealed them unto babes, even so, Father,
for so it seemed good in thy sight.`" Matt. 11:25-26.
And how many more examples in the Scriptures are on this account,
full and pertinent to the matter, comprehended in few words,
and not like the heathen in tedious repetitions,
who think to be heard for their much speaking.
Therefore all who approach unto God with their offerings, are to be watchful and careful,
both what and how they offer under this administration of the spirit,
and dispensation of the new covenant.

I have travelled under a deep sense and concern in this matter for some time.

William Edmundson.

The 12th of the First month, 1695.

He also wrote an epistle of advice to Friends, which was published in the year 1701,
containing wholesome caution against many superfluities then creeping in,
with respect to eating, drinking, apparel, furniture, trading and farming;
to which he subjoins some admonitory hints relating peculiarly
to the women in the exercise of their spiritual gifts,
wherein he signified,
that although in this day that Christ is repairing the tabernacle of David,
raising up the ruins thereof, and restoring the church into her ancient order,
where the wise-hearted and inspired may work for God and their own salvation,
men their part, and women their part,
by the appointment of Christ the great and wise undertaker;
and women inspired with the testimony of Jesus may pray and prophesy;
and even such faithful and approved women,
who are truly inspired and gifted for the work of the ministry, may, as the Lord moves,
go forth and travel in that service with the unity of faithful elders and brethren; yet,
that, as in preparing for the tabernacle of the old covenant, the women had,
by the wisdom of God, the easy part, the needle-work allotted to them,
being the weaker vessel, and of weaker capacity,
although help-meets in their places to the men; so now,
in repairing the tabernacle of the new covenant and restitution of all things,
the inspired women have, in general, the easier part of the work allotted to them,
(according to the rules and instructions, laid down in holy Scripture,
in the second chapter of Titus) suitable to their temper, capacity, and ability,
and the men the harder labour in this work,
as travelling journeys to publish the doctrine of the kingdom of Christ,
often attended with hardships, sufferings, perils, and temptations of divers sorts,
which in general the hardy temper, capacity,
and ability of man is the better adapted unto.

Thus does he express himself concerning this matter, telling us,
that he has sometimes observed some miscarriages and scandals to have befallen some,
for want of a due regard to the bounds and limits appointed by the wisdom of Christ;
not that he was an enemy to women`'s preaching, as some have insinuated,
but tender of the glory of God,
and jealous lest at any time they should make an ill use
of the evangelical liberty of speaking to edification,
exhortation, or comfort, which they enjoy in our Christian society.

To conclude; this great and good man,
having laboured in doctrine and discipline for the good of the church above fifty years,
according to the ability given of God, through many troubles, deep exercises,
and perils of divers kinds by sea and land in the wilderness,
by robbers and blood-thirsty murderers, by open opposers and enemies to truth,
and worst of all, by false brethren under the same profession,
was made at length to triumph in him in whom he had believed, saying,
as he often did in his old age, that the Lord was his song and his strength;
and having run the Christian race and kept the faith,
departed this life in peace with God, unity with his brethren,
and good-will to all mankind, in the 85th year of his age, and 57th of his ministry.

The following is a genuine epistle of the said W. E. written in his old age to his friend,
and fellow-labourer in the gospel, George Rooke in Dublin,
on occasion of an intended journey of theirs to the north of Ireland,
from which his sickness appears to have prevented him.

Tenele, 1704.

Dear Friend G. R.

I received thy kind letter per R. S. by which I understand thy purpose
in the will of God to visit Friends in the North the next week,
if the increase of my illness do not let.

Now, dear George, I must take notice of thy care and kindness for and towards me;
yet the public service for the Lord and his people must be preferred before all,
in which point it is to be doubted many are behind-hand in their day`'s work;
and as to the present affliction I lie under, it is very uncertain, only to the Lord,
which way it may turn, for it hangs in the balance of ups and downs;
but through the Lord`'s mercies, and Friends`' prayers,
my sharp afflictions are mitigated within the compass of my weak abilities,
and especially in the night-seasons, which are made something easy,
and Friends`' daily visits of love, from several places,
is refreshment in the Lord Jesus; and as to that of desiring to see me in Dublin,
I can say with a good heart, I am clear of them all,
and I hope of the blood of all men in the service of the Lord and my generation;
and I well remember when I was at Dublin last, in the public meeting,
being filled with the power and spirit of the Lord Jesus Christ,
in which many heavenly principles were closely spoke to,
in the authority of which I told them, as at many other times,
I was clear of all their transgressions, if I should never see them there again;
for I have not shunned to declare the whole counsel
of the Lord as he was pleased to reveal it to me,
and he is still supporting over both the frowns and smiles of the
spirits of this world in the testimony of truth and faith of Jesus,
which, by the Lord`'s assistance,
I have kept through many oppositions and contradictions of divers kinds:
and what have I now to do of my day`'s work?
my outward parts grow feeble, but blessed be the Lord of my abilities,
in the main I am as strong as ever,
and long and desire before all things to be dissolved from this old,
decayed house of clay into my lot of rest, which the Lord hath appointed for me,
where all the clamours of the unfaithful to God,
and false to their own professed faith and principles, cannot reach me.

And now, my trusty friend,
thou knowest my inclination was to have borne thee company to the North,
to visit Friends where my first labours in truth`'s service were,
and where my first sufferings were,
and to have taken my leave of them in the love of God,
and sweet communion and comfort of his holy spirit, as I did with Friends of Munster,
last at Clonmel,
where we had a sweet comfortable parting in that which is over death and the grave;
but being put by,
I desire my true love in the Lord Jesus Christ may be remembered to all true-hearted,
faithful friends and brethren; that they may know I am not afraid of death or the grave;
with desires that they may so steer their course,
that when the time comes that will overtake all,
with comfort of spirit to the praise of God, they may say, "`Death, where is thy sting?`"
and "`Grave, where is thy victory?`"
This is a combat belongs to this warfare: blessed are they that overcome;
in order to which the Lord gird you with strength and courage,
and with his spirit of wisdom and counsel, and of a sound mind,
that in a noble resolution, in the fear of God,
you may stand firm for his testimony in all its branches,
as it is received and established.

Dear George, I scribble over this, under great infirmity of body,
but hope it will be accepted.
My true and hearty love is to thee, in the Lord Jesus Christ, whether in life or death,
the will of the Lord be done.

William Edmundson.

Besides other ministering Friends from abroad, Benjamin Holme was here this year,
and spent seven months in this visit; having meetings pretty frequently among strangers,
and being instrumental to the convincement of several in this journey.

In some part of his travels he had been accompanied by John Burton,
with whom having parted, he went towards Londonderry, accompanied by Patrick Henderson,
intending to have had a meeting in that city, which the magistrates would not permit,
but dispersed those who came together; whereupon Benjamin wrote to the magistrates,
shewing how disagreeable it was to Christianity thus to
treat men who came to call the inhabitants unto repentance:
also he and Patrick wrote to the inhabitants of the city in general,
reminding them of the late calamities they had been under,
and of their forgetfulness of God`'s deliverance of them, for which ingratitude,
with other provoking sins, the Lord would bring his judgments on them,
if they did not timely repent.

After this our said Friends had several meetings in that county,
and in the county of Donnegal, among strangers, as also in the province of Connaught.
Benjamin also travelled into Munster twice, and had several meetings among strangers,
and from thence passed again, through some parts of Leinster,
into Connaught a second time, and had several meetings with the people in that province:
he also visited those few Friends that had lately been convinced near Sligo,
having a particular concern upon his spirit to strengthen and encourage
them to a faithful perseverance in the way of life and peace.

In the Second month, 1713, Benjamin and three other Friends, coming to Longford,
set up their horses at an inn,
desiring of the landlord that they might have a meeting in a room in his house,
to which he consenting, they went to invite the people, and acquaint the sovereign;
who said he had nothing against their having a meeting,
but desired them to acquaint Benjamin Spann of it,
who was both a justice of peace and minister of the parish.
The Friends, considering him as a magistrate, thought it proper to speak to him;
accordingly Benjamin Holme, and Benjamin Parvin, went to him and told him,
that they had appointed a meeting that day there at their inn; but he,
in a furious manner, told them they should have no meeting in that town.
B+++.+++ Holme mildly told him they did not come to ask his leave, but as he was a magistrate,
to acquaint him with it, and that he might come to it if he pleased,
and pleaded the queen`'s toleration for liberty of conscience,
and so parted for that time.

Their landlord hearing of this their success, being somewhat cowardly, said,
he durst not by any means let a meeting be held in his house; "`For,`" said he,
"`Mr. Spann will ruin me.`"
Whereupon B. Holme and B. Parvin, went to seek for another place,
but meeting with the said priest in the street,
he attacked them afresh upon the same subject.
B+++.+++ Holme, as before, pleaded the queen`'s toleration (but the priest,
in a furious manner, denied that either man or woman in England or Ireland,
could grant a toleration), and desired him to do as he would be done by.
The priest said, "`That is no rule for me;`" upon which they came to an argument,
in which the priest finding himself pinched, called for a constable;
but no constable appearing, he laid hold of B. Holme himself; and,
seeing the jailer near, he commanded him to take him into custody,
and the priest led him by one arm, and the jailer by the other,
till they put him into the dungeon; and after using abusive language,
the priest also himself laid hold of Benjamin Parvin, and delivered him to the jailer,
who obeyed his orders, and put him also into the same place,
where the Friends sat together in great peace and sweetness for about six hours;
and then the jailer took them into a room above stairs,
where several friendly persons came to see them;
and among them one that brought them a discharge from the priest,
upon condition they should promise not to come again,
nor hold any meeting in or near Longford.
They told him they could make no such promise,
letting him know that no true minister of Christ was his own master,
but must answer the requirings of him that had called him into his work and service;
and so they parted, and were locked up that night in the room,
where they lay on the boards in their coats and boots.

Next day a friendly man, a merchant in the town, sent them a bed;
and B. Parvin asked the jailer,
whether he had any thing from the justice but his bare word; he answered,
"`No.`" B. Parvin told him,
he thought he could not lawfully detain them above twenty-four hours without a mittimus,
and that then they would demand their liberty.
The jailer said he would go and tell Mr. Spann that, and so he did,
and in a short time came again, and said he had a mittimus.
They desired a sight of it, and with some entreaty got it,
and found the tendency of it to be,
"`that whereas they came in contempt of the queen`'s authority, by force and arms,
in a hostile manner, to the terrifying the queen`'s peaceable subjects,
to hold a Quaker`'s meeting in the borough of Longford,`" etc.
When they read it, they told the jailer it was false,
and demanded of him where their arms were;
and that it was not they that did contemn the queen`'s authority, but the priest,
who had in the open street, before the crowd of people that gathered about them,
denied that either man or woman in England or Ireland,
could grant a toleration for liberty of conscience.

The jailer went to the priest and reported to him the conversation they had had,
and when he returned to them, he said the priest wished he had never seen them,
who in the evening of the same day,
sent an order under his hand to the jailer for their liberty;
whereupon the jailer told them, they were free from their commitment,
but he wanted his own and the sheriff`'s fees.
They told him they were innocent prisoners, and therefore they could pay no fees.
He said he would forgive them his part, but the sheriff said they should pay their fees,
or lie in jail till they rotted,
and commanded the jailer to turn them into the dungeon again; which he did not,
but gave them their liberty two nights,
upon their word to return to the jail if the sheriff did not acquit them,
which he did at last without their paying any fees.
When B. Holme was set at liberty from his confinement at Longford,
he went a second time into Ulster, being accompanied by Alexander Seaton,
and they visited divers places in the county, of Down, as Dunaghadee, Newton-Clanobuys,
Cummer, etc. having large meetings among the Presbyterians,
unto whom they were drawn forth, in the love of God, to declare the way of truth.
Our said friend B. Holme published this year at Dublin,
A Tender Call and Invitation to All People, to Embrace the Offers of God`'s Love,
and to Break Off From Those Things that Provoke Him to Anger,
Before the Day of Their Visitation Pass Over.

This year (1713) it was proposed to the national meeting by Friends of Ulster,
that they apprehended it might be of service to publish
something concerning the universal love of God to mankind,
and against that erroneous principle of absolute predestination to all eternity;
and accordingly the chapter in Robert Barclay`'s Apology, treating on this subject,
with a preface to it by John Chambers,
was ordered to be reprinted to the number of two thousand,
as was also two thousand of Alexander Pyott`'s Apology.

John Hall, of Monktheselden, in the county of Durham, was here this year,
and besides visiting Friends and others in the three provinces,
delivered the following prophetic warning^
footnote:[As the compiler of this history desires
to discharge the part of a faithful historian,
and, in the foregoing part of this work,
hath related instances of prophetic declarations,
which appear to have been visibly accomplished;
so he thinks himself obliged also to relate such declarations of this sort,
whereof the visible completion hath not as yet appeared;
of which kind is this here mentioned, besides several others to the like general purpose,
viz. Intimating that God would speedily pour forth his judgments upon the people,
for their sins and disobedience:
in reference to which it may be observed,
{footnote-paragraph-split}
lst.
That the ancient Jews, when a prophet had foretold calamities which did not come to pass,
made great allowances in their censures of that prophet,
in considerations of the great mercies of God:
concerning which we may undoubtedly very safely say with the prophet, Lam. 3:22,
"`It is of the Lord`'s mercy that we are not consumed,
because his compassions fail not.`"
Thus though the prophet Jonah did, by divine direction,
denounce destruction on the city of Nineveh,
and this within the limited time of forty days; yet, upon their repentance, we read,
chap.
3:10, that "`God seeing their works, that they turned from their evil ways,
repented of the evil he had said he would do unto them, and he did it not.`"
And, in Genesis 18, upon the intercession of Abraham with God,
on occasion of the denunciation of the destruction of Sodom, God said,
"`If there shall be found ten righteous persons in the city,
I will not destroy it.`"
{footnote-paragraph-split}
2ndly.
That the "`judgments of the Lord are a great deep,`" Ps. 36:6. And as to prophecies,
even divers of those recorded in holy Scripture,
it is no new thing for them to be obscure,
it being allowed that many of them have not been understood until they were fulfilled.
{footnote-paragraph-split}
3rdly.
If it be supposed that some of the persons concerned in these declarations might,
from their great zeal against sin,
conclude that the judgments of God were never to
be poured out upon an ungrateful and rebellious people,
than they really were, this will be no objection against, but an argument for,
preserving a record of this sort, even as an instructive lesson of humility, fear,
and caution,
especially to such who may apprehend themselves authorised
to publish any thing concerning the determinations of Providence:
which undoubtedly over-rules the various successions of peace and war,
plenty and scarcity, sickness and health,
dispensed unto nations according to adorable wisdom; which dispensations,
though they may be often very mysterious to shortsighted frail man,
and though the punishments due to sinful nations and particular persons,
may not be apparently and suddenly inflicted in this life,
yet inasmuch as the doctrine of rewards and punishments in a state of futurity,
when every man shall be judged according to his works, is revealed, published,
and universally received,
it behooves us in the mean time to exercise patience and submission to the divine will,
and rest assured that the time hastens when those who "`obey not the gospel of Christ,
shall be punished with everlasting destruction,`" according to 2 Thess. 1:9.]
in several cities, towns, and villages in this kingdom, in the Second, Third,
and Fourth months of this year, viz.

My friends,

I am come in the dread and fear of the great and Almighty God,
to proclaim the great and terrible day of the Lord amongst you, that is come,
and coming upon all sin and wickedness.
Haste to repentance, I beg it of you, lest the day come upon you at unawares;
and remember that you are this day warned to the salvation of, God;
and whether you will hear, or whether you will forbear, God will be clear of your blood;
and unto this I am concerned to add,
that a terrible and grievous plague God will send into this your land and nation,
that shall sweep away thousands of its inhabitants; they shall lie dead in their houses,
and dead in the streets;
there shall scarcely be a people living found willing to bury them,
their stench shall be so great.
Oh repent and turn from your evil ways, that God may shew you mercy.

Signed by John Hall.

Accounts were given from Ulster,
that there was a great openness to hear truth declared in many places in that province;
and more stirrings in the minds of people to receive truth than for some time past;
and that some were convinced, especially in some parts of the county of Derry,
near Dunclaudy, and near Sligo and Scarnegirah;
and that there were a few near Monaghan convinced,
who held a meeting for the worship of Almighty God.

Upon a representation and complaint offered from
one of the provinces to the National meeting,
in the Ninth month this year,
that some under our profession are too much captivated with the love of earthly things,
and more earnest in the pursuit of the riches and greatness off this world,
than of the heavenly treasure that would enrich their souls unto life eternal; and that,
in the present time of outward ease and plenty,
there is as much need as ever for Friends to be heartily, and zealously concerned,
against those things that tend to draw into the world, or a liberty from under the cross;
advice and caution was given forth from the said National meeting, that Friends,
in this day of outward tranquillity,
might not be eager in laying hold of opportunities
of launching into great things in order to get riches,
or to the endangering the properties of others;
and it was desired that every monthly meeting might inspect into these things.

This year died John Chambers, a native of Scotland,
who sometimes travelled abroad in the work of the gospel,
yet his most continued service and labour, was in Dublin,
where he resided about sixteen years,
the Friends of which city have given an ample testimony
concerning him to the following purpose:

He was one whom it pleased the Lord to visit very early;
in order to prepare and sanctify him as a chosen vessel for his service;
and whilst but a youth, to endue him with a gift in the ministry; in which,
being faithful,
he grew and became skilful in the word of righteousness and mysteries of Christ`'s kingdom;
and, having a dispensation of the gospel committed to his trust,
a necessity was upon him to preach the same in the
love of Christ which constrained him thereunto,
and he freely ministered of the gift he had received, according to the ability God gave,
as a good steward and servant to many for the Lord`'s sake,
labouring for the salvation of souls: but more particularly,
he was zealously concerned that those who had known God`'s gracious
visitation to their souls might in an especial manner,
beware of an inordinate love and desire after the lawful things of this world,
lest thereby the good seed should be hindered from bringing forth fruit to perfection.
He was earnest, with such who, having been descended of godly parents,
that had served the Lord faithfully, and been honourable in his church,
were of pretty orderly conversation among men, and had a clean and plain outside,
and a form of religion by education, that they should not trust in these things,
but be earnestly concerned to seek after God for themselves,
that they might witness the washing of regeneration and circumcision of the spirit,
that they might be Israelites indeed, Jews inward,
and the seed of Abraham by faith in Christ Jesus,
and so succeed their parents in the line of righteousness.

He was very helpful to Friends upon many occasions, having good natural endowments,
sanctioned by the inspiration of the Almighty,
whereby he was well qualified not only for doctrine,
but also for discipline in the church,
and to stand in defence of the truth against oppressors.
He was sharp in reproof to wilful and obstinate sinners, but when any had slipped,
through weakness or sudden temptation,
and were truly humbled under godly sorrow for the same,
he was very tender toward them in order to their restoration.
He departed this life in peace, in the thirty-ninth year of his age.

This year also died Sarah Baker, alias Peyton, born at Dudley in Worcestershire,
on whom it pleased the Lord to bestow a gift in the ministry about the age of twenty-one,
in the exercise of which having laboured both at home and in Ireland and America,
she afterwards was married to Samuel Baker, an honest friend of the city of Dublin,
where she resided for the most part of the remainder of her time,
and was very serviceable to truth and Friends in many respects;
being devoted to the service of God,
and a diligent labourer and fellow-helper with her brethren in the gospel; and,
in the authority of Christ Jesus, who had called her into that service,
did freely and frequently, in larger and lesser assemblies, preach and teach,
the things concerning the kingdom of God,
and the redemption that is in his Son Christ Jesus, in whom male and female are one, and,
as a faithful mother in Israel, was carefully concerned,
not only to feed the babes in Christ, as furnished by him,
to give unto the household in general a portion of meat in due season,
rightly dividing the word of truth committed to her, and speaking the same faithfully,
that she might be clear in the sight of God of the blood of all men.
She often mourned for Zion`'s sake, and for the abominations committed in the land,
pouring forth fervent supplications unto God the Father,
in the name of his beloved Son Christ Jesus, for the prosperity of his church,
and tranquillity of the nations; and, as one skilful in lamentation,
would invite others thereunto, that both male and female might mourn apart,
first for themselves, and then for others.
She had also good service in women`'s meetings, being a diligent follower of good works,
in relieving the poor and visiting the sick and afflicted in body or mind.
When outward abilities declined, her inward strength was renewed,
and her lamp being trimmed, did burn clearly, through the supply of heavenly oil,
to the conclusion of her time;
and at her departure she had the comfort of an evidence of peace with the Lord,
and that a crown of righteousness was laid up for her.

The Sixth month, this year, died queen Anne,
during whose reign Friends peaceably enjoyed their
meetings for the worship of Almighty God;
and now king George, through the good providence of God,
succeeded to the throne of these realms,
who soon manifested his mild disposition towards Protestant dissenters,
so as not in the least to impair the toleration allowed them by law.

Indeed the public tranquillity was greatly interrupted (1715) by
the apprehensions of the destruction and ruin that threatened us,
through the rage of some restless people, disaffected to the king and government,
who raised a rebellion in Scotland,
being animated with expectation of foreign assistance, whose counsels were blasted,
and their progress effectually stopped through the mercy of Providence:
and as in that time of great affliction Friends were calm in their spirits,
and shewed true affection to the Protestant interest, and peace of the nation,
it was well accepted by the government,
which hath since been demonstrated in several instances,
particularly in their exempting us from the penalties we had been liable to,
for our conscientious refusal of fighting and swearing, of which hereafter.

In the mean time the following address was drawn up on the above mentioned occasion,
and presented:

To Charles Duke of Grafton, and Henry Earl of Galway, Lord`'s Justices,
and Chief Governors of Ireland.

The Humble Address of the People Called Quakers,
From Their National Half-Year`'s Meeting Held in Dublin, the 10th of the Ninth Month,
1715.

May it please the lords justices,

The many and great privileges continued unto us under the king`'s
mild and favourable government and those in authority under him,
more especially that we have liberty peaceably to worship Almighty God,
according as he hath persuaded our consciences, we esteem great blessings,
and lay us under great obligations of humility and thankfulness,
first to God and then to the king, for the same.

The king having been pleased to place you chief governors of this kingdom, we take leave,
in our plain way to congratulate you upon your safe arrival here,
and to assure you that we are well affected to king George and the present government,
and have a just detestation and abhorrence of all conspiracies, plots,
and rebellion against the king and government;
and that as it hath been our declared principle as well as practice,
ever since the Lord called us to be a people,
to live peaceably and behave dutifully toward those,
whom he hath placed in authority over us, so, by divine assistance, we are resolved,
according to our duty, to demean and behave ourselves towards the king,
and those in authority under him.

And as we are a people liable to sufferings for our tender consciences towards God,
we entreat, that if any such thing should attend us under your administration,
you will be pleased favourably to admit us to lay our suffering case before you,
in order to seek for redress.

We sincerely pray to Almighty God,
that he may endue your hearts with divine wisdom so to govern,
that virtue and piety may be encouraged, and the contrary restrained,
that so his blessing may attend you here in this life,
and eternal happiness in that to come.

Signed in behalf of said meeting, by

George Rook, Gabriel Clark, John Hoop, John Dennis, John Barcroft, Jacob Fuller,
Nicholas Harris, Thomas Ducket, William Sandwith, Richard Sealy, Thomas Willson,
Thomas Lightfoot, Nicholas Lock, Amos Strettell, William Richardson, Eli Crocket.

This year Thomas Wilson and several other Friends,
by approbation of the National meeting,
went over to attend the service of the yearly Meeting at London, as usual;
and at this time with a particular view to join Friends of England,
in soliciting further ease with respect to the affirmation,
some Friends having been great sufferers,
by reason they could not make use of the affirmation in the form it then was.
(See the year 1696.)

Besides other Friends of the ministry, Thomas Story, from Pennsylvania,
was here this year, who had several meetings, not only among Friends, but strangers,
and for the most part without interruption, except at Kilkenny,
where great opposition was given, as will appear in the following narrative, which,
because it also furnishes divers and entertaining remarks, I here insert,
as it stands in the said Thomas Story`'s journal.

They (at Kilkenny,
1716) had exercised their violence and disturbance upon Elizabeth Jacob once,
and another time upon Margaret Hoare and Abigail Craven, and hindered the meetings;
which Friends had bore for peace sake, without any complaint to the government;
but now they proceeded more violently, for as we were met, according to appointment,
on the twenty-seventh of the Twelfth month 1716 about the second hour after noon,
and many of the towns people with us,
some time after I had stood up in came Arthur Webb and Robert Shervington,
and made disturbance, bidding me to be silent, and the people to disperse.
I did not mind them for some time, but went on,
till they had so disturbed the meeting that the people were not in a condition to hear,
and then I stopped and asked who they were and by what authority they did that:
they answered they were the churchwardens.
I replied, that the churchwardens, as such, had no business with us,
or power to hinder us, and desired them to desist, and sit down quietly as others did.

They seeing that would not fright us, as they had imagined,
then began to speak to particulars of their own sort,
threatening them with the bishop`'s court, and excommunications,
and such like frightful things, and began to take some names in writing,
which some being afraid of, went out, but the greatest part stayed,
and some were much troubled at the spoiling of the meeting, for it had begun well;
but the envy of Satan, and the pride of ungodly men rising higher,
whilst we were at this work, in came one Joseph Worley,
one of the mayor`'s sergeants at mace, and a constable, with a warrant,
and I being still standing,
and sometimes exhorting the people as well as I could in such disturbance,
they bad me come down and go with them,
for they had a warrant from a justice of the peace to apprehend me,
and disperse the meeting.
Then I said, we were well known to be an innocent people, readily subject to government,
either actively or passively, but desired them to have a little patience,
till I had cleared myself among the people;
and they did not seem very forward to take me away,
till some of the superior persecutors towards the door, cried out,
"`How well do you execute your warrant?`"
And then they took me and Edward Cowper, Henry Ridgway, and John Harris,
away in custody up to the justice`'s house, but he would not be seen,
being much troubled that he had signed the warrant,
it having been ready drawn by Robert Connell, the bishop`'s register,
and sent to the justice by the bishop, desiring him to sign it,
which he had done with great reluctancy.

They then took us from place to place, to find a justice, but none cared to see us;
till at last we were brought before the mayor, and this Connell,
who being one of the aldermen, was also a justice of the peace for the city, ex officio.
They were a little rough, and pretty high upon us, but the Lord,
for whose name and cause we were there, kept us over their spirit and power.
John Boles, John Lackey, Samuel Watson, Thomas Pim, John Pim, Jr.
and other Friends, continuing the meeting, and many of the people with them;
the officers also brought away these Friends last named,
before the mayor at the same time.
They charged us with a riotous and unlawful assembly; I told them,
they themselves did not believe it to be a riotous assembly;
and there were many witnesses that we were peaceable,
till the churchwardens and their officers disturbed us.
Then Robert Connell himself confessed we were not making any disturbance,
but said it was an unlawful assembly,
the act of toleration in England not extending to Ireland.
I answered, that act being for the liberty of the subject,
extended everywhere in Ireland, and other countries,
where the subjects of England are settled under the crown of England.
Then they demanded security for our appearance at the assizes,
and for our good behaviour in the mean time.
We told them, we were not of ill behaviour, and therefore needed not to be bound;
but seeing their wicked design, we all refused;
they then wrote a mittimus pretending to send us to jail;
but at last they told us we might go where we pleased; only they charged us,
upon pain of what should follow, not to have any more meetings there, for if we did,
they would take more severe measures with us.
Then they having a full bottle of wine upon the table, would have given us some,
but we all refused it, at which they were angry, and so we left them,
and went down to Thomas Dale`'s at the Swan, where many of us lodged,
and pretty many Friends being together there after supper,
we concluded to have another meeting next morning,
and some Friends were appointed to give notice to the mayor, some to the justices,
some to the soldiers, and some to the people of the town.

28th. The next morning, about nine, we went to this second meeting,
where the people did not gather much till about ten,
and I had stood up about half an hour, when in came the same churchwardens,
and made the like disturbance as before, taking names,
and threatening the people with the bishop`'s court and excommunication,
frightening some, but most did not seem to mind them, and I went on for some time,
till also came two of the mayor`'s sergeants at mace, and constables,
and a great mob after them, and they commanded me to be silent,
and the meeting to disperse.
Some of the meaner sort went out of the house as fast as they could, being fearful;
but many stayed to see the issue, and they taking me into custody, I went with them,
but they took no other friend.
The mayor, this alderman Connell, and some others, being together,
I was had before them without any warrant; they were very angry,
and gave me some threatening language.
I told them, they were not to insult the king`'s peaceable subjects,
nor exercise their own passions upon them; but if I had broken any law,
I was subject to the law, either actively or passively, and if they acted without law,
they also were punishable by the law.
They were very angry still, and the mayor said, I had assembled myself with others,
contrary to law, and demanded security for my appearance at the next assizes,
the sixteenth of next month, at the city of Kilkenny,
and in the mean time to be of good behaviour.
Then I said, "`What law have you here in Ireland against our meetings?`"
The mayor said, "`There is no law for them here;`" then said I,
"`There is none against them; and where there is no law, there is no transgression;
and the act of toleration in England gives us,
as well as all others the king`'s Protestant dissenting subjects,
liberty everywhere in his dominions.`"
Then they wrote a mittimus as followeth, viz.

City of Kilkenny, fs.
By John Birch, Esq.
Mayor of the said city, and Robert Connell, Esq.
one of his Majesty`'s Justices of the Peace for the said city.

We herewith send you the body of Thomas Story,
he unlawfully assembling himself with several other persons,
and refusing to find sufficient security for his appearance next assizes,
and for his good behaviour, and him in safe custody to keep,
till thence discharged by due course of law; and for so doing this shall be your warrant.
Given under our hands and seals this twenty-eighth day of February, 1716.

John Birch, Mayor,Robert Connell.

To the Keeper of his Majesty`'s jail, of the said city, These.

Here is a copy also of the warrant, viz.

Com.
Kilken.
Com. Civit.
Kilken,By Ebenezer Warren, Esq.
one of his Majesty`'s justices of the Peace for the said counties.

Whereas complaint hath been made unto me, that a set of people called Quakers,
are riotously assembled, these are therefore in his Majesty`'s name,
to will and require you, and every of you, on sight hereof, to disperse the said Quakers,
and in case of resistance or refusal,
to apprehend the bodies of the several persons so refusing or resisting,
and them so apprehended to bring before me or some other
of his majesty`'s justices of the peace in the said counties,
to be dealt with according to law, whereof fail not at your peril,
and for so doing this shall be your warrant.
Given under my hand and seal this 27th day of February, 1716.

Ebenezer Warren.

To the several Constables and Officers, in and through the said Counties.

This justice Warren having all along in parliament (for he was
a member) been friendly and kind to Friends in all their concerns,
and being inadvertently precipitated into this affair by the bishop,
we were better satisfied that we had this second handle to proceed upon,
than to have any occasion for his name in the contest;
and so I was sent to the common jail of the town, among thieves in irons,
where I stayed not long in the custody of the jailer, till Anthony Blunt,
the sheriff of the city, a very civil young man, and loyal to king George, came to me,
and shewed his resentment sufficiently at their doings;
for he not only called for the mittimus,
that we might have a copy of it (which the jailer had refused,
being an Irish papist) but left it in my own hand till he returned,
going immediately to some of the justices (Warren for one) to have
their opinions and concurrence in taking me to his house,
which he readily had, and accordingly took me with him,
and provided me a very great room in his house, and agreeable accommodations,
to the disappointment of that great episcopal envy thus levelled against me.
All this I observed to be the Lord`'s doing,
for the furtherance of the gospel and his own glory,
and the Lord was with me in a good degree, to my great comfort and only sure help.

On the Sixth and Seventh days came Friends from several parts to see me,
and many stayed in town till the First-day, being the third of the First month,
and in the forenoon we had a meeting in the sheriff`'s house,
where his wife (a very good-natured sober woman) and family were present,
and many of the neighbourhood.
We had a good open time,
wherein I had an opportunity to expose Antichrist and his ministers,
which I am apt to think went to the bishop`'s ears, as it did quickly through the town,
the people wondering at our boldness, not knowing our foundation.

4th. The next day I went to take the air in the late duke of Ormond`'s gardens there,
and some Friends with me, and several people came to us,
and among others some French Protestants, and an Irish papist; who seemed friendly,
and repeated some verses against such as seemed to be religious,
but aimed at nothing but promotion and worldly honour and glory by it.
I guessed what he was, and gave him the following lines,
which he took on a piece of paper with a pencil:

Natural religion was simple first and plain,

Tales made it myst`'ry, offerings made it gain;

Sacrifice and shows were at length prepared,

The priests ate roast-beef, and the people star`'d.

He seemed pleased with the verses.
Then I told him some people`'s religion made them worse than their natural temper,
which could not be right; for the end of true religion is an improvement upon nature,
and restoration from the fall, even in this life,
and rendering men more sociable and safe; but that priestcraft of many kinds,
tending to one evil end, had, as to great part of mankind,
eluded all the means hitherto offered for the help of man,
and made a prey of him instead of that aid designed;
for though there is nothing more plain than religion in its native simplicity,
yet the priests, the better to effect their own designs,
had invented abundance of lying mysteries to confound and amuse the people,
and persuaded them that offerings of many kinds were essentials of religion,
which offerings were ever at the priest`'s disposal, and for his gain and advantage;
and taking advantage of the natural propensity of the people to admire tricks and shows,
much of that had been invented to gull the people,
setting them a gazing at shows which are of no value,
whilst the cunning priests eat up the roast,
for they dearly love to have the ruling of it, and in whatsoever they differ,
in this they all agree, with feigned words to make merchandize of the people;
and how to have them for their own gain, and promotion is the great bone of contention,
which will ever continue till the people receive the Lord Jesus,
and turn to his light and grace as their true teacher.

In the mean time, as we were at this sort of conversation, in came justice Warren,
alderman Haddock, and Clark, the collector of the king`'s customs, and some others,
and entering into conversation with us, some told them of the verses,
and desired me to repeat them, which I did, to their satisfaction;
and by degrees they fell to discourse upon my confinement,
which they all did with considerable resentment, and some of them observed that,
to make a show now after the people had talked so broad in the streets, the mayor,
and that party, had shut up the mass houses, which before had been connived at;
and also how angry they were with our meeting the day before,
but could not help themselves, since I being a prisoner,
could not be hindered from speaking to such as came to me: and very friendly they were.

In the mean time in came the mayor and alderman Connell in a great chase,
which was heightened to see these persons with me conversing so friendly together.
Their business was to persuade justice Warren, alderman Haddock,
and whom they could besides, to join with them to send me out of the county,
from constable to constable; for I becoming very burdensome to them,
they had fallen upon this contrivance to get rid of me;
and their power extending no further than the town,
they could not send me out of the county,
but out of the town only and then they feared I would come in again immediately,
but if out of the county, being some miles,
it is probable they imagined I would not take the pains; but in this,
instead of helping themselves, they were worse; for as they advanced towards us,
I began to speak to these persons with me, above-named,
concerning the grounds upon which my adversaries built all this their structure,
viz. upon a supposition that the toleration act extended not to Ireland;
but I told them they were mistaken, for all men by nature are free,
till that freedom is taken away, either by policy or force.
Some penal laws then, made by an antichristian policy, and applied by tyrannical force,
having obstructed the liberty of the subjects of England for a time,
yet that liberty was not destroyed, but that force being removed, liberty revived,
and turned into her natural channel; for there are many statute laws in England,
wherein though there are new forms and clauses of enacting, yet, in reality,
are not initiatory of new matter, or new laws,
or privileges never before claimed or enjoyed by the people of right;
but declaratory only of rights and privileges in
possession by them and their ancestors before,
endangered by evil counsellors to kings and princes, who,
for their own advancement in Tavour,
are too frequently the wicked instruments of tyrannical and enslaving counsels,
where they meet with any degree of propensity in
the tempers of their princes biasing them that way;
and (of like nature is this act of toleration in England) which native rights
and privileges all Englishmen carry along with them into all regions of the world,
where they settle under the regimen of the crown of England, now upon a very worthy head,
who declares for liberty to all his Protestant dissenting
subjects throughout his dominions the world over,
and that indulgence they now enjoy everywhere but here.

The act of toleration then extends to Ireland, America, and all the king`'s dominions,
being in its nature declaratory, not only of English, but also of gospel liberties,
and which we now insist upon against the unjust force of such as oppose themselves here;
and that this is and ever hath been the mind of the king and his predecessors,
since that law was made, is plain, by extending that liberty and indulgence here,
as likewise to all his English dominions; and not only thus,
but the king hath given us his royal word for his protection,
upon several addresses on sundry occasions,
and particularly upon one from our last Yearly meeting at London,
the twenty-sixth day of the Third month, 1716;
and another since from our last National meeting at Dublin here in Ireland,
to which he was pleased to answer in these words,
viz. "`I thank you for the assurance of duty and affection
to my person and government contained in this address,
and you may always depend upon my protection.`"
I myself being present with many more when the king
received us with this first address in his own bed-chamber:
so great was his condescension and regard to his loving and peaceable subjects.
But it seems the mayor and magistrates here think it their
interest to insist upon an opinion quite of another nature,
at the hazard of what may follow; for you may assure yourselves,
we are as jealous and tenacious both of our gospel and natural liberties,
as anybody here can be bent to deprive us of them.

This being finished, the mayor and his party shewed a great deal of rancour,
but could not help themselves, and immediately after,
the mayor and Connell made application as aforesaid for assistance;
for their envy had made them both mad and blind; but instead of that,
the justice at once refused it,
and told them he had done too much of this drudgery for them already,
and would do no more, but would leave them to their own measures.
This vexed them heartily, and occasioned some more words,
which were pretty hot on both sides, till the justice,
and the rest that were for the king and indulgence,
asked them how they came to connive at so many masses in view,
and be so furious upon the king`'s friends and peaceable subjects.
"`And pray, Mr. mayor,`" said he,
"`what notice have you taken of the seditious sermon you
heard yesterday in the afternoon in the little church?
You can hear such with pleasure,
whilst you treat these loyal subjects with so much severe usage.
Did you, sir, demand that person`'s notes, and bring him to account for it?`"
Said the mayor, "`That was my lord bishop`'s business, not mine.`"
"`If that was not your business, being a matter of religion,
pray how comes it to be so much your business to meddle with these people,
who have given you no other occasion but about their religious opinions;
to which they have equal right and liberty with all
other his majesty`'s Protestant dissenting subjects,
and are much more useful to the government than some you connive at;
and pray from whom arises the common danger?`"

We, hearing them thus far, and things rising higher and higher,
thought best to withdraw and leave them, the dispute turning favourably on our side,
and so we did: but in the evening the sheriff told me that they ended in heat;
and that the mayor and alderman Connell,
finding they could not have any aid of the others, were resolved, as they pretended,
to send me out of the town next morning by the constables, and that if I came again,
they would put me in the stocks.
I told him I did not fear them, let them run the length of their chain;
for though they thought to frighten me with their threats,
I knew the laws better than they imagined, and that they could not do it,
but by illegal violence.

5th. But the next day the mayor was much cooler,
and intending to go out of town the day following,
to meet the judges at Wexford (being deputy clerk of the crown), he took up the mittimus,
and sent me word by the sheriff, that I was at liberty,
and might go when and where I pleased; and said also,
that he would not have done what he had done against us but that the clergy, as one man,
greatly urged him to it; saying, they had thought him a man for the church,
but to find him so remiss in suppressing the Quakers, looked quite otherwise: and added,
that for his own part he did not care what meetings we had,
but intended to get out of the way of it,
and leave alderman Connell in his place (as he ought of course) till he returned,
hoping all would be over in his absence.

Upon this message,
I told the sheriff that they had committed me publicly by a mittimus till the assizes,
as if I had done some heinous crime,
and as on the one hand I could not accept of a private discharge, so on the other,
this discharge was not legal,
which was an indication they were either ignorant or arbitrary;
for they ought to have returned their proceedings before the judges,
that the matter might be heard at the affixes; but in a case of discharge before that,
it ought to have been by a liberate in writing, under their hands and seals,
or of some other justices, and therefore I remained with the sheriff;
which displeased my adversaries worse than before, and heightened their rage.

Many Friends visited me from divers places,
and on the Seventh day (being the 9th of the First
month) came some from neighbouring places,
and considering together of a meeting next day,
we spoke to the same person about the same place we had before,
and he readily granted it.
So all was prepared, as seats, etc. and notice was given by some Friends,
to alderman Connell (now deputy mayor) and the justices, of what we intended,
but he said he would disperse us again, and that we should not have any meeting there;
however we went to meeting,
and though I had some things in my mind to say in the meeting,
before I found the proper time to stand up, one of the churchwardens came,
and soon after the mayor`'s sergeant at mace, commanding the people to disperse,
and the churchwardens took their names,
and threatened the people with the bishop`'s court.
Then I reasoned the case a little with the constables and sergeants,
and they seemed troubled that they were put upon using us so, but could not help it,
being under authority; and after awhile I went with them,
having first made some remarks on things to the people,
and they put me in jail the second time, where I was hardly well entered,
till they brought William Brookfield of Dublin thither also;
for some Friends from thence coming to see me, and he among others,
and the meeting continuing after they had brought me away, William had stood up to speak,
and some of the constables took him down and brought him to us.

We had been in prison but a small time till the sheriff
came and took us home to his house,
where, the other Friends came to us, after the meeting was over, which they held,
notwithstanding all the disturbance, till it regularly ended.

But the deputy mayor being come from his worship sent for me before him,
and seemed very angry, and asked me how I came to appoint another meeting,
being in custody?
Then, said the sheriff, "`Sir, the gentleman was not in custody,
for Mr. Mayor took up the mittimus before he went out of town,
and told me he was at liberty,
only he would not go out of the town till he himself thought fit, being free,
as he apprehends, to go or stay, at his own election.`"
Then, said I to the deputy mayor, "`These proceedings are very arbitrary,
what have I done now to deserve imprisonment?`"
"`Did not I tell you, sir,`" said he, "`that I would disperse you,
(for I had met him in the street as we went to meeting)
and that you should have no meeting here?`"
"`It is true,`" said I, "`but since there is no law against our meeting,
thou hadst no right to say so, nor was I obliged to take notice of it, being without law;
but besides, the gospel must be preached,
and God must be worshipped according to his own appointment,
whoever will make laws to the contrary,
or apply an unjust and illegal force to restrain it.`"

Then said one of the sergeants to the deputy mayor, "`Sir,
this gentleman said nothing in the meeting,
he was not preaching;`" and immediately he laid hold on that to get rid of us,
(for he wanted his dinner, then staying for him) and said, "`I cry mercy,
I thought you had,`" and so dismissed me; but before we parted,
I told him that although he had used us so ill,
I had a secret apology in my mind for him,
and yet could not be positive whether he deserved it; and that was,
I conjectured that he did not act altogether from
a native spring of dislike in his own mind,
but as excited by some other person or persons,
for some other reasons than perhaps he cared to express or own; upon this he told us,
he had no enmity against Friends,
but had upon occasion forgiven some of them fees (being
register of the bishop`'s court) to the value of seven pounds;
and so we were dismissed, without any further conditions.

About three in the afternoon we went to meeting again in the same place, and the bishop^
footnote:[Sir Thomas Vescy.]
hearing of it, and walking in the Tholsel, said to one of the sergeants,
if we met again he would have them put us in the stocks till he came from church;
but being sat, many people came to us, and the Lord,
who never fails nor forsakes his own, was with us, to our great comfort,
whilst envy and rage tormented our enemies.
I had something to say, and had gone on some time,
the people being greatly desirous to hear, and very still,
and satisfied with what they heard, till in came the constables and sergeants again,
but so faintly, and with apologies, that they could hardly touch me;
but after some time one of the sergeants named the bishop to be concerned in it,
which I laid hold of,
and told the people we were not ignorant all this time who was at the bottom,
but now they heard plainly it was the bishop; and after some further remarks,
viz. that as our Lord said,
"`Some of you shall Satan cast into prison,`" was now fulfilled in us;
for though that evil one could not cast any into prison by himself, as he is a wicked,
destroying spirit; yet as ungodly and wicked persecutors are excited,
hurried and instigated to that evil work by Satan, he, as the first mover,
is said to do it;
so that they might plainly see on what bottom they were who thus abused us;
and the people (nay even many of the Papists who came thither
to hear and see) were generally displeased with them,
and the truth reached them through our works and patience,
and exposed our enemies to the just censure of all.

The sergeants and constables taking me away, many of the people followed, calling out,
"`shame,`" and blaming the magistrates, but we desired them to avoid disturbance,
that no advantage might be taken.
The officers became so troubled and ashamed,
that they entreated me to walk up to my lodging, till the church was done,
but I told them I was in their custody, and could not go but where they took me,
and they went with me to the sheriff`'s house,
where they expressed their great concern that they should be in offices
that subjected them to actions so much against their inclinations;
but the meeting continuing after I was brought away, William Brookfield had a good time,
in a short testimony among them; and though some constables were there,
they stood without as if they had no mind to understand or hear anything;
and the meeting ended in order, and Friends were greatly comforted.

In the evening the deputy mayor sent me word by the sheriff,
that he would wait on me by and by at my lodging, about that afternoon`'s meeting.
I replied, that was not so proper; but that if he had any thing more to say,
and required it, I would wait on him where he pleased.
The sheriff told him what I said,
and he sent the sheriff to ask me if I intended to go out of town the next day,
and if I did, he had no more to say: but if I did not go out, he would put me out.
I replied,
that if the mayor had sent to ask me that question without any threats annexed,
I would have answered him freely and plainly as to my intent,
but was not to be frightened, being at my own liberty to stay or go as I pleased.

This the sheriff told him, and then he made the sheriff take it down in writing,
which he did; but told the mayor, he would keep it in his own custody,
and accordingly shewed it to me; the mayor, I suppose,
thinking to make me afraid by this poor little shift.
Then I told the sheriff, I intended to go out of the town in the morning,
to take some meetings in the country, and return thither again at the assizes,
the latter end of the week.

Then the sheriff told me, the bishop was very angry with him,
and so were all his creatures, for letting me have my liberty,
and had sent for him that morning,
but that he would not go till we were gone out of the town.
I told him he had best go then, lest the bishop might take some advantage,
as if he did not regard him; but as for us, we did not fear anything he could do to us.
However he went not whilst we stayed, which was till about the eleventh hour,
I going to see several of the aldermen who had shewed us countenance, and also,
colonel Warren (before named) before we took horse,
and went openly through the greatest part of the town,
telling the people on every occasion, I intended to see them again at the assizes,
as on the First-day evening I had told +++_______+++ Sandford, the colonel`'s son-in-law,
whom they had put into the bishop`'s court on this occasion, when he asked me about it,
which he approved much, "`because,`" said he, "`they want only to be rid of you,
being such a torment to them by staying, that they do not know what to do,
and would have you away at any rate;
but when they know you intend to come again at the assizes,
it will perplex them the more.`"

We set forward about eleven, on the 11th of the First month,
and several Friends being in company, in comparing things,
we found we had all had a share of the burden,
but were very easy and comfortable in our spirits, concluding,
that as we had come laden thither, and left our burden behind,
it was gone upon those who had opposed truth, and would be heavier and heavier on them,
till they sunk under it, or yielded.
And so we saw the hand of the Lord in the whole, and rejoiced together in him;
and that day I went home with Edward Cooper.

12th. The next day we had a meeting at Samuel Watson`'s, which was a large open meeting,
and other people, as well as Friends, were satisfied.

13th. The day following we had another meeting at Carlow,
which was also well filled with people of several sorts,
and they were very quiet and sober in time of silence.
I had taken cold in the transactions at Kilkenny,
and upon that had taken a fit of the looseness,
incident to strangers in the country of Ireland,
which had weakened me as to my natural strength; but the Lord strengthened me,
so as to make me instrumental to deliver many things to edification, information,
and comfort, and it was a good meeting to some, and the people were generally satisfied,
and some much pleased; that night I went home with John Lackey, about a mile from Carlow,
back towards Kilkenny, where I was well entertained,
and had some things proper for my distemper,
as I had had the day before at my friend Samuel Watson`'s.

14th. The day following being wet and stormy, I stayed here till the afternoon,
and Edward Cooper coming from his house on purpose, I went home with him that evening,
where I stayed till the 16th (being the Seventh of the week) and Patrick Henderson,
Samuel Braithwait, Edward Fawcet, and Paul Johnston coming from Dublin,
we went together (and some others), to Kilkenny,
to see what they had to say to me at the assizes,
to which I had been committed by the mittimus aforesaid,
not thinking it honourable in the truth to take liberty by word only, lest being absent,
they might pretend I had given them the flip,
to which I had no temptation from first to last.

In our way we fell in upon the road with some persons going to town,
and one of them offering some discourse about religion, I perceived, after a while,
he was a Roman Catholic;
and after some other points we came upon that of transubstantiation.
He urged the words of Christ, where he said concerning the bread, "`Take,
eat ye all of it;
this is my body which is broken before you;`" (Mark
14:22-24) and again concerning the cup,
"`This cup is the New Testament in my blood which is shed for you, etc.`"
This he said was so plain and distinct, that there could be no mistake in it,
"`This is my body, this cup is the New Testament, etc.`"
I answered, "`This is a figurative speech: this bread signifies my body,
which shall shortly hereafter be broken for you; and this cup (that is to say,
the wine or liquor contained in it) symbolizes or
signifies the New Testament in my blood;
for if it were a proper speech, without any figure,
many absurdities would follow against both sense and reason;
whereas Christ and his apostles suit their doctrine and miracles to both;
for in working of miracles, if the senses were not infallible (as they are concerning,
their proper objects, where the sense is not imposed upon by false mediums,
or any depravation in itself;
for all mankind will conclude a man to be a man at first sight,
though they may express that thing (or man) by different names, as a man,
viz. anthropos homo,
etc.) then it could not be certainly known whether such a thing as raising the dead,
making the lame to walk, opening the eyes of the blind, etc. was done at all;
and as to reason, Christ often uses it; '`No man can serve two masters,`' etc.
(Matt. 6:24). '`No man goes to build, but first counts the cost,`' etc.
(Luke 14:31). '`He that goes to war, first considers whether he is able,
with ten thousand, to encounter his enemy in the field with twenty thousand,`' etc.
And again saith reason, it is impossible that both the body of Christ and the bread,
can occupy one and the same place, at one and the same time;
for when the body is present, the bread must be absent; and when the bread is present,
the body must be absent.

"`And again, to the senses; the apostle John says that, '`we have heard with our ears,
seen with our eyes,
and our hands have handled of the good word of life,`' alluding
to the infallible certainty of sense in preaching the gospel;
for the life was made manifest, and we have seen it;
so that as certain as is sense in sensible subjects and objects, so certain,
and yet more,
were and are all the true ministers of Christ of those saving
and divine truths they deliver from the spirit,
or essential truth and life, manifested in them in its own power and virtue,
and so certain also may the hearer be of the truth of the ministry,
by the manifestation and answer of the same spirit working in him.`"

I further urged, that "`it was a figurative speech for this reason, because he saith,
'`This cup is the New Testament.`' Were it of wood, stone, earth, or metal, that cup,
whatever it was, was the New Testament, according to thy and your notion,
where then is that cup?
If the cup be lost, then also is the Testament, if the cup be the Testament.`"

This was a little pinching, and drove my antagonist to this reply;
viz. "`This speech of Christ hath two parts, the first is proper concerning his body,
but the second is figurative concerning the cup.`"

"`Thy reason for the difference, pray,`" said I, "`friend?`"

"`Because (said he) it was impossible to drink the cup, but only that which is in it.`"

"`It is a good reason,`" said I, "`friend, and holds as well the other way;
for if that must be figurative respecting the cup,
because of the impossibility of drinking the cup
itself to common reason even so for the same reason,
deduced from the impossibility of the thing,
I justly conclude there is no transubstantiation.
But if it had been so, then this, and many other like absurdities, would have followed,
viz. whilst Christ sat at table and said,
'`This is my body,`' the body which brake it and
called it his body must cease to be that body,
and the other (the bread) must commence and begin to be his body (which it was
not before) and be really so before he could properly and truly call it so,
or else there must be many (nay innumerable same bodies) at the same time,
and yet all but that one body, which is absurd and unreasonable.

"`Again, if whilst Christ sat at the table with his disciples,
they all eat the whole entire Christ the evening before he was crucified;
pray then who was left uneaten to be crucified the next day?
and if the first to whom he gave a piece of bread had all the whole Christ,
what remained for all the rest?
I think nothing at all.`"

Then he said, "`Christ told the people,
that except ye eat the flesh and drink the blood of the Son of Man,
ye have no life in you;
there must then be some way of eating and drinking to make good that saying,
which is also very plain in its own nature, the flesh and blood in a proper sense.`"

To this I answered, that "`Christ did say so, and the people took him to mean properly,
and without a figure as ye now do,
looking upon the impossibility of the thing as it
really is in the sense they and you take it;
but when they were all offended and gone,
he turned to his disciples and explained it to them,
for they seemed not rightly to understand him, saying, will ye also leave me;
to you it is given to understand the mysteries, but to them (the world) in parables.
What then was the parable, or mystery?
it is the spirit that quickens, the flesh profiteth nothing;
and thus it is in your own bible as well as ours.`"
I further added,
that "`if therefore the bread were really transubstantiated after the words said,
and were the true body and blood of Christ,
and if they eat and drank the same flesh and blood which then they beheld,
it would profit them nothing.`"

"`Then,`" said he, "`itis true the flesh and blood by itself, without the spirit,
does not profit; but when we eat the flesh and blood together, we eat the spirit also,
and that quickens as we eat it.`"
This was a deep fetch, and the last shift, which I answered thus, viz.

"`This cannot be Christ`'s meaning, for here he does not only distinguish,
but divide between the flesh and spirit; it is the spirit that quickens.
Here is the whole work of quickening ascribed to the spirit,
and the same that quickens also continues life in him who is quickened;
for from the spirit came flesh, blood, bread, wine, and the whole universe,
and all that in it is, and are all continued by the same spirit,
the substance of all things, but the flesh profiteth nothing.
Here it is set apart from the spirit, in the same sentence,
and profiteth nothing to be eaten; and for the further interpretation of this,
observe first the words of Christ to Satan, '`Man shall not live by bread alone,
but by every word that proceedeth out of the mouth of God;`' the
words which proceed out of the mouth of God are spirit and life,
as said the Lord Christ, who is that word, '`My words they are spirit,
and they are life;`' which words the apostles knew
by experience to make them alive and preserve them,
as appears, secondly, by the answer of Peter at the same time; '`Whither shall we go?
Thou hast the words of eternal life.`' So that this quickening is not
by this so gross and carnal eating and drinking here imagined,
but by receiving of the spirit through the words of Christ,
abstracted and apart from that holy body, and all other corporeity or body;
and for the further understanding of sayings of this nature,
observe that when the disciples of Christ were showing him the temple at Jerusalem,
and the beauty of it, he said to them, '`Destroy this temple,
and I will raise it up in three days.`' The temple at Jerusalem
was the object of their eyes and subject of their discourse,
which gave them just occasion, as men,
to suppose he meant that temple which they said was forty years in building,
and could he raise it in three days?
they admired at his saying; but yet, in the sequel of things, they understood afterwards,
though not at the time, that be spoke of the temple of his body.
Again, in like manner, where he saith, '`I am the vine, ye are the branches,`' etc.
This may well explain that other saying, '`I will drink no more of the fruit of the vine,
till I drink it new with you in my Father`'s kingdom;`' which can
mean no other than as his coming in the flesh consecrated the way,
and was previous to the coming of the spirit,
so his drinking new wine in the kingdom of God, must intend that community of spirit,
intended in the words of the apostle afterwards, concerning the whole church;
'`We have all been made to drink into that one spirit.`'`"
My opponent by this time being weary of the subject,
advanced a question concerning the spirit itself, viz.

"`How do you know that spirit from another spirit,
since Satan is transformed into an angel of light, may it not be that evil one,
and not the spirit of Christ?`"

I replied, that the divine essential truth is self-evidencing,
that the quickened soul is assured of him by his
own nature and quickening power and virtue,
as saith the apostle,
"`Hereby we know that he abideth in us;`" 1 John 3:24
(or to this effect,) by the spirit which he hath given us;
and he that is in a state of doubting, is in a state of condemnation and reprobation,
and hath not yet known the spirit, but is yet in death and darkness,
and ignorant of God and Christ, and in such, and not in the quickened or regenerated,
Satan is transformed;
for such as wanted a proof of Christ`'s speaking in and by the apostles,
were by Paul referred back to themselves; "`Know ye not your own selves,
how that Jesus Christ is in you, except ye be reprobates?`"
and again, "`The spirit itself helpeth our infirmities,
with sighs and groanings which cannot be uttered, and searcheth all things,
even the deep things of God.`"

By this time we drew near the town, and then he said,
no doubt but I had a good intent in what I did, in travelling so in the world; but said,
I must have some good considerations for it,
(meaning as their priests have gold and silver) and
mentioned about three hundred guineas for that time.
I told him no, we whom God had raised up and qualified in some degree,
in this age to that service, were advanced above any such mean, base,
and mercenary considerations, as to take any thing from men for this labour,
which we bestow freely in the love of God,
and by his commandment for the common good of men.
"`Why,`" said he, "`the apostles were but poor men, and wanted necessaries,
and must have received of the people or wanted.`"
"`True,`" said I, "`then they say, '`having food and raiment,
let us be therewithal content,`' and where that is really the case,
such as are poor among us, we would not begrudge them that;
but it is very seldom or never so among us, but rather with Paul we can generally say,
'`These hands of mine have ministered to my necessities,`' having
no desire that any such thing should be done unto us,
and we generally have sufficient of our own.`"
Then said he, "`But in case your friends,
after some very good sermon that pleased a great congregation well and generally,
should offer you a purse of two or three hundred guineas, would not you accept it,
being freely given?`"

I replied, no, I hope it would be no temptation, if so it were,
which never can be as long as they and I abide in the truth we profess,
either to give or receive that way;
I should rather be greatly troubled to see so great
a degeneracy as to subject them to so great an evil.
"`Well`", said he, "`I cannot tell, you say well, and I am apt to believe you;
but if you would not, there are many would be glad of the offer, and make no bones on`'t,
but receive it with both hands.`"

"`I believe it,`" said I, "`for there are too many mercenary hirelings in the world,
in this age,
who though they pretend a mission to '`go teach and baptize all nations,`' Matt. 28,
yet, as unfaithful servants,
(if they were sent at all) sit down where they can have the first maintenance,
and never move till the voice of a better cry in their ears, and then, and not till then,
they run where God does not send them.
"`

"`There is too much of it,`" said he, and so we parted in friendship,
with good wishes on either side.

Coming to town, with many Friends from other parts, it was soon known,
and many were looking what would be the issue of things.
William Sandwith being there, he and some others went to the judges,
and apprized them of matters and the case,
and how Friends and I had been used by these high-church persecutors,
especially the bishop of Ossory now here at Kilkenny; and Amos Strettell,
and some other Friends at Dublin,
procured a letter from one of the intended lords
justices to one of the judges (in his private capacity,
not being yet sworn) to see that justice should be done us,
for the government favoured us,
but our enemies and theirs proceeded under a pretence of law that was not to be over-ruled;
but they inclined to do all they could in honour and safety,
which was all we desired of them.

They sent for the sheriff to see the calendar, and not finding the mittimus returned,
they saw our adversaries had no mind to meddle against us, but were willing to drop it,
which they rather advised us to overlook for that time,
since we might in time have our meetings free, which was all we desired;
but that evening one of the judges said in open court, when he gave the charge,
that it was treason in any to pull down or deface any public, religious meetinghouse;
which going quickly through the town, many rejoiced on our account,
it being a great stroke on our adversaries; and I made this construction of it,
that as the house was a circumstance and accommodation to the meeters,
who were of more regard than the house, and it only regarded for their sakes,
if it were treason to deface the house,
how much more so in thus disturbing and abusing those that met therein?
which some laying hold of,
inculcated it among the people to our further advantage upon our enemies.

17th. The next day (being the first of the week)
we appointed another meeting in the same place,
for we were for the same cause still, the liberty of the gospel without fear of any,
and went accordingly, and a full meeting it was,
and very comfortable and quiet to all outward appearance;
but I had felt all the night before an inward load and sting from some corner or other,
and expected another bout, and so it happened;
for Patrick Henderson kneeling down to prayer,
in the mean time came in the mayor`'s sergeants, but as civilly as could be desired,
and made no disturbance during the time of prayer
and one of them went out again soon after,
but the other stayed: a little after prayer was ended, I stood up and spake a while;
but had not got well into the matter in my mind, till the other sergeant stood up,
and with great reluctancy (for we all believed it
was much against his will) and low voice said,
he was sent of the mayor to command us in the king`'s name to disperse;
but quickly added, but if you will not, I cannot compel you,
nor have any orders to force, and so went civilly away.
Then I proceeded in my testimony, many things opening to the state of the people,
particularly relating to the duty of a Christian, not to believe only,
but also to suffer when thereunto called,
and plainly set forth the nature and ground of persecution, Satan the cause,
and wicked men his instruments in it; as Cain, Jezebel, the high-priests,
popes and prelates; as they might now see in this present case,
though but a shadow to what we had met with, not always by plain and open violence,
but more generally under the specious pretext of law and right;
and then I concluded the meeting in prayer.

After the meeting was over, we heard that one of the churchwardens had been there,
and he and the sergeant which disturbed us (for the other said he had been troubled
in conscience since the first time) were sent for by the bishop,
who in the hearing of the judges (they dining there) examined them about the meeting,
what we were doing, and what we said.
They told him we were at prayer when they came in, and a good-like, black man,
(meaning P. Henderson) prayed heartily and devoutly
for the king and him (the bishop) too;
and all of them, for he prayed for all in authority under him.

Then the bishop asked them if I had preached, and the churchwarden said I did;
upon which the bishop tendered him his oath,
it being me his great spite and envy was bent against chiefly.
Then he had the act of uniformity of the 14th of Charles the Second
in England (but the 17th in Ireland) brought before him,
and discoursed upon it with the judges, he thinking it reached us,
and would have pumped the judges, and had their opinion on it,
but they were wiser than he, and said nothing, but let him take his own way;
for they were staunch friends to the king`'s interest, and were our friends,
as knowing our integrity to the king and his government,
and so the bishop`'s rage and envy blinding him (if he could at all understand
the act) he first gave a warrant and mittimus in his own name,
directed to the sheriff of the town,
to arrest and commit me to the common jail for three months without bail or mainprize;
where this antichristian judge (for there are many
now as of old in the world) intended I should lie,
until the full time was expired, without any liberty as before;
if either by hardship or otherwise (for I was then but weak
and tender) he had not murdered me in the mean time,
for he had, before I went out of the town,
sent for the sheriff and reprimanded him sharply,
for letting me go abroad in town upon my first commitment,
threatening to have him before the House of Lords the next session of Parliament.

Our afternoon meeting this day being over,
which was very peaceable (for now we had conquered him so far as that none disturbed
us) I found a secret sting as I went to the inn with the Friends,
who lodged there, from Dublin; and we were there but a short time,
till I was told there was another warrant and mittimus out against me from the bishop,
and then I hasted to my quarters at the sheriff`'s house, where I expected it;
and found that such a warrant had been directed to the mayor,
and sent to the sheriff to be executed, but it not being directed to the sheriff,
he would not receive it, but sent it back to the mayor.
Then the bishop, mayor, and alderman Connell, and some more consulted further,
and found their error, as to the bishop`'s giving a warrant himself;
for all the act requires in the case for which it was made, is that the bishop,
as ordinary,
should certify the offence (only relating to those of his own sect) to any two justices,
or mayor, etc. and then they to grant a warrant and mittimus,
which now the mayor granted accordingly, a copy whereof followeth, viz.

City of Kilkenny, ss.
By John Birch, Esq.
Mayor of the said city.

Whereas I received a certificate,
under the hand and seal of the right reverend father in God Thomas lord bishop of Ossory,
in which he certifies, that Thomas Story, a Quaker,
did this day preach in the said city of Kilkenny,
contrary to the act of uniformity made in the seventeenth
year of the reign of king Charles the Second.

These are therefore in pursuance of the said act and certificate,
to will and require you, on sight hereof, to apprehend the body of the said Thomas Story,
and him so apprehended to convey to the common jail of the said city,
there to remain for the space of three months, without bail or mainprize;
whereof fail not at your peril, and for so doing this shall be your warrant.
Given under my hand and seal this 17th day of March, 1716.

John Birch, Mayor.

To the several Constables and Officers of the said city.

This warrant the same sergeant, which came last in the forenoon to disturb our meeting,
brought to the sheriff`'s house now in the evening, but delayed execution for an hour;
and in the mean time some Friends advised with some counsellors
of their acquaintance in town at the assizes;
and some of them said it was in the nature of an execution,
so that it might be more dangerous for the sheriff to give liberty,
or let me be in his house, than before, so that things looked a little harder;
but as I had not read the act for a long time, and not remembering the tenor of it,
I thought there must be something in it to justify their proceedings,
or else they would not have done it,
and so was resigned in my mind to submit to it for the truth`'s sake, and was very easy,
being in more danger of too deep a resentment of their base and wicked usage of me,
than of repining at the loss of my liberty,
for I had a view of some things to employ my time in,
which would have made my confinement much more uneasy to the bishop (who now I saw,
and so did every body there,
to be the author of all this persecution upon us) than to me, for the Lord was with me.

After some time the sergeant came into the room (for we
let the door be open on purpose) and served me with a warrant;
but the sheriff said, I should not go out of his house that night however,
come on it what would, and so I stayed there; but the truth arising in me,
I observed the indignation thereof against the bishop, but no enmity in me against him,
as a man; and after a little inward concern that way,
I sent for the act and read it carefully, and saw they were all quite mistaken;
for the act had no relation to us, or our meetings or preaching, but to themselves,
the priests and bishops only; for after the coming in of king Charles the second,
there were many priests, who in Oliver`'s days,
had been in the benefices (the bone of contention
they ever strive for) and finding the sweet of them,
would fain have held them,
and yet could not readily swallow the Common Prayer and services of the others,
which they had furiously opposed and rejected, so lately before,
till this law forced them,
which they generally complied with rather than lose their gains;
which respected only their own priests, to bring them all to one scantling,
or uniformity of prayers and worship, or image of it, but concerned no other.

Then, after a while, I told the sheriff it was false imprisonment,
and desired him and others to take down in writing, what time I was arrested,
because there might be occasion for their evidence;
the sheriff seemed a little surprised at it that the great
bishop and his counsellors should miss it so far,
but took no account of the time.

The next morning, before I rose (for I laid till eight,
being a little fatigued) several Friends had been with the judges,
and they had given their thoughts freely,
how much this was against the mind of the government to disturb our meetings,
and did not doubt but this would do us service in the end; however they advised,
that seeing how times stood (the talk of an invasion by the Swedes not being over,
and that town a dangerous place to be in prison in) if the bishop would set me at liberty,
they would have me choose it rather.
But of this I had heard nothing, nor would Friends give ear, any more than I,
to make application to the bishop, for that he wanted.

About nine in the morning, whilst I was at breakfast,
came the same sergeant that arrested me, with a message from the mayor,
that he had taken up the warrant and mittimus,
and I was at liberty to go where I pleased, if I would accept of it.
I told the sergeant he ought to send me a liberate under his hand and seal,
and not think I was wholly at his disposal, to toss in and out of prison as he pleased,
but had my remedy by law against him and them who had used me thus.

Then also came several military officers to see me, and expressed their great dislike,
in their soldiery way; some of them among themselves, drinking healths to king George,
and all his loyal subjects, and damnation to the pope and all rebels;
but I discountenanced that, saying we did not wish hurt to the souls or bodies of any,
though we were greatly engaged to love and honour the king, and be thankful to God,
as we truly were, for the liberty we enjoyed under him.
"`In all places,`" said one of the officers,
"`except in this jacobite popish town of Kilkenny, with whom we hope to be even ere long,
for all their affronts to the king and government.`"

A little after this came the mayor himself to my lodging, to tell me I was at liberty,
for he had taken up the mittimus, and destroyed it.
I then told him, "`Since that violence, by which my just liberty had been obstructed,
was removed, it was now returned into its own natural course,
and if I could find it consisting with what I professed,
I should consider of ways and means how to do myself
justice against such violent and illegal proceedings;
but as it was a wrong done me for the sake of my religion,
I might probably bear it with patience for that reason,
being sensible enough of the advantages I had of my enemies.`"
He made very little reply, but civilly departed.

After this I went to several places in town to take
leave of such of the magistrates as had been friendly;
for all the king`'s friends were so, and some papists were troubled at these proceedings,
as working no good for them.

Truth was honoured, and gained by all this,
and the eyes of many were opened to see the bishop and his spirit and party,
and what many might expect if he and they should prevail;
and many tongues were let loose, after their several ways, to speak their sentiments,
by all which our persecutor and persecutors greatly lost ground,
and fell quite short of their wicked designs.
But before I departed the city, I met with R. Connell,
the peevish tool of this proud bishop, and told him I was at liberty,
which he pretended to be surprised at;
but I told him if I had stayed longer some of them might have had the more to pay;
for it was false imprisonment, the act they went upon being about their own priests.
He desired me to go to his house (being near) and see the act;
I told him I had seen it already.
Then said he, "`I have as good counsel as any in Ireland, that says it does affect you.`"
I replied, that I would debate it with all the counsel in Ireland,
and that it had no relation to us at all.
Then he wished me well, when he could do me no more hurt, and so I left him.

18th. That afternoon about three, I left the town, most Friends being gone,
seeing the thing at an end, and went that evening home with Joseph Firth, to Ballinakill.

19th. The next day we had a meeting there, which was not large, but a good open meeting,
the Lord being near to comfort and refresh us after so much fatigue;
for many Friends thereabout came to visit me in my confinement,
and some or other were always with me, and several from this place.
The earl of Donnegall was in this meeting,
and behaved more soberly than he was known to do before,
being apt to be restless and troublesome at some other times;
and that afternoon I went home with John Harris to Mountrath,
who had been several times with me at Kilkenny, and now had seen the conclusion.

21st. On the 21st was their meeting day (the Fifth of the week).
It was a large, open meeting, many of the neighbourhood, papists and others, being there,
and a good time the Lord gave us together.

23rd. On the 23rd I went to Mountmellick, lodging at the widow Mary Bale`'s,
and next day had a meeting there in the forenoon which consisted mostly of Friends,
and was not very open, but larger in the afternoon, some of the neighbourhood coming in,
which I generally observed freshens meetings,
and many things were opened in the authority of truth, to edification, confirmation,
and comfort.

26th. Here I tarried till the Third day afternoon, and then set forward for Dublin.
That night I reached Kildare, and the next day arrived safely in Dublin,
where I was kindly received, and was at the meeting on sixth-day following,
the 29th. It was a fresh and open meeting, and we were comforted together in the Truth,
which, as the heavens transcend the earth, exceedeth all other enjoyments.
Hearing of a vessel going for Chester,
and I intending for the yearly meeting at that place,
took timely care to secure my passage in it; but the wind not answering,
I stayed there till the first-day following.
The meetings were very large, especially at Sycamore Alley in the afternoon,
where came together a great concourse of people, hardly a greater meeting seen there;
and things were open and well, and the blessed Truth over all,
who is worthy above all forever.

The wind continuing contrary, I stayed still at Dublin,
and was at their third-day meeting, where I had some time,
things opening to many states very closely; and I came away easy,
leaving the better sort under good satisfaction.
Many came to see me before I went off, and among others Captain Smith.
He had been in military offices, but being under some convincement,
was at that time under great inward struggles;
for having a commission for being a captain of dragoons then offered him,
he would gladly have seen it lawful and consisting with Truth,
to accept the commission and sell it, not intending to act by it;
but upon some private discourse with him, he was much straitened about it,
and was very tender and humble; we parted in love and friendship,
he owning his satisfaction in that conference.

On the Fifth day, the 4th of the month, accompanied by several Friends,
I set off from Dublin Bay, about two in the afternoon, with a fresh gale about West,
and the next day, about the same time, arrived at Park Gate, on Chester river,
but that evening, the waves being high, went on shore there,
where we tarried that night at an inn, and next morning went up to Chester,
and lodged at the Golden Talbot, an inn.

[.asterism]
'''

In the year 1717, died Abigail Abbot, alias Smith, at Moeg, near Charleville,
in the province of Munster.
She was daughter of Richard Boles of the same place, was married to one Smith,
and after her husband`'s death was convinced by the ministry of William Bingley,
about the year 1675,
and about eight years after her convincement was called to the ministry.
She was an eloquent woman, of a majestic presence, much admired and followed.
She travelled on truth`'s account both in this nation and in England,
had acceptable service in many places,
and several persons were convinced by her ministry.
She was greatly applauded by many, and being not strong enough to bear praise,
was transported into pride thereby, lost her gift, and fellowship with Friends,
and from the highest pitch of applause, fell into as low a degree of contempt.
It is certain however, that she became sensible of her fall,
and suffered many bitter agonies on that account;
passing the latter years of her life in retirement, great sorrow, and mortification,
and has left behind her a pathetic paper of self-condemnation, which is here annexed,
as a caution to all these that think they stand, although in the highest station,
to take heed lest they fall.

Besides the following paper, she also afterwards drew up another,
wherein she more particularly specified her miscarriages,
and warned those concerned in the ministry to watch against that luciferian spirit,
which would deck and adorn itself with the gifts and graces of the Holy Spirit,
and not to value themselves upon any gift which God bestows on them,
because that opens a wide door for temptation,
and was (as she confesseth) the first inlet to all the miseries that befel her:
hence she grew impatient of contradiction, and deaf to advice,
and at lengths in contempt of the good order established among Friends,
was married by a priest, to a man not in unity with them.

Her paper of condemnation, first mentioned, was as follows:

Friends and people,

I once thought, that if I might gain all things here below the sun,
yet I would not commit the least sin knowingly against God,
who in years past evidently enlightened my understanding,
when I was sore afflicted in body and mind,
and all comforts and help of this transitory world failed me;
and when I concluded the true worship of God was generally hid from mankind,
for I knew of none that went heartily enough about it,
nor could I sufficiently bewail those infirmities and imperfections
that apparently possessed and hindered that great work in me,
and which I feared too many concluded themselves secure in on easier terms.
Thus in a day of great distress, the Lord was pleased to bring down my mind,
and reduce my spirit into a calm.
Then did occur many things which before slept unseen to me,
for I plainly saw I need not ascend, or descend to look for Christ, the true Light,
that enlightens every man that comes into the world,
for his quick and powerful word was in my heart,
which teaches to deny every evil and vain thought,
by the learning of which a man becomes godly;
and so the peace of God is shed abroad in the heart, even in this present world;
and in this quiet, peaceable, and comfortable condition, or estate,
I rested with God and in his will in all things,
withdrawing myself from society with any sort of people, having proved many.

At this time some said I was a Quaker, and that I knew it not,
which thing I put far from me,
not thinking it worth my while to consider those
that were more spoken against than any I knew,
as a poor, whimsical people, led by an erroneous spirit: nay,
to the degree of bewitching people.
But some time after this,
my heart being drawn near to God in a spirit of supplication to him,
that he would daily renew a right spirit within me, then these people called Quakers,
came afresh into my mind, with much satisfaction in myself, that I might seek them,
to know them whom perhaps the world was ignorant of.
This was the first moving cause that brought me acquainted with those people;
and finding them to be an inward people,
owning the spiritual light and life which comes by Jesus Christ, and makes manifest,
and reproves the works of darkness in the hearts of the children of men,
etc. to the end that Christ might rule and reign in his temple; for this I loved them,
and desired fellowship with them,
and after some time their love to me in Christ was great,
with whom God not only joined me in society, but in a sweet union and fellowship,
and with them made me partake of many seasons of divine consolations and refreshments,
which he vouchsafed from his presence, and also gave me power to declare to many,
the justice and mercy of Almighty God which is in Christ Jesus,
whose powerful Spirit so attended me in it, as not only silenced gainsayers,
but extorted an assent to the truth thereof.

And now, O all people, which of you could think that such an one as I,
whom God so evidently and graciously visited with exceeding kindness,
and as a tender father lifted up the light of his countenance on me, should fall away?
He led me by the hand, and forsook me not in my distresses,
but supported me through many exercises, till he conducted me out of those things,
and out of that estate to which his wrath by an eternal decree belonged,
and in matchless mercy brought me into that estate,
wherein I found peace and comfort with God,
and also brought me to an acquaintance with that people,
with whom he also dealt as he did with me, having an evidence in my conscience,
from my own experience, that they were a chosen people of God.
Yet let none wonder, but let all hear, fear, and tremble,
with watching and prayer continually, lest any thinking they stand, might fall;
for the enemy of man`'s soul is as busy now, as ever he was in all ages,
states and conditions; and woe is me, that I, by not keeping watchful,
in true humility before the Lord, have done dismally foolish,
by letting in a high mind contrary to the mind of Christ,
who would always have preserved me, had I kept near him in my first simplicity;
for it is an ever lasting truth,
there is no estate higher to be attained on this side the grave,
than a truly humble watchful state, which I neglected,
and by reason of this I held fast deceit, and refused to return,
which many of the Lord`'s people saw, who truly loved me,
and tenderly admonished me with many tears oftentimes;
but the enemy of my soul so prevailed over me, and darkened my understanding,
that I thought they were too severe with me,
from whence a prejudice arose in my vile heart against them,
and I had not room left in me to receive their Christian counsel and admonition;
that in time my understanding was so clouded,
through a murmuring spirit which soured my mind and perverted my judgment to that degree,
that when my friends refused to let me take my now
husband in their assemblies on my own terms,
I foolishly concluded,
that though I went from the people of the Lord to marry
my husband with a minister of the world`'s people,
yet the Lord would still be with me as before,
seeing he had brought me near himself before I knew them.

Thus Sampson-like, who slept on the lap of his Delilah,
I knew not that my strength was departed from me, and so, rashly and resolutely,
I rushed into the congregation of the dead, as a dog returns to his vomit,
which thing was displeasing to God, and afflicting to his people,
and so accomplished my design, which gave date to many miseries and unspeakable sorrows,
which can never be repaired by only crying peccavi.
And the Lord in his justice raised many and strong enemies against me on every side;
but no lion roared like that in my own bosom, though those without afflicted me sorely;
from which proceeded frettings, quarrelings, wranglings, and boilings of heart;
but all this forwardness in me did but add storm to storm, sting to sting,
and burden to burden; all which the ever-merciful God, in his time, made me sensible of,
how much precious time I had spent in musing how to get out of such a trouble,
how to get off such and such a burden,
and how to revenge myself of such and such a wrong.
This, I say, the Lord made me sensible of, that it was he himself was the chief agent,
and had the greatest hand in all my just and great afflictions;
and it was he that was to be eyed and owned, and not any secondary cause;
and he is just in all that is brought upon me, and I have done exceeding wickedly;
and when I consider the truth of this,
it enables me to bear with much patience all that God is pleased to dispense to me,
which hitherto hath been too little, I greatly fear, for such an one as I,
who at once abandoned both my religion and my reason too,
by acting such prodigious and premeditated wickedness;
so that I have nothing to excuse or shelter me from the stroke of divine justice,
it makes so directly at me;
who by not only acting counter to all I have professed and declared of,
but also by my great folly,
have given occasion to the adversaries of the Lord`'s truth
to rejoice and to speak evil of the spirit of truth,
another than which will never be revealed, which is Christ the way;
and I greatly fear I have been a stumbling-block in that to many.

This great wickedness I myself have done, by not keeping the body of sin under;
but I do not complain because of my punishment, for I have greatly sinned;
and O how can I sufficiently bewail, mourn, weep, and lament!
O, what pangs, sighs, and tears, can expiate my guilt?
Doubtless many shall be turned into hell, who never sinned against so clear a light,
especial love, and precious mercies, such close and strong reasonings of the spirit,
and deep convictions of conscience, as I have done.
What lamentations shall I take up for the loss of the presence of God,
which I once had with my spirit, and those melting, warming, quickening joys,
in which I found peace with God, whose free mercies pardoned all my sins,
and whose grace adorned my soul.
Oh, how can I now but wax hot against myself,
and be contented to be trodden under foot by all, as mire in the streets;
for misery is my portion; and as for any comfort, I refer that to God`'s will only;
for could I pour out a sea of tears,
yet then could I not deserve any thing but the fiery torments of God`'s hot displeasure;
and O that the Lord would not spare his sharp rod, nor withhold his judgments,
nor the pangs of hell from before mine eyes, until he,
through the mercy and love which is in Christ Jesus, redeem my soul thereby,
and clothe me with his righteousness once more, before I go hence;
for surely no sin shall pass unrevenged, neither great nor small, in this world,
or in the world to come.

And O, all you who have been enlightened, and have tasted how good God is,
and have known something of the powers of the world to come, and yet remain lukewarm,
or are fallen with me, though not into such a deep pit of mire,
as to dash dirt in the face of God`'s truth, and people, as I have done;
for I know none can parallel me in this our age; surely none so wicked as I,
who have dishonoured the holy name of God, and on his pure religion brought reproach;
weak saints I have discouraged; my own conscience is wounded and my soul endangered,
my candle is put out, my crown is fallen from my head which once covered it,
and by which I had knowledge and skill how to behave myself in the church of God:
I am stripped naked, and spoiled of all that excellency with which God adorned me.
O, that all you might be warned, and with me call to mind whence we are fallen,
and do our first works,
and bring forth every forbidden and accursed thing which hath occasioned our fall,
and the stumbling of many; and let us make confession to God, and give glory to him;
for had all who have made profession of the everlasting gospel,
which is the power of God, been faithful in their day, O,
what a conquest would have been gained over the world that lies in wickedness before now;
but I am here silenced, for I am one that has fled before the Lord`'s enemies,
the accursed thing was in my own heart; and it hath given cause to the heathen to say,
"`The Lord of Hosts, whom we trusted in, is not able to save us.`"

O, Friends, what have we done that have not been faithful to God?
And it is sealed from God upon my spirit, that the Lord is jealous for his honour,
and he hath given space to me and many more to repent,
and there remains but a little time behind ere many of us
shall be cut off out of the land of the living forever,
except we speedily repent, and double our diligence,
and cry to the Lord with all our hearts in a sense of our own vileness,
and of the great wrath we lie under if the Lord should take us away in his sore displeasure:
and O, that my eyes may not sleep, nor my head nor heart rest, till the Lord shew mercy,
and turn from his fierce wrath, and have pity on us!
And I desire none may think that this is sent abroad into the world,
which may last amongst men when I am gone to my place,
to please any society or sect of people whatsoever,
any farther than God might be glorified, and his blessed spirit of truth,
which lights and guides all people into happiness that will be led by it; I say,
that this might be rescued from the tongues of a multitude of ungodly men,
into whose bands I have betrayed the Lord of life as much as in me lay, Judas-like.

Woe is me, seeing I have done nothing,
nor can do any thing to wipe away this great reproach which I have brought;
only this I would have all know, this great, great fault and sin, is mine;
I take it to myself; sorrow, trouble, and great affliction is my due;
I take it home to myself as the fruit of my own doings,
from the hand of the Lord that is jealous of his honour;
and though he is long-suffering and of great mercy,
forgiving iniquity and transgressions, yet by no means clearing the guilty;
they shall not go unpunished, either in this world, or in the world to come.
And O,
that a spirit of forgiveness from the Lord may rest
upon the hearts of all that truly fear him,
so as that they may heartily desire that a spirit of judgment from
the Lord may rest upon me here to the purifying of my soul,
so that I might rest with him hereafter forever and ever.
Amen.

Abigail Abbot.

The book called The Spirit of the Martyrs, revived,
(1718) being an abridgment of the history of the martyrs, was now ordered to be printed,
for the benefit of youth and others.

In the year 1718, and about the sixty-fourth of his age, died Samuel Randal, near Cork,
whose qualifications and good services as an elder,
though he had not a public gift in the ministry, deserve to be commemorated.
His grave and solid conversation, when but a youth, adorned his Christian profession;
but in the station of an elder he was truly deserving of double honour,
being not only a good example himself in plainness, temperance, and justice among men,
but also zealously concerned for the honour of God and promotion of truth;
and that Christian discipline and good order might
be maintained among the professors thereof,
and justice and judgment duly exercised on loose and disorderly walkers,
and our Christian profession be thereby cleared of the reproach
and scandal which was by such brought upon it;
and, in his dealings with particular persons, or families,
he discharged his duty faithfully, and without respect of persons.
And as he was sensible that the conversation of the world,
and the eager pursuit after the riches and grandeur thereof,
had proved hurtful to many in their spiritual condition,
he was tenderly engaged to be exemplary in his own conduct, in that respect;
for when probable prospects of considerable opportunities
of worldly gain presented themselves,
he often declined embracing them for truth`'s and example`'s sake.
He was cheerfully given up to the service of truth, not only at home,
but by a constant attendance of both national and provincial meetings for many years,
in winter as well as summer, until natural strength failed.
He died in unity with the brethren, peace with God,
and a calm resignation to his holy will.

The same year died also Margaret Hoare, alias Satterthwaite,
concerning whom we have the following testimony:
that her conversation was exemplary and edifying as became a minister of Christ.
She was of a good understanding, and her conduct attended with great sobriety, humility,
and prudence.
She had an excellent gift in the ministry, which was as well doctrinal,
as sweetly comfortable and edifying; and she travelled frequently on this account,
both in England and Ireland, and had meetings not only among Friends, but strangers;
and when at home, was very serviceable in visiting Friends families,
and doing other good offices in the church.

In her last sickness she plainly triumphed over death,
saying that her salvation was sealed to her; and near the time of her departure,
uttered these, among other sweet and excellent expressions to some Friends about her:
"`Remember my dear love to all my dear Friends, and tell them, I am going to my God,
and their God, to my King, and their King.
I have a clear conscience, void of offence towards God, and towards all men:
my soul doth magnify the Lord,`" etc.

In the year 1719, and eightieth of his age, died Robert Hoope, of Lurgan,
in the county of Armagh, a native of Skelton near Gisborough in Yorkshire,
who came into Ireland in the year 1660.
He was educated a Protestant after the manner of the church of England;
and continued such until several doubts concerning
matters of religion began to possess his mind;
which at length, about the year 1667 or 1668, were effectually cleared up,
by the powerful ministry of that faithful servant of Christ, Thomas Loe,
who was then visiting those parts in the service of the gospel;
and from that time he always assembled himself with the people called Quakers,
although he met with many persecutions and trials by imprisonment,
and sufferings of many kinds.
In some few years after his convincement,
it pleased God to bestow upon him a gift in the ministry,
in the exercise of which he laboured faithfully, to the edification of souls;
and although his preaching was not with eloquence of speech,
yet it was attended with life and power.
He was a plain, sound-hearted man, free from ostentation, a peace maker,
a true disciple and follower of Jesus in self-denial,
and preferring the glories of the heavenly kingdom
before the perishing riches of this world,
of which he gave a signal proof in the latter part of his life, having,
for the space of about twenty years before his decease,
when his health and capacity might have allowed him to pursue the affairs
of this life with a prospect of an increase of outward riches;
separated himself from the encumbrances of the world,
living a life of solitude and meditation,
and devoting himself to the service and promotion of truth.

The years 1718 and 1719 were memorable for the first advances towards the deliverance
of Friends from the sufferings to which they had long been liable,
on account of their conscientious refusal to swear.
Great sufferings having lately attended them on this occasion, particularly by litigious,
wicked persons, filing bills in Chancery against them,
where their answers would not be admitted without an oath,
(a grievance they had long laboured under^
footnote:[See above, in the year 1673.]) it was now concluded,
that endeavours should be used, if a plain affirmation,
or such as might be easy to all Friends, could not be obtained,
to get a clause in a proper bill to empower the chancellor,
and the barons of the exchequer, to receive Friends answers without an oath, where,
and in such cases as they may think convenient;
which endeavours were crowned with a happy success: for in the year 1719,
in an act of parliament, entitled, "`An Act for the Amendment,
of the Law,`" etc. a clause was obtained,
allowing Friends`' answers to bills in Chancery upon their solemn affirmation,
and producing a certificate signed by six credible Friends.

The same year also a clause was obtained in an act passed for exempting
Protestant dissenters from certain penalties they were liable unto,
allowing Friends the privilege (in common with other Protestant
dissenters) of worshipping God according to their conscience,
without molestation, viz. it was hereby enacted,
"`That the statute of the 2nd of queen Elizabeth,
for the uniformity of the Common Prayer,
etc. whereby all persons are required to resort to their parish church or chapel,
or some usual place of Common Prayer,
etc. shall not extend to any Protestant dissenter who shall take the oaths of fidelity,
etc. provided that the place of meeting be certified to the bishop of the diocese,
or to the archdeacon, or to justices of the peace at the quarter-sessions,
and that the assembly be not held with the doors locked, barred, or bolted;
and every Quaker who shall make or subscribe the declaration of fidelity to king George,
of renouncing the pope and pretender, with the doctrines of purgatory,
transubstantiation, etc. shall be exempted from all penalties in the aforesaid act,
and shall enjoy all the like privileges and advantages at other Protestant dissenters.`"
