[short="A Summary of Sufferings"]
== A Summary View of the Sufferings of the People, in Ireland

Many and grievous were the sufferings which this people underwent at the beginning,
merely for being exercised in preserving a conscience
void of offence towards God and man,
in testifying against the corruptions, superfluities, and excesses,
vain pleasures and pastimes, superstitions, dead formality and hypocrisy,
prevailing among professed Christians.
On these accounts they become the objects of popular scorn and derision;
and besides personal abuses, they frequently suffered severe fines and imprisonment.
This will appear the less wonderful,
when we call to mind and consider the saying of the apostle, Gal. 4:29,
"`He that is born after the flesh, persecuteth him that is born after the Spirit.`"

But there was one thing which rendered them in a peculiar
manner the objects of the rage of a man-made ministry,
viz. their conscientious scruple of paying tithes in these gospel-times,
as being an antichristian imposition.
Hence was verified among these what was observed of the
prophets that caused the people to err formerly,
Micah 3:5, "`He that putteth not into their mouths,
they even proclaim war against him.`"
And accordingly the priests were commonly the instruments of stirring up the magistrates,
and even the rabble against them; and on the above named account,
viz. their refusing to pay tithes,
they very frequently had their goods spoiled and taken away; sometimes to three, six,
ten, or twenty times the value,
and were often imprisoned and kept prisoners several years, and sometimes unto death;
thus sealing with their blood their testimony against the antichristian yoke of tithes,
as having been commanded to be paid by the eleven tribes of Israel, to the tribe of Levi,
both for their continual service and attendance in the tabernacle of the congregation,
and in lieu of their part or share in the land of Canaan,
which they were hereupon expressly deprived of (see Num. 18:20,23,24),
and not affecting the Gentiles, of whose race we are,
but made null by the coming and offering up of Christ Jesus our Lord,
on which consideration the satisfying of this demand, in these gospel times,
hath been ever deemed, by this people,
a virtual (or in effect) denying the efficacy of the coming and suffering of
Christ Jesus to abolish the ordinances commanded to the Jews for a time only,
of which tithes was one,
from whence the imposition of them has been by them called
an antichristian yoke of oppression upon Christians.

To enumerate all the instances that might be given of their sufferings on this account,
were to fill a large volume.
A compendious view of their sufferings in this kingdom,
for not satisfying this and other ecclesiastical demands,
such as building and repairing the places called churches,
burying and christening (so called) their children, and churching their women,
even when none of these offices had been done for them,
was published in Dublin in the year 1731;
where is also a narrative of their sufferings for conscience-sake on several other accounts,
whereof I shall here give a brief sketch, as follows:

For not going to the church, so called,
but meeting together purely to worship Almighty God,
according to the dictates of their consciences, they were cruelly used, indicted,
greatly fined, had their goods spoiled, and were long imprisoned;
and when there was a prospect of their enlargement,
because they could not satisfy the unjust demand of fees,
as having done no wrong (thus bravely, though passively,
asserting their Christian liberty), some of them were detained in prison,
and others stripped of their clothes and then turned out.

There was one occasion more of their suffering,
whereof we meet with frequent instances in the early days,
which (though it may seem very strange,
and perhaps to some scarcely justifiable) appears however
very reconcilable to the practice of Christ and his apostles,
who frequently taught and preached not only in the temple and synagogues of the Jews,
but in other places of public concourse,^
footnote:[This, however uncouth it may seem, through long desuetude,
to divers modern Christians,
might be further defended by the practice of the great Socrates,
whose familiar custom it was, publicly to preach to, or instruct the people in just,
grave, and virtuous manners; and thus he did, frequently, at any time of the day,
and in the very streets, as occasion served, and as his good genius moved him;
neither was he a hireling, for he did it gratis.--See Penn`'s [.book-title]#No Cross, No Crown.#]
and to the liberty enjoyed in the primitive Christian churches,
where we read that not one man only,
but all might prophesy (i. e. in the sense of the apostle, speak to edification,
exhortation, and comfort) that all might learn, and all might be comforted,
and if any thing were revealed to one that sat by, the first was to hold his peace.^
footnote:[1 Cor. 14:3,30,31.]
What I mean is their practice of exhorting and warning
the people to repentance and the fear of the Lord,
sometimes in the streets and markets,^
footnote:[See the above note.]
and sometimes in the public places of worship,
commonly after the priest had ended his service;
where also they sometimes desired the priests to prove their doctrine,
and some even took the liberty of reproving the priests,
when it appeared evident to them that they had preached
things false and contrary to Scripture.^
footnote:[See the compendious [.book-title]#View of Extraordinary
Sufferings of the People Called Quakers in Ireland,#
page 106, 111, 112.]

On these accounts they suffered loss of goods, fines, whippings, cruel beatings,
and long imprisonment.

The same treatise from whence this extract is taken,
gives many instances of great and grievous sufferings
they also underwent by spoiling of goods,
fines, and imprisonment, for their not daring to break the command of Christ,
"`Swear not at all;`" and some for not fighting.

Nor were their sufferings inconsiderable merely on the account of their
conscientiously refusing to take off their hats in honour to man (as deeming
this to be a mark of reverence proper to divine worship,
according to 1 Cor. 11) as appears from the following instances in the same treatise.

A+++.+++ D. 1661.
William Edmundson, Thomas Lunn, Richard Faile, William Parker, and Thomas Hutchinson,
were fined by judge Alexander, at the assizes at Cavan,
seven pounds a man for not taking off their hats.

In the year 1655, Michael Richards, for wearing his hat on in the court of Cork,
being sent for thither as a witness about his master,
who was then at the bar upon his trial, was by John Byffe, then judge,
fined twenty pounds.
And for the same offence, at the assizes in New Ross, was John Rodman,
committed to jail by judge Louder, kept a prisoner three months,
and then banished +++[+++from] that country.

They also suffered greatly by spoiling of goods;
and some instances occur in the above treatise,
of excommunication and imprisonment on the account merely of their
following their lawful vocations on the days called holy days,
as judging these observations entirely superstitious,
introduced in the dark night of apostasy,
and that they were called of God thus to bear an open, public testimony against them.

I shall here subjoin a short extract from the treatise aforesaid,
exhibiting the sum total of Friends sufferings,
and numbers of prisoners under each reign from the beginning,
and then conclude with the total annual sufferings to the present time,
with a few remarks.

++++
<table class="tableblock frame-all grid-all spread">
  <colgroup>
    <col style="width: 36.3636%" />
    <col style="width: 18.1818%" />
    <col style="width: 9.0909%" />
    <col style="width: 9.0909%" />
    <col style="width: 9.0909%" />
    <col style="width: 18.1819%" />
  </colgroup>
  <thead>
    <tr>
      <th class="tableblock halign-left valign-top"><em>Under the Reign of</em></th>
      <th class="tableblock halign-left valign-top">No. of Years they reigned.</th>
      <th class="tableblock halign-left valign-top" colspan="3">Value Taken.</th>
      <th class="tableblock halign-left valign-top">Prisoners.</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="tableblock halign-left valign-top"></td>
      <td class="tableblock halign-left valign-top"></td>
      <td class="tableblock halign-left valign-top">
        <p class="tableblock"><em>£.</em></p>
      </td>
      <td class="tableblock halign-left valign-top">
        <p class="tableblock"><em>.s</em></p>
      </td>
      <td class="tableblock halign-left valign-top">
        <p class="tableblock"><em>.d</em></p>
      </td>
      <td class="tableblock halign-left valign-top"></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top">
        <p class="tableblock">The Protectors, (so called)</p>
      </td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">5</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">86</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">13</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">6</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">101</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top">
        <p class="tableblock">K. Charles II.</p>
      </td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">36</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">3824</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">16</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">8½</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">780</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top">
        <p class="tableblock">K. James II.</p>
      </td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">4</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1583</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">14</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">3</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">12</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top">
        <p class="tableblock">K. William &amp; Q. Mary</p>
      </td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">13</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">13724</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">9</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">3½</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">33</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">Q. Ann</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">12</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">16199</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">15</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">3½</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">13</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top">
        <p class="tableblock">K. George I.</p>
      </td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">13</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">22513</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">14</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">10</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">27</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"></td>
      <td class="tableblock halign-left valign-top">
        <p class="tableblock"><strong>In all</strong></p>
      </td>
      <td class="tableblock halign-left valign-top">
        <p class="tableblock"><strong>57933</strong></p>
      </td>
      <td class="tableblock halign-left valign-top">
        <p class="tableblock"><strong>3</strong></p>
      </td>
      <td class="tableblock halign-left valign-top">
        <p class="tableblock"><strong>10½</strong></p>
      </td>
      <td class="tableblock halign-left valign-top">
        <p class="tableblock"><strong>966</strong></p>
      </td>
    </tr>
  </tbody>
</table>
++++

[.offset]
The annual sum total of Friends`' Sufferings, chiefly for tithes, priests maintenance,
and other ecclesiastical dues so called; and for repair of parish worshiphouses,
from the year 1727 to 1751, inclusive.

++++
<table class="tableblock frame-all grid-all spread prisoner-table">
  <colgroup>
    <col style="width: 12.5%" />
    <col style="width: 12.5%" />
    <col style="width: 12.5%" />
    <col style="width: 12.5%" />
    <col style="width: 50%" />
  </colgroup>
  <thead>
    <tr>
      <th class="tableblock halign-left valign-top" colspan="4">
        <span class="force-center">K. George II.</span>
      </th>
      <th class="tableblock halign-left valign-top">
        <span class="force-center">Prisoners</span>
      </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">Years</p></td>
      <td class="tableblock halign-left valign-top" colspan="3">
        <p class="tableblock"><span class="force-center">Sums.</span></p>
      </td>
      <td class="tableblock halign-left valign-top" rowspan="4"></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"></td>
      <td class="tableblock halign-left valign-top">
        <p class="tableblock"><em>£.</em></p>
      </td>
      <td class="tableblock halign-left valign-top">
        <p class="tableblock"><em>.s</em></p>
      </td>
      <td class="tableblock halign-left valign-top">
        <p class="tableblock"><em>.d</em></p>
      </td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1727</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1939</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">2</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">2</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1728</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1777</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">2</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">0</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1729</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1921</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">10</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">0</p></td>
      <td class="tableblock halign-left valign-top" rowspan="5">
        <p class="tableblock">
          <span class="prisoner-desc"
            >Three friends of Charlemont meeting, on account of tithes.</span
          >
        </p>
      </td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1730</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1368</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">3</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1731</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1589</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">19</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">9½</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1732</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1591</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">6</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">3</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1733</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1585</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">0</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">4</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1734</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1534</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">7</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">4</p></td>
      <td class="tableblock halign-left valign-top" rowspan="9">
        <p class="tableblock">
          <span class="prisoner-desc"
            >James Simpson, and Joshua Deale, in Cavan gaol, through the severity of Hugh
            Reilly, a popish tithe-taker under Witnel Sneyd, vicar-general of Kilmore and
            Ardagh, and continued prisoners above a year.</span
          >
        </p>
      </td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1735</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1458</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">7</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">7</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1736</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1485</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">18</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">0</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1737</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1599</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">17</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">9</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1738</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1486</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">13</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">7</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1739</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1511</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">0</p></td>
      <td class="tableblock halign-left valign-top">
        <p class="tableblock">8 <span class="faux-footnote">*</span></p>
      </td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1740</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1884</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">6</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">0</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1741</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1738</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">15</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">7</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1742</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1532</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">7</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">8</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1743</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1460</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">9</p></td>
      <td class="tableblock halign-left valign-top">
        <p class="tableblock">6 <span class="faux-footnote">†</span></p>
      </td>
      <td class="tableblock halign-left valign-top" rowspan="9">
        <p class="tableblock">
          <span class="prisoner-desc"
            >Joshua Thompson of Carlow Monthly meeting, on account of tithes, who
            continued a prisoner for some time.</span
          >
        </p>
      </td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1744</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1505</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">3</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">11½</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1745</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1687</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">14</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">6</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1746</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1687</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">14</p></td>
      <td class="tableblock halign-left valign-top">
        <p class="tableblock">6¾ <span class="faux-footnote">‡</span></p>
      </td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1747</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1450</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">9</p></td>
      <td class="tableblock halign-left valign-top">
        <p class="tableblock">3½ <span class="faux-footnote">§</span></p>
      </td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1748</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1605</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">11</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1½</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1749</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1564</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">11</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">11</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1750</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1760</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">7</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">8</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1751</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">1743</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">19</p></td>
      <td class="tableblock halign-left valign-top"><p class="tableblock">0½</p></td>
    </tr>
    <tr>
      <td class="tableblock halign-left valign-top">
        <p class="tableblock"><strong>Total</strong></p>
      </td>
      <td class="tableblock halign-left valign-top">
        <p class="tableblock"><strong>40469</strong></p>
      </td>
      <td class="tableblock halign-left valign-top">
        <p class="tableblock"><strong>17</strong></p>
      </td>
      <td class="tableblock halign-left valign-top">
        <p class="tableblock"><strong>6¼</strong></p>
      </td>
      <td class="tableblock halign-left valign-top"></td>
    </tr>
  </tbody>
</table>
++++

[.offset]
+++[+++The reader is referred to the footnotes for additional details
corresponding to the symbols found in the table above.+++]+++^
footnote:[+++*+++In the year 1739, a certain grievous suffering befel some Friends,
on a particular occasion, which was owing to the imprudence of some on the one hand,
and the inveterate rage of a party on the other, newly awakened;
of which it may not be improper to subjoin some account:--On the 5th of the Ninth month,
being the day usually celebrated by the Protestants in commemoration
of their deliverance from the Gun-powder Plot,
certain Protestant journeymen and servants belonging to some Friends living at
Timahoe in the county of Kildare (where is a settlement of Friends amidst great
numbers of Papists) did likewise make a fire there on an eminence on that day,
which being supposed to have been done by Friends,
though unjustly (except some giddy young persons who were not so clear of encouraging
the thing as they ought to have been) such methods of rejoicing having ever been inconsistent
with the declared principles and practices of this people on all such occasions,
the popish rabble took offence, aggravated the affair by misrepresentations and lies,
and carried their resentment to such a degree of insolence and barbarity,
that they first burnt Friends meetinghouse there,
and afterwards several of their outhouses, from which proceedings,
together with other insults and menaces,
there was great reason to apprehend that their fury, unless speedily repressed,
would have been extended to many other Friends in distant places.
Hereupon Friends of Dublin made application to the government for protection,
and personally to the Duke of Devonshire, then lord-lieutenant,
whose great tenderness towards Friends on this occasion,
deserves to be gratefully commemorated, in sending down instantly upon their application,
parties of soldiers to Timahoe, for the protection of Friends there,
in issuing a proclamation for apprehending the offenders,
and ordering a commission of Oyer and Terminer, to bring them to justice; which,
although it did not succeed, through a defect in,
and gross prevarication among the evidences,
was such an instance of the countenance and regard
of the government as was of great service;
and the damages were afterwards recovered upon the popish inhabitants,
according to act of parliament.
{footnote-paragraph-split}
+++†+++To the year 1743 add 18£. 11s. 9d.
being the damage sustained by several Friends of Limerick, Waterford, and Clonmel,
by a rude mob of soldiers and others, breaking their windows, etc. because,
for conscience-sake,
they could not join with the multitude in illuminating their windows,
and making bonfires, on the news of a late supposed victory at sea.
{footnote-paragraph-split}
+++‡+++To the year 1746 add 27£. 4s. 4d. being the loss
suffered by Friends of the City of Cork this year,
by a rude assembly of soldiers and other rabble breaking their windows,
because they could not illuminate them on a night of rejoicing for the
victory obtained by the king`'s forces over the rebels in Scotland,
and this not through the least disloyalty or disaffection to the government,
they being sensible of the great savour of Providence in delivering them,
in common with other Protestant dissenters, from the late imminent danger,
but purely for conscience-sake,
as believing such way of rejoicing not to be consistent with the
gravity and reverence becoming a Christian on such occasions,
nor with that precept in holy Scripture, Ps. 2:11, "`Serve the Lord with fear,
and rejoice with trembling.`"
{footnote-paragraph-split}
On this occasion Primate Hoadley, Robert Lord Newport, and Henry Boyle, Esqrs.
Lord`'s Justices, were applied to by Friends of Dublin in behalf of their Friends of Cork,
who wrote forthwith to the mayor of Cork, Walter Lavit,
in order to discourage such practices for the future.
{footnote-paragraph-split}
+++§+++To the year 1747,
add 10£. 9s. 11+++½+++d. being the damage again sustained by Friends of Cork this year,
on a like occasion as that mentioned last year.]

A few Remarks, arising partly from the foregoing account,
and partly from a perusal and impartial consideration
of the records of the state of the society,
from the year 1727 to the year 1748 inclusive, are obvious, viz.

[.numbered-group]
====

[.numbered]
1+++.+++ That during the reign of our present gracious sovereign
George II. whilst the great blessing of liberty of conscience,
and of preaching the gospel freely, is enjoyed,
the testimony of truth gains esteem in divers places,
and the wrong apprehensions of many concerning Friends, are removed.

[.numbered]
2+++.+++ The chief sufferings of Friends are for tithes, priests maintenance,
and other ecclesiastical demands, and during these twenty-one years,
there have been but six prisoners on this account.

[.numbered]
3+++.+++ That sometimes the priests take their tithes both in a cruel and in an illegal manner,
which brings hardships on the poor (which most frequently happened
in the province of Ulster) and the rather because divers priests
set their tithes to wicked and vexatious persons.

[.numbered]
4+++.+++ It is not less worthy of observation, that in this calm summer-season,
when the severe penalties of fines and imprisonments formerly inflicted on Friends,
for not daring to forsake the assembling themselves
together for the worship of Almighty God,
are entirely withdrawn, negligence and lukewarmness, with respect to that essential duty,
hath crept in and prevailed among the descendants of this once persecuted people;
it being a common complaint during the above mentioned period,
that a conformity to the vain and corrupt fashions of the world prevails among the youth,
and a coolness of zeal in attending the meetings
of worship and discipline among those of riper years.

[.numbered]
5+++.+++ Though a faithful few be preserved alive to mourn over the declining multitude, yet,
as the negligence before-mentioned is undoubtedly an inlet to many evils,
these sometimes break forth openly, to the great obstruction of the progress of truth,
and stumbling-blocks are thrown in the way of the sincere inquirer: nevertheless,
whilst a wholesome discipline is continued to be exercised on offenders,
the society is no longer justly chargeable with the scandal hereby given.

====

[.the-end]
Finis
