== Part II.

[.heading-continuation-blurb]
Of the Reformation, and its Gradual Progress, and the Defects Yet Attending it.

Of the woeful darkness above described,
which did for some ages eclipse the brightness of the gospel-day,
it has seemed good to Divine Providence to forewarn us in the Revelation,
where the church is supposed to be represented by the "`woman clothed with the sun,
and the moon under her feet,
and upon her head a crown of twelve stars,`" and being with child,
and persecuted by the dragon "`whose tail drew the third
part of the stars of heaven and did cast them to the earth;
and he stood before the woman which was ready to be delivered,
for to devour her child as soon as it was born; but the child being brought forth,
and caught up to God and his throne,
she fled into the wilderness,`" (a state of obscurity) and
was to remain there during the time appointed her of God:
which was but a limited time, and is believed to have been accomplished,
and that the return of the church out of the wilderness commenced at the reformation,
and that this great work shall be carried on and perfected in God`'s time.

It must indeed be acknowledged, to the glory of God`'s good providence,
that even in the most dark and corrupt ages there was still preserved a faithful remnant,
who bore witness against the prevailing corruptions,
though the greater part of these were branded for heretics by the ruling majority,
whereof it is necessary to subjoin a few instances.

A+++.+++ D. 815, Claudius, bishop of Turin,
is stigmatized for an arch heretic for teaching that the cross is not to be worshipped,
nor the sepulchres nor relics of saints, and that pilgrimages are vain:
and for the like reason were Petrus de Bruis and Henricus ex Monacho,
A+++.+++ D. 1119 branded for heretics.^
footnote:[Synope Concilior.
Paris 1671]

In the year 1146 lived Hildegardis, a prophetess,
and indeed so esteemed by the papists themselves, who among other things^
footnote:[[.book-title]#Fox`'s Eccl.
History, Vol 1,# p. 237-238.]
prophesies against the priests and prelates of the Romish church thus:

[quote]
____
Now is the law neglected among the spiritual people,
which neglect to teach and do good things; the master likewise and the prelate do sleep,
despising justice, and laying it aside:
and in a certain vision the church appeared to her in the shape of a woman
complaining that the priests had bewrayed her face with dust,
rent her coat, etc. and that they did not shine over the people, neither in doctrine,
nor example of life that all ecclesiastical order did every day be come worse and worse,
and that the priests did not teach, but destroy the law of God:
and for these horrible crimes she threatens and prophesies
unto them God`'s most heavy wrath and displeasure,
and doleful punishments.
The crown of apostolical honour shall be divided,
because there shall be found no religion among the apostolical order;
and for that cause shall they despise the dignity of that name,
and shall set over them other men and other archbishops,
in so much that the apostolic see of that time shall have scarce
Rome and a few other countries thereabouts under his crown.
And these things shall partly come to pass by incursion of wars,
and partly also by a common counsel and consent of the secular and spiritual persons.
Then shall justice flourish,
so that in those days men shall honestly apply themselves
to the ancient customs and discipline of ancient men,
and shall observe them as ancient men did.^
footnote:[Ibid, _Vol. 1,_ p. 238.]
____

A+++.+++ D. 1160, one Waldo, a merchant of Lyons,
applying himself to the study of the Scriptures,
and finding there no grounds for several of the popish doctrines,
and particularly transubstantiation, publicly opposed them.
His followers, called Waldenses, were grievously persecuted by the reigning power,
some of them burnt to death, and others scattered into various countries;
and indeed they did overspread a great part of Europe,^
footnote:[[.book-title]#Rapin`'s History of England, Vol. 3#]
by which means (to the glory of God`'s Providence bringing
good out of evil) the reformation was also spread.

[.offset]
Among others of their tenets were the following:

[quote]
____
That the church of Rome is Babylon spoken of in the Revelation:
that praying for the dead is vain, and a thing only found out for the profit of priests:
that the host is an idol:
that the feasts and festivals of the saints ought to be rejected:
that preaching of the word is free to all men called thereunto.^
footnote:[[.book-title]#Fox`'s Ecclesiastical History, Vol.
1#]
____

And indeed in that dark interval of time, between the year 1170 and 1470,
many bore a public testimony against the corruption and
abominable idolatry which was crept into the church;
though commonly with the loss of their liberties or lives;
for a further account of whom I refer to the last-cited author; and it is observable,
to the glory of the power and providence of God, now as formerly,
"`choosing the weak things to confound the things that are mighty;`"
and that though there were some learned men among these,
many of them were mean persons, mechanics, and several women,
(who suffered for their testimony to the Truth):
not for the most part the men of the establishment, the mercenary priests and bishops,
who were commonly their persecutors, and hindered, as much as in them lay,
the progress of the reformation.

In the year 1370, lived Bridget, dignified by the name of Holy,
the church of Rome having canonized her not only for a saint, but prophetess, who,
not withstanding, in her book of revelations,
was a great rebuker of the pope and of the filth of his clergy,
calling him a murderer of souls, a spiller and piller of the flock of Christ,
affirming that the prelates, bishops, and priests,
are the cause why the doctrine of Christ is neglected and almost extinct;
that the clergy have turned the Ten Commandments of God into two words, _Da Pecuniam,_
or "`Give money;`" and prophesies that the see of the pope
shall be thrown down into the deep like a millstone.^
footnote:[[.book-title]#Fox`'s Ecclesiastical History#]

But it were an inexcusable neglect, in a discourse of this kind,
to suppress one fact redounding to the singular honour of the English nation,
or rather a notable instance of God`'s goodness worthy of the most
grateful commemoration from the people of these nations,
namely,
that England was one of the first that was favoured
with the dawn of the glorious light of the reformation,
even long before the days of Martin Luther, by the means of John Wickliff,
who has been called the morning-star of the reformation,
and was born about the year 1324, was Divinity Professor in Oxford,
and afterwards parson of Lutterworth in Leicestershire.
He flourished in the latter end of king Edward III.
and the beginning of king Richard II`'s time,
about 130 years before the reformation of Luther.^
footnote:[[.book-title]#Neal`'s History of the Puritans#]
He published certain conclusions against transubstantiation
and the infallibility of the pope,
and that the church of Rome was not the head of all other churches.
That the New Testament is a perfect rule of life and manners,
and ought to be read by the people.
He also declared against the establishment of tithes, asserting them to be pure alms,
and maintained that to restrain men to a prescribed form of prayer,
is contrary to the liberty granted them by God.^
footnote:[[.book-title]#Neal`'s History of the Puritans#]

For these and other pretended heresies his books were, by the pope and his cardinals,
condemned to the flames,
and his bones were taken out of the grave and burnt forty-one years after his death,
by a decree of the synod of Constance, as is before observed.

His followers, otherwise called Lollards, in the year 1389,
began to separate from the church of Rome,
and to appoint priests from among themselves to perform divine service in their own way;
and it is observable, that the church of England,
though she embraces Wickliffs doctrines with regard to articles of faith,
cannot however forbear expressing very little esteem for that doctor,
because he has combated the hierarchy which she has thought fit to retain.^
footnote:[[.book-title]#Rapin`'s History of England.#]

That we may judge how necessary, and at the same time how great and difficult,
that work of reformation was, which he was instrumental, through God`'s good providence,
to promote,
it seems worth our while to look back and consider
what the state of the church was in those days,
which is thus described by Fox in his [.book-title]#Ecclesiastical History.#

[quote]
____
The Scriptures, learning, and divinity, were known but to few,
and that in the schools only, and there also converted almost all into sophistry.
Instead of Peter and Paul, men occupied their time in studying Aquinus and Scotus,
and the master of sentences.
The world leaving and forsaking the lively power of God`'s spiritual word and doctrine,
was altogether led and blinded with outward ceremonies and human traditions,
wherein the whole scope in a manner of all Christian perfection did consist and depend.
In these was all hope of obtaining salvation fixed: hereunto all things were attributed.
Instead of the apostolic gifts, and continual labours and travels,
slothfulness and ambition was crept in among the priests.

Thus, in these times of horrible darkness and ignorance,
what time there seemed in a manner no one spark of pure doctrine left remaining,
did the aforesaid John Wickliff, by God`'s providence, rise up,
through whom the Lord would first waken and raise
up the world overwhelmed with human traditions.
____

Walter Brute was another of the first reformers mentioned by the same author,
who appeared also in king Richard II`'s time, among other truths contending for this,
that tithes are not due by the law of Moses, nor by the law of Christ,
but by the tradition of men only:
he also reasoned strongly upon Christian principles against fighting and swearing.

A+++.+++ D. 1410, the doctrines of the gospel began to be spread in Bohemia,
by means of the books of Wickliff (which happened
through the interaction between England and Bohemia,
upon occasion of king Richard II. marrying queen Ann,
who was a Bohemian) which then coming into the hands of John Hus
(a learned man and preacher at that time in the university at Prague),
and others both men and women, especially of the lay-sort and artificers,
were a means of awakening them: and Jerom, of Prague, Master of Arts,
was the companion of the said Hus, and his fellow in bonds,
and both underwent the same tragedy: they were burnt to death,
and their ashes thrown into the river.
About the year 1517 and 1521, Luther, in Germany, and Zuinglius, in Switzerland,
wrote against the Pope`'s indulgences and pardons,
and from there proceeded gradually to detect many other of the errors of popery,
as is above observed;
and the reformation made a considerable progress in those
countries by the preaching and writings of the said Luther,
Zuinglius, Melancton, Oecolampadins and others,
some of whose books which had been published in those parts,
being translated into English,
excited the curiosity of the people to look into the state of religion at home.

At a time not far distant from this, "`William Tindal,
brought up in the university of Oxford,
where he increased as well in the knowledge of the tongues and liberal
arts as (and more especially) in the knowledge of the Scriptures,
whereunto his mind was singularly addicted,
considering the great mischief done to the church,
by keeping the Scriptures of God hid from the people`'s eyes,
was therefore moved to translate the Scripture into his mother-tongue,
for the public utility of the simple vulgar people of the country,
and accordingly did translate the New Testament about
the year of our Lord 1527 or 1529. But,
did the clergy and prelates encourage the publication of it?
No such matter; they cried out strenuously against it,
representing that there were a thousand heresies in it;
that it was not fit to be corrected, but utterly to be suppressed.
Some said, that it was not possible to translate the Scripture into English;
some that it was not lawful for lay-people to have it in their mother-tongue;
some that it would make them all heretics;
and to the intent to induce the temporal rulers also to their purpose,
they said it would make the people to rebel and rise against their king.
Such were the forward devices of the English clergy to drive
the people from the text and knowledge of the Scripture,
which they would neither translate themselves,
nor yet abide it to be translated by others: to the intent (as Tindal himself says) that,
the world being kept still in darkness,
they might sit in the consciences of the people through
vain superstition and false doctrine,
to satisfy their lusts, their ambition, and insatiable covetousness.
In fine,
the clergy never rested until they had procured by proclamation
the prohibiting the said translation of the New Testament of Tindal,
and not contented herewith,
proceeded further to entangle him in their nets and bereave him of his life,
which at length they effected.`"^
footnote:[[.book-title]#Fox`'s Ecclesiastical History.#]

However,
this translation of the Scriptures into the vulgar
tongue did at length prevail over opposition;
whereby the doctrines of the New Testament were spread among the people,
whose curiosity was also hereby greatly raised;
and although the bishops bought up and burnt all
the books of this sort they could meet with,
the testament was printed abroad, and sent over to merchants in London,
who dispersed the copies privately among their friends and acquaintance:
and at length Tindal`'s bible, reviewed and corrected by Cranmer,
was allowed by authority, and in the year 1538, by king Henry Vlll`'s injunctions,
was set up in all the churches in England, that the people might read it.^
footnote:[[.book-title]#Neal`'s History of the Puritans.
Vol. 3#]

Such light was by this means diffused among the people,
as soon detected many of the abominable corruptions of the Christian doctrine,
which had crept in, in the times of darkness and ignorance; particularly purgatory,
the power of indulgencies, transubstantiation, the worship of saints,
and veneration of images, the supreme authority of the church and bishop of Rome,
etc. which, like birds of the night, disappeared on the dawn of this glorious day:
and indeed the first reformers deserve to be acknowledged as excellent instruments,
raised up by God`'s good providence, to begin the purging and building of his house,
and worthy to be had of us and posterity in everlasting remembrance: but,
without in the least detracting from the honour due to those Christian heroes,
it must be acknowledged that the great work of a complete reformation and restoration
of the primitive purity and simplicity was not the work of one day,
year, or age;
and indeed as the apostasy itself did not arrive at that
tremendous height to which I have traced it,
so neither is the return from there to be effected, all at once;
but notwithstanding several considerable advances have been made at different times,
and in different countries in this great work, and some establishments been formed,
yet that some of the dregs of popish corruption have been, and still are, retained,
we acknowledge and deplore, with many sincere protestants of other communities,
the removal of which is earnestly to be desired.

To this purpose I think it worth while here to recite
some part of the memorable speech of John Robinson,
an Independent minister, on his taking leave of his congregation,
mentioned in [.book-title]#Neal`'s History of the Puritans,# in the time of king James 1. A. D. 1620:

[quote]
____
Follow me no farther than you have seen me follow the Lord Jesus.
If God reveal anything to you by any other instrument of his,
be as ready to receive it as ever you were to receive any truth by my ministry;
for I am verily assured that the Lord has yet more
truth to break forth out of his holy word.
For my part I cannot sufficiently bewail the condition of
the reformed churches who are come to a period in religion,
and will at present go no farther than the instruments of their reformation.
The Lutherans cannot be drawn to go farther than what Luther saw:
and the Calvinists stick fast where they were left by that great man of God,
who yet saw not all things.
This is a misery much to be lamented;
for though they were burning and shining lights in their times,
yet they penetrated not into the whole counsel of God.
It is not possible that the Christian world should come
so lately out of such thick antichristian darkness,
and that perfection of knowledge should break forth at once.
____

I proceed therefore to the ungrateful talk of specifying
several instances of the imperfection of the reformation,
and to show the true grounds of the separation of
this people from the established church of this nation,
with respect to some of the most important particulars wherein they differ from it;
whether they be such as are common to them and other protestant dissenters,
or such as are peculiar to themselves.
That too much of the pride and covetousness, and some degree of the tyranny,
of antichrist is still retained, among the men called the clergy of the establishment,
will be too manifest if we consider,

[.numbered-group]
====

[.numbered]
I+++.+++ That they also appropriate unto themselves both
the name and jurisdiction of the church,
excluding those they call Laicks both from the title and the power annexed to it;
hereby depriving them of their original rights as Christian brethren,
according to the primitive example, as is before shown;
and that the entire separation of laymen from the ecclesiastical
assemblies was the genuine effect of the growing pride of the clergy,
and did not take place until Pope Innocent II`'s time.

[.numbered]
II. What,
but the remains of the pride of antichrist has induced those called Lords-Archbishops
and Lords-Bishops to assume a lordship over God`'s heritage,
and to become too little apt to teach, contrary to the primitive injunctions to bishops?

[.numbered]
III.
Persecution is another of the vile relics of the pride and cruelty of antichrist;
and to say the truth,
too much of the principles and spirit of persecution came over with the reformers themselves;
and almost all parties and denominations in their turn have
had a notion of serving God by doing mischief to men,
men who could not believe as they pleased,
or would not lie in professing to believe what they did not.
Thus, though the church of England be justly esteemed at present for her moderation,
having long since ceased to punish dissenters, as formerly, with imprisonment,
and the loss of estate or life; yet as long as Athanasius`'s creed,
together with the sentence of everlasting perdition thereunto annexed, is retained,
and a subscription of certain articles of faith is imposed in their universities,
on all their members, on pain of their entire exclusion from there,
I think it can hardly be denied that something of
that same tyrannical spirit (which as is before shown,
arrogated to itself the supreme direction of universities)
is still retained also in this instance:
and indeed every imposition of creeds, common prayers, and liturgies,
scarce possible to be so framed as everyone can honestly subscribe them,
seems to have taken its rise from the same origin;
and the multiplication of creeds has ever been attended with the
pernicious consequence of scattering and dividing Christians,
although proposed as a means to unite them.

I find that the very same spirit prevailed likewise both in the Kirk of Scotland,
and the Presbyterians in England; for in the year 1645,
the Scots published a declaration against the toleration of sectaries,
and liberty of conscience, in which they even say,
that liberty of conscience is the nourisher of all heresies and schisms;
and the Presbyterians, during the anarchy,
frequently addressed for the suppression of all sectaries by the civil authority,
and declared against toleration and liberty of conscience,
both from the pulpit and press.
They pressed covenant uniformity, yes, and uniformity in matters of belief,
on pain of imprisonment and death itself,
as appears by their ordinance against what they are pleased to all blasphemy and heresy.^
footnote:[[.book-title]#Neal`'s History of the Puritans, Vol.
III.# p.497-500.]

[.numbered]
IV. I proceed next to consider the covetousness of those
who call themselves the clergy of the reformed church.

====

What a trade the pope and his dependents exercised with the gospel;
how gainful to themselves, and oppressive to the people, has been amply shown above.
It were greatly to be wished, that it could be affirmed truly,
that nothing of the same spirit possessed the hearts of the reformers: but the truth is,
that the present support of their ministry is worldly, and their call,
though professedly from a motion of the Holy Spirit, is truly like a merely human one,
undertaken not only for the support, but aggrandizement of families,
contrary to the tenor of the precepts of the gospel.
Their maintenance by tithes is no other than a Jewish rite,
a popish innovation which took place in the midnight of apostasy and degeneracy,
as has been before observed; when a corrupt ministry,
becoming strangers to the love of God and their brethren, lost also confidence in both,
and so deemed it necessary to have secured to themselves
by law what lacked authority in the gospel,
and by force to extort a maintenance formerly yielded by free will:
nor indeed can we say better of some of the pretended reformers in the anarchy;
for although the Independents and Anabaptists concurred in desiring
the abolition of tithes as being of Judaical institution,
which was also one of those national grievances the army proposed to redress,
yet the reigning party were not willing to part with
an establishment so grateful to flesh and blood;
for the parliament in the year 1644,
published an ordinance enjoining the payment of tithes.
A few more particular instances of covetousness too flagrant,
and such as are both highly reproachful to a Christian ministry and hurtful to mankind,
will but too clearly evince what I proposed:

[.numbered-group]
====

[.numbered]
I+++.+++ What is the dispensing with the publication of the bans of matrimony in the congregation,
by a bishop`'s licence, for a certain sum of money,
but a corruption of Christian discipline for the sake of dishonest gain?
and truly of the same spirit and origin as the dispensing power of the Pope,
or the redeeming of penance with money;
a corruption so much the more worthy of being taken notice of,
as by this means the rights of parents are daily invaded,
many an unthinking couple are precipitated into ruin,
and the peace and religious economy of families is destroyed
through this truly licentious method of marriage,
and which by a strict; and wholesome discipline, might, in many cases, be prevented.

[.numbered]
II. What shall we think of their pluralities of benefices, and their non-residence,
but as reproachful instances of the same spirit of covetousness still subsisting,
and an express breach of the solemn promise made by every priest at his ordination?
"`that besides administering the doctrine and sacraments and discipline of Christ,
he will be ready to use public and private monitions and exhortations,
as well to the whole as the sick within his cure, as need shall be given,
and as occasion shall require?`"

====

I have above shown, that these non-residences and pluralities,
as likewise the translation of bishops from one city or bishopric to another,
are severely prohibited by several canons and decrees
of councils received even among the papists;
and that the dispensing with them is, in its origin,
a genuine fetch of popish policy to get money;
from which it is greatly to be wished that the churches
professing reformation were entirely delivered.

As I look upon this affair, how much soever countenanced or neglected at present,
to be of great importance,
I think it worth my while to transcribe here (from [.book-title]#Fox`'s Acts
and Monuments#) the sense of a king of England on this matter,
that is, Henry III.,
who on this occasion wrote to one of his bishops in the following terms:

[.embedded-content-document.letter]
--

[.blurb]
=== The King to the Bishop of Hereford Sends Greeting

Pastors or shepherds are set over their flocks that by exercising
themselves in watching over them day and night,
they may know their own cattle by their look,
bring the hunger-starved sheep into the meadows of fruitfulness,
and the straying ones into one fold, by the word of salvation and the rod of correction,
and to do their endeavour that unity in dissoluble may be kept.

But some there be, who damnably despising this doctrine,
and not knowing to discern their own cattle from another`'s,
do take away the milk and the wool, not caring how the Lord`'s flock may be nourished:
they catch up the temporal goods, and who perishes in their parish with famishment,
or miscarries in manners they regard not: which men deserve not to be called pastors,
but rather hirelings.

And that we even in these days, removing ourselves into the marches of Wales,
to take order for the disposing of the garrisons of our realm,
have found this default in your church of Hereford, we report it with grief;
for that we have found there a church destitute of a pastor`'s comfort,
as having neither bishop nor official, vicar nor dean,
that may exercise any spiritual function or duty in the same.
But the church itself (which was accustomed in times past to flow in delight,
and had canons that tended upon days and nights service,
and that ought to exercise the works of charity, they forsaking the church,
and leading their lives in countries far from here)
has put off her stole or robe of pleasure,
and fallen to the ground, bewailing the loss of her widowhood,
and there is none among all her friends and lovers that will comfort her.
Verily, while we beheld this, and considered diligently,
the prick of pity did move our souls,
and the sword of compassion did inwardly wound our heart very sore,
that we could no longer dissemble so great injury done to our mother the church,
nor pass the same over uncorrected.

Therefore we command and strictly charge you, that all occasions set aside,
you endeavour to remove yourself with all possible speed unto your said church,
and there personally to execute the pastoral charge committed unto you in the same.
Otherwise we will you to know for certainty, that if you have not a care to do this,
we will wholly take into our own hands all the temporal goods and
whatsoever else does belong unto the barony of the same church;
which for spiritual exercise therein it is certain our progenitors
out of a godly devotion have bestowed thereupon.
And such goods and duties which we have commanded hitherto to be gathered,
and safely kept and turned to the profit and commodity of the same church,
the cause now ceasing,
we will seize upon and no longer permit that he shall reap temporal things,
which fears not unreverently to withdraw and keep back spiritual things,
whereunto by office and duty he is bound,
or that he shall receive any profits which refuses
to undergo and bear the burden of the same.

[.signed-section-context-close]
Witness the king at Hereford, the 1st of June, in the 48th year of our reign.

--

So much for the pride and covetousness;
I proceed next to consider whether or no some degree of the superstition and
idolatry of Antichrist be not also retained among our professed reformers.

By superstition I mean a strenuous adherence to several of those things
which were introduced in the time of Popish darkness and apostasy,
without any authority from Scripture, And by their participating of idolatry,
I understand their inordinate and unjustifiable veneration of mere outward signs,
shadows, and representations.

[.numbered-group]
====

[.numbered]
Under the first head I rank the present observation
of saints days among those of the establishment,
who though they have justly thrown out the great rabble of Romish saints and saintesses,
yet still retain many without any authority from Scripture;
the observation of which is still grossly perverted to the purposes of vice, idleness,
and the impoverishment of families, to the no small scandal of the Christian profession,
which surely it were now much better to lay aside,
even as for this very reason was the celebration of the feasts
appointed on the days of the deaths of the early martyrs,
being perverted to excess and intemperance, in process of time, laid quite aside.^
footnote:[[.book-title]#Cave`'s Primitive Christianity.#]
To the same head I refer their dedications of churches,
and consecrations of grounds and houses.

[.numbered]
II. Though they have in part thrown out the holy water, one Jewish rite,
they have thought fit to retain another, that is, the clerical habits,
which have been before shown to be derived from the Jews,
and were established in the times of popery,
and yet are to this day insisted on as essential.
What is this but an evident breach of gospel liberty, and a relapse into Jewish bondage,
the New Testament being entirely silent about these things.

[.numbered]
III.
Though they have indeed most justly thrown down the popish altars as well as images;
yet if we impartially consider the degree of veneration paid by them to
those two outward signs and shadows commonly called the sacraments,
it seems to fall very little short of idolizing them.

====

[.offset]
That this may appear, I offer to their consideration,

[.numbered-group]
====

[.numbered]
I+++.+++ That there have been raised more controversies and quarrels (yes,
sometimes excommunications and persecutions even to bloodshed),
on account of these outside things, both between Papists and Protestants,
and among Protestants between themselves,
than matters essential to the salvation of the souls of men.
Now, what are such vehement and inordinate contentions about such things,
but the genuine products of carnal minds preferring forms, shadows, and circumstances,
to the power, substance, and essence of things: to the destruction of charity,
the badge of Christian discipleship?

[.numbered]
II. The church of Rome indeed is accused of flagrant
idolatry in falling down to worship a piece of bread;
and the zeal and indignation of many of the first reformers on this occasion,
is very remarkable,
some of whom did snatch the host out of the priest`'s hands and destroy it,
in order to show by the evidence of sense the impotency of this their new-made god:
a method of reasoning that seems to me very justifiable
from what I find recorded with marks of God`'s approbation,
in the conduct of king Hezekiah, in a case that seems to bear analogy to the present;
namely,
when the children of Israel burnt incense to the brazen
serpent (though formerly erected by divine appointment),
he broke it to pieces, and called it by way of contempt,
Nehushtan, i. e. a piece of brass.
But to return,

====

The common snare to catch the first reformers,
was to ask them what they believed of the sacrament of the altar, and their usual answer,
that it was an idol, speedily condemned them to the flames.
Now as the Reformation had its beginning in their
thus bearing testimony against the superstitious,
inordinate, and extravagant regard paid to outward signs and shadows,
so shall it receive its completion, when men,
rejecting all vain confidence in these things, shall embrace the substance.

In the mean time it must be owned that many of the successors of the first reformers,
have been so far deficient in this respect,
or at least so far from a harmonious and consistent conduct on this occasion,
as to have given too much grounds for the following sarcasm of an adversary:

[verse]
____
"`The Papists have a better plea
Than you, when they adore`'t they say
It is no longer bread and wine,
But changed by the word divine
Into the body of our Lord,
And therefore ought to be ador`'d.`"
____

[.offset]
But of the church of England, he says thus;

[verse]
____
"`Kneeling when they communicate,
Although it is but bread they eat.`"
____

They do not indeed avow with the Papists that the bread and wine
is a propitiatory sacrifice for the living and dead,
and a means to deliver souls out of purgatory; but yet,
when besides the circumstance of kneeling,
enjoined upon pain of a deprivation of various civil as well as religious privileges,
it is also made a _viaticum morientium,_
or passport for dying sinners when (without authority from Scripture)
it is dignified by the title of a principal seal of the covenant of grace;
and when we are told that the worthy receivers do really
and indeed feed on Christ crucified and receive of his fullness,
and are hereby made partakers of all the benefits of Christ`'s
death to their spiritual nourishment and growth in grace;
I pray,
what mighty difference is there between these things and what the Popish
manual pronounces concerning their venerable sacrament of the altar,
namely, that herewith we are nourished, cleansed, sanctified,
and our souls made partakers of all heavenly graces and spiritual benedictions?
Is not all this an abundant evidence of an inordinate
and superstitious regard paid hereunto,
and such as cannot be warranted by authority from Scripture?
Is not this (in the words of an eminent author)^
footnote:[[.book-title]#Plain Account of the Sacrament of the Lord`'s Supper,# published in London,
1735.]
plainly attributing that to a single ceremony, which,
according to the constant tenor of the New Testament, is due only to a universal,
faithful observation of the laws of God: and I add,
to the great damage of the souls of men,
who may be hereby betrayed into a dangerous and unwarrantable
confidence in these outward things?
And how much all this falls short of idolizing the outward and visible sign,
I leave to the judicious.

Let us next see whether we can entirely acquit them
of the same error with regard to water-baptism.
I do indeed find that the church of Rome places infants
dying unbaptized in the upper part of hell;
and truly the baptism of infants seems to have been the genuine consequence
of an opinion of its being absolutely necessary to salvation,
thus their licensing of midwives to baptize children in some cases;
and they affirm that it makes them children of God, infuses justifying grace,
and all supernatural graces and virtues.
Now though I dare not affirm of several Protestants,
that they do literally proceed to all these lengths,
yet when we find that when the child is required to answer,
that by baptism it was made a child of God, and an inheritor of the kingdom of heaven;
when in the office for the burial of the dead,
over all who have undergone this operation, whether saints or sinners, these words,
are pronounced,
"`Forasmuch as it has pleased God of his great mercy to
take the soul of our dear brother here departed unto himself,
we therefore, etc. in sure and certain hope of the resurrection to eternal life,`" etc.
But on the contrary, if any have not been baptized,
he shall not have the honour of this which is called Christian burial; in short,
when unto the ceremony of baptism is peculiarly annexed regeneration,
purgation from original sin, and a sure and certain hope of a happy resurrection,
as it seems to be by the letter of the [.book-title]#Common Prayer;# it is obvious to remark,
that what the judicious author above quoted has observed concerning the Lord`'s supper,
is also justly applicable to these accounts of baptism (in
reality but very little short of the above mentioned accounts
which the church of Rome has been pleased to give of it),
namely, that this also is plainly attributing that to one single ceremony,
which the whole tenor of the New Testament attributes
to universal holiness and obedience to God`'s commands,
a more effectual seal and sign undoubtedly of a man`'s
being a child of God of his sins being remitted,
and a far better ground for a hope of a happy resurrection;
or in other terms that one baptism whereof the New Testament frequently speaks,
and particularly in Pet.
3:21. "`The baptism which now saves us is not the putting away the filth of the flesh,
but the answer of a good conscience towards God, by the resurrection of Jesus Christ.`"
And Rom. 6, that baptism by which we "`are buried with Christ into death,
that like as Christ was raised up from the dead by the glory of the Father,
even so we should walk in newness of life.`"

Such a baptism seems most suitable to the spirituality of the new covenant dispensation,
even the substance forever to be magnified above all the "`outward washings and
carnal ordinances imposed until the time of reformation,`" Heb. 9:10,
and whereof these things are no more than a shadow or representation,
although so strenuously cried up by the ministers of the letter;
while all such as have not undergone these administrations from
their hands have ordinarily been by them numbered among infidels;
whereas the others do hereupon (if we believe them) instantly commence "`children of God,
regenerate and heirs of everlasting life.`"
Now how far all these things fall short of idolizing the outward and visible sign,
I must also leave.

I proceed in the next place,
to consider the sentiments and practice of the men of the establishment,
with regard to the call and qualifications of a Christian ministry,
and the exercise of spiritual gifts in the church:
as another important instance of their falling greatly short of the primitive pattern.

It might indeed seem rash to affirm that the call and qualifications
of the ministry of the establishment are merely human and worldly,
seeing in the book of [.book-title]#Common Prayer,#
an essential requisite to the constitution of a deacon is,
that he declare that he believes he is inwardly moved
of the Holy Spirit to take upon him that office;
and that the bishop in the ordination of every priest says,
"`Receive the Holy Spirit;`" thus undoubtedly the first compilers of that
book must have deemed such qualification essential to a Christian ministry;
and indeed to suppose that they who give and receive holy orders at this day,
do it not sincerely, were to suppose them gross prevaricators with God and man.
I shall therefore suppose them to be sincere in what they do;
but then shall beg leave to ask them, by what authority they have,
to the utmost of their power,
limited the free and universal grace and Spirit of our Lord Jesus Christ to themselves,
and to such only as shall be clothed with certain particular vestments,
and have studied the liberal arts?

Such limitations of the gifts of the Holy Spirit,
such restraints on the liberty of prophesying, seem to be very remote from the spirit,
temper, and practice of the holy men recorded in the Old and New Testament:
for we read of Moses,
(Numbers 11) that he was so far from such a monopolizing disposition,
that when news was brought to him that Eldad and Medad did prophesy in the camp,
and he was desired to forbid them, he answered, "`Are you envious for my sake?
Would God that all the Lord`'s people were prophets,
and that he would put his Spirit upon them;`" and Moses himself was a keeper of sheep,
as well as Jacob and David; Elisha, a ploughman; Amos a herdsman; Peter and John,
fishermen; Matthew, a toll gatherer; Paul, a tent-maker; and Luke, a physician;
and though looked upon as lay people by the priests of those ages, yet it pleased God,
by the operation of his Spirit, not to be bounded by mortal man,
to inspire and make of them prophets, apostles, and evangelists.

This indeed will be easily allowed with respect to those former ages,
but is pitifully denied to later times; whereas according to my sense,
it was the same Spirit that inspired our first reformers,
even that wisdom which is described to be the "`Breath of the power of God,
and a pure influence that flows from the glory of the Almighty,
which entering into holy souls,
makes them friends of God and prophets:`" (Wisdom of Solomon, 7:27) or in other words,
that eternal word of which we read in the First of John,
which took flesh in the person of Jesus Christ,
who afterwards promised to be with his disciples to the end of the world;
which can be no otherwise than by the same Word or Spirit;
and accordingly I make no difficulty in believing
that it was this same spirit that actuated Waldo,
the merchant of Lyons above mentioned, and his followers, those early reformers,
and particularly (to return to our point) their teachers,
though some of them were mechanics, as Weavers and cobblers,
which when it was offered as matter of reproach to them, they answered,
that they were not ashamed of them because they laboured with their hands,
according to the example of the apostles. Acts 20:34.

Such a liberty of prophesying is also through the
goodness of God revived and maintained in our days;
and though less adapted to tickle the ears than such preachings
as come recommended by the decorations of human art,
yet herein also more conformable to the primitive pattern,
as well as experienced more effectual to the edification of the hearers;
(1 Cor. 2:4-5) and indeed the purity and simplicity of the doctrines of the
gospel (how through the blessing of God no longer concealed in foreign languages,
but obvious and clear to an ordinary capacity) seem more likely to be
preserved among men of clean hearts and moderate understandings,
than among many of those whose learning, not being sanctified,
has tempted them to corrupt, under a pretence of refining it.

Another instance of gospel liberty revived, and agreeable to the primitive example,
though forbidden in the national and most other churches,
is that of prophesying (or speaking to edification, exhortation, and comfort) one by one,
that all might learn, and all might be comforted. 1 Cor. 14:3,31.

I know it will here be alleged,
that prophesying or preaching as a gift of the Holy Spirit, is now ceased,
together with other extraordinary operations thereof,
as the gifts of healing and tongues.
But to this I answer,
that the gift of prophesying (i. e. in the sense of Paul the apostle,
"`Speaking to men to edification, exhortation,
and comfort,`" 1 Cor. 14:3,31) is not less necessary
now than in the early ages of the church,
which cannot with truth be affirmed of the gifts of tongues and healing; tongues,
by the testimony of the same apostle, "`being for a sign not to them that believe,
but to them that believe not (which is applicable to the gift of healing);
but prophesying serves not for them that believe not, but for them which believe.`" 1 Cor. 14:22.

And indeed, as I conceive,
the only reason why the gift of prophesying in the above-mentioned apostolical sense,
is not now more diffused among Christians,
or why such is not now experienced to be the ordinary operation of the Holy Spirit,
is carnality and spiritual idleness; the promise of Christ to his disciples,
that he would be with them "`always even to the end of the world`"
and that "`where two or three were gathered in his name,
he would be in the midst of them,`" being not confined to the days of
the apostles but graciously experienced at this day to be fulfilled;
even that he is present with them who gather in his name; not as an inactive,
dormant principle, but powerful Spirit, enlightening their understanding,
warming their hearts, furnishing them with diversities of gifts,
and giving to one the "`Word of wisdom; to another faith; to one a doctrine;
to another a revelation; to another a psalm,`" etc.
1 Cor. 12 and 14,
to the glory of God and edification of the church
which assuredly now as in the primitive times,
edifies itself in love, Eph. 4:16; that fruit of the Spirit,
that greatest of all Christian graces, that love of Christ, which possessing,
the heart of Peter, the consequence was to be the feeding his sheep. John 21:16.

And indeed this love of God and the brethren (though
supplanted by the love of this world in a human,
carnal, and apostatized ministry, who have made a trade of the gospel,
and followed Jesus for the loaves and fishes) is all the
encouragement and support such a ministry needs:
and as love begets love, whatever outward support may be needful,
will be administered freely and voluntarily according to the primitive pattern, Luke 10;
and though such a ministry may not enjoy greats riches or revenues,
yet as these are provocations to luxury, and many other evils,
this will be no loss to them as spiritual men, but on the contrary,
less temptation being administered, in respect to the cares and pleasures of this life,
they will be enabled to apply themselves to the concerns of the other with less distraction,
and mine as living examples of piety among the people;
whereas on the contrary great riches settled on the
ministry have ever proved incentives to that pride,
covetousness, and luxury, which has been their disgrace and ruin:
agreeable to the observation of the difference of
the ancient from the modern times in this respect,
namely, that wooden chalices were attended by golden priests,
but golden chalices by wooden priests.

Having now shown that prophesying or preaching in the Christian church,
both was and is a gift of the Holy Spirit,
I am led to consider more minutely the practice of that
and other acts of devotion among the professed reformers,
as falling short of the primitive precepts and example: and first as to preaching.

The apostle expressly testifies "`that his speech and preaching
was not with enticing words of man`'s wisdom,
but in demonstration of the spirit and of power,
that their faith should not stand in the wisdom of men,
but in the power of God,`" 1 Cor. 2:4-5:
and that the knowledge of the things spiritual whereof they spoke,
was not attained unto by natural wisdom, but by the revelation of the spirit,
and by the spiritual man only, is the plain tenor of the contest.

But the modern preaching is with enticing words of man`'s wisdom;
and the knowledge of the things whereof the moderns
speak is acquired by study like any other science,
and by the mere natural man.

Next, as to praying and singing, the same apostle says,
"`I will pray with the spirit--and I will sing with the spirit`"--1 Cor. 14:15,
Eph. 6:18, and Jude 20, and elsewhere praying in the spirit,
and in the Holy Spirit is recommended; and the necessity of the assistance of the Spirit,
as well as the impotence of man without it is expressed in these words,
"`the Spirit also helps our infirmities: for we know not what to pray for as we ought,
but the Spirit itself makes intercession for us with groanings that cannot be uttered.`" Rom. 8:26.

Now what is complained of in the exercise of preaching, praying, and singing,
among many of the professed reformers, is their neglect of this assistance,
and of that due preparation of heart which is necessary
to the performance of these duties,
so as to render them acceptable to God or profitable to themselves.

We see no deficiency of sermons, prayers, or songs,
all made ready to be uttered at a certain hour appointed;
but whether these be a mere lip-labour, or mechanical effusion of sounds;
whether the preacher act the vain orator, preaching himself rather than Christ Jesus,
whether he affect more to tickle the ears than mend the hearts of his
hearers (who also love to have it so according to the prophecy,
"`heaping unto themselves teachers having itching ears`") 2 Tim. 4:3,
whether they either preach, pray, or sing with the spirit, whether they really pray,
or only say prayers, is very little considered.

It is, however,
the lack of this consideration that is the true reason of
the unfruitfulness of the modern prayings and preachings,
that too frequently appears both among Papists and Protestants;
and that their assiduity in observing the set hours and seasons of prayer,
etc. has little or no influence on their lives and conducts,
but these remain for the most part as bad as ever.
Men, finding it easier to sacrifice in their own wills than obey God`'s will,
have multiplied sacrifices without obedience.

Now that in this case it would be both more acceptable
to God and more profitable to men to learn silence;
yes, what is more,
that in the view of heaven the sacrifices of such are no
other than an officious and even criminal activity,
we may learn from the following express declarations of God`'s will in the holy records:
"`Unto the wicked God says, what right have you to do to declare my statutes,
or take my covenant into your mouth,
seeing you hate instruction and cast my words behind you?`" Ps. 1:16-17.
And again, "`Restore me unto the joy of your salvation,
and uphold me with your free spirit: then will I teach transgressors your ways,
and sinners shall be converted unto you.`" Ps. 50:12-13.
Again, "`You desire not sacrifice, else I would give it;
you delight not in burnt offering: the sacrifices of God are a broken spirit:
a broken and a contrite heart, O God, you will not despise.`" Ps. 51:16-17.
"`The sacrifice of the wicked is an abomination to the Lord,
but the prayer of the upright is his delight.`" Prov. 15:8.
"`To what purpose is the multitudes of your sacrifices unto me?
says the Lord.
When you come to appear before me, who has required this at your hands,
to tread my courts?
Bring no more vain oblations: incense is an abomination unto me;
the new moons and sabbaths, the calling of assemblies I cannot away with: it is iniquity,
even the solemn meeting.
Wash yourselves, make yourselves clean;
put away the evil of your doings from before my eyes, cease to do evil,
learn to do well.`"
Isaiah 1:11-13, 16-17.

To the same purpose is Isaiah 46:1-4, from all which it is evident,
that for wicked men to rush into the exercises of preaching and praying without previously
witnessing some degree of that power that changes and cleanses the heart,
is so far from being acceptable to God that it is criminal in his sight;
or in other terms that in this case silence is preferable to speaking;
and that contrition of spirit and trembling at the word of the
Lord is far more acceptable than the most pompous shows of devotion:
and if the Jews when in captivity in Babylon could no longer "`sing the song of the Lord,
but chose to sit down and weep and hang their harps on the willows,`" Ps. 137,
surely the analogy will hold,
that the like disposition of mind is most suitable also
to such whose souls are under the captivity of sin:
and this is one case wherein silence is better than speaking: there is yet another.

Men whom we call good, in this state of probation and purgation, do sometimes,
without consciousness of any crime,
experience withdrawings of that power and spirit
which at other times animates their souls:
they are left barren and impotent,
and it seems very consistent with Divine wisdom and goodness that it should be so,
in order that, being humbled under a sense of their own weakness,
they might depend on and seek after God,
a way of speaking (though much out of fashion among many modern Christians,
yet very frequent in the holy writings.) In the 104th Psalm we have a beautiful description
of God`'s power and providence over the animals even of an inferior order,
of which if it be justly said in that address to Almighty God,
"`These all wait on you that you may give them their food in due season:
you open your hand, and they are filled with good: you send forth your spirit,
they are created, and you renew the face of the earth:`" and on the other hand,
"`You hide your face and they are troubled,`" they must have a very contracted
idea of the Divine providence and goodness who could suppose that it does not
at least equally operate in the world of spirits and rational souls of men,
as-among those creatures of an inferior order:
and the latter part of the text seems also not less applicable
to the state of the souls of men in times of languor,
impotence, and desertion, according to these sayings of the Psalmist,
"`You did hide your face and I was troubled:`" and
"`O forsake me not utterly;`" Ps. 30:7 and 119:8.

Now it is expressly promised that "`They who wait on the Lord shall renew their strength,`"
Isaiah 40:31,41:1. and in the following verse silence is enjoined for this purpose:
and Ps. 46:10 it is said "`Be still and know that I am God.`"

The amusements of sensible objects, the distracting cares of this life,
and the activity of our own imaginations,
are undoubtedly great impediments to the operation of the Divine Spirit in our minds,
and not infrequently drown the voice of that eternal wisdom,
of which the wise man speaks in the 8th of Proverbs,
and pronounces that man blessed who "`hears it, watching daily at its gates,
and waiting at the post of its doors,`" which surely
he is most likely to do who is in a state of silence.
Is it not, therefore just matter of surprise, that waiting upon God in silence,
in his worship,
should be treated with such contempt as it has even lately
been among some professing great advancements in religion?

This brings me to mention a third case,
wherein silence may sometimes be chosen preferably to speaking,
which I mall express in the words of Barclay, in his 11th Proposition concerning worship:

[quote]
____
The meeting may be good and refreshful,
though from the sitting down to the rising up thereof,
there has not been a word as outwardly spoken;
and yet the life may have been known to abound in each particular,
and an inward growing up therein and thereby, yes,
so as words might have been spoken acceptably and from the life:
yet there being no absolute necessity laid upon anyone so to do,
all might have chosen rather silently and quietly to possess and enjoy the Lord in themselves;
which is very sweet and comfortable to the soul,
that has thus learned to be gathered from all its own thoughts and workings,
to feel the Lord to bring forth both the will and the deed,
which many can declare by a blessed experience;
though indeed it cannot but be hard for the natural
man to receive and believe this doctrine;
and therefore it must be rather by a sensible experience,
and by coming to make a proof of it, than by arguments,
that such can be convinced of this thing; seeing it is not enough to believe it,
if they come not also to enjoy and possess it.
____

So far Barclay, who moreover observes that this worship of God in silence,
though very different from the many established invented worships among Christians,
and such as may seem strange to many,
yet has it been testified of and practised by the most pious of all sorts in all ages
even among some of those that were otherwise over clouded with the darkness of popery,
and particularly by the mystical writers, a sect generally esteemed by all,
and so called from their professing and practising thereof,
whose books are full of the explanation and commendation of this sort of worship,
where they plentifully assert the inward introversion and abstraction of the mind,
as they call it, from all images and thoughts, and the prayer of the will; indeed,
they look upon this as the height of Christian perfection.^
footnote:[See Barclay`'s [.book-title]#Apology,# Prop.
2, Sect.
16.]

To the above instance let me add an account of a certain people,
called a sect prevailing very much among the Protestants of Germany and those of Switzerland,
who call themselves Pietists,
which has been left us by a very learned writer in his travels to Italy,^
footnote:[Joseph Addison]
of whom though he be no admirer,
nor indeed recommends their practice as an example worthy to be followed,
yet as his naked narration of matter of fact seems well worthy of notice,
and to be pertinent to my present purpose of showing
that not only the despised people called Quakers,
but many others, of different ages and countries,
have also both recommended and practised this worship of Almighty God in silence,
I shall here subjoin it:

[quote]
____
They pretend to great refinements, as to what regards the practice of Christianity,
and to observe the following rules: to retire much from the conversation of the world:
to sink themselves into an entire repose and tranquillity of mind.
In this state of silence to attend the secret elapse and flowings in of the Holy Spirit,
that may fill their minds with peace and consolation, joys, or raptures:
to favour all his secret intimations,
and give themselves up entirely to his conduct and direction, so as neither, to speak,
move or act, but as they find his impulse on their souls:
to retrench themselves within the conveniencies and necessities of life--to
avoid as much as possible what the world calls innocent pleasures,
lest they should have their affections tainted by any sensuality,
and diverted from the love of him who is to be the only comfort, repose, and delight,
of their whole beings.
____

I shall conclude my recommendation of silent worship,
by giving one particular example more of it,
(in another country also) and of its good effects:

The lady Guion in France, a great promoter of piety and virtue,
and who was instrumental to the conversion of multitudes of the inferior sort of people,
and some others in the southern parts of France,
to a more religious and Christian-like way of living,
and who in her writings taught and recommended, above all things,
the knowledge of pure and divine love (whose doctrine
the famous archbishop of Cambray defended,
and was thereupon exiled); I say,
this lady being permitted to instruct the young women of the house or college of St. Cyr,
in the ways of piety, instead of repeating a number of prayers by rote,
as they had been taught,
put them upon silent prayer and inward recollection of mind and thought,
by which they might see their own conditions, and what they stood in need of,
in order to make them acceptable to God; and indeed,
the good effects of this practice appeared in a signal manner,
in setting them at liberty from the captivity of their darling lusts;
for whereas some of these had been working the ruin of their families by then gaming,
and the expensiveness of their apparel,
these now having their hearts directed to the love of more amiable objects,
were brought off from the inordinate love of themselves and decking their bodies,
and from affectations of new fashions and modes of dress,
and from misspending their time at cards, dice,
and other diversions too common among persons of high rank and quality.^
footnote:[Apologetic preface to Archbishop of Cambray`'s [.book-title]#Dissertation on Pure Love.#]

So much may suffice concerning the worship of Almighty God:
it seems next to be of no small importance,
to consider the exercise of Christian discipline in the church,
or rather the relaxation or loss thereof, among the men of the establishment,
as another essential defect in the reformation.

With respect to the celebration of marriage,
I have already hinted how much the rights of parents are daily violated,
and the peace and religious economy of families destroyed;
and with regard to the morals of both clergy and laity,
is there not an almost universal neglect?
What discipline, for instance is exercised in the church on fraudulent dealers,
and bankrupts, drunkards, whoremongers, swearers, and litigious persons?
Are not such often entertained in the body of the
church without either expulsion or admonition?

But what need I dwell on this matter?
The church of England in her liturgy expressly acknowledges this loss of Christian discipline,
but contents herself with wishing for its restoration;
and in the meantime pronouncing the comminations, on the day called Ash-Wednesday,
without a direct application to the offending individuals:
which how well it quadrates with the apostolical precept in 1 Cor. 5 on such occasions,
as well as Christian zeal and prudence, I offer to their consideration;
and hasten to the mention of two more instances of a deficiency in the reformation,
and those are fighting and swearing among professed Christians,
and which I am apt to think few will dispute with me,
but that they shall cease when the prophecy,
that the "`kingdoms of this world shall become the
kingdoms of the Lord and his Christ,`" Rev. 11:15,
shall become accomplished.

[.offset]
In the mean-time,

[quote]
____
It will scarcely be denied that because of oaths the land mourns;
nor that it is a shameful thing and very dishonourable to the Christian religion,
that those, who pretend themselves to be the true followers of Christ,
should so degenerate from his doctrine and example,
as to need and use scaring asseverations (not known even to ancient Jews
and heathens) to ascertain one another of their faith and truth,
that religion must have suffered a great ebb, and Christianity a fearful eclipse,
since those brighter ages of its profession;
for bishop Gauden in his treatise of oaths confesses
that the ancient Christians were so strict and exact,
that there was no need of an oath among them; and surely,
the prohibition of Christ in the 5th of Matthew,
comprehends not only those called profane oaths, but others; and when it is added,
whatsoever is more than yes, yes, and no, no, comes of evil,
this is applicable also to asseverations made before the magistrate; for distrust,
and dissimulation are the grounds of going beyond
a simple affirmation or negation in both cases.^
footnote:[[.book-title]#Treatise of Oaths# published in behalf of the people called Quakers, A. D. 1675.]
____

Noble therefore and consistent both with this and the spirit of the ancient Christians
seems to have been the following testimony of the people called Quakers:^
footnote:[[.book-title]#Treatise of Oaths# in behalf of the people called Quakers, A. D. 1675.]
"`God has taught us to speak truth as readily without an oath as with an oath,
so that for us to swear; were to take God`'s holy name in vain.`"

And that several of the ancient fathers did hold all taking of an oath unlawful,
is acknowledged by Cave in his [.book-title]#Primitive Christianity#--Polycarp
particularly refused to swear because he was a Christian:
and we are assured, as a thing well known,
that "`the ancient fathers of the first three hundred years after Christ
understood the words of Christ to be a prohibition of all sorts of oaths.`"^
footnote:[Barclay`'s [.book-title]#Apology,# Prop: 15.]
And one of the popes of the fifth or sixth century,
is said to have been the first author of the institution of swearing
by the gospel so that the present establishment of oaths,
among Christians,
should seem to deserve a place among other innovations and corruptions of popery.

Next, as to fighting; there are two express prophesies of the same event,
uttered in the some words by two different prophets,
the completion of which we are surely to expect in these gospel times:

"`Nation shall not lift up sword against nation,
neither shall they learn war any more:`" Isa. 2:4. and Micah 4:3. Which prophesies
the ancient fathers of the first three hundred years after Christ did affirm to be fulfilled
in the Christians of their times who were most averse from war.
Agreeable to this are the words of the Christians in Justin Martyr,
"`We fight not with our enemies,`" and the answer of Martin
to Julian the apostate related by Sulpicius Severus,
"`I am a soldier of Christ,
therefore I cannot fight,`" which was three hundred years after Christ.^
footnote:[Ibid.]
And as the true causes of wars and fightings according to the apostle,
(James 4:1) are the lusts of men, an obvious consequence is,
that when these shall be subdued and mortified, wars, their effect, shall cease.

It seems to be strongly hinted, even in the Old Testament,
that there is something of a defiling nature in the spilling of human blood;
for this is alleged under Divine sanction,
as a reason why David was a person unfit to build the house of the Lord;
for we read that the word of the Lord came to David, saying,
"`You shall not build a house unto my name,
because you have shed much blood upon the earth in my sight.`"`' 1 Chron. 22:8.

The same sentiment, concerning spilling of blood,
seems also to have been entertained even among the heathens;
for whereas many of the fathers held fighting unlawful to Christians,
particularly Justin Martyr, Tertullian and Origen;
the last of these in his answer to Celfus upon this subject, speaks thus,
"`Your own priests and those who belong to your temples,
keep their hands from being defiled with blood,
by reason of the sacrifices they must offer, with unbloody and unpolluted hands,
to those you esteem your gods; and when you go to war,
you never take of the priestly order for soldiers.`"

If then you heathens saw thus far,
surely we by the help of gospel-light should see farther:
for my part I do not see how the method of determining
controversies by fighting is reconcilable to reason;
for surely the righteous cause is not always a necessary
concomitant of the longest sword;
and much less do I see how the reparation of injuries received is, by this method,
reconcilable to the following sublime precepts,
recommended to the practice of all Christians:
"`See that none render evil for evil to any man, and overcome evil with good,
and love your enemies, bless them that curse you,
etc. that you may be the children of your Father, which is in heaven.`"
1 Thess. 5:15, Rom. 12:21, Matt. 5:44-45.

From all which I conclude,
that wars and fightings are an effect of the corruption of mankind,
another strong instance of the deficiency of the reformation,
and shall entirely cease among Christians,
when they shall arrive at that standard of purity and perfection
which is prescribed to them in the gospel.

I have now but one thing more to take notice of,
before I conclude this my introduction to the [.book-title]#History of the People called Quakers,#
and that is the disposition of the age at that juncture of time,
when this people made their first appearance in the world,
as being one considerable cooperating means of making
way for the reception of their doctrines.

[quote]
____
The true church (in the words of William Penn,)^
footnote:[[.book-title]#Rise and Progress of the People called Quakers.#]
having fled into the wilderness, did at length make many attempts to return,
but the waters had yet been too high and her way blocked up,
and the last age did make considerable advances to a reformation both as to doctrine,
worship, and practice.
But practice quickly failed,
for in a little time wickedness flowed in as well
among the reformers as those they reformed from,
so that by the fruits of conduct they were not to be distinguished.
And the children of the reformers, if not the reformers themselves,
betook themselves very early to earthly policy and power to uphold
and carry on their reformation that had begun by spiritual weapons,
which seems to have been one of the greatest reasons
why the reformation made no better progress,
as to the life and soul of religion.
For while the reformers were lowly and spiritually minded, and trusted in God,
and looked to him, and lived in his fear, and consulted not with flesh and blood,
nor sought deliverance in their own way,
there were daily added to the church such as one might reasonably say should be saved:
for they were not so careful to be safe from persecution,
as to be faithful and inoffensive under it,
being more concerned to spread the Truth by their faith and patience in tribulation,
than to get the worldly power out of their hands
that inflicted those sufferings upon them.

Those before mentioned, owned the spirit, inspiration and revelation indeed,
and grounded their separation and reformation upon the sense and
understanding they received from it in reading the Scriptures.
But yet there was too much of human invention,
tradition and art that remained both in praying and preaching,
and of worldly authority and worldly greatness in
their ministers.--They were more strict in preaching,
devout in praying, and zealous for keeping the Lord`'s day,
and catechizing of children and servants,
and repeating at home in their families what they had heard in public.
But even as these grew into power, they were not only for whipping some out,
but others into the temple: and they appeared rigid in their spirits,
rather than severe in their lives, and more for a party than for piety:
which brought forth another people, that were yet more retired and select.

They would not communicate at large, or in common with others;
but formed churches among themselves of such as could give some account of their conversion;
at least, of very promising experiences of the work of God`'s grace upon their hearts;
and under mutual agreements and covenants of fellowship, they kept together.
These people were somewhat of a softer temper,
and seemed to recommend religion by the charms of its love, mercy, and goodness,
rather than by the terrors of its judgments and punishment;
by which the former party would have awed people into religion.

They also allowed greater liberty to prophecy than those before them;
for they admitted any member to speak or pray, as well as their pastor,
whom they always chose, and not the civil magistrate.
If such found anything pressing upon them to either duty,
even without the distinction of clergy or laity, persons of any trade had their liberty,
be it never so low and mechanical.
But alas! even these people suffered great loss: for tasting of worldly empire,
and the favour of princes, and the gain that ensued, they degenerated but too much.
For though they had cried down national churches and ministry, and maintenance too;
some of them, when it was their own turn to be tried,
fell under the weight of worldly honour and advantage,
got into profitable parsonages too much,
and outlived and contradicted their own principles: and, which was yet worse, turned,
some of them, absolute persecutors of other men for God`'s sake,
that but so lately came themselves out of the furnace: which drove many a step farther,
and that was into the water; another baptism,
as believing they were not scripturally baptized;
and hoping to find that presence and power of God in submitting to this watery ordinance,
which they desired and lacked.

These people made also profession of neglecting, if not renouncing and censuring,
not only the necessity but use of all human learning as to the ministry;
and all other qualifications to it, besides the helps and gifts of the Spirit of God,
and those natural and common to men.
And for a time they seemed like John of old,
a burning and a shinning light to other societies.

They were very diligent, plain, and serious; strong in Scripture, and bold in profession;
bearing much reproach and contradiction.
But that which others fell by, proved their snare.
For worldly power spoiled them too;
who had enough of it to try them what they would do if they had more:
and they rested also too much upon their watery dispensation,
instead of passing on more fully to that of the fire and Holy Spirit,
which was his baptism, who came with a fan in his hand,
that he might throughly (and not in part only) purge his floor,
and take away the dross and the tin of his people, and make a man finer than gold.
They grew high, rough, and self-righteous; opposing further attainment:
too much forgetting the day of their infancy and littleness,
which gave them something of a real beauty;
insomuch that many left them and all visible churches and societies,
and wandered up and down, as sheep without a shepherd, and as doves without their mates;
seeking their beloved,
but could not find him (as their souls desired to know him)
whom their soul loved above their chiefest joy.

These people were called Seekers by some, and the Family of Love by others: because,
as they came to the knowledge of one another, they sometimes met together, not formally,
to pray or preach at appointed times or places, in their own wills,
as in times past they were accustomed to do; but waited together in silence,
and as anything rose, in any one of their minds,
that they thought savoured of a Divine spring, they sometimes spoke.
But, so it was, that some of them not keeping in humility and in the fear of God,
after the abundance of revelation, were exalted above measure;
and for lack of staying their minds,
in a humble dependance upon him that opened their understandings,
to see great things in his law, they ran out in their own imaginations,
and mixing them with those Divine openings, brought forth a monstrous birth,
to the scandal of those that feared God, and waited daily in the temple,
not made with hands, for the consolation of Israel, the Jew inward,
and circumcision in Spirit.
____

Thus it appears that the fields were now ripe unto the harvest;
and as the same author proceeds,

[quote]
____
It was about that very time, as you may see in the annals of George Fox,
that the eternal, wise, and good God was pleased,
in his infinite love to honour and visit this benighted and bewildered
nation with his glorious day-spring from on high;
yes with a most sure and certain sound of the word of light and life,
through the testimony of a chosen vessel,^
footnote:[George Fox,
whose character is thus given us by William Penn and Thomas Ellwood,
from an intimate acquaintance and conversation with him:
"`He was the first and chief elder in this age;
a man though not of elegant speech or learned after the way of this world,
yet endued with a wonderful depth in Divine knowledge;
and although his expressions might seem uncouth and unfashionable to nice ears,
his matter was nevertheless very profound;
and as abruptly and brokenly as sometimes his sentences
about Divine things would seem to fall from him,
it is well known they were as texts to many fairer declarations:
and indeed this showed that God sent him,
that no art or parts had any share in the matter or manner of his ministry,
and that so many great and excellent truths, as he came forth to preach to mankind,
had nothing of man`'s wit or wisdom to recommend them;
nor were those truths notional or speculative, but sensible and practical,
tending to conversion and regeneration,
and the setting up the kingdom of God in the hearts of men.
He was a discerner of other men`'s spirits, and very much a master of his own:
he had an extraordinary gift in opening the Scriptures; but above all,
he excelled in prayer: the inwardness and weight of his spirit,
the reverence and solemnity of his address and behaviour,
and the fewness and fullness of his words have often struck even strangers with admiration,
as they used to reach others with consolation.
He was an incessant labourer both in doctrine and in discipline,
the care of the churches being much upon him; and as he was unwearied,
so he was undaunted in his services for God and his people,
being no more to be moved to fear than to wrath.
{footnote-paragraph-split}
He suffered abundantly, not only from strangers,
but from some of the same profession,
and (which was not the least part of his honour)
he was the common butt of the envy of all apostates,
whose good notwithstanding he earnestly sought.
He held his place in the church of God with great
meekness and a most engaging humility and moderation,
being on all occasions (like his blessed Master,) a servant to all,
exercising no authority but over evil, and that everywhere and in all, but with love,
compassion, and long-suffering.
He was sound in judgment, able and ready in giving, discreet in keeping, counsel:
of an innocent life, no busy-body, nor self-seeker, not touchy nor critical;
very tender and compassionate to all under affliction; a most merciful man,
as ready to forgive as unapt to take or give offence; very civil,
beyond all forms of breeding, in his behaviour; very temperate, eating little,
and sleeping less.
Thus he lived and sojourned among us, and as he lived, so he died;
and in his last moments was so full of assurance that he triumphed over death.`"
See Penn`'s [.book-title]#Rise and Progress# etc. and Ellwood`'s
[.book-title]#Testimony of George Fox# prefixed in his journal.]
to an effectual and blessed purpose, can many thousands say,
"`Glory be to the name of the Lord forever.`"

For as it reached the conscience, and broke the heart,
and brought many to a sense and search,
so that which people had been vainly seeking without, with much pains and cost,
they by this ministry, found within, where it was they lacked what they sought for,
namely, the right way to peace with God.
For they were directed to the light of Jesus Christ within them,
as the seed and leaven of the kingdom of God; near all, because in all,
and God`'s talent to all: a faithful and true witness, and just monitor in every bosom:
the gift and grace of God to life and salvation, that appears to all,
though few regard it.
This, the traditional Christian, conceited of himself,
and strong in his own will and righteousness, and overcome with blind zeal and passion,
either despised as a low and common thing, or opposed as a novelty,
under many hard names, and opprobrious terms; denying in his ignorant and angry mind,
any fresh manifestation of God`'s power and Spirit in man, in these days,
though never more needed to make true Christians: not unlike those Jews of old,
that rejected the Son of God,
at the very same time that they blindly professed to wait for the Messiah to come;
because, alas, he appeared not among them according to their carnal mind and expectation.
____

And as it was one great and principal distinguishing business of the people
called Quakers (at a time of such high profession as that was,
when they made their first appearance in the world) to call men off from
an acquiescence in the mere history and letter of the Scripture,
without experiencing the spirit and mystery thereof; or in other terms,
to shake hypocritical professors,
in their vain confidence in the mere belief of what
Christ did without them in respect to his life,
doctrines, miracles, and sufferings (matters of faith, undoubtedly of great importance,
and necessary to be assented to, and most gratefully acknowledged,
but without a further work so far from being effectual to salvation,
that doubtless the revelation of these truths will
aggravate the condemnation of the impenitent),
and to awaken their attention to the inward appearance
of the same Christ in their own hearts;
to republish to the world faith in Christ,
not only as sitting in power and great glory at the right hand of the Majesty in heaven,
according to the testimony of holy writ,
but also as the light of the world according to the same testimony,
and that men "`should believe in the light that they
might be the children of the light,`" John 12:36,
according to the precept of Christ;
and that there is a divine efficacy in this light to make men sons of God,
according to the first chapter of John the Evangelist: now I say,
as this was the distinguishing testimony of the people called Quakers,
so there are not wholly lacking among some of the writers
of those times instances of a concurrence herewith.
It shall suffice for this purpose to transcribe, a single instance,
being a short extract from two sermons preached at
Allhallows in Lombard-street in the year 1654,
by John Webster:

[quote]
____
It is not holding forth the highest profession of Christ, in the letter,
that makes us free, except Christ come into the heart and make us free indeed.
The chief thing that every soul is to mind, in reading and hearing,
is to examine whether the same thing be wrought in them.
Whatever we find in the letter, if it be not made good in us what are the words to us?
We must see how Christ is crucified and buried in us,
and how he is risen and raised from death in us;
the chief thing I say is to look into our own breasts.
All generally that hold forth a profession of Christ,
they say in words that Christ is the deliverer, but that is not the thing;
is he a deliverer to you?
is that glorious Messiah promised and the deliverer with power, come into your soul?
has he exalted himself there?
has he made bare his arm and been a glorious conqueror in you?
has he taken to himself his great power to reign in you?
is he King of kings and Lord of lords in you?
Whatever you speak of Christ and his miracles, if you have no witness,
no evidence of the truth of them in your own heart, what is all that ever he did,
and what is all that ever he suffered to you?
It may be you may have a notion and opinion of the things of God,
and you have them by history and by relation, or education, or example, or custom,
or by tradition, or because most men have received them for truths:
but if you have no evidence of his mighty miracles and God-like power in your own soul,
how can you be a witness that they are the things that you have seen and heard?
for all those outward things are but shadows and representations,
figures and patterns of the heavenly things themselves.
You may have a strong opinion, but no experience of them, namely,
that Christ has freed and delivered your soul.--Have you really seen yourself in captivity,
deaf, dumb, blind, and lame?
Oh that men were but come to this condition, to be sensible of their misery!
Oh then what mourning, what hanging of their harps upon the willows,
and sitting by the rivers of Babylon, and crying out,
how shall we sing the Lord`'s song in a strange land?
Till they have deliverance they cannot but mourn, and who can deliver them,
but the Lion of the tribe of Judah?
To such a soul only Christ is precious:
others may talk of him and make a great profession of him,
but they cannot love him till he be Immanuel and Saviour in them.
Forms and ordinances cannot be the rest of a Christian,
because they may be used and lived in, and admired and prized,
while those that use them may be carried away with various lusts.
Thus may not one be dipped and receive water-baptism and yet be a sorcerer?
Was not Simon Magus so?
May not one be at breaking of bread with Christ, and yet be a devil?
Yes, for so was Judas.
____

[.offset]
So far Webster.
