== Chapter I.

[.chapter-subtitle--blurb]
From the first appearance of this people in Ireland,
to the settlement of church-discipline among them in the year 1669;
wherein is given an account of the first ministering Friends who visited Ireland,
and their labours in the gospel; (and particularly of William Edmundson);
of the sufferings and hardships they underwent;
the effects of their labours in the convincement of many;
and the first settlement of particular meetings, and of provincial,
monthly and national meetings.

It seemed good to a half year`'s meeting assembled in Dublin, in the Third month 1700,
that a faithful narrative should be preserved and transmitted to future generations,
of what great things the Lord had done for a people
within the compass of forty-five years then past,
and not out of the memory of some elders then living.
Accordingly such a narrative was by their advice compiled,
being collected from several authentic papers and certificates,
from which the following account was drawn by Thomas Wight, of Cork, a worthy elder,
whose character is given in due course of time in the following history.

It is true, William Sewel did, in the year 1722,
publish a general history of this people,
who (in his own words) "`began to take heed to a divine conviction in the conscience,
and preached unto others the doctrine of an inward
light with which Christ had enlightened man,
and in the latter end of the time of king Charles I. began to increase in number,
and became a separate society among men,
distinguished by the scornful appellation of Quakers,`" for an account
of whose particular doctrines the reader is referred to Barclay`'s [.book-title]#Apology.#

The present undertaking may therefore perhaps be prejudged by some as superfluous:
nevertheless, as several occurrences have happened peculiar to Ireland,
both before the year 1700 when the aforesaid Thomas Wight finished his account,
and through a series of years to the present time,
and such as seemed worthy of observation as matters of instruction and edification,
the collections of Thomas Wight have been revised and improved by some important additions,
particularly of several epistles, testimonies, or characters,
of various eminent ministers and elders,
together with a minute and faithful account of their spiritual experiences,
and of the various steps which the divine wisdom led them through,
in their pursuit of everlasting happiness, taken from their own writings,
and some other matters of fact,
tending to give unto those of the present age a true idea
of the spirit and disposition of their predecessors,
and of the present spiritual situation of the society,
with which view the history is continued down to the present time; and moreover,
as neither Sewel nor any author I am acquainted with, has, as yet,
given such a minute and circumstantial account of the Christian discipline exercised
among this people as either the subjects or its importance and usefulness seem to demand.

[.asterism]
'''

William Edmundson, born at Little Musgrove in Westmoreland, in the year 1627,
having received Truth in the love of it, and obtained mercy of the Lord to be faithful,
was made instrumental for gathering and convincing some (by declaring
what God had done for his soul) before any other ministering Friends
came out of England in the message of the gospel,
of whom as also of his own inward exercises, trials and sufferings,
he kept an account in writing,
which we shall therefore in the first place subjoin with his own words:

[.embedded-content-document]
--

It pleased the Lord in my youthful days to bring
me often to a consideration of my soul`'s happiness,
and when I was in the army in Scotland under Oliver Cromwell,
matters relating to my salvation came more close upon me; for the Lord was visiting me,
and striving with me both in judgments and mercies.
In the year 1651, I came out of Scotland into England,
and being in Derbyshire where the name of a people called Quakers was much talked of,
and one George Fox to be the ring-leader of them;
various reports went abroad concerning them, some for good, and many for evil;
but my heart was drawn towards them for good.

Now about this time I married and left the army, and was about to settle in Derbyshire:
in the interim my brother John Edmundson being then a soldier in Ireland,
came over into England to visit his relations,
and persuaded me to go and live in Ireland: my wife being willing, we prepared for it,
and taking with us one servant, some necessaries, and merchants`' goods,
we landed in Dublin, where I was strongly importuned to settle;
trading being then very brisk, and houses upon easy terms,
it being not long after the plague;
but I was prevented by a secret hand that I did not then know,
which preserved me from the deceitfulness of riches; with which,
if I had given way to this temptation, I had according to all probability,
been laden as with thick clay, and thereby been hindered from the Lord`'s service,
as some others are.

So from Dublin we went into the North, and took a house in Antrim,
and my brother lived with us, for the troop he belonged to,
quartered in and about that place:
I soon sold off my goods and went for England to buy more; and going into the North,
understanding George Fox and James Nayler (of whom
I had heard) were come into those parts,
I was glad of that opportunity, and went to a place where was James Nayler,
who spoke of the things of God`'s kingdom, and work of regeneration;
and though his words were not many, they were powerful, and reached God`'s witness in me,
that had long strove with me, and my heart being then opened,
as the Lord opened the heart of Lydia, I knew it to be the truth,
and received it in the love of it; for I had longed after it,
and was ready for the Lord`'s harvest.
Things appeared so plain, and concurred with so many Scriptures,
which were brought to my remembrance, that I thought, all that heard it declared,
must needs confess it was the very truth.
In a very few days the Lord`'s prayer mightily seized on me, and hedged up my former way,
and I was under great exercise of spirit on many accounts;
so when I had done my business in England,
I intended by God`'s permission again for Ireland, bound for Carrickfergus, or near it,
and at sea the Lord`'s hand was heavy on me,
and great wrestlings and conflicts of spirit I had;
under which exercises I landed at Carrickfergus; it was something late in the afternoon,
yet I rode twelve miles to Antrim, where my wise and aforesaid brother were.
He meeting me at the door appeared with his usual salutation,
but the Lord`'s power so seized on me that I could not join in it,
and I was broken into many tears.
We went in, and sat down,
and I was mightily exercised under the sense of the Lord`'s power,
which begat in me a true godly sorrow, but mixed with comfort in his tender mercies.
My wife and brother sat quiet, with no small admiration at the change;
(this was in the year 1653.)

Now I came to the entry of my goods which was no small exercise to get through,
because at the custom-house an oath would be required, and when they required it of me,
I told them I could not swear; for Christ had forbidden it.
This was a strange thing to them, not having met with the like before; my deportment,
and speech in using the words _Thee_ and _Thou_ to them,
and not putting off my hat was very offensive; but the Lord strengthened me,
and my mind was towards him, which enabled me to stand in the cross,
and despise the shame, and so according to my small measure,
I stood in my testimony for his truth, by which I got through that exercise,
and received my goods and came home.
By this time great discourses were about the Quakers;
and I was yet under great exercise of spirit,
the Lord`'s hand being mighty upon me in his judgments, yet, as I said before,
mixed with his mercies,
and my pain and trouble in creased as a woman`'s in travail bringing forth her first-born;
and in the night season I wished for morning, and when the morning came,
my travail and hard labour ceased not, and then I wished for night again,
that my bed might give me ease; thus was I like one tossed,
and afflicted in this spiritual warfare,
wherein I could find none that could speak a word of comfort,
that had trod in this strait path.
Many professors came to jangle and contend, and spoke evil of the way of truth,
which added trouble to my wounded heart, and broken spirit, but it wrought for good,
for it raised discourses far and near what a people there was, and of their ways,
manners, and behaviour; which settled so in the minds of sober people,
that it put them upon an inquiry into the principles and faith of them.

Now was my name much talked of abroad, and one Miles Bousfield called a major,
who had received some convincement in England by George Fox,
came soon away upon it into Ireland, and being about that part of the country I lived in,
and hearing of me, and the great exercise of conscience I was in, came to see me,
but it happened I was from home: he spoke much of religion,
and the work of the inner man to my wife, and how glad he would be of my company, etc.
When I came home, my wife informing me of him, and his discourse, I was very glad;
for I would have gone far to find an experienced friend
that could have informed or helped me in my great straits;
for I saw my own poverty, and weakness,
and the enemy as a strong man armed making war within and without:
so I rode to see major Bousfield twelve miles and abode with him all night.
He talked much of the work of God in man; spoke well of the way of truth,
and of George Fox, and James Nayler, and exhorted me to be cheerful and merry,
and not to be cast down with those troubles,
for it was the enemy`'s work to drive me into despair;
for I had the tokens of God`'s love, and he would love me to the end,
and nothing in me could hinder his work, etc.
I gave attention to his words, being low, and dejected in my spirit;
his words answered me in that which pleased self;
for something in me would have enjoyed the Lord without bearing his righteous judgments,
or living in the daily cross of Christ:
and this I found major Bousfield was a stranger to,
but made me easy over God`'s witness in my conscience, and healed my hurt too fast;
for in a few days after I left him, it broke but again, the Lord`'s hand pursuing me,
in whose light I saw and felt something yet in me that withstood the work of God,
which must be slain and crucified by the Lord`'s judgments,
and the daily cross of Christ Jesus.
Then my wound was opened, and I saw there was no physician but the Lord alone,
and I also saw where Bousfield was, and all of that spirit;
that they took up their rest and satisfaction in a talk and notion of religion,
without the true cross of Christ, that should mortify their lusts, wills,
and vile affections, and crucify them to the world, and the world unto them,
being at ease in a form of godliness without the real work of the power.

--

[.offset]
So far William Edmundson.

In the beginning of the year 1654, Miles Halhead, James Lancaster, and Miles Bateman,
plain men, came out of England with a testimony for truth,
on which account they had some service with the chief rulers and officers of the army:
they made little stay, but went into the North,
and took shipping at Belfast for England again.

At that time William Edmundson was removing his habitation from Antrim to Lurgan,
and soon after his brother came and dwelt with him,
and a meeting was kept at his house in Lurgan,
which was the first settled meeting of the people called Quakers in Ireland.
This meeting was but small at first, but as their minds were kept inward,
waiting in stillness upon God,
they felt his presence to comfort and strengthen them in time of great sorrow and weakness,
and their number increased; for the name of Friends and fame of truth did spread,
and other sober people that sought after the knowledge of God joined with them,
as William Soulden and his wife, John Hendryn, William Lynas, and several others:
and the Lord was pleased to give William Edmundson a part in the
word and testimony of his kingdom and gospel of salvation,
which he laboured in according to his measure in much weakness and fear.
He was moved to go to the public worship house be longing to Lurgan,
to declare truth in the time of their worship,
and was much beaten there by colonel Stewart;
but his testimony reached the hearts of some, particularly Mark Wright and Mark Sawyer,
who followed him out of the said worship house, and joined with Friends.

The next Friend that came out of England was John Tiffin,
who came and sat with the above-mentioned Friends in their meeting,
and did sometimes speak a few comfortable and edifying words among them:
William Edmundson and he travelled together to several places,
and had good service for truth, and discoursed and had disputes with professors,
and many began to listen to them and inquire into their faith, and principles,
and truth began to spread, though through great opposition;
for now the priests andd people began to be alarmed and in a rage,
and Friends were exposed to great sufferings upon several obvious accounts; particularly,
as the testimony of truth was against all hireling teachers,
and their forced maintenance,
these made it their business to incense the magistrates
and rulers against Friends as holding damnable doctrines,
led away with the delusions of Satan, etc. and their conscientious scrupling to swear,
in obedience to Christ`'s command,
"`Swear not at all,`" was a strange thing to the people,
as was also the use of the plain and proper speech of _Thou_ and _Thee_ to a single person,
and refusing to take off their hats,
as being a testimony of honour and respect due to Almighty God only;
and few could suffer these things,^
footnote:[These practices of theirs were not the result of humour,
or of a framed design to declare or recommend schism or novelty,
or to distinguish themselves as a party from others:
but God having given them a sight of themselves,
they saw the whole world in the same glass of truth,
and sensibly discerned the affections and passions of men,
and the rise and tendency of things.
See Penn`'s [.book-title]#Rise and Progress of the People called Quakers.#
And in a treatise of the same author entitled [.book-title]#No Cross No Crown,#
these matters are discussed at large,
and particularly the true honour excellently distinguished from the vain and worldly.]
but frequently on these accounts treated them with abusive words,
and sometimes with blows or throwing stones.
The keeping to one price in selling of goods and to the first demand without abatement,
was also a great stumbling-block to most,
and made them decline dealing with them for some time,
until they saw into the justice thereof.^
footnote:[[.book-title]#Edmundson`'s Journal,# Sect.
2.]
But to return to John Tiffin.

He and William Edmundson went to Belfast (a town of great profession) where there
was but one of all the inns and public houses that would lodge them;
here John Tiffin lodged, and often endeavoured to get an entrance for truth in that town,
but they resisted, shutting their ears, doors and hearts against the publishers thereof.^
footnote:[Ibid.
Sect.
3.]
Near this town there dwelt one Laythes,
who promised to let them have a meeting at his house,
but through some slavish fear failed of his promise and disappointed them;
yet this did not hinder them, namely, John Tiffin, William Edmundson,
etc. from holding a meeting in the open air;
for there being a little way from the said Laythes`'s house three lanes ends that met,
they sat down and kept their meeting there,
and were a wonder to the people who came about them;
and something was spoken to direct their minds to God`'s Spirit in their own hearts.
These exercises, though in much weakness and fear, spread the name and same of truth,
and occasioned many honest people to inquire after it,
and some were added to the meeting at Lurgan.^
footnote:[Ibid.]
John Tiffin having spent five or six weeks with Friends, returned for England.

Thus at the beginning, was the way strait and difficult,
but yet truth gained ground and prevailed, and the number of Friends increased,
and they had a godly care over their words and actions,
that they might give no occasion to the adversaries of truth, who were many;
but as Friends kept low in the fear of the Lord,
they were preserved and God`'s witness in the people was reached;
of which it may not be impertinent to mention one instance.
John Shaw of Broad-Oak near Lisnegarvy,
(who with his family were convinced about this time) often said that William
Edmundson`'s words and deportment were a means to convince him of the truth.

The next Friend that came out of England in the ministry was Richard Clayton,
who came to William Edmundson`'s house, by the Lord`'s direction, as he said;
so he and William Edmundson travelled together on foot in the Lord`'s
service (for then it was not easy for travellers to ride,
or get lodging at inns,
the people being prejudiced against Friends by the instigations of the priests,
throwing stones and dirt at them as they passed along.)
They went through several towns and villages to Coleraine,
and there published the truth in their streets,
and put a paper upon their worship house door;
for the inhabitants would not receive them, nor let them lodge in the town,
but banished them out of it, so they lodged at a cabin in the mountains,
and next day they went to Londonderry,
where one Evans hospitably received and entertained them.
They had two meetings there,
and he and his wife and two sons and one daughter were convinced of the truth:
the governor was at both meetings,
and he and several others acknowledged the truth declared by them,
showing themselves kind and affectionate.

From there they travelled to Strabane and Newtown-stewart, Omagh, Dungannon,
and Charlemont, and to the house of Margery Atkinson (near Killmore,
where William Edmundson had been once before), a widow and a worthy woman,
who received the Truth with gladness, and lived and died in the Lord,
and her memorial is blessed.
They had a meeting at her house upon the first day of the week,
at which meeting Richard Clayton was very serviceable,
and several tender people received the truth at that time in the love of it,
as William Williamson the elder, a faithful, godly man,
and his son William Williamson (a faithful,
serviceable man to his dying day) and their wives and families: also John Williamson,
Matthew Homer and wife, and several others; and soon after, old William Brownlow,
Francis Hobson, Lawrence Hobson and several others;
and having settled a meeting there (which in time
became large) they parted in the love of God,
and soon after Richard Clayton went for England.
Now the truth began more to spread, and its friends increased,
and they had meetings in several places.
Not long after this a meeting was settled at the Grange below Antrim,
at the house of Gabriel Clark, an honest, religious, ancient man, who received truth,
as also his wife and family.
Another meeting was also held at Toberhead at the house of Archibald Scott,
who also received truth (a religious, honest-hearted man),
and people more and more were convinced,
insomuch that the priests and professors still raged, many tender people leaving them;
and to revenge themselves they cast William Edmundson into prison in Ardmagh,
the county-jail not being repaired after the war.
He was put into a little room in the jailer`'s house,
where although he was weak in his own eyes, the Lord was his strength,
and his power comforted him, and he was made a terror to the jailer and his wife,
although he said nothing.

This year James Lancaster and John Tiffin came over from England,
in the ministry a second time.
They landed in the North, and being at meeting on the green in Lurgan,
near the market-place, many rude persons came there,
and beat the said two Friends and William Edmundson very severely,
and drove them to the town`'s end, thinking to drive them out of it,
but the more sober sort of people rose up against them and prevented it.

In the beginning of this year also came over, and landed in Dublin,
Elizabeth Fletcher and Elizabeth Smith, who having the testimony of truth to declare,
published the same both at the public worship house called St. Audeon`'s,
and at a meeting of the Baptists.
For the first they were committed by order of Richard Tigh, Lord mayor of the city,
to Newgate prison, and the Baptists rejected the testimony of truth.
After they were released from Newgate,
they had a meeting at the chamber of Richard Fowkes, a taylor, near Polegate,
which was the first meeting that can be remembered to have been kept in Dublin,
and the first settled meeting was at George Latham`'s near Polegate.
Their service was also great in the southern parts, particularly at Youghall,
where some were convinced by their ministry, namely, captain James Sicklemore,
Robert Sandham, and several others;
and the same two women were the first of the people
called Quakers that came to the city of Cork,
in the same year 1655; and with Edward Burrough and Francis Howgil,
who also arrived the same year,
were instrumental to the convincement of many in the province of Munster,
and particularly in Cork, namely, Elizabeth Erberry, Alexander Atkins, and Ann his wife,
Thomas Mitchel, and Susanna his wife, Philip Dymond, Richard Pike,
and Elizabeth his wife, Francis Rogers, William Rogers, Stephen Harris, and his wife,
George Webber, George Gamble, Henry Faggater, Thomas Ridge, and others.

Not long after this several were convinced, as Elizabeth Gardner, a faithful,
zealous woman who lived and died in the truth, Samuel Claridge, James Fade,
and William Wadman.

The aforesaid Elizabeth Fletcher visited Ireland a second time about two years after,^
footnote:[As this record of the Friends of Ireland may be relied on as authentic,
the person called Elizabeth Fletcher, who in [.book-title]#Sewel`'s History,# p. 91.
is said to have died soon after the abuse she received in the year 1654,
must either have been another of the same name,
or else it must have been a mistake that she died soon after that time.]
and Francis Howgil recommended her by the following
testimony addressed to the Friends of Ireland:

[.embedded-content-document.testimony]
--

I am glad that my dear and well-beloved sister Elizabeth Fletcher (who is a helper
and worker in the Lord`'s vineyard) is moved to come to you again,
who is sound, honest, precious, and of good report in the family of God,
who I know will be serviceable to the Lord and to you,
in this his day wherein he is spreading his name through the nations.

[.signed-section-signature]
Francis Howgil.

--

The said Elizabeth Fletcher having declared Truth in the market-place at Youghall,
after she had had a large and satisfactory meeting, James Wood, an independent teacher,
opposed women`'s preaching; but she, having spoken largely before,
and particularly among other things,
of the Lord`'s pouring forth his Spirit upon sons
and daughters according to the prophet Joel,
and recommended the people to the grace of God, was not forward to answer his cavils;
but James Sicklemore and Edward Laundy took up the argument in her behalf,
and in the conclusion truth prevailed over the opposition then raised against it.

About this time W. E. relates in his journal that he had some drawings
on his spirit to go for England and see George Fox,
whom he had not yet seen; and accordingly went over,
and met with him at Badgeley in Leicestershire, and that George Fox took notice of him,
and they went into a retired place, where G. Fox kneeled down and prayed,
and that the Lord`'s heavenly power and presence was there:
he told George of several being convinced in Ireland,
and of the openness among people in the North of that nation to hear the truth declared,
and of the lack of ministring Friends in the gospel there,
who hereupon wrote the following epistle to Friends of Ireland,
and sent it by William Edmundson:

[.embedded-content-document.epistle]
--

[.salutation]
Friends,

In that which convinced you, wait, that you may have that removed you are convinced of;
and all my dear friends, dwell in the life, and love, and power, and wisdom of God,
in unity one with another, and with God;
and the peace and wisdom of God fill all your hearts,
that nothing may rule in you but the life, which stands in the Lord God.

[.signed-section-signature]
G+++.+++ F.

--

And W. E. upon his return to Ireland read the foregoing epistle to Friends in a meeting;
whereupon he further relates that the power of the Lord seized
on them whereby they were mightily shaken and broken into tears.

The summer of the same year was memorable for the
landing of Francis Howgil and Edward Burrough,
two able eminent preachers of the gospel of peace: they had great service in Munster,
several receiving their testimony and adhering to the doctrine they preached.
It was therefore resolved that they should not be permitted to stay long in Ireland,
but by an order from the government, at the instigation of the priests,
they were taken prisoners in Cork,
and sent by a guard from garrison to garrison to Dublin in order to be banished.
They had no meeting in Dublin,
yet had some service for the Lord with those that came to see them,
being confined to the house of Mortimer, sergeant at arms,
and after some time were in a violent manner haled a ship-board,
and banished for England.

Some hints of their services are left us, which I shall here insert,
and next an account of the first convincement of Friends at Limerick.

And first of the service of the said Francis Howgil at Bandon,
where he was received by Edward Cook (a man of great parts,
a cornet of horse in Oliver Cromwell`'s own troop and receiver to the lord Cork),
who also went with him on a First-day of the week to the public worship house at Bandon,
where the said Francis having declared truth among the people,
Edward Cook invited them to come to a meeting to be held at his house that evening;
where there was a great concourse of people, to whom Francis preached the gospel,
and opened the way of life and salvation;
and many confessed to the truth of what he declared, and joined in society with Friends,
as Edward Cook and Lucretia his wife, Daniel Massey and Sarah his wife,
Robert Mallins and Mary his wife, Katharine Smith, William Smith, Matthew Pan,
William Driver, Joan Frank, Thomas Biss, etc.

Concerning the aforesaid Edward Cook the following testimony is left us:
"`he embraced the truth with his whole heart, and retained it;
was given up to serve the Lord, and lived and walked under the cross of Christ Jesus,
in great self-denial to the world and the glory and greatness of it, to his dying day,
and laid down his head in peace with God, and sweet unity with true-hearted Friends.`"

On the Seventh day of the week Edward Burrough and Francis Howgil,
and with them James Sicklemore and Edward Cook, went to Limerick,
and next morning to the public place of worship, and after some time,
attempting to speak, were run upon by the people,
and next day put forth through the gates by an order; and as they rode along,
Edward Burrough preached through the streets on horseback,
and without the gates had an opportunity of speaking to a great multitude that followed;
as also Francis Howgil, James Sicklemore, and Edward Cook spoke a few words;
the tendency of which was to direct the people to Christ Jesus,
a measure of whose light was given to everyone to profit withal.
These acceptable tidings of the gospel of peace took place with Thomas Phelps,
Richard Pearce, John Love, etc.

Several also were convinced the same year at Kinsale by the ministry
of the aforesaid Edward Burrough and Francis Howgil,
and among the rest Susannah Worth, wife of Edward Worth, afterwards bishop of Killaloe,
who, though she suffered much from her husband, lived and died in unity with Friends.

After some time, several other Friends came to Limerick, as John Perrott, Robert Mallins,
Humphrey Norton, William Shaw, Thomas Loe, and some women Friends, as Barbara Blaugdon, etc.
Now those who had received some degree of convincement, being yet but tender and weak,
went for some time to hear one Robert Wilkinson, a captain in the army, and a preacher,
a man in great esteem, much given to religious disputation,
and attended by a large auditory, who, according to the account given of him,
appears to have been a man that had received some illuminations,
but too much a stranger to that silent and humble waiting in the divine light,
which would mortify the carnal will,
that would busily but unprofitably intermeddle in spiritual matters.
Him, however, these newly convinced went to hear, until one Abraham Newbold,
by an impulse on his mind,
came from Waterford and went also to that meeting
where the said Robert Wilkinson was preaching,
and stood up, and with a strong voice uttered these words,
"`Serpent be silent;`" a few words, but powerful, which when Wilkinson heard,
he would have entered into dispute and known by what spirit the said Newbold spoke,
to which Newbold only gave answer, "`You know not.`"
Wilkinson attempted however to proceed in his preaching;
but was so discomposed that he could not, but was carried out of the meeting,
and on the next meeting day was so disordered that he was taken out of the meeting fainting,
and from that time ceased preaching any more,
and became foolish in the latter end of his days.

In process of time it came to pass that those convinced,
being more enlightened in their understandings, met together in silence,
and also became concerned to bear a testimony to
the truth against the world`'s fashions and manners;
and their words, habits and deportment made them a reproach,
and brought them into sufferings, as imprisonment, etc.
Indeed, the magistrates did publicly forbid the people to buy anything of Friends,
and particularly of Richard Pearce, apothecary in Limerick;
and this suspension continued on him several months, but he regained his business,
and followed it with reputation the rest of his days.
He was the first in Limerick that received Friends into his house,
where meetings were kept for many years, and was succeeded by his son Thomas Pearce,
both in his outward and in his inward calling.
But to return to Edward Burrough; besides several places in Munster, he visited Kilkenny,
where he laboured in the gospel, and several were convinced,
and a meeting was settled there and kept up several years:
but William Mitchel and his wife fell into some wild imaginations,
and George Danson and his wife into quarrelling, and so the meeting came to be lost,
yet one ancient woman, by name Esther Beaver, continued faithful to her dying day,
who received Friends that came to visit the said place,
and meetings were many times kept there, afterwards.

In order that my reader may form some idea of the
spirit and character of the aforesaid Edward Burrough,
I shall here insert the substance of two papers written by him,
breathing forth the spirit of evangelical liberty:

[.embedded-content-document.paper]
--

[.blurb]
=== To the Judges and Justices and All That Handle the Law

Christ Jesus is the light of the world, by which every one of you is enlightened,
which light if you love and be guided by, it will lead you out of the world`'s ways,
nature, and unrighteousness, and will give you in entrance into everlasting life;
and in this world it will teach you how to serve God in righteousness in your generation,
and to give righteous judgments and counsels among
your brethren without respect of persons.
None can rule for God but who are ruled by him,
with his light that shines in the conscience, by which you being governed,
will by it govern in the earth righteously.
You are not to judge for gifts and rewards, for if you do, you judge not for God,
but for yourselves,
and you and your judgment is to be judged and condemned with the righteous law of God,
which is free; but such who fear God and hate covetousness, and gifts and rewards,
are to bear rule, and such will handle the law righteously,
and be a terror to evil doers, and will stand for the praise of them that do well.
But if such bear rule and handle the law which know not God, nor are ruled by him,
these will abuse the law and be a terror to righteousness and good works,
and will strengthen the hands of evil doers,
and will let vice and wickedness escape unpunished.

The law was added, to slay unrighteousness, against the disobedient and lawless;
but it was not made for the righteous,
whose consciences are exercised towards God and towards
man by the pure law of God written in the heart.
If you make a law in your own (carnal) wills, and judge by such a law,
then you will make the innocent suffer, and oppress them who walk in the law of God,
and in the exercise of a pure conscience: Christ was put to death by such a law,
and the saints in all generations were persecuted
by such laws which were made in the will of man,
contrary to the will and law of God: so take heed what you do,
and know your place and the length and breadth of your law, which is committed to you,
which is to keep the outward man in good order, and the nation in peace and truth,
and from theft, and murder, and adultery, and quarreling, and drunkenness,
and wronging one another, and such like:
such who act these things walk contrary to the light,
and so bring themselves under the penalty of the law: but over the inward man your law,
which is outward, has no power to limit,
to tie to or from any way of worship in religion; but let religion defend itself,
and lay not your law upon the conscience to exercise dominion
over it (for it is Christ`'s seat in which he will rule),
lest you be found tyrants and numbered for destruction; nor limit the Spirit of the Lord,
how, when, where, and by whom it must speak;
for the holy men of God in all ages ever cried against
such rulers as did judge false judgment,
and for gifts and rewards,
and against such priests and prophets as preached for hire and divined for money,
and sought for their gain from their quarter,
and through covetousness made merchandize of souls: therefore be warned,
if such you uphold, by law, who act such things which the Scripture declares against,
the Scripture which you profess will stand a witness against you,
and the law of God will condemn you; and God will lay your honour in the dust,
and cast you out of the seat of judgment: but judge the cause of the poor and needy,
of the widow and fatherless, and join mercy with judgment,
and lay your swords upon oppression and all tyranny and wrong dealing,
that the land may be cleansed of evil-doers, and equity and righteousness may flow down,
and the nation in good order may be kept, in peace and righteousness,
and so God will establish you among his children, who are taught of him alone,
and are far from oppression.

[.signed-section-context-close]
Written at Dublin the 23rd of the Eighth month, 1655, by

[.signed-section-signature]
Edward Burrough.

--

[.offset]
He also wrote another paper entitled, [.book-title]#The Unjust Sufferings of the Just Declared,
and Their Appeal to the Just Witness of God in all Men`'s Consciences,#
which was as follows:

[.embedded-content-document.paper]
--

[.blurb]
=== To All You Colonels and Commanders and Officers, and to All the Honest-Hearted in the City of Dublin and Elsewhere, to Whom This May Come.

Hereby we the prisoners of the Lord, for the testimony of Jesus,
and for the exercise of a pure conscience, do lay down our cause before you,
and to the light of Jesus Christ in all your consciences
we appeal in this our cause of righteousness and innocency,
to be judged thereby.
We are men fearing God and working righteousness,
and are friends to the commonwealth of Israel,
and are exalters of justice and true judgment in the earth,
and are subject to all just power,
and to every just ordinance of man for conscience-sake,
and have suffered the loss of all, and have borne part of the burden with you,
that we might obtain the freedom of the righteous seed,
and the liberty of tender consciences, to serve the Lord in his own way;
and we are well known to the Lord though strangers to you,
and are freemen in the record of heaven,
though now sufferers unjustly under your present authority,
who have taken the place of exercising lordship over, our, pure consciences,
and have imprisoned us, and endeavoured to give judgment of banishing us,
only upon false accusations, and informations and slanders,
without the proof or testimony of any accusation of evil justly laid to our charge.
And to you hereby be it known, that not for evil-doing do we thus suffer,
for to this present no man has convinced us of any evil,
nor justly proved the transgression of any law, martial or civil, against us,
though we stand accused of many grievous things,
of which we are clearly innocent in the sight of him that lives forever,
and do nothing more desire herein but to be tried by the law of
equity and righteousness and judged according thereunto.
By virtue of command given unto us by the eternal
Spirit of the Lord came we into this land of Ireland,
contrary to the will of man, not to seek ourselves, nor our own glory,
nor to prejudice your nation nor government, nor to be hurtful to your commonwealth,
but with the message of the gospel of Christ Jesus
we came to turn from darkness to light,
and from the power of Satan to the power of God,
and to minister the word of reconciliation and salvation
freely (without gift or reward) unto lost souls;
and hereof God is our witness, and also we have the seals of our ministry,
which unto us herein can give testimony by the same spirit,
and this are we ready to seal with our blood.

And these six months and upwards have we laboured in travels and sufferings,
and reproaches, and have passed through your cities and towns in soberness;
and in meekness have we preached the kingdom of God,
and have held forth the word of truth and the testimony of Jesus;
and our lives have we not loved till this day,
though sometimes dangers on every side have beset us,
that we might hold forth the faith of Jesus, the author of our profession,
in the exercise of a pure conscience, both by doctrine and conduct;
and herein are we justified in the sight of God, and who is he that condemns us?
And we call heaven and earth to record,
and the light in all men`'s consciences who have heard our doctrine and seen our conduct,
to witness for us herein; and we challenge all your nation of Ireland, our very enemies,
to prove the contrary;
though otherwise we stand falsely accused and falsely
reputed to be disturbers and makers of disorders,
to the breach of public peace and such like grievous things,
upon the false information whereof a warrant was issued
out from the chief ruler and council of Ireland,
and we thereby were apprehended in the city of Cork,
and haled by guards as malefactors too, before the council in this city,
where none of all these false accusations were or could be proved against us,
nor the transgression of any known law could we be convicted of;
and though occasions were sought against us, yet none could be found,
and though snares were laid for our feet, yet were we not entrapped,
but were cleared in the sight of God, witnessed by the light in all their consciences,
and were found innocent and without reproof in the eye of the Lord;
and by our innocency were their orders of false accusations made of none effect,
and we thus far proved to be guiltless before the throne of true judgment:
yet notwithstanding, contrary to the light in their own consciences,
and contrary to the just laws of the nations (which afford freedom to
the free-born and righteous) were we committed to prison without conviction,
or any guilt charged upon us, or the least appearance of evil towards any man`'s person,
though falsely accused, yet no true testimony given against us,
whereby our boldness in the way of the Lord could be discouraged,
as having the testimony of the Spirit of God bearing us witness in the Holy Spirit,
that in all good conscience towards God and towards man we have lived to this day;
also are without reproof in the sight of God and all just men;
and though upon search and examination we were found guiltless thus far,
yet farther has the enemy, the devil, prevailed in cruelty against the innocent,
that it is endeavoured that we be banished under the account of vagabonds,
which last accusation is the most false and unrighteous; for we challenge this, Of whom,
have we begged?
Or to whom have we been burdensome?
Or whose bread have we eaten for nothing?
Or what evil have we done?
Where is the testimony of your slanders?

But innocently do we suffer these things, bearing reproaches,
and binding the cruelty done unto us as chains about our necks,
and as crowns upon our heads,
having the assurance that for well-doing we suffer
these things from the hands of the rulers,
through the lies and slanders of the teachers, who are in Cain`'s way of persecution,
till they have fulfilled their measure of wickedness,
and be laid waste as the wilderness.
And this is our cause, and hereby it comes before you,
by the light of Christ in your consciences to be judged,
if your hearts be not altogether hardened, and your mind wholly blinded;
and we lay it at your door to receive sentence from you,
and without respect of persons hold forth our guiltless cause before you,
not begging anything from you, but herein to clear our consciences,
that you may save yourselves from this preverse generation, whose root is corrupt,
and fruit bitterness; for while we have breath from the Lord,
and enjoyment of his presence, our duty is to serve the Lord,
in bearing witness against injustice, and all cruelty and oppression,
and shall appeal to receive justice from the present power that now rules;
for in the name of the Lord we challenge our privilege of freedom, as being free born,
till we be accused guilty by the just law of equity,
unto which we are subject for conscience-sake, and not to any man`'s will,
but by word and writing are bound by the law of God to bear witness against
the unjust proceedings herein of the heads and rulers of Dublin,
and shall seal our witness against them,
and against their unrighteous decrees sealed in their cruelty against the innocent,
with our blood, if thereunto we be called.

[.signed-section-signature]
Edward Burrough.

[.signed-section-context-close]
Dublin, the 26th of the Twelfth Month, 1655.

--

He also wrote a paper dated from the city of Cork, entitled, [.book-title]#A Discovery of the Idol Dumb Shepherds in Ireland,
and a Lamentation over their Starved and Strayed Flocks.#
And another from Catherlough, entitled, [.book-title]#An Invitation to All the Poor Desolate Soldiers,
to Repent, and Make Their Peace With the Lord,
and Their Duty Showed Them What the Lord Requires of Them.#
Both which may be seen in his works.

So much may suffice as specimens of the said Edward
Burrough`'s method of addressing strangers:
I shall next subjoin an epistle of his to the brethren here,
both as a specimen of the language and sentiments of Friends in those days,
and as containing matter not unworthy the attention of those of the present generation:

[.embedded-content-document.epistle]
--

[.blurb]
=== To All the Seed of God in Ireland, Whom the Lord is Gathering by His Out-Stretched Arm, and Making Vessels of His Honour, that He May Dwell with You.

The grace, mercy, and peace of God be increased among you,
that the Father may reap fruit of you, who is glorified by bringing forth much fruit:
I say unto you all, love the Lord and his truth above all things,
and let his fear be before your eyes, and his judgments in your hearts continually,
that you may never offend his Spirit in you, nor grieve his righteous soul.
Take heed unto yourselves and be watchful, lest the enemy prevail over you,
and lead you aside from the way of truth and peace,
and then trouble and wrath come upon you if you sin against him.

Therefore every particular of you know and feel a
measure of the strength of Christ in you,
that you may be warned against all the wiles of Satan,
whose power works and moves in the fleshly part which rules above the seed of God,
which part must be crucified and circumcised with the circumcision made without hands,
that you may be pure and clean, vessels of honour fitted for the master`'s use;
for none can honour the Lord but those that are purified by him,
and Christ comes to purify, and he is sitting as a refiner`'s fire,
and this is witnessed among all that wait upon him.

So you that are turned to the power of God in you,
mind it and be obedient unto it in all things, and resist the power of Satan,
which would lead from God, and wait for power that you may be the children of God,
and may fulfill his will in all things,
and unto this you are called by the preaching of
the gospel which came among you from the Lord,
that you may know things which are eternal, and might be reconciled to God thereby.

I say from the Lord, you are not called to fulfill your own wills in any things,
but the will of the Lord in all things, which if you do his will,
you will thereby be sanctified, and the old man will be put off,
and all the works of the devil will be destroyed,
and Christ the second Adam will give you power over all your enemies within and without,
as the fleshly part in you is subdued by the working of his Spirit,
which every one of you must feel and know, which leads into all truth,
and condemns all evil:
and all that are in the evil are not led by the Spirit
of God though they profess the Scriptures,
and such are not the children of God, nor heirs of his inheritance,
which every one of you must wait for,
and to be born of the incorruptible seed by the word of God, which lives forever,
which word you must feel in you, and its operation, which is as a fire,
and like a hammer: so the saints said it was, and so we witness it to be;
and everyone that handles, tastes and feels of this word,
thereby is the enmity slain in its ground and fruits, and the body of death is put off,
and the new man is put on, who is the express image of God,
which every one of you must know and witness,
for it is the Father`'s mark upon the forehead,
for you that bear it not cannot be justified nor saved in the day of the Lord.

Every one of you having a measure of light from Christ the Saviour,
unto this you are to take heed only,
and it leads to Christ to receive him and be joined to him:
so everyone take heed to your own measures of the grace of God,
and a sufficient teacher you will witness, and the new covenant you will know,
where sin and iniquity is not remembered, but forgiven and blotted out;
and here is the true rejoicing where power is received over all sin,
and death is destroyed, and victory is known, and the sonship is witnessed,
and into this must everyone grow, into perfection and completeness in Jesus Christ.

So all Friends, I do warn you all, patiently to wait upon the Lord,
that you may witness the fulfilling of the promises,
and may know these things in the spirit, and may have them as a treasure in your hearts;
for the knowledge of God is a treasure, and to know him is life eternal;
and it is the upright in heart whom he teaches knowledge,
and it is into the pure heart that his knowledge is put.

So mind that which will purify your hearts, that the Lord may dwell in you and with you,
and let love and unity abound one towards another, and serve one another in love;
and all serve the Lord Jesus, and dwell in the cross to the world and all its ways;
for the cross of Christ is the power of God which slays the enmity,
and brings forth the seed of God,
and everyone keep to your own measures which God has given you,
and that will guide you in all the ways of peace.

Judge not above your measures, for then the Lord does not guide you; neither be hasty,
rash, or forward, for then you go out of God`'s counsel,
and lay yourselves open to temptations to be overcome of the devil,
you going from the light you lose your armour,
and that which should defend you from the devil,
and your latter end is worse than your beginning, if again you be overcome of him:
therefore all Friends, be circumspect and watchful,
lest at any time you be tempted and overcome, and so lose your peace,
and then trouble and sorrow take hold upon you,
whensoever you have lost the countenance of the Lord.

Keep your meetings in the fear of the Lord, and you will see the Lord among you,
and his presence refreshing your hearts; and as you are moved with the power of the Lord,
be obedient in everything, and watch over one another with a single eye,
and inform and instruct in the fear of the Lord,
and be examples one to another in righteousness,
and give no occasion unto the world by an impure conduct,
but walk in wisdom and in the fear of the Lord towards all men,
that the witness of God in everyone may answer for you and justify our God.

The Lord has a seed in Ireland gathering and to be gathered,
and your heavenly conduct will preach to others,
and so everyone will be a minister of Christ in his place,
as you walk in the light which Christ has enlightened you with,
who enlightens every man that comes into the world, that all men may believe;
and he that hates the light remains in unbelief and under condemnation;
but he that loves the light, his deeds are wrought in God,
and they shall not be condemned.

My love in the Lord is towards you all that hunger after righteousness,
and my prayers are for you all, that perfect rest you may obtain, and salvation.

I am now a prisoner for Christ`'s sake, and for his truth`'s sake,
through the cruelty of men who hate the Lord and his servants,
but am perfectly well in the Lord,
knowing that this shall be for the furtherance of the gospel of Christ.
The presence of the Lord be among you all,
and his eternal power give you victory over all your enemies.
Amen.

[.signed-section-signature]
Edward Burrough.

[.signed-section-context-close]
From the common jail in Kingston upon Thames, in the county of Surry,
the 25th day of the Sixth month, 1657.

--

Concerning the said Edward Burrough and Francis Howgil,
this testimony is given in the account of the early sufferings of Friends in Ireland:

[.embedded-content-document.testimony]
--

They were made a blessing to us, the Lord working mightily by them,
to the turning of many from darkness to light, and from Satan`'s power unto God;
and their doctrine and conduct was such as truly reached
unto and answered the witness of God in our consciences;
and we may praise the Lord on their behalf, who were unto us the messengers of salvation.

--

The same day,
or a few days after that Edward Burrough and Francis Howgil were banished for England,
landed Barbara Blaugdon from the west of England, who went to Henry Cromwell,
then lorddeputy, and bad him beware he was not found fighting against God,
in opposing the truth and persecuting the innocent;
but like wise Gamaliel to let them alone, for if the work was of God, it would stand,
but if of man, it would fall.^
footnote:[See [.book-title]#Sewel`'s History of the Quakers.#]
The deputy heard her moderately,
so that she perceived the enmity did not lie so much in himself,
as that he was stirred up to persecution by evil magistrates and priests.
Having performed her service in Dublin, she went to Cork,
where she had some acquaintance and relations; but her sufferings were great,
for she was imprisoned almost wherever she came,
being moved to follow those of her acquaintance into several steeple houses;
yet wherever her mouth was opened, there were some that received her testimony.
Not long after, she was moved to come a second time to Ireland,
and in Dublin she went into the court of justice and spoke to the judges,
exhorting them to righteousness; which was taken so ill that she was imprisoned for it,
but was released by the intercession of sir William King, colonel Fare,
and the lady Browne.^
footnote:[Ibid.]

This year (1656) several others in the ministry came over,
and had good service in turning many to the Lord,
particularly John Bowran of Cotherstone in Yorkshire, who landed in Dublin,
and afterwards travelled into the North.
He visited Ireland six times in six years.
See [.book-title]#Piety Promoted,# Part 3.

About the same time William Edmundson, was moved in spirit to leave off shop-keeping,
and take a farm, in order that he might, by his own example,
minister strength and encouragement in the testimony which this people
deemed themselves conscientiously concerned to hold forth and maintain,
against that antichristian yoke of oppression,
the enforcing the payment of tithes in these gospel-times.
With this view he and several Friends leaving the
meeting to which they belonged well settled,
namely, Richard Jackson, Anthony Jackson, John Thompson, Richard Fayle, John Edmundson,
William Moon, and their families, removed and took land in the county of Cavan,
and dwelt there, and settled a meeting in that county,
and held meetings in various places to the advancement of truth and increase of Friends,
several being convinced and joining with Friends: particularly John Pim, Robert Wardel,
William Neale, William Parker, Thomas Lun, Thomas Morris, John Chandley, John Savage,
Isabel Acton, and many more.

But as their numbers increased, so did their sufferings also increase,
and they were greatly exposed to the scorn, derision, and soul abuses of the people,
in bearing their innocent testimonies, in their lives and conducts, against the pride,
pleasures, pastimes, vain fashions and customs,
with the excesses and evils that were in the world, both among professors and profane,
even the very priests themselves,
who incensed the magistrates and other people against Friends, as being heretics,
deceivers, and what not?

Of these sufferings W. E. in particular met with a large share,
besides the many hard and dangerous travels and exercises he went through,
when he was alone in the times when tories and robbers, after the war, were abroad,
being sometimes put under the necessity of passing deep
waters in the winter-season where bridges were not built;
and once particularly he was put into prison in Strabane, in his wet clothes,
after travelling and swimming, by which he grew sick,
and received no help from any but the Lord, who healed him:
yet through all these difficulties truth prevailed, and several were convinced,
particularly at Strabane,
where a meeting was settled and continued until the restoration of king Charles II;
but then great sufferings being expected, Robert Burgess and another,
who were looked upon as the leading men of that meeting, proved unfaithful:
the latter through fear of persecution fled,
and Burgess accepted of the office of a parish-clerk
to the episcopal priest that then came in;
but in a little time he was smitten with great affliction both in body and mind,
which he believed to be for his backsliding from the truth,
as he confessed to W. E. who went to see him in his illness, and soon after he died;
and so through the unfaithfulness of those men the meeting fell.

The state of Friends in general, about this time,
and some particular memorable transactions at Belturbet,
are so minutely described in the journal of W. E.
that I shall here insert them in his own words:

[.embedded-content-document]
--

Now truth was much spread, and meetings settled in several places,
many being convinced and brought to the knowledge of God, were added to Friends;
but sufferings increased for not paying tithes, priests`' maintenance,
and towards repairing their worship houses,
for not observing their holy days (so called) and such like;
they fleeced us in taking our goods, and imprisoned some of us.

In those days the world and the things of it were not near our hearts,
but the love of God, his truth and testimony lived in our hearts;
we were glad of one another`'s company, though sometimes our outward fare was very mean,
and our lodging on straw.
We did not mind high things, but were glad of one another`'s welfare in the Lord,
and his love dwelt in us.

Now I was often abroad in truth`'s service, visiting of Friends,
and getting meetings in several places.
I was moved to travel into Leinster province,
and went from place to place as the Lord`'s good Spirit guided me.
I came to Rossenallis, and there met with two families come out of England,
convinced of the truth; from there I went to Nicholas Starkey`'s near Athlone,
and had a meeting there on a First-day, to which several sober people came,
and the Lord`'s power and presence was with us.

From there I went to Mullingar, and lodged there one night,
where was a trooper that was convinced, who rode with me several miles the next day,
and continued coming to meetings.
I came that night to Finagh, but the innkeepers in the town refused me lodging,
for that (they knew) I was a Quaker: it was in winter-time, and cold weather;
so I inquired for the constable, and they showed me his house.
I told him he must provide me lodging, for I was a traveller,
had money to pay for what I should have, and had been at the inns,
where they refused me lodging.
He kept an ale-house, and had also refused me, but after much discourse with him,
he told me I must be content with such lodging as he had for me.
I told him, to let me have a room with a fire to sit by, and hay for my horse,
and I would be content: so I alighted, went into the house,
and there were troopers drinking.
They soon perceived what I was, and began to scoff and to ask me many questions,
which I answered in my freedom; but when I thee`'d and thou`'d them in our discourse,
they were very angry, and one of them swore,
if I thou`'d him again he would cleave my head;
but in our discourse when it came in its place I thou`'d him again,
and he starting up in anger, drew his sword;
but one of his corporals sitting by him stopped him,
and commanded him to put up his sword, for there should be no cleaving of heads there;
so caused the troopers to go to their quarters,
but he stayed with me discoursing late in the night, and was convinced, being tender,
received the truth, and came to meetings.

About this time we had a meeting at Belturbet,
and the Lord`'s power and presence was with us,
but the provost of the town was an envious man; who came with some rude people,
broke up our meeting, and took us to prison, both men and women;
we were all night in a very cold place, the women were mightily pinched with cold,
it being frost and snow; the next morning he set all the other Friends at liberty,
but me he put in the stocks in the marketplace, and people gathered about me,
where I had an opportunity to preach the truth to them, which they heard with soberness,
were tender and reflected much upon the provost for abusing us.

Robert Wardell then (being but a boy) told the provost,
he had set a better man than himself in the stocks,
and there was a time when such as he dared not have meddled with me;
therefore the provost took him and set him in the stocks by me;
but his father soon heard of it, and threatened the provost with the law;
for he was then master of the store,
(there being a garrison of soldiers there) so Robert
Wardell was soon taken out of the stocks;
who being convinced, kept with Friends,
and afterwards became a serviceable man for truth, and a preacher of it.

The people were much dissatisfied with the provost;
so he sent his officer to let me loose, who opened the stocks,
and bid me take out my leg, for I might go my way; I told him, I had been grossly abused,
and made a public spectacle to the people, as though I had done some great offence,
but was not convicted of the breach of any law;
so let the provost come himself and take me out, for he put me in.
The provost came and opened the stocks, bidding me take out my leg.
I told him, no, for he had made me a spectacle to the people,
and I knew no law that I had broken, but let him take out my leg that put it in;
so he opened the stocks with one hand, and took my leg out with the other:
his name was Richard West.

At this time, Oliver Cromwell had put forth a declaration,
that such should be protected in their religion, as owned God the Creator of all things,
and Christ Jesus the Saviour of man, and the Scriptures,
and several other things mentioned therein: so the governor of that garrison,
with the officers and chief men in the town,
and abundance of people with them (that filled the
courthouse) would try us by the declaration,
whether we and our religion were under Oliver`'s protection, or not:
the provost was there, and I was sent for in; the clerk of the garrison,
who was then a Baptist (but afterwards a friend) read the declaration,
and I was called to answer to the particulars; I answered them so,
that the governor and they with him gave their judgment, that we were under protection,
and our religion was to be protected.

Then I called aloud, that they would bear witness,
how long we had been imprisoned illegally,
and that I sat in the market-place in the stocks wrongfully,
and that the law provided reparation in such cases;
several of the chief of them offered to be evidence,
if we would take the advantage of the law against the provost;
he was quite dashed and looked very pale.
The governor came from his seat, and took me by the hand,
saying he was sorry that I and my friends were so abused,
and did assure me that he had no hand in it.
I asked him, who he was?
He said, he was the governor of that garrison.
I asked him, where he had been those two days,
that he did not appear with his band of soldiers to appease the uproar;
for I had read in the Scriptures, that at Jerusalem,
when there was an uproar on the like account, the governor came with a band of soldiers,
and rescued Paul from them, and appeased the uproar; and was it not a shame for him,
that a heathen should out-do him that professed to be a Christian?
He was a Baptist, and so were several that were in authority thereabouts.
My spirit was borne up in the power of the Lord, as upon the wings of an eagle that day:
truth`'s testimony was over all their heads,
and my heart was filled with joy and praises to the Lord; many were convinced that day,
and several of them received the truth, and abode in it.

There was one William Parker, a preacher among the Baptists,
he had opposed me strongly at a court a little before this;
his wife was a Friend convinced in England; she was a prisoner with us;
they lived then in the country, and his wife not coming home,
in the morning he came to look for her,
and finding me sitting in the stocks in the cold winter, in the open market-place,
he was smitten to the heart; after I had done with them all, I was at liberty,
and came to Friends with my heart full of joy.
The said Parker was with Friends, so I asked him, what he thought of his brethren,
to allow us to be thus used; and they chief in command in that place?
He answered with tears in his eyes, he was ashamed of them,
that had been so long professing and fighting for conscience,
now to allow conscience to be trodden in the dirt; he went to them no more,
but came to our meetings, taking up the cross of Christ, and became an honest,
zealous man of truth, having a public testimony in meetings,
and died in the true faith which Jesus is the author of.

There was also one William Morris, an elder among the Baptists, in great repute,
captain of a company, justice of the peace, commissioner of the revenues,
chief treasurer in that quarter, also chief governor of three garrisons;
to whom the news of this day`'s work was soon carried,
whereat he was in much troubled in mind, and told the messenger,
who was a justice of peace, it was a shame for them to allow us to be so abused, saying,
the time would come, that they would be glad to shelter under our wings.
The rumour soon went among the Baptists, and to the court at Dublin, that capt.
Morris was turned Quaker, whereupon he was removed with his company Southward;
not long after he was sent for to Dublin,
to appear before the general and chief officers, many of whom were Baptists;
he was examined about his being turned Quaker, which he did not deny,
but confessed our faith and principles, and at that time was discharged from his command,
because he was a Quaker; he was a worthy, wise man, had a testimony in our meetings,
and died in the faith of Jesus.

--

Thomas Loe, who was a lively minister of Christ Jesus, and could divide the word aright,
came over this year (1657) from Oxford in England, and had good service in Munster,
and from there travelled to Dublin on foot,
where he declared the day of the Lord through the streets thereof;
preaching the word of life and salvation from James`'s
gate until he came to Lazer`'s hill:
he lodged at Stephen Rich`'s, where he sometimes had meetings; also at captain Allen`'s,
but the settled meeting was at George Latham`'s by Polegate: he had blessed service,
and many were convinced by him.
Dublin was also visited this year, by W. E., Edward Cook, and others,
who had good service, being instrumental to the convincement of several.

Richard Roper and William Waller also came over about this time,
in the service cf the truth: they were sincere and serviceable men,
and they and Thomas Loe visited some Friends who
had received truth in the county of Carlow,
and several were convinced by their testimony, as Thomas Weston and his wife, Henry Rose,
and others.

The before-mentioned Thomas Loe also visited Friends in Ulster, and had good service,
many being convinced by him there, as also in most other parts of the nation.

This year (1658) Friends in the ministry, with great zeal and fervency,
travelled up and down, and settled meetings where they could in new places;
and particularly W. E. travelling towards the Moate,
a meeting was held at the house of Nicholas Starkey at Ballykilroe,
being the first meeting that Friends had obtained in those parts.

This year (1659) landed at Donaghadee in Ulster, John Burnyeat, an eminent,
faithful servant of the Lord.
He travelled on foot through various parts of that province,
and by his means many were convinced,
and converted to God from the evil and vanity of their ways.
From there he travelled to Dublin, and had good service for truth there,
from which place he proceeded to Mountmellick, to Kilkenny, and so to Munster,
from there to Ross, Wexford, Carlow, and back again to Mountmellick,
and had meetings in other places as he travelled, preaching the true faith of Jesus,
and returned to the North; and at Lurgan he met with Robert Lodge,
who was newly come from England, who was also an able minister of Christ,
and they joined in travels as true fellow-labourers in the gospel of the Son of God,
spreading truth and convincing many.
They went to Londonderry, but when the people discovered what they were,
they were unwilling to receive them, or let them have lodging for their money.
They went to the steeple-house there on the First-day of the week,
and had a good opportunity to declare the truth among the people;
but at length the mayor sent his officers and forced them out of the city,
from which place they proceeded to several other places in the province of Ulster,
and to Dublin, Mountmellick, Athlone, Gahvay, Limerick, Cork and Bandon,
and returned to the North again:
and thus they spent their time with diligence and hard travel, often in cold, hunger,
and hardship, many parts of the country being then uninhabited.
They were imprisoned several times, as in Armagh, Dublin, and Cork,
besides other abuses that they received,
because of the testimony they had to bear in towns and steeple-houses,
against hireling priests:
and thus having laboured in the gospel together for the space of twelve months,
and being instrumental to the convincing and gathering of many to the truth,
being clear of their service here, in the Seventh month, 1660,
they took shipping at Carricksergus for England.

Among others that believed and were added to Friends about the years 1658 and 1659,
and continued faithful and serviceable in their day,
by the lively ministry of the above mentioned Thomas Loe, W. E. John Burnyeat,
Robert Lodge and others, were Francis Robson, Roger Webb, Peter Ross, Robert Hoope,
and George Gregson, who after some time was endued with a clear, lively,
convincing gift of the ministry.

This year (1659) several of the Friends above-mentioned,^
footnote:[See page 99.]
by reason of their landlords not performing covenant with them,
removed from the county of Cavan, and settled in and about Mountmellick,
in the Queen`'s county, namely, W. E., Richard Jackson, John Edmundson, John Thompson,
William Moon, John Pim, and others, with their families;
and several having been convinced thereabouts some time before,
a meeting was settled at Mountmellick, which is since become large.
As to the places they removed from, they left the meetings there in a settled condition,
and so they continued, particularly the meeting at Cavan,
until it was lost by means of the wars, Friends that lived there being dispersed thereby,
and driven from their habitations.

This year a meeting was settled at or near Moate, at the house of Thomas English.
Some time after John Clibborne, James Wisely, Henry Fuller, formerly a captain,
Abraham Fuller, Samuel Strangman, Thomas Beale, William Slade of Athlone,
and many others being convinced,
the meeting was removed to the house of John Clibborne at Moate.
About the same time W. E. and other Friends visited Drogheda, where some were convinced,
and a meeting settled:
much labour of ministering Friends has been since bestowed upon that place,
but through the unfaithfulness of several who lived there,
the meeting has decayed rather than increased,
yet a small meeting remains there unto this day.

Robert Turner having, about the year 1657,
been instrumental to the convincement of a few who lived at Grange,
near Charlemont in the province of Ulster, this year (1660),
their numbers being considerably increased through the labours of other travelling Friends,
a meeting was settled there.

About this time also a meeting was settled at Ballykilroe in the Queen`'s county,
Christopher and John Raper being convinced.

The state of Friends this year (1661) is described in the following words,
by W. E. in his journal, p. 39, 40.

[.embedded-content-document]
--

Now was king Charles coming in, and these nations were in heaps of confusion,
and ran upon us as if they would have destroyed us at once, or swallowed us up;
breaking up our meetings, taking us up in high-ways, and haling us to prison;
so that it was a general imprisonment of Friends in this nation.
I was prisoner at Maryborough, with many more Friends,
yet the Lord supported and bore up our spirits above sufferings and mens`' cruelties;
so that Friends were fresh and lively in the Lord`'s
goodness and covenant of light and life,
contented in the will of God; for we had many heavenly, blessed meetings in prison,
and the Lord`'s presence with us, to our great comfort and consolation in him,
who wrought liberty for us in his own time.

--

This year (1664) John Burnyeat aforementioned,
came over a second time and visited Friends in many parts of the nation,
and had good service, several being convinced by his means,
and about the Seventh month he took shipping at Galway for Barbados.
The number of Friends increased greatly,
and many visits this nation had in those days by faithful labourers in the gospel,
both of its own inhabitants and strangers,
notwithstanding that through the covetousness of the priests,
great spoil was made of Friends`' goods,
a great deal being forcibly taken away for tithe and other demands,
which Friends for conscience-sake could not pay;
thus some of them were cast into prison upon writs
of excommunication and definitive sentences;
yet still the Lord wrought favour in the hearts of rulers,
and sheriffs were often very favourable to Friends,
granting them their liberty when it was in their power.

The state of Friends at this time (1665), about Mountmellick,
is thus described in William Edmundson`'s journal:

[.embedded-content-document]
--

I having my liberty, found a concern on my mind,
to solicit the government against the priests`' fierceness and cruelty:
for George Clapham, priest of Mountmellick,
endeavoured to prevent the miller`'s grinding our corn for our families,
or any to speak or trade with us or any of our families;
he watched the market and Friends`' shops; and those he saw or knew to deal with Friends,
he sent the apparitor to summon them to the bishop`'s court;
so forced them to pay him and the apparitor money, to get freed from that trouble,
they being afraid of the bishop`'s court, it bore such a great name.

This priest told his hearers, that if they met any of us in the high-way,
they should shun us as they would shun the plague; and if they owed us anything,
they need not pay it; or if they knocked us on the head, the law would bear them out.
At which the people were mightily troubled,
and in general their love declined from the priest, and drew towards Friends;
they would offer their servants to carry our corn to the mill,
that we might get bread for our families, or any other kindness they could do for us.

I drew up a great deal of his gross proceedings,
and got many hands to them of his own people, who had been abused;
so went to Dublin and petitioned the government, who with the primate took notice of it,
and the privy-council resented it, being contrary to all law and rule;
so sent an order for the priest and apparitor to appear before the council; they came,
and were sharply reproved,
and had been punished (for the primate said he would make them examples),
but that I told him, we desired nothing but to be quiet,
and live peaceably in our callings, and that they would desist from their cruelty.
The primate, Boyle, who was also chancellor, said, if they do not desist,
do but write to him, and he would make them examples to the nation; so I forgave them,
and let all fall.
This gained much on the minds of many chief men in authority.

Now this priest was very angry against me,
although I had forgiven him as aforesaid (being very greedy and covetous).
One time he took a neighbour`'s horse and cart, came to my house,
and loaded and carried away a great deal of cheese;
also at that time took away much goods, corn, and wearing-clothes,
from Friends of our meeting, for some church-dues as he said;
and I being at a meeting in Mountmellick, as I used to be when at home,
he being a justice of the peace, sent a constable to apprehend me,
and made a court order to send me to Maryborough jail;
but the earl of Mountrath superseded his warrant,
and set me at liberty till the court session.

When the court session came, he stood by me against the said priest,
who had drawn up two indictments against me; and when they came into court, four lawyers,
one after another pleaded for me, though I knew nothing of them, or gave them any fee;
but the Lord gave us place in the hearts of people, and their souls yearned towards us.
The indictment was quashed, and the priest hissed at by the court to his shame;
the judge also turned against him;
several Friends came a great way to see and hear the trial,
and greatly rejoiced in the Lord to see the priest frustrated in his evil designs.

Another time this priest Clapham indicted several Friends
of our meeting at the court session at Maryborough,
and me, for being at a meeting such a day, which he called an unlawful assembly,
and for not being at church (as he called it) the same day;
he also indicted me for not paying a levy, or sess,
towards the repairs of his worship house;
though the wardens and constable had before taken from me for the same,
a mare worth three pounds ten shillings.
Several Friends were thus proceeded against, and we were fined,
and order given to distrain our goods:
so I rode to Dublin and petitioned the lord lieutenant and council.
I and one other friend were admitted into the council chamber, to state our grievance,
and had a very fair hearing,
that judge being present who gave judgment against us at the court session;
the council gave their judgment that their proceedings were illegal;
and the lord lieutenant would know, why we did not pay tithes to the ministers?
So I showed him out of the Scriptures, the law was ended that give tithes,
and the priesthood changed that received them, by the coming and suffering of Christ,
who had settled a ministry on better terms, and ordered them a maintenance;
he would know, what maintenance the ministers must have?
I told him, Christ`'s allowance; and I showed him from the Scriptures what it was,
as the Lord opened them to me, by his Spirit and Power that was with me,
which gave me wisdom and utterance, and set home what I said to their understandings.
There were three bishops present, and not one of them replied in all this discourse,
though so nearly concerned in it.
In the conclusion, the lord lieutenant bid God bless us; adding,
we should not suffer for not going to their public-worship,
neither for going to our meetings.
Now this quieted the priest, and it soon went abroad,
that the Quakers had the liberty of their religion, which was a great ease to Friends,
for we had been often imprisoned, and had much goods taken from us on that account.

--

In the year 1666 a certain person,
who afterwards became very conspicuous for his good
services both to the church and to mankind in general,
namely, William Penn, was convinced; his father, sir William Penn,
then vice-admiral of England,
having committed to his care and management a considerable estate in this kingdom,
which occasioned his coming here;
and being informed that Thomas Loe was to be at a meeting in Cork, he went to hear him;
who began his declaration with these words; "`There is a faith that overcomes the world,
and there is a faith that is overcome by the world;`" upon
which subject he enlarged with great clearness and energy;
and by the living and powerful testimony of this man (which had made some
impression upon his spirit ten years before) he was now thoroughly convinced,
and afterwards constantly attended the meetings of the people called Quakers,
even through the heat of persecution.

On the 3rd of the Ninth month, 1667, being again at a meeting at Cork, he,
with many others, was apprehended and carried before the mayor,
who observing that his dress discovered not the Quaker, would have set him at liberty,
upon bond for his good behaviour; which he refusing, was, with about eighteen others,
committed to prison.
He had, during his abode in Ireland,
contracted an intimate acquaintance with many of the nobility and gentry, and,
being now a prisoner, wrote the following letter:

[.embedded-content-document.letter]
--

[.blurb]
=== To the Earl of Orrery, Lord President of Munster

The occasion may seem as strange as my cause is just;
but your lordship will no less express your charity in the one,
than your justice in the other.

Religion, which is at once my crime, and my innocence,
makes me a prisoner to a mayor`'s malice, but my own freeman;
for being in the assembly of the people called Quakers,
there came several constables backed with soldiers,
rudely and arbitrarily requiring every man`'s appearance before the mayor,
and among others violently haled me with them.
Upon my coming before him,
he charged me for being present at a tumultuous and riotous assembly,
and unless I would give bond for my good behaviour,
who challenge the world to accuse me justly with the contrary, he would commit me.
I asked for his authority; for I humbly conceive without an act of parliament,
or an act of state, it might be justly termed too much officiousness.
His answer was, a proclamation in the year 1660,
and new instructions to revive that dead and antiquated order.
I leave your lordship to be judge if that proclamation relates to this concernment:
that only was designed to suppress fifth-monarchy killing
spirits and since the king`'s lord lieutenant and yourself,
being fully persuaded the intention of these called Quakers by their meetings,
was really the service of God,
have therefore manifested a repeal by a long continuance of freedom,
I hope your lordship will not now begin an unusual severity, by indulging so much malice;
in one whose actions favour ill with his nearest neighbours,
but that there may be a speedy releasement to all for attending their honest callings,
with the enjoyment of their families, and not to be longer separated from both.

And though to dissent from a national system, imposed by authority, renders men heretics,
yet I dare believe your lordship is better read in reason and theology,
than to subscribe a maxim so vulgar and untrue;
for imagining most visible constitutions of religious government,
suited to the nature and genius of a civil empire, it cannot be esteemed hereby,
but to scare a multitude from such enquiries as may
create divisions fatal to a civil policy,
and therefore at worst deserves only the name of disturbers.

But I presume, my lord, the acquaintance you have had with other countries,
must needs have furnished you with this infallible observation,
that diversities of faith and worship contribute not to the disturbance of any place,
where moral uniformity is barely requisite to preserve the peace.
It is not long since you were a good solicitor for the liberty I now crave,
and concluded no way so effectual to improve or advantage this country,
as to dispense with freedom in things relating to conscience;
and I suppose were it riotous or tumultuary, as by some vainly imagined,
your lordship`'s inclination, as well as duty, would entertain a very remote opinion.
My humble supplication therefore to you is,
that so malicious and injurious a practice to innocent Englishmen,
may not receive any countenance or encouragement from your lordship;
for as it is contrary to the practice elsewhere,
and a bad argument to invite English here, so, with submission,
will it not resemble that clemency and English spirit,
that has hitherto made you honourable.

If in this case I may have used too great a liberty, it is my subject,
nor shall I doubt your pardon, since by your authority I expect a favour,
which never will be used unworthy an honest man, and

[.signed-section-closing]
Your Lordship`'s faithful, etc.

[.signed-section-signature]
W+++.+++ Penn.

--

His request in the letter, so far as related to himself, was quickly granted,
for the earl forthwith ordered his discharge.

His late imprisonment was so far from terrifying,
that it strengthened him in his resolution of a closer union with that people,
whose religious innocence was the only crime they suffered for.
And now his more open joining with the Quakers,
brought himself under that reproachful name.^
footnote:[See [.book-title]#Penn`'s Works, Vol.
1.#]

From the year 1665 to 1668,
it does not appear that Friends were under any great sufferings, except by the priests,
on account of tithes, etc. but the number of Friends increased,
and they gained credit by their faithfulness, and several new meetings were settled,
whereof an account is given in due place hereafter.
And now the number of Friends being become great,
the necessity of church-government and discipline did more and more appear;
and the weight thereof did rest upon some,
and chiefly upon W. E. whom the Lord has been pleased to honour,
as the chief instrument in this land,
for the spreading of truth and preserving Friends faithful therein;
so that provincial meetings were set up to be held once in six weeks,
and these were prior to the monthly meetings (even as the quarterly
meetings in England were also prior to the monthly meetings there);
and those affairs which have since fallen under the cognizance of monthly meetings,
were transacted at the provincial meetings,
because in those times of infancy and sufferings the mutual help
and advice of brethren assembled from different parts was necessary,
when particular meetings were frequently but small and weak.
The chief business of these meetings was to take care of the poor, fatherless,
and widows;
that marriages should be decently and orderly accomplished
according to the example of Holy Scripture,
that justice and equity upon all occasions might
be practised by such as frequented our assemblies;
and whereas some of these did not walk consistently with their profession,
it was necessary that the judgment of truth might be exercised on such,
in order that the Christian reputation of the society might be maintained and preserved.

Thus was good order and discipline introduced in this kingdom,
which was farther confirmed,
and monthly meetings and national half-year`'s meetings
were established here upon the arrival of George Fox,
in the following year.

In the mean-time, in the year: 1668, died that eminent minister of Christ, Thomas Loe,
concerning whom the Friends of Ireland have left the following testimony:

[.embedded-content-document.testimony]
--

He was a man of an excellent gift, sound, clear, and powerful in his ministry,
elegant in speech, sharp and quick in his understanding,
and his testimony was very convincing, to the stopping the mouths of gainsayers.
Much people flocked after him;
many Friends up and down this nation received their convincement by him,
and many were by him confirmed in the Truth.
He was often in meetings engaged by priests and opposers of truth,
in which exercise he was as a sharp threshing instrument
in the hand of the Lord to confound them.
In conversation he was sweet and pleasant,
and sympathizing with friend under afflictions, in which state, yes,
and in all states he had a word in season to administer.
He travelled this land very much, visiting it several times from England,
and was several times a prisoner for his testimony to the truth.
He was freely given up to spend and be spent in the service of the gospel,
and in his last visit to Ireland, his natural strength was much impaired;
after which when his service was finished, he returned to England,
and laid down the body at London in great peace,
singing praises to the Lord on his deathbed.

--

A more minute account of this may be seen in the first part of [.book-title]#Piety Promoted.#

The county of Wicklow, which had been formerly visited by Thomas Loe and John Edwards,
was this year, 1669, visited again by J. Haydock and some other Friends,
who had good service; Thomas Trafford, the Penroses and some others being convinced;
and some time after a meeting was settled at Thomas Trafford`'s house at Garrymore;
but the said Thomas removing to Wicklow, some time after,
it pleased the Lord to give him a share in the ministry, and the meeting was kept there.

This year (1669) also came over from England in the service of truth John Kilburne,
who had good success, and Roger Roberts particularly was convinced by his ministry.

The same year also was memorable for the arrival
of that eminent minister and elder in the church,
George Fox, who together with Robert Lodge, James Lancaster, Thomas Briggs,
and John Stubbs, landed at Dublin, and had a large meeting there on a weekday,
and from there passed on to other parts,
and had great service both among Friends and other people.

After the conclusion of one of their meetings some Papists who had been present,
were angry and raged much: whereof when George Fox heard, he sent for one of them,
but he refused to come to him,
whereupon George sent a challenge to him with all the friars, monks, priests,
and Jesuits to come forth and try their god and their christ,
which they had made of their bread and wine, but no answer could he get from them,
therefore he told them they were worse than the priests of Baal:
for Baal`'s priests tried their wooden god,
but these dared not try their god of bread and wine,
and Baal`'s priests did not eat their god as they did, and then make another.^
footnote:[This fact may serve abundantly to manifest the absurdity
of a scandal which some would affix on the original Quakers,
as having been Jesuits in disguise,
as it likewise shows that they are one with other sound Protestants,
in renouncing the idolatry of the church of Rome.]

George Fox in his journal gives the following account of this visit:

[.embedded-content-document]
--

The priests and magistrates were envious, but the Lord disappointed their counsels,
and gave us many sweet and blessed opportunities
to visit Friends and spread truth in that nation.
Meetings were large, Friends coming to them far and near: many were reached,
and convinced and gathered to the truth, and Friends greatly refreshed.
Oh the brokenness that was among them in the flowings of life! so that in the power
and spirit of the Lord many together broke out into singing with audible voices.^
footnote:[See [.book-title]#George Fox`'s Jounal.#]

--

The said George Fox had a singular gift in church discipline,
and having in the year 1667 recommended the setting
up of monthly meetings throughout England,
he in the year 1668 wrote to Ireland and other countries,
advising Friends to settle the like meetings there also,
and afterwards visited those countries in person,
(and particularly this kingdom this year) and assisted
them in settling their men and women`'s meetings,
and at Dublin he recommended the holding their men and women`'s meetings every two weeks,
which has been continued ever since; and the general meetings,
consisting of some from each province, were concluded to be held half-yearly,
on the Third and Ninth months,
the first appointed meeting of which sort was in the Third month, 1670,
and this settlement remains unto this day.^
footnote:[Altered to a yearly meeting in 1793.]

In those early days there was little more done at those general meetings
than collecting the sufferings of Friends for conscience sake,
and making a record thereof with the causes alleged,
and by whose order and on whose account; and if any Friends were in prison,
to endeavour to make proper application for their release.

But in process of time many other weighty affairs,
respecting good order and discipline in the church,
became the subjects of their consideration in these meetings;
and indeed Friends of this nation became justly conspicuous
by their zeal and diligence in the exercise hereof,
and the same good Spirit led both them and their brethren in England
into the same wholesome rules so excellent in themselves,
and so highly conducive to the preservation of a Christian community.

But to return to George Fox;
after he had travelled over several parts of the nation and visited
Friends in their meetings for business as well as worship,
and recommended the settlement of meetings of discipline as above,
and had answered several papers and writings from monks, friars,
and Protestant priests (who were enraged against him) he, with Robert Lodge,
Thomas Briggs, etc. returned for England,
parting with Friends in much tenderness and brokenness in the sense
of the heavenly life and power that was manifested among them.

This year (1669) also Solomon Eccles was put into prison at Galway,
by an occasion somewhat extraordinary.
His zeal was so great that what he judged evil he opposed with the hazard of his life,
an instance of which occurred in a strange action he performed
in a chapel of the Papists without the said town of Galway,
where he went naked above his waist with a chafing-dish
of coals and burning brimstone upon his head,
and entered the chapel, when all the people were on their knees praying to their idol,^
footnote:[Or images.]
and spoke as follows: "`Woe to these idolatrous worshippers:
God has sent me this day to warn you and to show you what will
be your portion except you repent;`" which when he had done,
he went away to the town, where he was presently made a prisoner.^
footnote:[[.book-title]#Sewel`'s History.#]

Another transaction of the said Solomon Eccles recorded by the same historian,
A+++.+++ D. 1670, and a memorable instance of his zeal against time-serving, was as follows;
the said Solomon going into the cathedral at Cork,
found there Benjamin Cross preaching in a surplice,
who having formerly been a Presbyterian preacher in Dorsetshire, had there said,
that he had rather go to the stake and be burnt, than put on a surplice.
This priest (now become a turncoat for gain) having
finished his sermon and concluded with a prayer,
Solomon Eccles declared that the prayer of the wicked is an abomination to the Lord,
and knowing the deceitfulness of the said priest, and that he was an apostate,
added these words:
"`What shall be done to the man that makes shipwreck of a good conscience?`"
For this he was taken and committed to prison by the mayor, where being kept ten days,
he was accused as a vagabond, and, without examination,
whipped through the streets of Cork, from north-gate to south-gate, and,
having received about ninety stripes, was expelled.

Besides the above-mentioned,
several other Friends also this year visited this nation in the service of truth, namely,
Thomas Janny and John Abraham;
and John Burnyeat landed here a third time and had blessed
service in Dublin and other parts of the nation;
and thus by the blessing of the Lord upon the labours of his ministers,
many in various parts of the nation were convinced of the truth, and joined with Friends.

This year (1669) also Anthony Sharp came from England and settled in Dublin,
who was very serviceable in many respects to Friends,
and after some time received a gift in the ministry.
See the testimony concerning him A. D. 1706.
