== Chapter II.

[.chapter-subtitle--blurb]
From the settlement of Church-discipline to the end of the troubles under
King James 2. The progress and increase of Friends in a state of suffering.
Their peculiar zeal and steadiness in keeping up their Meetings for Divine
worship in a time of persecution while other dissenters fled.
The state of Friends under King James 2. and their
wonderful preservation during the troubles.
Summary accounts of the lives, characters,
and Christian experiences of several of their eminent ministers interspersed.

Sufferings still attended Friends, on various accounts,
particularly for bearing their testimony against the antichristian oppression of tithes,
for refusing to swear, for not observing the days called holy days,
and frequently for mere meeting together peaceably to worship God,
on which account they suffered imprisonment and fines.

William Penn, who was here this year, did frequently visit his friends in prison,
and hold meetings with them,
omitting no opportunity he had with those in authority to solicit on their behalf;
and as the Ninth month national meeting was this year held at his lodgings in Dublin,
an account of Friends`' sufferings was there drawn up by way of address,
which he presented to the lord-lieutenant,^
footnote:[John Lord Berkly, Baron Stratton.]
whereupon an order of council was obtained for the release of those that were imprisoned.

For a more minute account of the sufferings of Friends
on the above-mentioned and other occasions,
I must refer my reader to the [.book-title]#Account of the Sufferings
of the People called Quakers in Ireland,#
from the year 1655 to the end of the reign of King George I. published in Dublin, 1731.

The following instance however of the innocency of the sufferers on the one hand,
and of the severity of the persecutors on the other, I shall here insert:

// lint-disable modernize-words "Holden"
Blanch Holden and Margaret Trotter, two very poor women,
for going to the public worship house at Lisnegarvy,
alias Lisburn in the county of Antrim, on the day called Christmas-day,
and saying these or the like words, "`Let them that keep a day,
keep it to the Lord,`" were fined by judge Kennedy,
at the court session at Carricksergus, one hundred marks each,
and committed to Carricksergus jail, where they continued prisoners above two years.

This year John Banks, from Pardshaw in Cumberland, came into Ireland a second time,
having in the foregoing year visited the northern parts
of the nation in company with our ancient friend John Tiffin:
he landed in Dublin the Third month, the morning the half-year`'s meeting began;
and on the following Seventh-day of the week,
in pursuance of a particular exercise upon his spirit
to go to a certain place southward from Dublin,
in order to have a meeting there the next First-day of the week,
he went from Dublin to Wicklow, where no meeting of Friends had been kept before.
He, accompanied by two Friends, went to an inn that night,
and gave notice that he intended to have a meeting in that town next day,
being the First day of the week: so the report soon spread among the people,
that an English Quaker was come to preach there:
and there was a mighty noise of it in the place,
the people being stirred up by the priest; and the governor, one Hamman,
lived at the castle, where a garrison of soldiers was then kept:
the following part of this narrative I shall give
in the said John Bank`'s own words from his journal:

[.embedded-content-document]
--

When I was ready to go from the inn where we lodged, the landlady said to me,
"`For God`'s sake go not along the street,
for there is a guard of musketeers waiting at the cross to take you.
I will show you a back way;`" I said, "`I accept of your love,
but I must not go any private way, but along the townstreet,
for I have a testimony to bear for the Lord, in love to the souls of people.`"
So by that time we were well sat down, before my mouth was opened,
came a sergeant with a halbert and a guard of musketeers, and said to me,
I must go along with him to the governor.
I answered, "`What authority do you have to take me?
if you have a warrant so to do, I shall go.`"
He held out his halbert, and said, "`This is my warrant.`"
I said, "`You need not to have come to us with your swords and guns,
as those that came against Christ, with swords and staves;
we are known to be a peaceable people: howbeit I shall go with you.`"
So they took me to a house where was the priest, his wife, the governor, etc.

The priest was in a great rage when I came in, and said to the governor, "`Sir,
this is the deceiver, this is the deluder that is come from England,
to delude the people here, I hope you will do justice and execute the law.`"
The governor being pretty moderate said nothing for some time--and
the people being in an uproar pressed in at the door,
and I being willing to let the priest rage on a little,
till he had something vented himself, that he might be more manifest to the people,
at last said to him, "`You say I am a deceiver and a deluder.`"
He answered in a great fury, "`So you are, so you are:`" but I said, "`Have patience,
and let your moderation appear unto all men,
and hear what I have to say to clear myself from your false accusation:
for I shall not take your assertion for proof: I have had patience to hear you:
are you a minister of Christ?`"
"`Yes,`" said he, "`I am.`"
I replied, "`but if I prove you a liar, as by the witness of this people you are;
(in charging me with what you can bring no proof for) and if so,
you are out of the doctrine of Christ and so no minister of Christ, but of antichrist,
and so of your father the devil,
and therefore you are the deceiver and the deluder of the people.`"
Upon which the priest`'s mouth was stopped.

--

And then John had an opportunity of declaring truth to the people;
yet the governor committed him and two more to prison: but the jailer was favourable,
and gave them the liberty of a room, where the people followed,
and John preached the way of life and salvation to them in and through Jesus Christ,
by believing in his pure light, and walking answerable to the teachings of his grace,
and reproof of his Holy Spirit;
by which they might receive power to become the sons of God,
and several were convinced that day, and received truth in the love of it.
He was kept in prison three days, where there was a great resort of people to see him,
and to discourse about the principles of religion.
Then he returned to Dublin, and from there travelled into the North,
visiting Friends there; and on his return to Dublin he went to Wicklow again,
there being a letter from there signifying that the people desired another meeting,
which, notwithstanding the opposition of the priest, was held there peaceably;
and although the priest, as soon as he had opportunity,
began to prosecute and imprison Friends for tithes, and such like things,
and got several put into prison that came to visit that place, yet truth, prospered,
and a meeting was set up in that town, and still continues.

This year (1672) died in Cork, Susanna Mitchell, of that city:
she was a zealous faithful servant of the Lord for many years till her decease,
and often bore a public testimony to God`'s everlasting truth before magistrates,
priests, and people; for which she was often a sufferer in bonds,
and rejoiced to be found worthy.

This year (1673) Friends addressed the lord-lieutenant^
footnote:[Arthur, Lord Capel, Earl of Essex.]
and council for relief from their sufferings on many occasions, and particularly this,
that whereas they dared not on any account take an oath, as being forbidden by Christ,
wicked men laid hold on this their conscientious scruple to ensnare and defraud them,
by causing them to be subpoenaed into chancery,
where their answers without an oath would not be admitted; for instance,
in the county of Wexford,
Thomas Holme having about 200£ due to him from captain Thornhill,
for which judgment was obtained against him in common law,
was subpoenaed into chancery by the said Thornhill,
where he well knew Thomas could not answer upon oath, and so this friend lost his debt:
and in Dublin, James Fade having about 40£ due to him from one Ezekiel Webb,
was by the said Webb subpoenaed into chancery,
and because the friend could not give in his answer upon oath,
he not only lost the said debt,
but was constrained to give above 70£ to get clear of the debtor:
and indeed this iniquity continued in practice,
and Friends were exposed to sufferings on this account,
even until the reign of our late gracious sovereign George the First,
when they were delivered from this yoke of oppression.^
footnote:[See the year 1719.]

About the same time Friends met with great trouble and exercise at Cork, Dublin,
and several other places,
by reason of various persons that were gone into the loose
and foolish imaginations of Muggleton and others,
and perverted into looseness and indulgence of their carnal
wills and affections from the cross of Christ and self-denial;
but truth prevailed, and God gave an understanding to place judgment upon them.

This year (1675) and about the fifty-fifth of his age, died Robert Sandham, of Youghal,
a faithful elder, though not a minister.
He was born at Woodcutt near Petworth, in the parish of Grassom and county of Sussex,
A+++.+++ D. 1620, was of a pious disposition from his youth,
and joined himself in society with the strictest sort of Baptists,
who were a persecuted and tender people at that time;
among whom he underwent great mockings, stonings in the streets,
etc. and was very zealous in their way,
travelling up and down on foot with their ministers,
insomuch that he obtained the name of young Timothy,
but in process of time finding that this people while they adhered to the form,
had too much lost the power that he first found among them,
his anxious soul panted after some further manifestation,
and a closer communion with his Maker.

In the year 1650 he came from England a lieutenant
in colonel Sanders`'s regiment of foot,
and arrived at Youghal, and in the year 1652, took to wife Deborah Baker of that town,
then an Anabaptist, afterwards a faithful friend, of whom hereafter.
He was convinced in the year 1655, by the ministry of a woman called Elizabeth Fletcher,
who preached in the streets at Youghal.
In the year 1661 he was imprisoned at Cork,
for not swearing when summoned to be on a jury, and was fined five pounds,
for which he had a horse taken from him of more than twice that value.

In the year 1662, he was in great doubt whether he should settle at Cork or Youghal.
Cork yielded him a prospect of the greatest advantage as to the riches of this world,
but Youghal was the place where it seemed to him
he should be the most serviceable as a Christian,
the meeting there being then but small and weak,
and upon some late occasion grown weaker; whereas Cork meeting was stronger,
having many faithful Friends belonging to it:
under this consideration he gave up in faith to dwell in Youghal,
trusting in God`'s providence as to his worldly support.

In the year 1663, a meeting was settled at his house; but persecution followed;
a sentinel being set at his door to keep Friends out,
and their meetings were broken up by guards of soldiers,
and Matthew Appleyard the governor, commanded him with his family to leave the town;
but being a freeman, he asserted his liberty as such,
and refused to obey the governor`'s unjust command.
The said governor however,
forcibly sent him away with a guard of soldiers on
foot (not permitting him to ride his own horse,
though he desired it, being under some bodily infirmity), to Charleville,
a journey of twenty-four miles, there to appear before Roger Boyle,
lord president of Munster, afterwards earl of Orrery,
who when he had read his accusation,
finding him charged with nothing except concerning the law of his God,
immediately set him at liberty; and he returned to Youghal, and continued to dwell there,
undergoing with patience and courage,
the reproaches and sufferings that attended him for the exercise of a good conscience;
and a meeting was constantly kept at his house while he lived, and after his death,
at his widow`'s, until a meetinghouse was built in that town,
which was in the year 1681.
He was just in his dealings among men, of a benevolent spirit, ready to do good to all,
especially those of the household of faith; zealous and firm in his testimony for Truth,
against apostates, backsliders, and false brethren,
and particularly against the erroneous and blasphemous principles of Lodowick Muggleton,
which prevailed on some, to their utter loss as to truth.
He was a sharp reprover of disorderly and unfaithful walkers, but a help to,
and a strengthener of weak brethren and the young convinced, by suitable counsel.
He died in a sensible and resigned frame of spirit.

This year (1676) Oliver Sansom visited Friends in the work of the ministry,
from whose journal the following passage will serve to give the reader
a just idea of the devout disposition of Friends in those days:

[.embedded-content-document]
--

The general half-year`'s meeting at Dublin, began on the Fourth-day of the week,
at the ninth hour in the morning,
and the meeting for worship continued until after the first hour.
About an hour after, Friends met again in order to consider of the affairs of the church:
but the power of the Lord broke forth so mightily among Friends in many testimonies,
prayers and praises to the Lord, that there was no time to enter upon business that day,
and so the meeting broke up.
Next morning the meeting began again about the ninth hour,
and continued until near the third hour in the afternoon,
and a precious heavenly time it was.
Then adjourning for one hour,
Friends came together again to go upon the business of the meeting:
but then again the Lord`'s power mightily appeared,
whereby many mouths were opened to declare of the goodness of the Lord,
and to offer up prayers and praises to him,
which took up the time of the meeting of that day also,
so that very little could be done as touching business.

But early next morning Friends went about the business of the meeting,
and continued at it the greatest part of that day, and the next day also,
when it was concluded, on the Seventh-day of the week, in the evening,
having been generally carried on in much unity and harmony.

--

The said Friend further relates, that besides several public meetings for worship,
and some at Friends`' houses in Dublin,
a meeting was also appointed for him at Chappel-izod, and held to good satisfaction,
and another again a little while afterwards in the same place.
He stayed four months in Ireland, and travelled 950 miles.

This year (1678) besides several Friends from England one Katharine Norton,
alias M`'Laughlin, travelled this nation in the service of truth.
Her maiden name was M`'Laughlin;
she was born of Irish parents of account in or near Colerain;
and was sent to Londonderry for education, where she remained for some time.
When she was sixteen years of age,
there came a ship to Derry to take in passengers for Barbados,
which she embarked in and landed in that island, where she was married;
and some time after, that island being visited by George Fox and some others,
she was convinced by their ministry; and afterwards became an able minister,
and in or about this year, 1678, came on truth`'s service into the kingdom of Ireland.
She visited Friends meetings in the North;
preached in Lurgan market on a market-day in Irish; had several meetings near Colerain,
where her relations lived, and several disputes on the account of truth,
which got the victory; from which place she travelled to Armagh, Cavan,
the Moate of Granoge; and had several meetings there and elsewhere,
to the satisfaction and edification of Friends;
and some time after she travelled to Dublin, and took shipping for England.
She was well qualified for the service, being of a sound judgment, large in testimony,
of a good utterance, had of her own to distribute,
and did not make the gospel chargeable.

This year (1679) Judith Boulby was here in Truth`'s service,
and being moved to go to Londonderry, having a particular message to that place,
she published the same in their public worship house, and for so doing was imprisoned;
but committed to writing, and left with them, the following lines:

[.embedded-content-document.address]
--

[.blurb]
=== A Few Words as a Warning From the Lord to the Inhabitants of Londonderry, and Also to the Whole Nation of Ireland.

Oh, repent, repent! for a terrible day from the Lord is approaching,
wherein the hearts of many shall fail, terror shall lay hold upon them,
but they that fear the Lord shall daily renew their strength.
My heart is troubled, I am pained as one to be delivered,
or as one whom wine has overcome, because of the Lord,
and because of the word of his holiness.
Thus says the Lord, "`How long will you scorners delight in scorning,
and you that hate knowledge harden yourselves against God`'s reproof?`"
God`'s day is come, and woe to all the workers of iniquity.
Woe is me; woe is me; for the misery that is coming upon you.
Your wound is hard to be cured; your physicians are physicians of no value;
your watchmen are watchmen of the night.
Oh nation, your teachers have deceived you,
they have spoken a divination of their own brain, and not from the mouth of the Lord;
they have cried "`Peace, Peace,`" when indeed, as the Scripture says,
"`there is no peace to the wicked.`"
The messenger of the new covenant has been rejected by you,
who has long waited to be gracious.
How has the visitation of his love been sounded forth in your markets and in your streets?
But now the herald of God`'s wrath, a noise of confusion, terror, and amazement,
is even ready to enter into your borders;
a bitter cup without mixture the Lord is handing, forth unto the nations,
and you must drink, it, except high and low, rich and poor, repent speedily.

Oh, is there none to intercede for you,
is there none to stand in the gap and stop the judgment, and stay the destroying angel,
who is ready with the sword in his hand to execute God`'s fierce wrath upon the nations;
and though you have driven furiously against the Lord,
and against his appearance in his people,
the Lord God will strike off your chariot-wheels; and that which is the joy, and comfort,
and satisfaction of God`'s people, will be your woe and torment;
it will be in you as a worm that will never die, it will gnaw you in your inward parts,
and it will be in you as a fire that can never be quenched,
until you know that the Most High rules in the kingdom of men,
and gives them to whomsoever he pleases.
And you, O friends, who are put in power to be governors of this nation,
O exercise it for God, and while you have a day, prize it,
lest that your power be given to others, and then the Scriptures be fulfilled upon you,
where God says, "`I called, and you refused; I have stretched forth my hand,
and no man regarded; therefore will I laugh at your calamity,
and mock when your fear comes;`" when tribulation shall come upon you as an armed man,
then shall you call, but the Lord will not answer, you shall seek him early,
but shall not find him,
and then shall you know that I have not written these lines of myself,
but the Lord God has sent me to proclaim these things in your ears.

[.signed-section-signature]
Judith Boulby.

[.signed-section-context-close]
7th Month, 1679.

--

This year (1680) died William Morris of Castlesalem in the county of Cork; who,
though a man of great parts and wisdom, was convinced of truth by a weak instrument.
He was serviceable upon many occasions with the government
in appearing on behalf of suffering Friends,
though he was also several times a sufferer in bonds for his testimony.
He wrote an excellent short treatise entitled, [.book-title]#Tithes No Gospel Ordinance.#^
footnote:[See a further account in 1656, page 104.]

This year (1682) Friends of the three provinces made collections,
and remitted to London the sum of 333£ to be applied to the redemption
of certain Friends that were captives in Algiers,
in conjunction with money collected in England for the same purpose;
and 281£ was subscribed here for the same use, in the year 1686.

In the same year (1682) Benjamin Bangs landed in Dublin,
and travelled up and down in the work of the gospel, and had great and good service,
many being convinced by means of his ministry.
At Antrim, a place of great profession, he had a meeting in the evening,
to which a great many came, and some with a design to oppose him.
The place was not large enough to contain the people;
which occasioned those without to be very noisy and turbulent,
some of the ruder sort pelting them with bits of dirt and turf,
while Benjamin was preaching: upon which he made a full stop,
which occasioned a general silence; and after a little time he said,
"`I understand this is a place of great profession of religion;
I am sorry to see so much irreligion as appears among you at this time,
through your rude behaviour.
It is not long since I came out of my native country,
and I think it will not be long before I return again,
and then what shall I say of you to your poor suffering brethren in England?`"

He relates that there was a dread upon them when he spoke these words,
which also affected those present,
for many of them trembled and their faces gathered paleness.
Upon which he advised them, if they had any regard to the reputation of religion,
to enquire after those that were the occasion of these disorders;
for that such behaviour was base and scandalous; and moreover he was moved to say,
that "`the time draws near when you will be blown
away like chaff before the summer threshing floor,
and the place of your meeting will not be found.`"
After this some cried out in a Scottish tone,
"`We be all ashamed;`" and getting out of the house,
enquired after those that were the occasion of the disorders.
Some lads they got and beat; others that absconded they took the names of:
after which they had a solemn good meeting,
the lively sense of the love of God reached to the hearts of many present,
and the meeting ended well.
At this meeting was a young man, a Papist and servant to William Wilkinson, convinced,
as were many more elsewhere in the North, etc.

He travelled through Ulster, and several parts of Munster and Leinster,
where he had many meetings, having departed from Dublin the 14th of the Ninth,
and returned there again the 25th of the First month, 1683.
After the conclusion of the following Third month`'s half-year`'s meeting,
he intended to have returned to England; and in order to it had sold his horse,
and prepared for the voyage, but the wind proving contrary, he could not get off;
and besides, he found some stop in himself,
a further service being presented to his view, to which he gave up,
though much contrary to his inclination, namely,
it fell with some weight upon him to have a meeting at Tralee in the county of Kerry,
where William Bingley had been:
accordingly he set out from Dublin the 17th of the Third month,
taking meetings in the way, and went to Cork, and from there to Tralee,
a journey of one hundred and fifty-eight miles, accompanied by John Hammond,
Thomas Wight, and some others.
He had a comfortable opportunity at Tralee, many hearts were tendered,
the Lord`'s presence attending and helping them; and after the meeting ended,
the people withdrew in a solemn and peaceable manner.
P+++.+++ White, a man of note in the town, came and offered them his house to meet in,
which they kindly accepted, as also of his invitation to dine with him next day,
and parted with him in much friendship.
After this he visited several meetings in Leinster province, and went to the North again.

As he was going from Antrim to the Grange, he saw ten or twelve men upon the road,
walking in a very solitary manner, and it arose in his heart,
"`These are sheep having no shepherd.`"
When he came up to them, he slackened his pace and queried of them, "`What news?`"
The men were startled at the question, and answered,
"`We know of none;`" continuing to go softly, he said, "`Are you going to a meeting?`"
They answered, "`Our minister is silenced,
for orders are come down commanding all dissenters not to assemble,
so now we have no teacher.`"
This brought to his remembrance what he had been concerned to deliver as above,
at the evening meeting he had at Antrim, where he met with so much rudeness, namely,
that the time draws near when "`you will be blown
away like chaff before the summer threshing-floor,
and the place of your meeting will not be found.`"
At this time all dissenters, except Friends, had declined keeping up their meetings.

Benjamin proceeded to discourse with the men aforesaid, and said, "`The hireling flees,
because he is a hireling and cares not for the sheep,`" as it is said, John 10:11-13,
referring them to the text,
further showing that it is happy for those that are come to the
knowledge of that teacher which cannot be removed into a corner.
God said, he should teach his children himself,
and the children of the Lord are taught of the Lord.
See John 6:45, and Isaiah 54:13,
and you may read in the first epistle of John 2:27 "`The
anointing which you have received of him abides in you,
and you need not that any man teach you,
but as the same anointing teaches you of all things,`" etc.
And in Titus 2:11-12. "`The grace of God which brings salvation,
has appeared unto all men, teaching us,`" etc.
Here he directed them to the great heavenly Schoolmaster, who said, "`Learn of me,
for I am meek and lowly in heart; follow me,
and you shall find rest unto your souls.`" Matt. 11:29.
Thus labouring to bring them from their hireling teachers,
to the teaching of God and Christ in themselves,
by which they might come to the knowledge of God and ways of his salvation,
"`For a manifestation of the Spirit is given to every
man to profit withal,`" 1 Cor. 12:7;
advising them to turn their minds inward, and mind the secret operations of it,
thereby they would find, through a lively experience,
that it checks and reproves for bad words and actions; and as they turned to that,
they would find it would lead them into all truth, with many more words to this effect.
They were well pleased with this discourse,
declaring at parting that they had never heard things so opened to them in their lives.

The number of miles our said friend Benjamin travelled in
Ireland were one thousand seven hundred and forty-six;
the number of meetings he had here, exclusive of Dublin, were one hundred and eighty;
and he spent in this service one year within a few days.
William Edmundson and Robert Jackson were put into the bishop`'s court for tithes,
excommunicated, taken with a writ and committed to prison,
and they were kept prisoners about twenty weeks.
The lord of Ely interceding for their liberty,
the bishop ordered them to come to his court at Kildare; and accordingly they came,
and there was the bishop, about ten or twelve priests, the lord of Ely,
and several other persons of note, and dean Sing was chancellor of the court.
The bishop began to discourse with William Edmundson concerning tithes,
which he was unwilling to enter upon, being sensible of his own weakness,
but the bishop urging it, a conference was commenced, which lasted three hours,
and in a quiet manner without any other business,
wherein wisdom and understanding was given to William Edmundson,
and scriptures brought fluently into his memory; so that he proved tithes to be ended,
and that it was antichristian to pay or receive them in gospel times which
was opened so clearly to the understandings of the people,
that there seemed to be great satisfaction in the court;
and dean Sing stood up before them all and said,
if he had known W. Edmundson as well before as now, he should not have suffered;
with several other expressions of kindness.

Several other matters were also then discoursed of,
and queries answered in relation to gospel-ministers, the Christian religion, faith,
and the true worship of God, to the satisfaction of those present; and the bishop,
ordering the two Friends to appear at the next court,
wrote to the sheriff to let them have their liberty till then;
and at the next court he wrote again to the sheriff, to discharge them out of prison,
which was readily done: thus this suffering and conference had a good effect;
and afterwards both the bishop and officers of that court were kind to Friends.

This year (1683) died Robert Cuppage of Lambstown in the county of Wexford,
a man of an exemplary life and conduct, who loved truth,
and had a sound testimony for it, and lived in it as well as preached it to others.

About the middle of this summer the government gave
order to the several sorts of dissenters in Dublin,
that they should forbear meeting publicly together in their worship houses as formerly.
The archbishop of Dublin also sent for Anthony Sharp,
and told him it was the mind and desire of the government that
Friends should also forbear meeting in their meetinghouses;
but Friends returned answer,
that they believed it was their indispensible duty to meet
together to worship the great God of heaven and earth,
from whom we receive all our mercies,
and not to forbear assembling ourselves together for fear of punishment from men,
for that we met purely to worship the Lord, and not upon any other account.
So according to the desire of the government,
other professors generally left their meetinghouses,
but Friends met together to worship the Lord as formerly,
as they were persuaded it was their duty to do:
so upon a First-day in the Sixth month this year came the marshal and
several of the mayor`'s officers to the meeting at Wormwood gate;
where John Burnyeat being speaking, the marshal commanded him to go with him,
which after some discourse he did.
He commanded the meeting to disperse, but Friends kept quiet in their places.
John was carried before the mayor, with whom he had some discourse to this effect:
he asked him, why they did act contrary to the government,
having been commanded not to meet?
John answered, "`We do nothing in contempt of the government.`"
"`But,`" said he, "`why do you not obey then?`"
John replied, "`because it is matter of conscience to us,
and that which we believe to be our indispensible duty,
to meet together to worship God.`"
To which he answered, "`You may be misled;`" John told him, "`If we are misled,
we are willing to be informed, if any can do it.`"
Then it was urged, other dissenters had submitted, and why would not we?
John said,
"`What they do will be no plea for us before the judgment seat of the great God.`"
So after some other discourse, the mayor committed John to the marshalsea prison,
to which also were taken afterwards Alexander Seaton, Anthony Sharp, and others.

Now several sober persons observing other professors to shrink in this time of persecution,
while Friends kept their meetings as usual,
came to our meetings and became faithful Friends.
The consideration of the great sufferings that were upon Friends
in England for their innocent testimony towards God,
whereby many of them were brought into great necessity and affliction
by the ravenous hands of wicked informers and violent persecutors,
being before the national meeting,
a collection for their relief was ordered from the several provinces.

Now, as well as before,
also in this nation Friends were not exempt from
suffering on account of their non-payment of tithes,
etc. and the unreasonableness of the fees and costs of the bishop`'s court;
on which occasion; they petitioned the lord-lieutenant and council.

This year (1684) was published an account of Friends`' sufferings on the occasions aforesaid,
and ordered to be sent into the several provinces.

Likewise this year, Thomas Ellwood`'s book, called [.book-title]#A Dissuasive From Persecution,#
was printed at a national charge.

The same year died Thomas Carleton, at Ballynacarrick in the county of Wicktow,
who was convinced in Cumberland about the year 1663,
before which he underwent great conflicts of soul,
which I shall describe in his own words from one of his treatises:

[.embedded-content-document.treatise]
--

I was early visited by the love and tender mercy of the Lord,
which often presented unto me my state and manner of life,
and by the same love and light he made known unto
me that his way and worship was a purer,
holier way and cleaner life than I had yet attained unto.
Thus I was induced to seek after the Lord;
I read and searched the Scriptures with much diligence and zeal,
and gave myself up to hear sermons, search catechisms,
etc. was often tossed in myself like restless waves in a troubled sea,
not feeling peace nor stability.
I often besought the Lord in contrition of spirit,
to clear my understanding and judgment, and make me to know his living way, truth,
and people, sects and opinions then abounding, one saying, "`Lo,
Christ is here,`" another, "`Lo, he is there;`" every denomination construing, wresting,
and interpreting the Scriptures to their sundry tenets,
and forcing meanings from them to answer their principles,
and to maintain every of their interpretations as authentic truths;
in all which I was as one without foundation, tossed with every of their windy doctrines;
but it still rested with me, that man was created for God`'s glory,
I being ever and anon judged and condemned in myself for sin and disobedience;
for the law was come by which is the knowledge of sin, and the commandment being come,
sin revived and I died as it were; then sin by the commandment became exceeding sinful,
and then I was driven to seek for peace night and day, early and late,
in public and private fastings, feastings, family devotions, etc. running from one house,
town, assembly, and worship to another,
seeking the word of the Lord in all their sabbaths, lectures, humiliations,
or thanksgivings, diligently observing every ordinance in which the minister said,
God was to be found, and all to obtain peace with my Maker; but it fled from me,
nor was to be found among them.

At length, after much humiliation, contrition, and distress,
it pleased the Father to reveal his Son in me;
and by his light that gives the knowledge of the
glory of God in the face of his Son Jesus Christ,
2 Cor. 4: 6, he was pleased to give me a glimpse of the heavenly land,
and of the way to the kingdom of God,
which I saw to be in and through the light of Christ Jesus,
which enlightens every man that comes into the world,
as it was then preached and testified by the servants of the Lord;
a measure of which I felt in myself, which told me all that ever I did,
secretly condemning every work in me,
with every word that was contrary to the will and mind of the Father;
and also justifying every word and work that was according to his will.

Thus the Lord having opened my understanding,
and given me in measure a feeling of himself,
I was forced to conclude (as the woman of Samaria did) that this was the Christ,
this was the way, this was the truth; as by daily experience I found,
by the operation of the light in my own heart,
compared with the testimony that the faints and servants of God had given in ages past;
and thus in the mouths of two or three witnesses
this testimony was established and confirmed in me.
But still how to receive and give obedience to it, I knew not,
the enemy often raising doubts and fears in me,
and the warfare between the flesh and spirit was great.
I saw that I should never find peace nor reconciliation with the Lord,
until I gave obedience to the light, and came into society with the children of light,
and to the worship that stood in spirit; contrary to all the ways,
worships and services of the world, set up in the wills and limitations of men,
which I saw to be only formal and traditional, and no less than idolatry,
as they then stood in the will-worship,
being prescribed and set forth at the wills and pleasures of men,
and established by the then present powers, government and authority;
as the [.book-title]#Independent Church Faith,# the [.book-title]#Presbyterian Directory,#
and the [.book-title]#Common Prayer Book# of the Episcopals may fully testify;
none being to question or object against anything that was
or is believed by their several churches and assemblies,
or prescribed by their rules or canons,
directories or service-books (though never so much dissatisfied in conscience),
without undergoing the censures or adjudications of their particular societies.
But they that are come to the light and liberty of the sons of God,
and to live and walk in the Spirit, by the Spirit,
they know the anointing which abides in them, and is truth and no lie,
which teaches them in all things to follow the Lamb only, wherever he goes,
and the leadings of his Spirit, and not the formal trash and traditional precepts of men;
and so they are ceased from man and his teachings,
knowing the Lord is come to teach his people himself;
whereof I being persuaded in my own heart,
was at length constrained to yield and resign myself unto the will of the Lord.

--

So far Thomas Carleton, respecting himself:
let us now hear testimony of the brethren concerning him.

[.embedded-content-document.testimony]
--

He came to Ireland about the year 1673, was a very zealous, honest friend,
and an able minister; having a divine gift to administer from,
in the exercise of which he was very serviceable;
both for the convincing of many who were strangers to the way of the Lord,
and for the edifying, building up and provoking to diligence, those already convinced.
He was a man of a good understanding and clear discerning, yet of a lowly mind,
and ready to prefer others before himself.
He usually stood up in great fear and dread,
when he was exercised under the powerful word of life.
He was valiant in asserting and defending truth against the opposition of its enemies,
and patient in suffering for it, as appears from a small tract he published, entitled, [.book-title]#The Captive`'s Complaint,#
or [.book-title]#The Prisoner`'s Plea Against the Burdensome and Contentious Title of Tithes,#
etc. wherein are laid down several grounds and reasons against the propriety
and payment of tithes in this evangelical day and dispensation.
He also published some other small pieces,
and particularly an excellent general epistle of admonition
and advice to Friends in Ireland and elsewhere.

While other dissenters on occasion of the prohibition lately mentioned, 1685,
left their usual meeting houses and met more privately,
Friends still continued both their public meetings for the worship of Almighty God,
and those for Christian discipline, and great unity and peace was among them;
great numbers also of other people came to our public meetings,
and Friends gained credit among many sober persons,
notwithstanding the prejudice and railing of the other dissenters who fled into corners.

--

There being a great resort to our meetings about this time
(1687) one James Barry an independent preacher raged,
and in his public preaching greatly railed against Friends:
hereupon several of his hearers, like the ancient noble Bereans,
came to Friends`' meetings to be satisfied whether his accounts were true or no;
and by the ministry of John Burnyeat and others, their prejudices were removed,
they were convinced and joined to Friends, and became very serviceable afterwards.

At this time also, under king James,
the government having made choice of some Friends to serve in corporations,
and as magistrates, and some few having accepted thereof,
though it was not of their own seeking, a paper of tender advice was drawn up,
by order of a general meeting, to Friends who were so concerned,
to keep to the truth in everything: that they might shine as lights to the world,
and be helpful to bring forth justice, judgment, and righteousness.
And on this occasion George Fox wrote a letter to William Edmundson,
dated from Kingston upon Thames, 1687, to this purpose:

[.embedded-content-document.letter]
--

[.salutation]
Dear William,

As for those Friends of Dublin, Cork, Limerick,
and other places that have taken those offices of aldermen and burgesses upon them,
they must consider and be wise; for if they keep to truth,
they can neither take any oaths, nor put any oaths to anyone,
neither can they put on their gowns and strange kind of habits,
as Friends have considered it here when they talk of putting them in such places;
and again, when they have the aldermen, or mayors or common-council feasts,
Friends here cannot join them in such things;
but if they will make the poor a feast that cannot feast you again,
Friends have offered themselves to join with them;
but to feast them that will feast you again,
and to join with them in their strange kind of habits and formalities, is not like truth,
that denies the pomps and fashions of this world:
but in their places they should do justice to all men,
and be a terror to them that do evil, and a praise to them that do well,
and preserve every man both in his natural rights and properties,
and in his divine rights and liberty, according to the righteous law of God, etc.

[.signed-section-signature]
George Fox.

--

The latter end of this year (1688) a war broke forth in this nation,
threatening a general overthrow of all the English and Protestants,
and in that frightful time many of these left their dwellings, stocks, and flocks,
and fled, some to England, and some to arms; but Friends generally kept their places,
and kept up their meetings, and trusted the Lord with their lives and substance,
that rules all things in heaven and earth, and bounds the sea,
and the raging waves thereof, though under great perils of various sorts,
by reason of multitudes of wicked, unmerciful, blood-thirsty men banded together;
and Friends in some places became great succourers to some
of the distressed English that had their houses burnt,
and were themselves driven out of their places, being stripped of their substance;
and a remarkable thing never to be forgotten was,
that they that were in government then seemed to favour us,
and endeavour to preserve Friends.
But notwithstanding all endeavours used, Friends sustained great losses,
and went through many perils by the outrageous rabble and
plunderers of the country besides the hardships by the army:
so that many lost most of their visible substance, and some were stripped naked,
and their houses and dwellings were set on fire over their heads,
and burnt to the ground, and their lives were in such danger,
that it seemed almost impossible that they should be preserved;
yet in the midst of such lamentable exercises,
the Lord`'s eminent hand of deliverance wonderfully
appeared to their great admiration and comfort.

In the Third month, this year (1689) accounts were sent up to the national meeting,
of the sufferings of Friends in several parts of the nation,
by robberies and spoils by soldiers and other people,
and the losses sustained by Friends of the province
of Leinster appeared to be above 900£.

Hereupon Friends made application to king James, who received them kindly,
and promised that he would take a particular care that they should be protected.

Notwithstanding it was with great hazard of their lives
that Friends from various parts came to the national meeting;
yet such at that time was their zeal for the Lord`'s service,
their faith and confidence in his providential care,
and their fervent desire of renewed edification,
that all the frightful commotions and threatening dangers of those days,
could not present their keeping up this and other meetings.

The national meeting was now pretty much taken up in considering
the distressed condition of their brethren through the nation,
and ordering convenient supplies.

At the next half-year`'s meeting in the Ninth month,
it appeared that the losses of Friends being still continued and increased,
those of the Friends of the provinces of Leinster
and Munster amounted to above 7,000£ sterling;
and in the year 1692,
it was computed that the losses of Friends throughout
the nation amounted in the whole to 1000,000£.

Now the Friends of the Meeting for sufferings in London,
sympathizing with their brethren here, did signify their readiness to assist them;
to which the half-year`'s meeting returned answer, acknowledging their tender care,
however at present they rather chose to decline the acceptance of their friendly offer,
the several provinces being as yet able to help one another.
However Friends here did afterwards accept of the benevolence of the brethren in England,
and in the year 1692,
they drew for six hundred pounds towards helping
Friends here reduced by the late calamitous times,
besides one hundred and fifty pounds remitted from London to Ulster,
and the sum of one thousand and sixty pounds more was sent for this purpose from London,
which in the year 1692, was ordered to be distributed proportionally to each province,
and a letter was sent to the Meeting for sufferings in London,
acknowledging their acceptance hereof,
but desiring that a full stop should be put to their sending any more.
Thus in those calamitous times were Friends very nearly united in affection;
and even from the Friends of Barbados there was 100£ sent
for the relief of Friends here on this occasion.
This year (1689) king James landing in the South, and coming up to Dublin,
the Protestants came to be a little quieter, and better settled in their minds,
nor so fearful of a massacre as formerly;
but still great havoc was made upon the stock of Englishmen, their cattle,
etc. being mostly taken or killed,
oftentimes more on purpose for destruction than for need;
and Friends underwent those abuses in common with other Protestants.
Here follows a particular account of the sufferings
and preservation of Friends in those days.

[.numbered-group]
====

[.numbered]
1+++.+++ At the town of Cavan (a place that lay open to both the armies,
and to the cruelty of the wicked rabble),
several Friends kept their places and dwellings, and held their usual meetings,
and though sometimes in skirmishes between the two armies many were slain,
yet Friends`' lives were wonderfully preserved,
though in their outward substances they were spoiled and stripped,
and at last commanded by the chief officer of the Irish army to depart,
and their houses were burnt.

[.numbered]
2+++.+++ At Old Castle, a place liable to the like perils, a few Friends dwelt,
who kept up their little meetings,
(which belonged to Cavan monthly meeting) and continued there;
their lives were also wonderfully preserved.

[.numbered]
3+++.+++ Near Charlemont, in the county of Tyrone,
Friends thereabouts generally kept their places, and particularly John Whiteside,
whose family wonderfully escaped the hands of cruelty with their lives,
being in imminent danger often by the Rapparees, and dwelling between two garrisons,
one English and the other Irish, who had hot disputes,
killing each other at his very house; and once there were seven hundred Irish,
to sixty English and French by computation; one of his out-houses was burnt,
and he and his son lying sick in another so near,
that it was admirable both it and they were not burnt;
and yet the Irish were forced to withdraw, who plundered Friends and burnt their houses.

[.numbered]
4+++.+++ One Thomas Greer, a Friend,
lost his life by a shot made into his mother`'s house in the night,
by a parcel of Rapparees coming to rob the house, as was supposed;
and Friends of Ulster have left this testimony concerning the said Thomas Greer,
that he was an honest friend, and zealous for truth.

[.numbered]
5+++.+++ Near Edenderry (an open place much exposed to the Rapparees)
Friends were greatly spoiled in their flocks and stocks,
and outward substance, but their lives were wonderfully preserved,
though the bloody ravenous Rapparees broke in upon the town one night,
and burnt part of it, and killed some of the inhabitants.

[.numbered]
6+++.+++ At and near Rossenallis,
in the Queen`'s county (a place that lay open to the like cruel sort of men),
William Edmundson and several other Friends kept their places;
though under great exercises, and troubles of various sorts,
and perils too tedious here to mention;
till such time as a great party of Rapparees came in the night to said William`'s house,
he and his family being in bed, and with great violence fell upon his house,
and several other houses thereabouts, and set his house on fire over his head,
firing several volleys of shot in at the windows;
and took himself and his two sons bare-legged and bare-headed,
and not so much other clothes as to save their bodies from the cold,
and hurried them that night through bushes and bogs, mire and water, up to their knees,
in cold weather, being the latter end of the Ninth month, about five or six miles,
to a wood, where William Edmundson was sentenced to be shot to death,
and his two sons to be hanged; and yet several of them owned that he was an honest man,
for he had often exerted himself to prevent men of their
party from being wronged and abused by the other,
and some times with the hazard of his own life among the English soldiers;
notwithstanding which they hoodwinked his sons to hang them,
and having prepared two firelocks to shoot him, they hoodwinked him also;
but William told them they needed not, for he could look them in the faces,
and was not afraid to die.

Now all things being prepared to effect their purpose,
they were divided among themselves, and another party came in,
who rescued them all three from those that were going to execute them,
and took them in a hungry cold condition to Athlone, where colonel Grace was governor;
and the people having had notice of their coming,
thousands of the worst sort of the Irish were gathered in the great street of that town,
and one Nugent, high-sheriff of that county animated them,
so that it was a wonder that both William and his sons were not slain;
but in the interim it so happened that an officer, and a goodly person of great presence,
thrust through the crowd of that rabble, and came to William,
who was wrapped about with a piece of an old blanket, asking him how he did;
and then turned to the rabble, telling them he knew William to be an honest man,
speaking it several times over, with some other words in his favour,
which quashed the rage of both sheriff and rabble:
thus the Lord provided help in great straits and perils;
then the said William and his sons were taken to the castle,
where the governor and many of the field and chief
officers of the Irish army were met in council,
and there were examined; and when they understood the state of the case,
there seemed to be a sorrow among them for the whole action, and the governor,
who had been formerly acquainted with the said William, stood up in a reverend manner,
and said with tears in his eyes, that he was sorry to see him there in that condition,
and if he had the Rapparees that burnt his house, he would cause them to be hanged.

At this time John Clibborn hearing of the distress of W. E. went to visit him,
and supplied him with necessaries; and afterwards,
upon giving security for the said William Edmundson,
prevailed on the governor to let him and his sons go with him to his house at the Moate;
and in a little time after they were set at liberty.

[.numbered]
7+++.+++ At Moate Granoge, John Clibborn aforesaid,
at whose house a meeting was settled by turn, kept his place long in much danger,
and so did most Friends of that meeting, which they still kept up in great difficulty,
it lying but fix miles from Athlone, then a chief Irish garrison,
and a noted place of refuge,
from which place did often scout parties that made great spoil upon the country,
and whereunto the bloody Rapparees usually led such English as they caught,
and carried from their own houses,
whom they were not permitted barbarously to murder as they had done many.
While the said John Clibborn could possibly keep his house, it was open to all,
and a succour to many, both Friends and others,
and in times of great skirmishes and slaughter he
did not flee till at length most hardly used,
plundered and quite spoiled in his outward substance.
He was taken by the hair of his head by the Rapparees,
who plundered his house in the night, threatening to cut his head off;
and at last he and other Friends were driven from their places,
and their houses were burnt.

[.numbered]
8+++.+++ Anthony Robinson and John Miller, dwelling three miles from Athlone,
had their houses plundered by the Irish,
and afterwards they and their families were threatened to be murdered;
had not an Irish justice of peace`'s wife, a near neighbour, appeared for them,
and took them in till the party was so insolent, and ready to break in,
that she counted she could not save them, upon which, running to them,
she desired them to escape with their lives if they could,
and conveyed them into her garden,
and from there they made hard shift to get into a wood hard by,
and there hid themselves some days and nights in a distressed condition,
sought for and hunted by the blood-thirsty Irish Rapparees,
but their lives were miraculously preserved,
and with great difficulty they got to the aforesaid John Clibborn`'s house at the Moate.

[.numbered]
9+++.+++ Mountmellick and Montrath,
two country unwalled towns (where two considerable meetings of Friends have been settled),
by reason of their bordering upon the bogs and mountains,
often had great store of the bloody ravenous Rapparees haunting them;
and being places of little or no defence,
Friends that dwelt in them sustained a large share
of the many hardships of the calamitous times,
and were greatly exercised under a concern both for their families and neighbours,
still keeping up their meetings with an eye to the Lord,
who did not leave nor forsake his people in their many trials,
but wonderfully provided for them;
so that it is to be admired how their little provision for their families held out,
considering how their houses were filled with people,
and many alarms came from the Irish, threatening to destroy those places,
and kill all the English.

[.numbered]
10+++.+++ Cloncourse, a lonesome place, where Christopher Raper dwelt,
having some walls of defence, and a small English garrison of soldiers being there,
was a little shelter to a small number of Friends who dwelt near it,
and used to meet by turns in that place, who suffered great hardships,
having lost most of what outward substance they had, and provisions being scanty,
were visited with a pestilential fever, and they were greatly straitened for room.

[.numbered]
11+++.+++ James Hutchinson dwelt at Knockballymagher, near Cloncourse,
and kept his place till a party of Rapparees, with some of the Irish standing army,
came in the daytime, plundered and burnt his house, took him,
and a few English tenants of his, prisoners,
forcing him over the Shannon about fifteen miles, and there, treated him very coarsely,
and compelled him to ransom his life, and then let him go in great hazards (by the way,
several English, both Friends and others, met with such like usage in those times).
His house had been of great use to the English.

[.numbered]
12+++.+++ Gershon Boat, dwelling at Borrisalcagh, remote from Friends,
and ten miles from any meeting, in a place of some strength, suffered many hardships,
and escaped many dangers, both at home, and on the road going to meetings;
his house being often set upon by the Irish, both of the army and tories,
but was wonderfully delivered out of their hands, and many English families,
both priests and others, were succoured there,
and helped on their way (when coming from about the river Shannon,
and going to Cashel and Clonmel) who had been much spoiled
and stripped in the Irish quarters where they dwelt:
kept his place till general Dayly placed a garrison at his house or castle,
and then with great difficulty and danger removed his family to Montrath aforesaid,
to live or die with Friends, times looking very dismal.

====

These particulars may show the eminent providential hand of the Lord over Friends,
and his care and kindness to preserve them in the midst of such great perils,
and many more might be instanced;
and though in those times many of the English neighbours
fell by the hands of those bloody murderers,
yet we know but of four that we could own to be of our society
in all the nation that fell by the hands of cruelty,
and two of them too forwardly ventured their lives when they were lost.
And besides all this, at the return of the armies to winter-quarters,
the country was filled with violent sickness, which took away many of all sorts;
and several that were driven away from their habitations,
and had lost most of their substance,
though they yet had left wherewithal to support nature for the present,
seemed to grieve at their losses and low estates, and so languished and died;
which Friends were greatly supported over, having an eye to the Lord,
who not only gives but takes, or allows to be taken away.
Now it pleased the Lord in mercy (and for a remnant`'s
sake no doubt) to shorten those times of great exercises,
that they were mostly ended in less than three years;
and Friends generally were low in their minds, and their hearts open one to another,
so that those who had something left,
were willing to communicate to those that were in need,
and Friends that were driven from their dwellings did generally return to their places;
and the national men`'s meeting took care that in every quarter Friends should be supplied
for the present with such necessaries as time and their abilities did afford;
and great care was taken in Friends settling,
that they might settle near together for the benefit of meetings to serve the Lord.

And it is remarkable that Friends meetings were preserved peaceable,
and that they kept their meetings according to the usual manner for the worship of God,
without much disturbance from either party,
as also their men and women`'s meetings for church discipline, both monthly, provincial,
and national meetings;
though many times Friends went to them in great perils by reason of the Rapparees,
who in many places waylaid people to rob and murder them;
and the Lord was pleased to accompany them in their
meetings with his glorious heavenly presence;^
footnote:[The words of Thomas Wight.]
and truth gained ground,
and Friends came more in esteem than formerly in the minds of many,
both rulers and people, through their innocent wise deportment in the fear of God.

William the Third having been proclaimed king of England, France, and Ireland,
came over this year, 1690; and,
having routed king James`'s forces at the battle of the Boyne,
became the happy instrument of delivering this kingdom from
the impending danger of popery and arbitrary power,
and of establishing liberty of conscience by law.

It is true that the people called Quakers did enjoy the liberty of holding
their meetings for the worship of God according to their consciences,
during the presence of king James in Ireland, as well as,
that their brethren in England had been by him set at liberty from their imprisonment,
and that king James on that occasion did declare,
that it was always his principle that conscience ought not to be forced,
but that all men ought to have the liberty of their consciences;^
footnote:[[.book-title]#Sewel`'s History of the Quakers, Vol.
2,# page 439.]
however, as Sewel observes,
"`perhaps that prince did not consider that if such a general liberty had been procured,
he should not have been able to have made it continue longer
than the popish clergy would have thought it convenient;
and though the king`'s intention might really have been sincere,
yet it is likely it might have been thwarted,
though he might have been willing it should have been otherwise.
And time has shown that king James was not to be the happy instrument
of settling liberty of conscience upon a lasting foundation,
but that this work was reserved for that great prince, king William,
who being born in a country where force upon conscience was abrogated,
when a Protestant government was settled there,
now also introduced the like Christian liberty in England.`"^
footnote:[[.book-title]#Sewel, Vol.
2,# page 439.]

This year (1690) died George Gregson, at his house in Lisnegarvy in the county of Antrim.
He was born a Papist, in Lancashire, as I am assured, but being convinced of truth,
continued faithful in his testimony for the same,
patiently bearing the false and malicious reports of wicked and envious men,
he being from the time of his convincement, the butt of their hatred and envy;
but he was valiant and undaunted in his testimony,
choosing rather to suffer affliction with the people of God,
than to enjoy the pleasures of sin for a season,
looking at the recompense of reward and yielding obedience to the Lord`'s power,
whereby he was enabled to declare unto others what God had done for his soul,
and his ministry was effectual to the convincing of many of the evil of their ways,
and manifesting unto them the way of life and salvation.
He was endowed with a great gift of understanding as well as utterance.
He was particularly concerned for the youth, and the newly convinced,
and for the children of believing parents,
that they might not content themselves with a bare profession of
the truth which they had received by education and tradition,
but that they might come to witness the washing of regeneration,
and the being renewed thereby.
He travelled in the work of the ministry in this nation, as also in England,
and suffered imprisonment and the spoiling of his goods, for the truth`'s sake.
He retained, in old age, his zeal for God and love to the brethren,
which he manifested by leaving a considerable part of his outward
substance to several meetings of Friends in this nation,
and also to Friends in Lancashire.

This year also died, that eminent and faithful servant of the Lord, John Burnyeat,
who was born in Cumberland,
and was brought forth early in the day of the breaking
forth of God`'s light and power in our age,
which many waited for, and were in readiness to receive, with joy and gladness of heart;
among whom was this our friend, whose convincement and spiritual exercise thereupon,
as he has himself described it in his own journal, I shall here present the reader with,
somewhat abridged, but his own words retained:

[.embedded-content-document]
--

In the year 1653,
it pleased the Lord to send his faithful servant
George Fox and others into the North parts of England,
and by the means of their ministry to discover the
right path of life unto thousands that were in error,
seeking the Lord, but not knowing where to find him, although he was not far from us;
namely,
by directing us unto the true light and appearance
of Christ Jesus our Saviour in our own hearts,
that we might come to know him and the glory of the Father,
through him in his appearance, and so come to believe in him with the heart,
and with the mouth confess him unto salvation;
and God by this the light of his blessed Son, which he had enlightened me with,
let me see the body of death and power of sin which reigned in me,
and brought me to feel the guilt of it upon my conscience,
so that he made me as it were to possess the sins of my youth.
And now all that I had built for several years;
and particularly my high profession and conceit of an imputative righteousness,
and that though I lived in the act of sin, the guilt of it should not be charged upon me,
but imputed to Christ, and his righteousness imputed to me; was now,
by the shinings of the discovering light,
seen to be but a Babel-tower which God brought confusion upon;
a presumption and invention of my own; or but like Adam`'s fig-leaved apron,
in which he could not abide God`'s coming.
I then came to see that the guilt of sin remained while the body of death remained,
and led into the act of sin:
then began the warfare of true striving to enter the kingdom;
then Paul`'s state was seen, wherein to will was present, but to do,
many times power was lacking; then confusion, amazement, horror, and distress beset me.

O the poverty and need that my soul saw itself in,
through the springings of the discovering light,
which also manifested the exceeding sinfulness of sin,
and the load and burden of it became exceeding grievous,
and all the pleasure of it was taken away from me and many more in that day;
and then we began to mourn for a Saviour, and cry for a helper and healer;
for the day of the Lord that made desolate had overtaken us,
and the fire and sword that Christ brings upon earth, by which he takes away peace,
had reached unto us.
We often assembled together, as the Lord`'s messengers had exhorted us,
and minded the light of Christ in our hearts and what that discovered,
and through its assistance warred and watched against the evil seen therein,
and according to that understanding received, waited therein upon the Lord,
to see what he would further manifest,
with a holy resolution to obey his will so far as we were able, whatsoever it cost us.
We valued not the world, nor any glory nor pleasure therein,
in comparison of our soul`'s redemption from that horror and terror we were in,
under the indignation of the Lord, because of the guilt of sin that was upon us;
and so being given up to bear the indignation of the Lord, because we had sinned,
we endeavoured to wait until it would he over,
and the Lord in mercy would blot out the guilt which occasioned wrath,
and sprinkle our hearts from an evil conscience, and wash us with pure water,
that we might draw near with a pure heart, in the full assurance of faith,
as the Christians of old did (Heb. 10:22):
and waiting in the way of the Lord`'s judgments, we began to learn righteousness,
and strongly to desire to walk therein,
and could no longer be satisfied with a talk thereof.

And when we were in our deep fears,
and our minds not well acquainted with either right striving out of self,
in the light and seed of life that does prevail and give the entrance,
or true waiting or standing still, out of our own thoughts,
willings and runnings which do not obtain,
the Lord sent his servants who had learned of him, to direct us in what to wait,
and how to stand still, out of our own thoughts and self-strivings,
in the light that did discover, and dwell in the judgment that we received therein;
and by them our understandings were informed,
and we got to some degree of stayedness in our minds,
which before had been as the troubled sea; and a hope began to appear in us,
and we met together often,
and waited to see the salvation of God which we had often heard of,
that he would work by his own power;
and after we had met together for some time as we had seasons and opportunities,
and also sought the Lord with travailing spirits both night and day,
when we were at our callings and upon our beds,
being in our assemblies exercised in the living judgment
that sprung in the light in our souls,
and looking for the salvation of God,
the wonderful power from on high was revealed among us,
and many hearts reached therewith, and melted and broken;
and great dread and trembling fell upon many,
and the very chains of death were broken thereby,
and the promises of the Lord spoken of by Isaiah the prophet, 49:9 and 42:7 and 61:1-3,
were fulfilled unto many, and a heavenly gladness entered the hearts of many,
who in the joy of their hearts broke forth in praises unto the Lord.
The same Comforter our blessed Lord had promised, John 14, being now come and received,
did teach us to know the Father and the Son.

Then were our hearts inclined to hearken unto the Lord, and our ears,
which he had opened to hear, were bent to hear what the Spirit`'s teaching was,
and what he said unto the church, who was the chief shepherd and bishop of the soul,
and thus were we gathered into a right gospel exercise and gospel worship;
and worshipped God who is a Spirit,
in the spirit received from him according to Christ`'s appointment, John 4:24,
and then we came to see over all the worships in the world,
which were set up either by imitation or man`'s invention,
and saw it to be in vain to worship God and teach for doctrines the commandments of men,
as our Lord had said, Matt. 15:9,
and therefore were we constrained to withdraw from them,
and also many of us to go and bear witness against
them in their invented and traditional worships,
where they were ignorant of the life and power of God;
and growing into experience of the goodness of the Lord, and of the sweetness, glory,
and excellency of his power in our assemblies,
we grew in strength and zeal for our meetings more and more,
and valued the benefit thereof more than any wordly gain: and thus continuing,
we grew more and more into an understanding of divine things and heavenly mysteries,
through the openings of the power that was daily among us,
and wrought sweetly in our hearts, which still united us more and more unto God,
and knit us together in the perfect bond of love, of fellowship and membership;
so that we became a body compact, made up of many members,
whereof Christ himself became the head, who was with us and did rule over us,
and so further gave gifts unto us, by which we came to be enlarged and further opened,
that we might answer the end for which he had raised us up,
and so far blessed and sanctified us through his word that dwelt in our souls;
and many through the favour of God grew in their gifts, and had their mouths opened,
and became instruments in the Lord`'s hand to bear witness unto
the world of the day of the Lord that was broken forth again,
even of the great and notable day that Joel prophesied of, and Peter bore witness unto.

--

So far J. Burnyeat concerned himself:
let us now hear what testimony the brethren have given of him.

[.embedded-content-document.testimony]
--

He was (say they) a man of an excellent spirit and deep experience
in the things of God and mysteries of his heavenly kingdom,
which were abundantly made manifest unto him,
and it was his delight to be meditating therein,
whereby his experience was daily increased unto the last.
He was always careful to wait for the motion of the word, and to keep close to it,
whereby he grew in his gift.
He was an early comer to meetings, and a diligent waiter therein.
Many times he would sit a pretty while in silence (not being forward to speak),
reverently waiting upon the openings of the heavenly
life (like the good householder spoken of),
to bring forth of his treasury things both new and old;
and indeed he was a blessed instrument in the hand of the
Lord for the convincement and conversion of many.
He was deep and large in his gift,
administering something that was suitable to every state; in judgment sound,
free in utterance, zealous for holiness, severe against unsound and dividing spirits,
most tender to penitents and returning prodigals, affectionate to the brethren;
of a grave and steady temper, yet sweet; hardy in his constitution,
unwearied and undaunted in mind; a skillful marksman, whose bow abode in strength,
and wisdom was given him to direct his arrows to the very mark;
so that the sturdy were wounded, the meek were comforted,
and the tender in spirit refreshed; and yet, although he was thus eminently gifted,
he would condescend to the weak capacities of all, to reach to the good in all.

He was not without honour, even in his own country;
for when at any time he came to Cumberland, where he was born and educated,
his neighbours would abundantly flock to the meeting to hear him;
yet he was far from glorying in his gift, or desiring to be popular,
but would rather restrain such who would applaud him, having self in no reputation.
He did greatly delight to read the holy scriptures, and often advised Friends,
especially the youth,
to read them and other books treating of the true principles of the Christian religion,
that none might be ignorant thereof.
He was of a grave and becoming behaviour;
his blamless deportment and conduct preached wherever he came.
He would often visit the sick and those that were in distress or affliction,
as well the poor as the rich,
and would freely administer of his outward substance to those that stood in need of it,
as well as spiritual comfort and refreshment.

He spent his time chiefly, if not altogether, in the Lord`'s work and service,
visiting Friends up and down in England, Wales, Scotland, Barbados, New England,
Long and Rhode Island, New York, and New Jersey;
but in Ireland in a more peculiar manner, both at his first entrance upon his ministry,
and also of later years: for he married,
and chiefly resided in Ireland about seven years before his decease.
He was very valiant for truth, not only in preaching, but suffering for it; and at first,
he with many faithful brethren, underwent many dangers and hardships,
Ireland not being fully inhabited, so that he was many times exposed to great dangers,
by waters, cold, hunger, and in prison often,
besides other great abuses he received for his testimony`'s sake.

The like may be said concerning his travels in New England,
with the islands and wilderness places where he accompanied G. Fox,
and was wonderfully preserved through all those perils.
He was a valiant in Israel, who never shrank in the times of the greatest trials,
sufferings, and storms of persecution; and whereas in the year 1688,
his wife being deceased, he had intended to have returned from Ireland to Cumberland,
the wars and troubles approaching, he had not freedom in himself to go,
but voluntarily gave himself up to stay here with
Friends to take part of what sufferings might happen;
and indeed he was a blessed instrument in the hand of the Lord for the strengthening
and comforting of his people in those suffering and calamitous times.
It is particularly recorded of him, that in the year 1690,
in his visit to Friends meetings, at a public province-meeting,
he delivered the following remarkable prophetic warning:
"`It is now a time of great trial upon you in losing what you have:
but the time will come when you will be as greatly tried
with getting wealth;`" which was soon after accomplished.

Besides a journal of his life he also published some
small controversial pieces annexed thereunto,
concerning the resurrection, imputative righteousness, perfection, tithes,
the call of the ministry, baptism, the supper, etc.
He laid down his head in peace with God and love to his people,
and good-will to all mankind, in the fifty-ninth year of his age,
and was buried at New-Garden, being accompanied by many ancient Friends and others,
where his eminent and faithful services were commemorated by William Edmundson.

--
