== Chapter IV.

[.chapter-subtitle--blurb]
From the registering of Friends Meetinghouses, in the year 1719,
to the year 1751.--The Church in danger from a spirit of libertinism and luke-warmness,
in the time of outward peace and freedom.--The solemn
affirmation first granted to Friends of England,
through the joint solicitation of Friends of that and this nation,
and afterwards extended to Friends of Ireland.--Various Visits to Friends and Strangers,
for the promotion of the Christian Doctrine and Discipline.--Summary of the lives,
characters,
and spiritual exercises of several of their eminent Ministers and Elders.--Chronological
Tables of the first Settlement of the several Meetings in Ireland,
and of the Visits of ministering Friends: as also,
a summary view of the Sufferings of this People, from the beginning to the present Year.

It is observable, that in this time of outward peace,
and freedom from sufferings of various kinds (1720),
to which Friends formerly had been exposed,
cause was given for complaints at the Third month national meeting, 1720,
of the breach of minutes,
through the prevalence of a loose libertine spirit among many of our youth,
and a careless, sleepy, slothful spirit, with respect to religious duties,
among some more aged;
and particularly about this time (1721) Friends were greatly
afflicted on an observation of the failings of some,
in relation to their trading and dealing beyond the bounds of truth and moderation,
to the invading the property of others, and obstruction of the progress of truth;
and complaint was made of the negligence of several parents in
educating their children in honest and suitable employments,
of pride in apparel, and the high living of some above their circumstances,
to the dishonour of truth, their own hurt, and the trouble of the church.
Now in order to stop the progress of these evils,
a provisional visit was made to the several monthly meetings,
in the provinces of Leinster and Ulster; and likewise a certain paper entitled, [.book-title]#A Brief and Serious Warning to Such as are Concerned in Commerce and Trading,
Who go Under the Profession of Truth, to Keep Within the Bounds Thereof,
in Righteousness, Justice, and Honesty, to all Men,# written by Ambrose Rigge,
was now reprinted for a general service, which was as follows:

[.embedded-content-document.paper]
--

Many days and months, yes, some years, has my life been oppressed, and my spirit grieved,
to see and hear of the uneven walking of many, who have a name to live,
and profess the knowledge of God in words, yes,
and also of some who have tasted of the good word of God,
and have been made partakers of the powers of the world to come,
and have received the heavenly gift and grace of God, which teaches all who walk in it,
to deny all ungodliness and worldly lusts, and to live soberly, honestly,
and righteously in this present world;
whose faithfulness (with great reason) has been expected
to God in things of the highest concern,
and to have walked as lights in the world, and in all faithfulness both to God and man,
to have stood as living monuments of the mercies of the Lord,
letting their lights so shine before men, that they might see their good works,
both in spiritual and temporal concerns;
and so might have honoured and glorified God in their day and generation,
and have convinced or confounded gainsayers,
putting to silence the ignorance of foolish men; whereby the worthy name of the Lord,
by which they have been called, might have been renowned through the earth;
and his precious truth and glory spread to the ends of it;
that many through the beholding their good and exemplary conduct in Christ,
coupled with the holy fear of God,
might have desired to lay hold of the skirt of a Christian indeed,
whose praise is not of men, but of God.

These are the fruits which we have laboured and travailed for,
through many and great tribulations, that many might be turned to righteousness,
and that the knowledge of the power and glory of the Lord might cover the earth,
even as the waters do the sea.
This was, and is, our only end and design, which, blessed be the Lord,
many are witnesses of, and established in, to our abundant joy and comfort.
But there are some among us, who have not walked humbly with the Lord,
as he has required, nor kept in that low state; neither inwardly nor outwardly,
which becomes such who are travelling up to Zion, with their faces thitherward;
but have launched from the rock which is firm and sure,
into the great sea of troubles and uncertainty, where some have been drowned,
others hardly escaping, and many yet labouring for the shore,
with little hopes of coming at it;
who have not only brought themselves in danger of suffering shipwreck,
but have drawn in others, and have endangered them also;
which has opened the mouths of the enemies of Zion`'s welfare,
to blaspheme his great and glorious name;
and has eclipsed the lustre of the glorious Sun of Righteousness,
both in city and in country: this is a crying evil, and ought not to go unreproved,
and that with a severe countenance; for God is angry with it,
and will assuredly punish it.

Many have got credit upon the account of truth, because at the beginning it did,
and does still, lead all, who were and are faithful to it, to faithfulness and truth,
even in the unrighteous mammon, and to let their yes be yes, and their no be no,
even between man and man in outward things;
so that many would have credited one that was called a Quaker with much,
and many I believe did merely upon that account, some whereof, I doubt,
have just cause to repent of it already:
but if truth and righteousness had been lived in by all who profess it,
there had been no such occasion given:
for they who still retain their integrity to the truth and life of righteousness manifested,
can live with a cup of water, and a morsel of bread in a cottage,
before they can hazard other men`'s estates to advance their own.
Such are not forward to borrow, nor to complain in need;
for their eye and trust is to the Lord their preserver and upholder,
and he has continued the little meal in the barrel,
and the oil in the cruse has not failed to such, till God has sent further help;
this is certainly known to a remnant at this day, "`who have coveted no man`'s silver,
gold, or apparel, but have and do labour with their hands night and day,
that the gospel may be without charge.`"

It is so far below the nobility of Christianity,
that it is short of common civility and honest society among men,
to twist into men`'s estates,
and borrow upon the truth`'s credit (gained by the just and upright dealing of
the faithful) more than they certainly know their own estates are like to answer;
and with what they borrow, reach after great things in the world,
appearing to men to be what in the sight of God and truth they are not;
seeking to compass great gain to themselves,
whereby to make themselves or children rich or great in the world:
this I testify for the Lord God is deceit and hypocrisy,
and will be blasted with the breath of his mouth; and we have seen it blasted already.

And that estate that is got either with the rending,
or with the hazard of rending another man`'s, is neither honestly got,
nor can be blessed in the possession: for he that borrows money of another,
if the money lent be either the lender`'s proper estate, or part of it,
or orphan`'s money that he is entrusted with, or widow`'s, or some such,
who would not let it go, but upon certain good security,
and to have the valuable consideration of its improvement; and the borrower,
though he has little or no real or personal estate of his own, but has got some credit,
either as he is a professor of the truth, or otherwise,
and has (it may be) a little house, and a small trade,
it may be enough to a low and contented mind; but then the enemy gets in,
and works in his mind, and he begins to think of a higher trade and a finer house,
and to live more at ease and pleasure in the world,
and then contrives how he may borrow of this and the other;
and when accomplished according to his desire, then he begins to undertake great things,
and get into a fine house, and gather rich furniture and goods together,
launching presently into the strong torrent of a great trade,
and then makes a great show, beyond what really he is, which is dishonesty.
And if he accomplish his intended purpose, to raise himself in the world,
it is with the hazard, at least, of other men`'s ruin, which is unjust;
but if he falls short of his expectation, as commonly such do,
then he does not only ruin others, but himself also,
and brings a great reproach upon the blessed truth he professes, which is worse than all;
and this has already been manifested in a great measure, and by sad experience witnessed.

But the honest, upright, heart and mind knows how to be abased, as well as how to abound,
having learned content in all states and conditions;
a small cottage and a little trade is sufficient to that mind,
and it never lacks what is sufficient: for He that clothes the lilies,
and feeds the ravens, cares for all who trust in him, as it is at this day witnessed,
praises to God on high; and that man has no glory in, nor mind out after,
"`superfluous or needless, rich hangings, costly furniture, fine tables, great treats,
curious beds, vessels of silver, or vessels of gold,
the very possession of which creates envy,`" as said the ancient Christian,
// lint-disable invalid-characters "æ"
Clemens Alexandrinus. Pædag. lib. 2. cap. 3. p. 160-161.

The way to be rich and happy in this world is first to learn righteousness;
for such were never forsaken in any age, nor their seed begged bread.
And charge all parents of children, that they keep their children low and plain in food,
drink, and apparel, and everything else,
and in due subjection to all just and reasonable commands;
and let them not appear above the real estates of their parents,
nor get up in pride and high things though their parents have plentiful estates;
for that is of dangerous consequence to their future happiness.
And let all who profess the truth, both young and old, rich and poor,
see that they walk according to the rule and discipline of the gospel,
in all godly conduct and honesty,
that none may suffer wrong by them in any matter or thing whatever:
that as the apostle exhorted, "`they may owe nothing to any man, but to love one another;
for love out of a pure heart is the fulfilling of the law:`"
which law commands to do justly to all men:
and he that has but little, let him live according to that little,
and appear to be what in truth he is; for above all God abhors the hypocrite,
and he that makes haste to be rich, falls into snares, temptations,
and many noisome and hurtful lusts (1 Tim. 6:9), which drown many in perdition;
"`and the love of money is the root of all evil, which while some have lusted after,
they have erred from the faith, and compassed themselves about with many sorrows.`"
(1 Tim. 6:10)

For preventing this growing evil for the time to come,
let such by faithful Friends be exhorted, who either live without due care,
spending above what they are able to pay for, or run into great trades,
beyond what they can in honesty and truth manage,
and let them be tenderly admonished of such their undertakings;
this will not offend the lowly, upright mind; neither will the honest-minded,
who through a temptation may be drawn into such a snare and danger,
take any occasion to stumble, because his deeds are brought to light.
And if after mature deliberation,
any are manifested to be run into any danger of falling,
or pulling others down with them, let them be faithfully dealt with in time,
before hope of recovery be lost, by honest, faithful Friends,
who are clear of such things themselves,
and be admonished to pay what they have borrowed, faithfully and in due time,
and be content with their own,
and to labour with their own hands in the thing that is honest,
that they may have enough to give to him that needs,
knowing that it is more blessed to give than to receive (Acts 22:35). And if they hear,
and are thereby recovered, you will not count your labour lost; but if they be high,
and refuse admonition, it is a manifest sign all is not well.
Let such be admonished again by more Friends, and warned of the danger before them;
and if they still refuse and reject counsel and admonition,
then lay it before the meeting concerned about truth`'s affairs,
to which they do be long; and if they refuse to hear them,
then let a testimony go forth against such their proceedings and under takings,
as not being agreeable to the truth, nor the testimony of a good conscience,
neither in the sight of God nor man; this will be a tenor to evil-doers of this kind,
and a praise, encouragement, and refreshment, to them who do well,
and nothing will be lost that is worth saving, by this care: for he that does truth,
whether in spiritual or temporal matters, will willingly bring his deeds to light,
that they may be manifested to all, that they are wrought in God.

These things lay weightily upon me, and I may truly say, in the light of God,
I wrote them in a great cross to my own will, for I delight not, no,
my soul is bowed down, at the occasion of writing such things; but there is no remedy,
the name of the Lord has been, and is likely to be greatly dishonoured,
if things of this nature be not stopped, or prevented for time to come:
therefore I beseech you all, who have the weight and sense of these things upon you,
let some speedy and effectual course be taken to prevent what possibly we may,
both in this and all other things, that may any way cloud the glory of that sun,
which is risen among us; and make this public,
and send it abroad to be read in true fear and reverence,
and let all concerned be faithfully and plainly warned, without respect of persons,
by faithful Friends, who have the care of God`'s glory,
and his church`'s peace and prosperity upon them:
so will the majesty and glory of God shine upon your heads,
and you shall be a good savour of life, both in them that are saved,
and in them that are lost.

Written by one who longs to see righteousness exalted, and all deceit confounded.

[.signed-section-signature]
Ambrose Rigge.

[.signed-section-context-close]
Gatton Place, in Surry, the 16th of the Eleventh Month, 1678.

--

This year (1721) several Friends, according to former practice,
by appointment of the national meeting went over to attend the Yearly meeting at London;
and particularly Thomas Wilson,
who not only visited Friends there in the service of the gospel,
but tarried a considerable time at London,
where he joined his assistance to Friends there,
who were soliciting for ease in the solemn affirmation;
and it pleased the Lord to bless their endeavours with success,
the king and parliament granting such an amendment
in the affirmation as made it easy to all Friends,
to their no small comfort and joy;
which laid the foundation for the same indulgence
afterwards granted also to Friends of this nation,
as we shall see in due time.

The form of the first affirmation granted to Friends in England, in the year 1696,
was as follows: "`I A. B. do declare, in the presence of Almighty God,
the witness of the truth of what I say.`"

The form of the affirmation granted this year to Friends of England,
and afterwards to Friends of Ireland, to universal satisfaction, was this: "`I,
A+++.+++ B. do solemnly, sincerely and truly, declare and affirm.`"

In the year 1721 died John Exham of Charleville, having been convinced while a soldier,
about the year 1658, and being faithful, according to his sense of his duty,
he became zealously concerned to visit the small
gatherings of Friends in those early days,
having received a gift in the ministry,
which although somewhat obscured by some natural infirmities,
yet in the exercise thereof, he did oftentimes deliver wholesome and profound truths.

About the year 1667,
he proclaimed repentance and amendment of life through the streets of Cork,
his head being covered with hair-cloth and ashes, for which he suffered imprisonment.
He was concerned in the like exercise in the same city, in the year 1698.

In the year 1710, being the eighty-first of his age, and when almost blind,
he gave a singular instance of the fervour and constancy of his love to the brethren,
by performing a religious visit to the greatest part
of the families of Friends throughout this nation;
in which service it appeared evident to those who were witnesses of it,
that he had a spirit of discerning, for he often times spoke very pertinently,
without having received any information from men,
to the particular conditions of several where he was thus concerned.
He was a man of an innocent life and conduct, just in his dealings, merciful to the poor,
and well beloved by his neighbours and friends,
and seldom missed any opportunity of giving good counsel.
He continued his residence at Charleville through
many difficulties and hazards during the last war.
He was greatly devoted to meditation,
commonly spending many hours in a day in retirement:
was esteemed to have had a prophetic gift,
many particular instances whereof cannot at this distance of time be collected;
but the two following are well attested.

[.numbered-group]
====

[.numbered]
1st. While he was performing the visit to the families above-mentioned,
being in a certain room, he called out and enquired who was there present;
and then told them,
there was among them a youth upon whom the Lord would pour forth his Spirit,
and that he should visit several nations, which was accomplished;
a certain young man then present, having afterwards received a gift in the ministry,
which he exercised to the edification of the churches both at home and abroad.

[.numbered]
2nd. Whereas before the accession of king James II. to the crown,
the earl of Orrery had a great house at Charleville, then a splendid structure,
unto which there was frequently a great resort of company.
At one particular time, when a large company of great persons were there assembled,
spending their time in feasting, mirth, etc.
John Exham had an impulse on his mind to go to the house,
and call the people there met to repentance,
which he accordingly did (a large crowd following him) and denounced the Lord`'s judgments,
and woe, to that great house, and that it should be destroyed,
and become a habitation for the fowls of the air.
Hereupon the earl`'s servants attempted to drive him away;
but the earl commanded them to let the honest man speak.
Having delivered his message, he went away, but in a little time returned back,
and called for the earl, and said to him,
"`Because you have been kind and loving to the servant of the Lord,
the evil shall not be in your days.`"
The event answered the prediction; for the great house above-mentioned,
in the time of the late wars, since the decease of the earl above-named,
was destroyed by fire, and visibly became a habitation for the fowls of the air,
which built their nests in it.

====

The said John Exham died in the ninety-second year of his age,
having been a minister sixty years, and retained his zeal and integrity to the last.

This year (1722) was memorable for the favour shown
by the legislature to Friends of this nation,
in granting them a plain affirmation (in many necessary cases) instead of an oath,
in the following words: "`I, A. B. do solemnly, sincerely,
and truly declare and affirm:`" which was granted for three years,
and to the end of the then next session of parliament.

In the year 1723, being the sixtieth of his age,
and about the twenty-seventh of his ministry, died John Barcroft of Arkill,
near Edenderry.
He was the son of William and Margaret Barcroft, born at Shralegh, near Rosenallis,
in the Queen`'s County, in the year 1664.
He was the first Friend who came to settle near Edenderry after the wars,
to which meeting he did belong, and was very helpful at that time,
to encourage some few families to meet together to worship God,
and became very serviceable in that meeting, which is since become large.

He was religiously inclined from his youth,
a zealous attender of meetings for the worship of Almighty God,
and a diligent waiter therein, whereby he grew in the knowledge of God,
and of the mysteries of his heavenly kingdom; and about the thirty-third year of his age,
it pleased God to call him into the ministry of the word and doctrine;
but being a modest man, he became possessed with great fears,
when first persuaded that the Lord would call him to this work,
both from the various censures of men, to which he must be exposed,
and from his observation of the misconduct of some,
otherwise lively and of large experience in the ministry,
who yet at times did hurt both to themselves and the people,
by sometimes exceeding the bounds of their gifts, and multiplying words without life.
Under these fears and reasonings with flesh and blood, he was greatly exercised,
until the Lord forsook him for a season,
but was afterwards graciously pleased to visit him again,
when he gave up to the heavenly call,
and in great dread uttered a few words in a meeting,
and in process of time be came a diligent and successful labourer for the good of souls,
both in this kingdom and in England;
having visited the meetings of Friends in the provinces of Ulster and Munster, severally,
eleven times in the service of the gospel, to his own soul`'s peace,
and the edification of the churches, and been ten times at the Yearly meeting of London.

His ministry was plain and lively, nor was he forward to appear without real necessity.
He was not slothful in his outward affairs,
but managed them with discretion and prudence; yet was fervent in spirit,
and freely given up to serve the Lord, his church and people,
and preferred the prosperity of Zion as his chief joy.
His conduct among men greatly adorned his profession, being pleasant and cheerful,
yet grave, meek, and humble, preferring others before himself; a peace-maker,
being singularly helpful in composing differences,
a useful helpmate in the government of the church, being gifted for that service,
and at the same time ruling well his own house; a frequent visitor of the sick,
charitable, and given to hospitality.

In the year 1718, being at London, he was under a particular exercise of mind,
from a sense he believed to be given him of the Lord,
of a dreadful day of mortality that was coming upon the inhabitants of England,
and particularly the city of London,
which he was concerned to publish at Devonshire-house meeting, and some other places;
and in the year 1720, at Dublin,
he published a prophetic warning to the inhabitants of Great Britain and Ireland,
to dread the Lord, and turn from the evil of their ways,
before his fury break forth upon them as an over flowing scourge,
setting forth that the measure of the sins of many seems now to be full,
and that the Lord had shown him that the stroke of mortality is near at hand,
and that he will surely visit speedily with a great and heavy scourge,
if not prevented by repentance.

In the first month, in the year 1724, being about the seventy-first of his age,
and forty-seventh of his ministry, died at Hillsborough, Alexander Seaton;
who was born at Cuttlecrags, near Lethinty, in Aberdeen county in Scotland,
about the year 1652.
About the age of seventeen years he was put to the college of the old town of Aberdeen;
and after being there about two years, was some time at the house of Alexander Forbes,
of Achorthies, whose wife was his kinswoman, and they being Friends and exemplary,
it pleased the Lord to open his understanding,
so that he was convinced of the truth in the year 1675.
He was afterwards further informed and confirmed by being
present at a dispute between Robert Barclay and George Keith,
and some students there; and in the year 1676,
he was committed to prison in the tolbooth of Aberdeen, with many more Friends,
and there detained about nineteen months.
In this time his mouth was opened in a living public testimony to the truth,
which he continued to bear afterwards when at liberty,
labouring in the gospel of our Lord and Saviour Jesus Christ,
and being instrumental to turn people from darkness to light,
and from the power of Satan to God: in Scotland, Ireland, and England.

Some time after his marriage, he took up his abode and resided for some years at Glasgow.
A pretty hot persecution then falling on the few Friends that were settled there,
both by the magistrates and a rude multitude of men and women,
who not only beat and abused Friends in their meetings, but, haling them thereout,
abused them in the streets to the danger of their lives, and committed them to prison;
where upon this our friend found himself engaged in mind to dwell at Glasgow,
not only to bear a part of the burden in the heat of that time of persecution,
but also for the strengthening, comforting,
and encouraging his brethren to faithfulness and constancy,
through various tribulations and persecutions;
which had so good an effect that he was instrumental, by the Lord`'s assistance,
to overcome the persecutions,
so that Friends enjoyed their meetings more peaceably than before;
but the people being settled in their empty professions,
without an openness to receive the truth, he was clear to leave the place,
and in the year 1699, he came from Glasgow, with his family, to Ireland,
and settled in the town of Hillborough, in the county of Down.

During all the time of his living there, until he grew infirm,
he duly attended meetings at home, as also the monthly and provincial meetings;
in which he was of good service both in doctrine and discipline, having a large, sound,
and clear gift in the ministry; and although a scholar,
was not much known to be such in his services for the Lord,
not esteeming that learning in comparison of the gift of God,
and the operation of his Holy Spirit; under which he was a jealous, faithful, humble,
and meek labourer in the work of the ministry,
to the informing the understandings of the ignorant,
and to the comfort and encouragement of Zion`'s travellers; prudent, considerate,
and reasonable in offering his gift, powerful in prayer;
in discipline of a deep and solid judgment, often helpful in difficult cases;
a man of good understanding, having been engaged in disputes with several priests,
on various religious subjects, upon which he reasoned with great clearness;
a man of few words in conversation, and ignorant in the things of the world.
He used daily to devote some part of his time to religious retirement,
and adorned the doctrine of our Lord Jesus Christ
by a solid deportment and exemplary conduct.
In the latter part of his time he was very much afflicted with bodily weakness;
which he bore with patience and resignation, and died in great peace and quietness,
having, among many other sweet expressions on his deathbed, declared,
that he had partaken of the earnest of that joy which should never have end.

In the year 1724, and the eighty-fourth of his age, died Thomas Wight,
of the city of Cork.
He was the son of Rice Wight, minister of the town of Bandon,
who was the son of Thomas Wight, who was also minister of the same town,
who came from Guildford, in England.
His father, Rice Wight, was a zealous man in the discharge of his office,
and more devoted and tender in that respect than the generality of the priests,
and very strict in the education of his children,
according to the manner of the church of England.
His son Thomas served a hard apprenticeship with a clothier in Bandon,
and while in his service hearing of a Quakers`' meeting to be held in that neighbourhood,
he went to it out of curiosity; but finding that the people sat silent for a long time,
he began to be very uneasy, and to think within himself,
that as he had heard the Quakers were witches,
he might be bewitched if he should stay longer.
However, he waited a little longer,
until Francis Howgill stood up and uttered these words; "`Before the eye can see,
it must be opened; before the ear can hear, it must be unstopped;
and before the heart can understand, it must be illuminated.`"
These three sentences,
as Francis opened them to the congregation with great clearness and energy,
made a deep impression on his mind, and he became, in a great measure,
convinced of the truth of the doctrine preached; but the prejudice of education,
and the shame and reproach he underwent from his
relations for going to the Quakers`' meeting,
did very much wear off the impression received;
until Edward Burrough came to visit Friends and the
people in the work of the gospel in those parts,
whose preaching was so powerful and reaching to the state of his soul,
and accompanied with such an evidence of truth, that he, with many others,
was no longer able to withstand it; and now he resolved, through divine assistance,
to be faithful, according to the light received,
through all difficulties that might attend;
and indeed he be came as a proverb and a bye-word among his relations and acquaintance,
which he bore with patience, not running into unnecessary disputations,
but rather giving himself up to silence, solitude, and reading the holy Scriptures.
In a short time he betook himself to the plain language, and plainness of apparel,
from a principle of conviction in himself,
upon which account he was rejected by his relations,
and lived for some time with his master, who had a great respect for him,
because of his singular faithfulness and trustiness in his service.

In the year 1670 he married, and in process of time had a numerous family,
whereupon he betook himself to much business, both in the clothing trade,
and in commissions from abroad, and in all probability might, in a short time,
have acquired a considerable share of worldly riches;
but he was stopped in the pursuit hereof by an illumination, as he thought, from heaven,
deeply affecting his mind with a sense to this purpose,
that he could not be heir of two kingdoms.
Hereupon he grew more retired from the world, and the concerns thereof,
and devoted in his mind to the service and promotion of truth,
preferring this before transitory riches; and particularly,
became an able scribe and clerk for the meeting of Cork, and for the province of Munster,
from the year 1680, till his death;
discharging this office from a religious impression on his mind,
and zeal for the good cause.
He was also the person principally concerned in compiling a historical
account of the first rise and progress of truth in this nation;
which he finished in the form of Annals to the year 1700,
and which was the ground-work to the present history.
He was a man of an exemplary life and conduct,
and good conduct in the education of his children, a pattern of plainness,
and a diligent attender of meetings both at home and abroad,
being zealous for the promotion of truth, both in the particular and in the general.
He was seized with an indisposition which proved mortal, in the Ninth month, 1724;
under which he showed great composure of mind, and resignation to the Lord`'s will;
and on his deathbed testified his great satisfaction that he had not
put off the great affair of the salvation of his soul to the last;
signifying that God had sealed his salvation to him:
to the great comfort of those present.

A provincial visit to the several monthly meetings in Leinster (1725) was performed
by Friends nominated from the several parts of that province for this purpose.
In the year 1725, being about the seventy-first of his age,
and forty-fifth of his ministry, died Thomas Wilson, who was born at Soulby,
in the parish of Daker, and county of Cumberland,
and educated according to the manner of the church of England; and, while a youth,
had great hungerings in his soul after righteousness
and the true knowledge of God and Christ;
at which time he was a diligent attender of sermons, and repeater of them,
delighting in these things as religious duties; sometimes, after sermon in the forenoon,
travelling eight miles on foot to hear another in the afternoon;
but the more he sought to hear, the more be found his inward hunger and thirst increased;
and in the time of singing of psalms a thoughtfulness seized him,
that men should be made holy before they could sing to the praise and glory of God,
and his mouth was stopped from singing with them,
through a godly sorrow possessing his heart, with humble prayers to God,
for the knowledge of the way of salvation,
he being now become weary both of the heavy load of sin,
and of the doctrines and worship of men`'s making.

After long travail of soul, the Lord was graciously pleased to make him sensible,
that what was to be known of God was manifested in man;
about which time he went to a meeting of the people called Quakers,
where a friend exhorted to an inward waiting upon the Lord in faith,
to receive power from him over every unclean thought;
by which heavenly power men might glorify and praise the
name of the Lord through the ability of his own free gift.
This affected him greatly, being sensible that this was what he much needed,
being the word of grace, which the apostles of our Lord preached,
and turned the minds of men unto; and great fear and trembling seized him,
so that the table whereon he leaned was shaken,
and he was full of inward cries to this purpose; "`Lord, create in me a clean heart.`"
And now was the time of the Lord`'s anger, because of sin, showing him, and condemning,
all the evil that ever he had done,
and he became willing to dwell under the Lord`'s judgments,
being convinced that this was the way to obtain mercy;
and now he found that he must cease from the doctrines of men, and hearing the priests,
and repeating their sermons (exercises which he had before delighted in),
and must mind the gift of God within himself,
and sit down among Friends in their silent meetings,
to wait upon the Lord in retiredness of mind,
for his heavenly teachings and holy leadings;
in the performance of which inward worship the power
of God did wonderfully break in among them,
and many were convinced of the inward work of God,
and turned to the Lord with all their hearts;
the Friends in general became very tender and heavenly-minded,
and had great love one to another;
the heart-melting power of the Lord being much felt
and inwardly revealed when no words were spoken;
and they experienced what the apostles exhorted the primitive Christians unto, namely,
Christ to dwell in them by faith,
and the renewings of the Holy Spirit to be increased
and shed on them abundantly in their meetings;
whereby some were so filled that they were concerned to declare,
and preach the things of the kingdom of God, and what he had done for their souls.

Among the rest, this our friend came forth in a testimony for the Lord,
in very great fear and much trembling;
the word of the Lord through him was as a devouring fire against all sin and iniquity,
and he soon became concerned to visit meetings in neighbouring places;
and indeed did spend the prime and flower of his days in the service of truth,
in many years`' travail in the work of the ministry, both in England, Ireland,
and America; before his marriage,
which he did not accomplish till the fortieth year of his age.
He was an able and faithful minister of Christ,
freely given up to go forth in public service in the Lord`'s acceptable time,
preferring truth`'s service before his worldly concerns.
His ministry was powerful and persuasive, and a lively zeal, mixed with love,
attended it, and his labours were successful to the turning many to righteousness:
he had milk for babes, and meat for them of riper years;
was skillful in laying open the mysteries of life and salvation,
as also the mystery of iniquity;
careful not to minister without the heavenly power that first raised him up in the ministry;
profound in heavenly mysteries, yet plain and clear in declaring them;
excellent in distinguishing matters of faith and principle,
to the general satisfaction of the people; a pattern of plainness and humility; and,
although eminently gifted,
chose rather to give way than to stand in the way
of any who had a word from the Lord to speak;
zealous for the due observance of the ancient rules and discipline,
settled in the church by our faithful elders,
maintaining that the order and the government of the church was established
by the same Divine Spirit which the true ministry sprung from;
and that all who speak in meetings for discipline,
should wait to have their words seasoned with grace,
and the influence of that Divine Spirit by which the order
and government of the church was first set up.

He was a man of good natural abilities, but little school literature;
of a grave and reserved deportment, avoiding popularity and imprudent familiarity; yet,
at times, very cheerful in conversation; cautious of giving just offence to any;
not busy beyond his calling.
He was sometimes awfully concerned to speak prophetically
of a time of great mortality approaching,
and did also declare to this purpose,
that the Lord would send his servants into the Popish countries, to preach the gospel,
which should spread and prevail in those dark parts of the earth,
though some might seal their testimony with their blood.

His first visit to Ireland was in the year 1682,
concerning which something singular occurs in his journal,
which seems not unworthy of notice in this place.
Having landed at Dublin, and from there travelled to some other meetings,
particularly the province meeting at Castledermot,
and visited Friends in the counties of Wexford and Wicklow,
and had several heavenly and satisfactory meetings with them, some little time after,
says he, "`the motion of life in me for travelling ceased,
and I dared not then go further; but returned back to the county of Wexford,
and wrought harvest-work at Lambstown for some time; after which James Dickenson,
from Cumberland, came to visit Friends, with an intention to go into Munster,
and the Lord was pleased to open my way to go with him,
and we travelled together in true brotherly love, and had a prosperous journey,
and I saw it was good to wait the Lord`'s time in all things.`"
When they had travelled through Leinster and Munster, James Dickenson went Northward,
but "`I was afraid,`" says Thomas,
"`of running before my true guide (because they who run, and are not sent of God,
can neither profit the people nor themselves) and so I stayed
at work in the city of Waterford about sixteen weeks,
and went from there to Dublin, and stayed at the Half-year`'s meeting,
which was large and very good, and so took shipping and landed at Liverpool,
with my former companion, James Dickenson.`"^
footnote:[See [.book-title]#Thomas Wilson`'s Journal.#]

In the year 1691, he and James Dickenson,
having both had a great exercise on their minds to visit Friends in America,
went to London,
and laid their intentions before the brethren there for their concurrence,
which they readily met with; but it seemed to be a dangerous time,
and was attended with some accidents, which proved a signal trial of their faith:
for the French had then a great fleet at sea,
and while they were at London the rumour was,
that it lay about thirty or forty leagues from the Land`'s End of England,
in the way they should pass.
This brought great concern upon them, with many supplications to the Lord,
that if it were his blessed will they might be preserved.
Under their deep trial of soul on this occasion,
they were both supported by what they believed to be an opening or vision from the Lord,
that it was his holy will to deliver them.
James had a more particular foresight, even of the manner of their deliverance,
and told his companion, while they were both yet at London, that the Lord had shown him,
that the French fleet would encompass them, but that the Lord would send in a great mist:
and darkness between them, in which they should sail away, and see them no more.
They freely imparted their minds to one another before they left London,
and their openings agreeing with one another,
they were confirmed in their belief of their divine origin;
and being strong in faith that it was easy with the Lord to deliver them,
they went on board the 9th day of the Fifth month, 1691, and after some time of sailing,
they met with the French fleet, who gave them chase,
coming up within musket shot of them, and began to fire at them hard,
a broadside at every time,
when on a sudden a great mist and thick darkness
was interposed between the French and them,
so that they could not see one another.
Then James arose from his seat and took Thomas by the hand, saying, "`Now,
I hope the Lord will deliver us;`" having so far seen the completion of his vision.
Thomas, on this occasion,
was exercised three days in fasting and supplication to the Lord,
that he who in time past smote his enemies with blindness, might be pleased to do so now,
which that it was graciously answered, the event convinced them;
for the French took all the ships of their company,
except the ship which T. W. and J. D. were in, and two more;
and all those on board believed the deliverance to be miraculous;
and those two ships of their company that escaped, soon after came up with them,
and the captain of their vessel, being a very kind man,
called to those in the other two ships, to come aboard them,
and have a meeting with them; which they readily did, and had a large and good meeting,
giving glory to the Lord`'s holy name for their great deliverance.
They pursued their voyage, and landed at Barbados in the Sixth month, 1691.

Here, in conjunction with his beloved friend, James Dickenson,
the labours of our friend were great, as also in New England, Rhode Island, Long Island,
East and West Jersey, Pennsylvania, Maryland, Virginia, Carolina, Antigua, and Mevis,
where many were convinced by him:
in some of which places he passed through great perils by sea and land,
lodging out in the woods in the winter season.
This visit was particularly serviceable to the brethren in Pennsylvania,
happening at a juncture when many were staggering in their principles
by means of an opposition and separation made by George Keith,
a man who had been of some note among Friends, a writer of many books,
of reputation for learning, and appearing as a minister,
whose peevish disposition and pride of heart soon appeared to faithful Friends,
and those he called a party against him.
Upon the arrival of our friend and James Dickenson, he endeavoured to gain them, who,
as strangers and worthy Friends, might otherwise be a weight against him;
but it was to little purpose, Thomas soon perceiving the spirit and design of the man,
and the evil tendency of that separation, and stood faithful in his testimony against it,
to the comfort of many who mourned in those times of trial and desolation;
nor was our said friend without a sight of the downfall of that perverse spirit,
as the event discovered, having at times boldly declared it,
and it soon after came to pass.

He visited Ireland in the service of the gospel several
times before he came to settle here.
In the year 1695, he was married to Mary Bewly of Woodhall, in Cumberland,
and soon after came into Ireland, and settled near Edenderry, in the King`'s County.
In the year 1696, he visited Friends in England in the work of the ministry,
and again in Ireland after his return home,
still approving himself a diligent and zealous labourer,
and having meetings in many places among strangers,
of whom some received truth in the love of it, and continued faithful thereunto.
From the year 1697 to 1713, he often visited Friends in this nation and in England,
within which space he was seven times at the Yearly meeting in London;
and in the year 1713, he undertook his second voyage to America, on truth`'s account,
again in company with James Dickenson, in which second visit he had also great service,
and was comforted in seeing the fruit of his former labours.

He continued a zealous labourer in the gospel, even in advanced years,
visiting Friends in England in the year 1721, and at home until the year 1724,
when his natural strength failed; and now, near the conclusion of his time,
he rejoiced that he had served the Lord in his day,
and laboured to promote the truth in his generation;
yet as he always had been a humble-minded man, so with respect to himself,
near the finishing of his Christian course, he said,
"`Notwithstanding the Lord has made use of me at times to be serviceable in his hand,
I have nothing to trust to but the mercy of God in Christ Jesus;`" but he was
not without an evidence of his everlasting peace in the kingdom of God.

In 1726 a general Province-visit was performed in Munster.

Benjamin Holme, who came over to this nation in the year 1724,
spent about two years in the service of the gospel, and continued his labours this year,
having meetings at places where no meetings had been held before, not only among Friends,
but strangers also, who were willing to come to meetings,
and many of them heard him with satisfaction,
and confessed to the truth of the doctrine by him preached.
He had, particularly, several meetings at Cork, a meeting at Kinsale, at Bandon, Ross,
Castlesalem, Skibbereen, and Baltimore; at Dunmanway, in the market-house,
he had a large and pretty satisfactory meeting, notwithstanding Scofield,
the priest of the place, made some disturbance,
though several of his hearers were displeased with him on that account,
and spoke well of the meetings and of what they had heard declared.
At his return to Cork he not only had meetings among Friends, as they fell in course,
but likewise visited most of the families of Friends there,
to their comfort and edification.
He also went Westward a second time, and had meetings at Klonakelty, Timolegue, Bandon,
Mallow, Middleton, Youghal, Tallow, Castlelyons, Capperquin, and Dungarvan,
where many attended and seemed well disposed to hear the testimony of truth.
He had also, for the benefit of strangers, various meetings in the county of Tipperary,
as at Carrick, Fethard, Piltown, Clonmel, Cashel, and Tipperary; went to Limerick,
and there into the county of Kerry, in the year 1725, accompanied by Charles Howell,
and several other Friends from Limerick, from which place they went to Rath-keale,
where they had a meeting among the Palatines and others,
in whom there appeared an open disposition to hear the truth declared;
next had a meeting at Newcastle, and then at Listowell, and at Lixna,
where four Friends went to visit the earl of Kerry, who kindly received them,
and gave liberty to most of his family to go to the meeting.
He likewise told Friends, that if some of them would come to settle there,
they might gain more by their conduct than by their preaching.

Their next meeting was at Ardfert, from which place they passed to Tralee,
and had two meetings there in the courthouse,
where many persons of high station in the world were present,
and truth was freely declared in the demonstration of the spirit,
and to general satisfaction.
He had several other meetings in the county of Cork,
and afterwards in several places in the counties of Kilkenny, Waterford, and Limerick;
and at Ennis, in the county of Clare, where he met with some disturbance from one Upton,
a priest and justice, who came in a furious manner, and demanded of B. Holme,
by what authority he stood there, and commanded the constable to pull him down,
which he did, though with some reluctance,
and conducted him and Friends to the said priest and justice,
whose doings some present resented, and B. Holme reasoned with him, telling him,
that the king allowed liberty of conscience,
and it was hard that his peaceable subjects should be thus treated for no offence committed;
after which he grew cool, and quietly dismissed B. H. and friends,
and Benjamin had good service among the people.

He had many meetings among the Presbyterians in the North.
At Letterkenny he met with some opposition from William Span,
priest and justice of the peace, who sent for him and his companion, John Sharpless,
of Edenderry, and asked Benjamin if he had any letter of recommendation from his Friends;
and he having a certificate from the Friends where he dwelt,
showed it to the said priest, who, notwithstanding this, said he would commit them,
if they would not take the declaration of fidelity to the king,
tendering them that made in the sixth year of the reign of queen Anne, which says,
"`you shall defend to the utmost of your power.`"
They said, they were very free to promise to be true and faithful to the king,
but not willing to promise to defend him to the utmost of their power,
because that might be construed, that they should take up arms and fight if required,
which they could not do; whereupon he, being angry,
wrote court orders and committed them both:
but the landlord and constable persuaded him to let them stay a day or two in town,
before he sent them to the county jail, which was at Lifford, about ten miles distant,
to which he consented; so being prisoners in their inn,
Benjamin wrote a letter next day to Forster, bishop of Raphoe,
acquainting him how they were committed: the bishop read the letter,
and wrote to the said priests who soon after sent for them, and set them at liberty,
upon their taking the declaration of fidelity made
in the second year of the reign of king George,
in which are not the words, "`you shall defend to the utmost of your power.`"

The meetings he had among strangers were generally satisfactory,
peaceable and without molestation, except some few places, and among the rest at Thurles,
where, having appointed a meeting, he met with great disturbance,
chiefly from the Protestant priest of the town, Walter Thomas, who,
as they had grounds to believe,
sent for the kettle-drums and trumpets to beat and sound in the time of the meeting,
to whom Benjamin wrote a letter,
representing to him how opposite such conduct was to a Christian spirit and temper,
and reasoning with him from the Scriptures concerning several
things which the said priest had objected against our friends.
Another instance of the like scoffing spirit appeared at Kildare,
where a meeting having been appointed, while they were at it,
a piper was brought in to play among them.
After some time Benjamin began to speak, and having spoken awhile, Edward Medlicot,
under-sovereign of Kildare, came and ordered the constable to take him away,
and put him with another friend into the stocks, which he did,
and there also the piper was ordered to play,
to prevent the people from understanding what might be said unto them;
nor did he meet with much more civil usage two or three weeks after,
when he appointed another meeting at the same place.

The said B. H. continued his labours here until the Third month National meeting, 1727,
when he returned to England, having, besides his good service in the ministry,
been exercised in visiting the families of Friends, and in private, friendly,
Christian visits, to brethren and strangers,
to both of which he also wrote many epistles,
breathing forth the spirit of true Christian love,
and ardent zeal for the promotion of the life and
power of truth among the professors thereof.
One specimen I shall here give of an epistle of his,
dated at Dublin the 3rd of the Third month, 1727.

[.embedded-content-document.epistle]
--

[.blurb]
=== To the Teachers Among the Presbyterians, that Refuse to Subscribe to the Westminster Confession of Faith.

As I believe in charity that you refuse to subscribe to the Westminster
confession of faith upon a conscientious footing,
I desire that you may live up to what the Lord makes known to you to be your duty;
and I wish that no interest or preferment may ever prevail with you to go against conviction,
or to sin against knowledge:
and as you are sensible that there is great discourse and division
at this time concerning the Westminster confession of faith,
I believe it would be great satisfaction to many well-inclined people,
if you would mention the particular articles in that
confession that you think not safe for you to sign,
with your reasons for not signing.
I confess I am glad that it has pleased the Lord so far to open your understandings,
as to let you see that it is unsafe for you to sign
several things that are in that confession;
as for instance, it says, "`That God, from before the foundation of the world,
predestinated some men and angels to destruction, and others to life everlasting,
and that the numbers are so fixed or definite, that none can be added to the one,
nor diminished from the other.`"
Which is contrary to what Peter says, Acts 10:34-35,
"`Of a truth I perceive that God is no respecter of persons;
but in every nation he that fears him and works righteousness,
is accepted with him;`" as also it is very opposite to what the apostle Paul says,
1 Tim. 2:4, that "`God wills all men to be saved,
and to come to the knowledge of the truth.`"
And I think that in the larger catechism,
where it is said that God has fore-ordained whatsoever comes to pass,
is very unjustifiable; for we read in Jer. 7:31,
"`And they have built the high places of Tophet,
which is in the valley of the son of Hinnom,
to burn their sons and their daughters in the fire, which I commanded them not,
neither came it into my heart.`"
Which makes it plain that this was not fore-ordained.

Also they say in the said catechism, that no mere man, neither of himself,
nor by any grace given, is able to keep the commands of God,
but does daily break them in thought, word, and deed,
which renders God to be a hard master, and his ways unequal,
if what the wise man says be true, Ecc. 12:13, "`Fear God and keep his commandments,
for this is the whole duty of man;`" although we
freely own that no man by his own power and strength,
as he is man, is able to do the will of God or anything that is good,
yet we believe there is power and sufficiency in
that divine grace of which the apostle says,
Tit. 2:11, "`The grace of God which brings salvation has appeared to all men,
teaching us that denying ungodliness and worldly lusts, we should live soberly,
righteously, and godly, in this present world.`"
It was by the sufficiency of this divine grace that the young men that we read
of in the first epistle of John 2:13 knew an overcoming of the wicked one;
and it was by the power of this that the apostle could say,
that he was able to do all things.
We believe, as the Lord said to the apostle when he was buffeted by a messenger of Satan,
2 Cor. 12:9,
"`My grace is sufficient for you;`" there is power in this divine
grace to enable men to resist the enemy in all his temptations,
and to enable them to do the will of God, and keep his commands, as they take heed to it.
And we think that in the confession of faith, where it is said that swearing,
when called before a magistrate, is a part of the worship of God,
is very contrary to the doctrine of Christ and the apostle James, Matt. 5:34,
James 5:12, with some other things in that confession of faith and catechism,
which we think are not agreeable to the holy Scriptures.
So with desires that the Lord may more and more open
your understandings by his holy Spirit,
and bring you to the knowledge of the truth as it is in Jesus, I remain,
with true love to you, your loving friend,

[.signed-section-signature]
Benjamin Holme.

--

The act for the affirmation granted to Friends of this nation in the year 1723, expiring,
solicitation was made for a renewal of it,
which was now granted them for the term of seven years,
and to the end of the then next session of parliament, under this restriction,
that he or she, the affirmer, shall produce a certificate,
signed by six credible Friends,
of their having been of the profession of the people called Quakers,
for at least five years then last past, if thereunto required.

It having been represented from Ulster province to the National meeting,
that the little book entitled, [.book-title]#A Brief Apology,# by Alexander Pyott,
etc. had given great satisfaction to many, particularly among the Presbyterians,
in that province, concerning our principles, with a request that it might be reprinted,
fifteen hundred of them were reprinted accordingly,
in order to be distributed among the people.
This year several Friends of the province of Leinster and Munster, namely, George Rooke,
Thomas Ducket, William Brookfield, Benjamin Parvin, John Russel, Tobias Pim,
Charles Howel,
and William Penrose performed a visit to the Monthly meetings in the province of Ulster,
for the promotion of church discipline,
and several of them also had good service in the ministry of the gospel,
and their visit was to the edification of Friends and their own satisfaction.

Our ancient friend James Dickenson, often mentioned elsewhere,
was at the National meeting this year, and offered to their consideration,
whether it might not be of service to collect the
total annual sufferings of Friends in this nation,
from the beginning; as also an account of the number of prisoners,
and of those who died in prison,
together with the respective governments under which those several sufferings were sustained,
and of remarkable persecutors, and likewise of those who showed favour to Friends,
which proposal was well accepted and put in execution,
and the account printed in the year 1731.

Among other ministering Friends who visited this nation this year (1728) was Jane Fenn,
from Pennsylvania, who besides her good services in the gospel,
both among Friends and strangers, did also, in company with our friend Jane Gee,
of Moate, perform a visit to most of the families of Friends in Dublin.
In our public meetings she sometimes spoke prophetically to the following purpose:
that a terrible storm and distressing time was approaching,
even as at the door of this nation, by reason of a sin,
if not diverted by speedy repentance.
Also, that notwithstanding the seeming degeneracy of the youth among Friends,
God`'s visitation was extended to them,
and should be effectual to the raising up of many of them for his service.

This year also was printed by order of the National meeting, a reply,
wrote by Samuel Fuller, late schoolmaster in Dublin, to certain subtle queries,
published by Joseph Boyce, an eminent Presbyterian teacher,
tending greatly to the dishonour of Friends, and misrepresenting their doctrines,
which are very well answered by the said S. Fuller,
author also of a short catechism composed for the instruction of youth,
afterwards printed in the year 1733.

This was an afflicting year to the province of Ulster,
(1729) occasioned by scarcity of bread, and sickness prevailing among them;
and though our Friends, by the love of subsisting among brethren,
were preserved from being burdensome to others, yet the distribution to the indigent,
both among Friends and others,
being heavy on some in this calamitous time (several Friends having
largely contributed to the support not only of their own brethren,
but of persons of all other societies) a free and voluntary subscription
was made by Friends of Leinster and Munster provinces,
of one hundred and sixty-seven pounds for the relief of Friends of Ulster.

This year, being about the seventieth of his age, died Joseph Pike,
the son of Richard Pike, of Newbury in Berkshire,
who came over to Ireland a corporal in a troop of horse in Cromwell`'s army,
and continued therein until about the year 1655, when,
by means of the ministry of Edward Burrough, he was convinced of the truth,
and for conscience-sake could not use arms for the destruction of man kind,
and was therefore turned out of the army,
and died a prisoner for the testimony of a good conscience.
His son Joseph Pike, was born at Kilcreagh, in the county of Cork;
upon whose tender mind the divine spirit began to work very early,
even before he was seven years old,
drawing it off from childish playfulness and vanities, from which time,
until he arrived at the age of eighteen years, he underwent great conflicts of soul;
and at length grew up to be a useful member of the church,
though never exempt from temptations and trials of faith.
He was a man of self-denial,
being often led to take up the cross and deny himself of things otherwise very lawful,
as to eating, drinking, and putting on of apparel,
when he found his mind too strongly inclined to them.

Although he had not a call to the ministry,
he was eminently gifted for Christian discipline, and zealous in the prosecution thereof,
as by the following instances may appear:
he and Samuel Randal almost constantly travelled
from Cork to attend the Half-year`'s meeting in Dublin,
both summer and winter, for about twenty years,
heartily joining with faithful brethren in the service of truth, according to ability.
He also went frequently to the Yearly-Meeting at London, on the same account,
where his service was acceptable.
He was particularly, in the year 1692, zealously engaged to join with the brethren,
in the concern then upon them,
for a reformation among Friends of several disorders in conduct,
superfluities in apparel, furniture and other things,
that were then creeping in fast upon them: and as he, in conjunction with his brethren,
was careful previously to their entering on this weighty service of admonishing others,
to cleanse their own houses of those superfluities which were to be condemned;
the work accordingly prospered in their hands,
and there was a pretty thorough reformation as to
outward things in the families of Friends,
both in the province of Munster, and throughout this kingdom;
although our friend lived to have cause to complain (in the year 1728,
when he wrote a journal of his own life) that as of old, when Moses, Joshua,
and the elders were dead, there arose another generation that knew not the Lord,
nor the works that he had done in Israel, the like disaster had befallen our society now,
with respect to the spiritual state of a surviving generation,
compared with that of their forefathers.

He wrote a treatise concerning baptism and the Lord`'s supper,
and a discourse concerning church government (yet in manuscript)
wherein he shows the necessity of it,
and its conformity as practised among the people called Quakers,
to that in the primitive times.
I shall conclude with the short sketch of the character of this elder,
given by the brethren at Cork, where he chiefly resided:
"`He was a man of a clear understanding, sound judgment,
tender over the weak where tenderness appeared,
but sharp against the high-minded and stubborn; in conversation solid and weighty,
without affectation, yet cheerful and agreeable without levity; a worthy elder,
ruling his own house well, and of great service in the church.`"

A provincial visit was made to the several particular
meetings in the province of Ulster (1730),
which was well received, and it was believed proved helpful to many.

This year (1731) died Thomas Braddock, at Ballytore, in the county of Kildare.
He was educated a member of the church of England,
but grew uneasy under their forms without the power of religion;
serious considerations concerning a future state, and his unpreparedness for it,
sometimes seizing his mind,
and affecting him with great trouble and earnest supplication to Almighty God,
that he would be pleased to show him his people, that he might join with them,
being persuaded that God had a people that were nearer
to him than those he was then in communion with.
He has left behind him in manuscript,
an account of the exercise of his soul on this account,
of which the following is an extract in his own words.

[.embedded-content-document]
--

As for the Quakers, I thought they could not be God`'s people,
because they denied the two great seals of the covenant of grace as they were called,
so that I thought they being wrong in that, must be wrong in everything else,
though I had a liking to their conversation,
and was inclined to go to one of their meetings, and see what sort of worship they had:
I knew they had no man appointed to preach to them,
and what they meant by their silent meetings, I could not tell.
I went however to one of them, and sat with them about half-an-hour,
when the great power of the Lord came upon me,
and made me fetch many deep sighs and groans, with tears;
and a trembling came over my whole body,
so that I was forced to take hold of the seat on which I sat,
to keep myself from falling.
I was very much ashamed to appear in that condition before so many people,
but I could not avoid it; and then the voice of the Lord came unto me, and said,
"`These are the people you must join with, and if you be faithful,
I will be with you to the end of your days,
and you shall have life everlasting in the world to come.`"
I gave up freely to the heavenly vision, and was willing to obey the Lord`'s counsel;
and the shaking and trouble abated, and I sat pretty quiet until the meeting was ended.
My wife meeting me, asked, whether I had been at a Quaker`'s meeting; I answered, "`Yes.`"
She further queried whether they had any preacher; I answered, "`Yes;
and the best of preachers.`"
She did not know that I had heard the holy Jesus,
but thought that I had been hearing a man.
Then it was that the great work of the Lord began in me,
and the light shined in my heart, and gave me to see the poor, lost, bewildered, dark,
and deplorable condition, that I had hitherto lived in, as without God in the world:
then were many sins brought to my remembrance with great trouble;
and many sorrowful days and nights I passed, with earnest cries to the Lord for pardon,
yet supported at times by the loving visitations of the Almighty,
to let me see that he had not forsaken me.

--

Thus was this our friend made a Quaker by an invisible power,
and by the same power was the work of reformation and sanctification begun in his soul,
and now his prejudices against this people,
as denying the two great seals of the covenant of grace so called,
Baptism and the Lord`'s Supper, vanished; for he calls this blessed exercise of his soul,
his Christian baptism: but now many enemies attacked him, both from within and without,
with rage and passion sometimes, which he overcame with the meekness of a lamb.

In process of time he became concerned, not only for the salvation of his soul,
but was sometimes seized with great trouble, trembling, and tears,
on the account of the unfaithfulness of others, particularly in meetings for worship,
where words did arise very lively in his mind,
tending to the edification of those present, which it seemed to be his duty to deliver;
but he, through weakness, refusing to yield obedience to the heavenly call,
the divine presence was for a time withdrawn from him, and he left barren,
and at times given up to lightness;
yet it pleased God in great mercy again to visit his soul, and let him see his error;
and indeed this our friend was a most signal instance of
the tender mercy and long forbearance of a gracious God;
for in the year 1725, even in his old age,
and about eighteen years after his disobedience before-mentioned,
a fresh concern came upon him to utter some words in a public meeting,
in testimony to the Lord`'s goodness to his soul,
and rending to the awakening the carnal professors among Friends.
This second trial, however, was to him almost as hard as death,
being a man of great humility and modesty, conscious of his own weakness,
and tossed with many doubts, fears, and carnal reasonings,
and greatly distressed both in body and mind.
At length, however, he gave up to the Lord`'s requirings,
and delivered what he gave him to say, to the great peace and comfort of his own mind;
and after that, until his death,
was at times concerned in public exhortation in a few words, but weighty, seasonable,
and edifying; and his conduct was suitable to his doctrine.

About the latter end of this year (1735) our solemn affirmation (without a certificate,
as required by the former act) was renewed for eleven years,
and to the end of the then next session of parliament.

Besides other Friends of the ministry,
Benjamin Holme this year visited Ireland the sixth time:
he spent three months in the province of Ulster,
having meetings there among strangers as well as Friends,
and after the Third month National meeting, went into the province of Connaught,
and returned by way of Sligo, Ballystrannon, and Letterkenny, to Londonderry,
having many quiet and peaceable meetings among other people,
being often drawn forth to visit them, and open our principles to them,
and declare the great love and mercy of God,
in sending his Son to taste death for every man.
From Ulster he went, by way of Dublin, to Limerick, accompanied by some Friends,
and from there to the county of Kerry, particularly to Lixnaw, the earl of Kerry`'s seat,
to Ardfert, Tralee, Coole, and Dingle,
and had several meetings among the people in that county, who,
though many of them were great strangers to Friends and their principles,
showed themselves friendly and respectful,
especially the Protestant gentlemen of the country,
who sometimes protected them from the rabble; in general they were well received,
and Benjamin was heard with great satisfaction, in his plain, clear,
and demonstrative way of preaching the doctrines of the gospel and terms of salvation.
At Mill-street, where the congregation was for the most part of the worse sort,
when they heard a hint of purgatory, several of them rose and went off, crying,
"`Glaush,`" i. e. "`Come away.`"
From there he returned to Cork and to Waterford, where he visited the bishop,
as he had done before the bishops of Londonderry, and Down, and Conner,
etc. who received him very kindly, and to some of the bishops he wrote letters,
and sometimes presented them with books, as the [.book-title]#Treatise on Oaths,# another on tithes, etc.
He departed from here, and returned to Great Britain, in the Twelfth month, 1736,
leaving to Friends of this nation a farewell epistle.

It was observable this year (1736) as well as for some years past,
in time of outward peace and tranquility,
that many of other societies frequently resorted to Friends`' meetings,
whose understandings were opened,
and their prejudices removed with regard to Friends principles,
so that it may be affirmed that the testimony of truth prevailed,
notwithstanding the degeneracy and unfaithfulness of too many under this profession,
who were as stumbling blocks in the way of some.

This year, being about the seventy-fourth of his age, died William Gray,
at Ballyhagen in the province of Ulster, a worthy elder,
whose services in the church were considerable for above thirty years,
although not called to the ministry till towards the latter part of his life.
He was given to hospitality, of a grave and solid deportment,
of a good understanding and a ready utterance, yet modest,
and diffident of his own abilities, helpful in composing of differences,
and often speaking pertinently to matters in meetings of business,
being well acquainted with the rules of our discipline.
He grew in his concern for the prosperity of the church,
as he advanced towards the period of his days, being, six years before his decease,
concerned at times in public and tender exhortation, and in meetings for business,
seldom omitting to advertise Friends to faithfulness, care, and circumspection,
in an orderly conduct, and diligence in the worship of Almighty God.

Among other Friends who visited the nation this year (1737) in the work of the ministry,
was David Hall, from Yorkshire, who at his departure, wrote an epistle to Friends,
which was ordered to be printed for a general service,
containing several weighty advices suitable to the different
stations of the several members of the church,
and cautions against some evils and disorders too much prevailing
in this time of our outward ease and liberty,
particularly negligence of attending meetings for divine worship,
living above our abilities, deviating from the plain language,
marriages with persons of other persuasions, etc.

This year also afforded an opportunity of reviewing and digesting those several matters,
which have been the usual subjects of the correspondence
between Monthly and Quarterly meetings,
which, being reduced to the form of queries,
were offered to the consideration of a Quarterly meeting held at Mountmellick,
and from there to the National meeting, which in the year 1740,
recommended them as proper to be answered from the several
Monthly to the Quarterly meetings through this nation,
a copy of which follows, etc.

[.numbered-group]
====

[.numbered]
_Query_ 1. Are meetings for worship, both on week-days and First-days, duly attended,
as also those for discipline; and are such as are negligent herein admonished;
and is care taken that no unfit persons sit in the latter?

[.numbered]
2+++.+++ Do the larger meetings assist and strengthen little meetings that are near them?

[.numbered]
3+++.+++ Do Friends keep to plainness of habit, speech, and furniture?

[.numbered]
4+++.+++ Do they avoid superfluous provisions at marriages and burials?

[.numbered]
5+++.+++ Unnecessary frequenting of ale-houses and taverns?

[.numbered]
6+++.+++ Do they so manage their affairs in trade and dealing,
as to keep their words and promises in the payment of their debts and otherwise?

[.numbered]
7+++.+++ Do Friends avoid encumbrances, hindering their growth in the truth,
and the service of it?

[.numbered]
8+++.+++ Are Friends in unity one with another; do they avoid back-biting,
and raising or spreading evil reports of any; is care
taken to put a speedy end to all differences?

[.numbered]
9+++.+++ How are the several advices of our National meeting, and that of London,
put in practice,
relating to Friends`' godly care of the good education
of their children in the way of truth,
sobriety, plainness of habit and speech, and all godly conduct;
and do Friends instruct their children in the principles of truth?

[.numbered]
10+++.+++ Are Friends`' children put to school among Friends,
and are the schools of Friends duly inspected?

[.numbered]
11+++.+++ Are the poor taken due care of,
and do their children partake of necessary learning to fit them for trades?
Are apprentices and servants placed out among Friends?

[.numbered]
12+++.+++ Does each Monthly meeting take care,
that a visit to the families of Friends be performed by well qualified Friends,
once a year, or oftener, as occasion requires?

[.numbered]
13+++.+++ Do Friends acquaint particular or Monthly meetings, and take their advice,
before they remove from their place of settlement?

[.numbered]
14+++.+++ Do Friends maintain their testimony against paying or receiving tithes, church-rates,
and all kinds of priest`'s dues so called; as also against bearing of arms?

[.numbered]
15+++.+++ Do any propose marriage without first obtaining the consent of parents or guardians?

[.numbered]
16+++.+++ Is care taken to deal with and censure transgressors in due time?

[.numbered]
17+++.+++ Have all Friends settled their outward affairs, by wills or deeds of trust,
according to their present minds and circumstances?
Is care taken that executors, guardians, and trustees,
do faithfully discharge the trust reposed in them?

[.numbered]
18+++.+++ Are all meetinghouses and burial-places firmly made over and secured,
and kept in good repair?

[.numbered]
19+++.+++ Are births and burials duly recorded?

[.numbered]
20+++.+++ Does each Monthly meeting take care that none
under our profession defraud the king of his duties,
custom or excise, or any way encourage the running of goods,
by buying or vending such goods;
and do they severely reprehend and testify against all such offenders,
and their unwarrantable, clandestine, and unlawful actions?

[.numbered]
21+++.+++ Is care taken by each Monthly meeting, that no misuse is made of the affirmation?

====

A general visit was performed this year to all or most of
the men and women`'s meetings in the province of Leinster.

In the year 1739, and eightieth of his age, died John Dobbs, at Youghal,
who although not called to the ministry,
was such a shining example of sincerity and self-denial,
that the following passages of his life seemed worthy to be recorded.

He was the eldest son of Richard Dobbs of Castle-Dobbs, who was a counsellor at law,
and justice of the peace of the county of Antrim,
from whom he was entitled to a considerable estate,
of which he suffered himself to be deprived purely for religion`'s sake.
He gave several proofs of an early disposition to piety,
some of which it may be worth while to specify.
When he was about eleven years old, a certain person asked his father,
the said Richard Dobbs, what he intended to bring his son up to; his answer was,
to the clergy, and he did not know but Johnny might come to be a bishop.
The child hearing this, says within himself,
"`It is a great concern to take the care of other men`'s souls upon me;
it is well if I can look well after my own.`"
At school he made some considerable proficiency in the Latin and Greek tongues,
and afterwards applied himself to the study of medicine;
but during this time a holy thirst possessed his soul after a knowledge of greater importance,
whereby he might obtain peace with God.
He was grieved with the loose conversation of his companions at school,
and upon some converse with the gentry of the country,
their tipling disposition became burdensome to him, and he deserted them.
He went afterwards to the university of Oxford,
from a desire to enquire further into the principles of true religion; but,
in his road to it,
he met with a somewhat discouraging observation from a certain
person he casually fell in company with at York,
who remarked that there were many gentlemen in the country,
who were afraid of sending their sons there lest they should be debauched.
He found there was too much ground for this observation, for when he came to Oxford,
he was much grieved at the profaneness of the students there,
and at first put himself in the way of conversing with them,
with a design to use his best endeavours to reform them,
but found this to be labour lost; and, to be brief,
was not easy to stay long at the college,
but obtained liberty of his father to return home.

He had an esteem for the people called Quakers,
from his observation of the innocency of their lives and conducts among men;
and his mother, Dorothy Dobbs, having joined herself in community with this people,
he had an opportunity of perusing several books written by some of them;
but before the nineteenth year of his age,
he had proceeded no farther than to entertain good wishes for them,
his father having threatened to turn any of his children
out of doors that should go to their meetings;
not withstanding which, in a short time after,
being desirous of hearing their testimony himself, and an English friend, Thomas Dockra,
visiting Carrickfergus, and having a meeting there, John went there,
and before that meeting was over,
was so effectually convinced of the truth of their testimony, that he, from this time,
continued stedfast in community with that people.
This was very disagreeable to his father, who endeavoured, first by persuasion,
to bring him off from that way of thinking; but this proving ineffectual,
he had recourse to blows, and other great severities,
which he exercised on this tender youth, which he bore with great patience and constancy;
particularly in keeping him prisoner in his house about half a year, in 1683 and 84,
during which confinement, at a certain time meeting him with his hat on,
he fell furiously on him, and beat him grievously on the head with a cane,
to that degree, that he fell into a fever from it,
nor did he ever entirely recover the injury thereby received.
Besides this, he deprived him of his right in his estate, which in the year 1681,
was three hundred and sixty pounds per annum,
leaving him by will only ten pounds per annum
during life, to keep him, as he said, from starving, or relying on those seducing people.
But all this could not taint his integrity.
His mother dying while he was young,
who had been his constant friend and support under his hardships,
his father would not see him, nor suffer him to come into his presence;
and so having none to support him, and there being no likelihood of a reconciliation,
he was necessitated to leave his father`'s house,
and went to England and learned chemistry with Charles Marshal,
and making further progress in the study of medicine, he returned to Ireland,
and practised it here with reputation, and lived and died in strict unity with Friends,
being an innocent and religious man, one that avoided popularity,
was more in reality than appearance,
and cared not how little noise the world made about him,
so that he enjoyed peace with God.

In the year 1739, being the sixty-fifth of her age,
and about the forty-second of her ministry, died at Waterford, Elizabeth Jacob,
the daughter of Thomas and Agnes Head, who was born at Ardee;
and afterwards lived in Dublin, where she underwent many and deep conflicts of soul,
before she became resigned to the Lord`'s requirings in bearing a public testimony,
which she did first in that city about the year 1697, and in the year 1699,
was joined in marriage to Richard Jacob of Limerick, to which place she removed,
and was of great service there, being, through her obedience to the heavenly call,
made a chosen vessel for the use of her Lord and Master,
fitted by his power and spirit for his work and service;
in the discharge of which she greatly desired to
be found faithful and clear of the blood of all men,
being fervently engaged for truth`'s prosperity,
and the promotion of godliness in the earth,
on the account whereof she was freely given up to
spend and be spent in many laborious journeys,
both in this and other nations, not only in her youth, but even in her advanced years,
and when attended with bodily infirmities; particularly in the year 1701,
she travelled in the North of Ireland, from there passed over into Scotland,
and had good service there and in the North of England.
Again, in the year 1705, she visited Friends in various counties in England,
and was twice at London, where she had large and satisfactory meetings.
And in the years 1711 and 1712, she visited Friends in Scotland,
and in many parts of England and Wales, for above ten months,
and by the Lord`'s power was made an instrument of good unto many; and in the year 1729,
she visited Friends in various counties of England,
and passed over to Holland in truth`'s service.

She had a clear and distinct utterance in her ministry,
which was attended with great reverence and tenderness,
to the reaching the hearts of the hearers,
and continued lively in the exercise of her gift to the last.
She was fervent and weighty in prayer, and a good example in conduct,
being preserved by the truth in circumspection and fear,
yet of a sweet and cheerful spirit.

In the year 1712 she wrote, from Worcester, an epistle of love to Friends in England,
which was printed and contains a farewell exhortation to Friends`' families,
wherein she addresses herself first to the elders, setting forth that,

[.embedded-content-document.epistle]
--

Whereas there is a great declension from the primitive plainness, simplicity,
and sincerity, into which truth led our faithful predecessors,
this is owing to the prevalence of the spirit of the world, pride, covetousness,
self-interest, and fleshly ease; and, in order to a reformation,
earnestly exhorts such who are fathers and mothers, and as pillars in the church,
carefully to observe the operation of the Lord`'s holy Spirit,
and to be often inwardly attending on the wonderful counsellor,
whereby they will be enabled to set up a holy discipline in their own families;
and that this godly care in families is the only
expedient for a right reformation in the churches:
that it is not enough for the elders, fathers, and mothers, masters and mistresses,
who have in any measure tasted of the good word of life,
and of the powers of the world to come,
carelessly to retain a knowledge of what they have experienced in times past;
that God has not lit their candles to be put out again or to be hid under a bushel,
but that they ought daily to wait upon and supplicate
the Lord for the renewing of his love and life,
that their lamps may be kept trimmed and their lights shining,
and they be a sweet savour of life unto life,
their conduct answering the witness of God in the hearts of their children, servants,
and neighbours,
stirring up the negligent to a lively commemoration of the Lord`'s mercies,
and exercising their Christian authority,
in the management and settlement of their own families in that decent order we,
through the mercy and wisdom of God, have been established in:
thus will parents be good examples to their children, and masters to their servants;
and that indeed the heads of families are, or ought to be, the Lord`'s ministers,
ruling them in the power of love, and thereby ordering them rightly in life and manners.

--

[.offset]
And she concludes with this warning to the unfaithful,

[.embedded-content-document.epistle]
--

That if the love of God to them, through his spirit and through his servants,
will not prevail, the Lord will be clear when he judges,
as he was in the destruction of the old world, and of the cities of Sodom and Gomorrah.

--

She next tenderly addresses herself to the children,
cautioning them against various evils, dangers, and temptations, peculiar to their age,
as pride or affectation of new fashions in apparel,
while the adorning of the better and immortal part is neglected;
as also against the needless friendship and familiarity
with those of a different persuasion in matters of faith,
whereby many have been betrayed into unequal marriages, to the wounding their own souls,
great trouble of their tender parents, and the destruction and ruin of many families.

A provincial visit was this year (1740) performed in Ulster.
And here it may be observed, upon a review of the foregoing records,
that in the province of Ulster, general visits to that province,
and for the most part to the several monthly meetings therein,
were performed in the years 1699, 1702, 1705, 1706, 1707, 1720 or 21, 1727, 1730,
and 1740.
In the province of Leinster the like general visits were performed in the years 1699,
1707, 1711, 1714, 1720 or 21, 1725, and 1737.
In the province of Munster the like general visits were performed in the years 1699,
1708, and 1726.

This year (1741) and in the eightieth of his age, died John Ashton, of Kilconinmore,
in the county of Tiperary, though a native of Cheshire, who,
about the fortieth year of his age,
was convinced by the lively ministry of Thomas Wilson;
and soon after his convincement was cast into prison,
on account of his faithful testimony against the payment of tithes,
and continued a prisoner about six months.

His zeal for the worship of Almighty God was remarkable;
for while he was a member of the meeting at Birr, he generally walked there twice a week,
though it was five miles of dirty road,
and he was often obliged to wade through a river in his way,
and sometimes in winter time to break the ice,
by which his legs and feet have been wounded.

His zeal also for the propagation of truth, and love to the souls of his neighbours,
was manifest in the following instance;
that when Friends travelling in the service of the gospel, came to his house,
he took great pains to invite the people near him
to come and partake of the benefit of their labours;
for which purpose it was his frequent practice to ride several miles round,
and this in the night as well as day,
and even in the depth and severity of the winter season;
and though some returned scoffs and abusive speeches,
yet many came and were well satisfied, and some convinced,
and among the rest some of his own servants;
and a meeting was settled at his house in the year 1710, which still continues.

He was a man of hospitality, and of a tender spirit,
sympathizing with the poor and afflicted.
About the sixty-second year of his age, he received a gift in the ministry,
in the exercise of which he was particularly zealous in testifying
against the follies and vanities incident to youth,
with respect to a conformity to the never-settled fashions of the times.
In the year 1733, he with another friend, visited Friends in sundry counties in England,
as also in North-Britain.

This year died at Dublin, Joseph Gill, born at Skelton in Cumberland, in the year 1674,
the son of William Gill, from whom he received a religious education,
which with the concurrence of the divine blessing, and his own endeavours,
was greatly improved to his spiritual advantage.

He manifested an early zeal for the worship of Almighty God,
in preference to the pursuit of worldly gain;
and when his outward business increased and prospered, was seized with a holy fear,
lest the multitude thereof should obstruct the spiritual
exercise and engagement of his mind,
for the acquisition of heavenly riches.

In the early part of his life,
he frequently accompanied ministering Friends in
their travels through several parts of this nation,
and met with great consolation and encouragement in so doing.

In the year 1709, he was led to settle his outward affairs and lessen his business,
in pursuance of a secret impression then made on his mind,
that he ought to be at leisure to follow the Lord as he should be pleased to lead him,
being resigned to what he believed to be the divine will concerning him;
though at this time he had no distinct perception of his being called to the ministry.
However, in the year 1711, being the thirty-seventh of his age,
his mouth was first opened in the assemblies of the people called Quakers,
but with great fear and concern of mind, by reason of various suggestions of the enemy,
which in process of time were overcome,
and he proving faithful to his sense of the divine requirings, grew in his gift,
and became a diligent and zealous labourer therein,
to the edification of the churches both at home and abroad.

In the year 1711 he visited the meetings of Friends in Ulster province,
in company with Richard Sealy, when, at Coothill,
James Sympson (who was bred a scholar and intended for a Presbyterian teacher) was convinced,
who became a serviceable man,
and suffered imprisonment in Cavan jail for his testimony against tithes.

In the year 1713, he had drawings in his mind to visit Friends in Ulster province again,
but not having a companion, and not deeming himself strong enough,
waited until the arrival of Luke Cock, a ministering friend from England,
and accompanied him in his travels to that province.
After this he very frequently performed visits in the work of the ministry,
to meetings in Leinster, Munster, and Ulster, and some times in Connaught,
where he had also meetings among strangers; and besides these visits at home, he,
at different times, visited Friends in various parts of England and Scotland,
and in the year 1714, in the Isle of Man; and in the 1734,
he took a voyage to America on the same account,
where he travelled five thousand five hundred and seventy-two miles,
and was at three hundred and eighty-two meetings.

He was diligent in attending the meetings of discipline, as well as worship,
and not only those at home, but particularly the Yearly meeting at London;
and from the year 1712 to 1741 inclusive, was thirteen times at the said Yearly meeting.

He was a man of exemplary life and conduct, and given to hospitality.
As he drew near the conclusion of his days, he had this comfortable reflexion to make,
that he had preferred the service of truth before the business of this world;
and declared,
that although he had several opportunities of enlarging his temporal possessions,
he dared not embrace them,
lest he should thereby be hindered from the discharge of his spiritual duties.
He also signified his sense, that although the church was now in her sable weeds,
and mourning seemed her present portion,
yet that he believed the Lord would cause Zion to shine and become the beauty of nations.
He died in a devout frame of mind, in this the sixty-seventh year of his age,
and thirtieth of his ministry.

This year died at Dublin that honourable elder and minster George Rooke,
the son of Thomas Rooke, born in the parish of Boulton in Cumberland.
He had been educated in the church of England, but about the twentieth year of his age,
being convinced of the truth of the doctrine preached by John Greaves,
a minister among the people called Quakers, he joined himself in society with them,
and proving faithful, according to his sense of his duty,
about the twenty fifth year of his age,
his mouth was opened to declare unto others his own experience of the Lord`'s goodness,
and he became early engaged in travelling abroad in the work of the ministry,
zealously and cheerfully devoting his strength and
youthful days to the propagation of the gospel,
and promotion of truth and righteousness in the earth; particularly in the year 1679,
he travelled on foot to Scotland on this account, accompanied by Peter Fearon.

In the year 1681, he visited Friends in all their meetings in Scotland a second time,
and the same year came to Ireland and visited most
of the meetings of Friends through the nation,
as he did also in the year 1684, and some time after his return,
visiting Friends in Westmoreland, and bishopric, he had a meeting at Stockton,
where the mayor of the town sent one of his officers to bring George before him,
and when he came, tendered him the oath of allegiance and supremacy: but because George,
for conscience-sake, refused to swear,
the mayor would have had him enter into bonds for his good behaviour,
and to appear at the next quarter-sessions: George told him,
he was bound to good behaviour already.
"`Have you been with some justice of the peace that has bound you already?`"
said the mayor.
"`No,`" said George,
"`but I am bound by my principle to behave myself towards
the king and all his subjects as becomes a Christian.`"
"`But for all that,`" said the mayor, "`you must enter into bonds.`"
"`I cannot,`" said George, "`for I believe you will call that a breach of good behaviour,
which I think is good behaviour.`"
"`What is that?`" said the mayor. "`I suppose,`" said George,
"`you will call it a breach of good behaviour,
if I go to one of our meetings before next quarter-sessions?`"
"`Sure enough, I shall,`" said the mayor.
George said,
he would not bring any of his friends into that snare to leave them bound for him.
"`It is but about a month,`" said the mayor, "`to the sessions,
and cannot you forbear going to meeting so long?`"
`"No,`" said George, "`if the Lord spare me health,
I can no more forbear going to meetings, than Daniel could forbear praying to his God,
although the decree was but for thirty days.`"
So the mayor committed him to Durham jail, where he was kept prisoner till the sessions,
when he was again committed and kept prisoner about a month longer,
because for conscience-sake he could not swear.

In the year 1685, he visited Friends in Ireland a third time, and again in 1686,
when he married and settled in Limerick; yet still continued laborious,
and frequently travelled abroad in the exercise of his gift,
for the edification of the churches;
and indeed his ministry appears to have been clear and convincing even among strangers,
of which an instance occurred in his travels through Wales, where,
at a meeting he had at Haverford-west, one of his hearers,
who had a right of the presentation of a parish called St. David`'s Head,
was so far affected by his preaching as to make him an offer of it;
but he was not one of those ministers who seek for reward or support from men.

He continued his habitation in Limerick in the years 1689 and 90,
in the troublesome times of the wars between king William and king James,
and during the first siege; but before the second siege,
while king James`'s army had possession of the city,
he removed himself and family to Cumberland; but not withstanding these troubles,
he still continued laborious and fervent in spirit, in visiting the meetings of Friends,
and in the year 1692, again visited the brethren in Scotland.

In the year 1693 he returned to Ireland, settled,
and continued his residence in Dublin the remaining part of his life, during which time,
while of ability, he frequently visited Friends in the three provinces,
and sometimes had meetings in places where no meetings of Friends were settled:
he also sometimes visited Friends in England and Wales,
and was frequently at the Yearly meeting of London.
He was a very diligent attender of meetings for worship, and those for discipline,
and was scarce ever absent (unless when engaged in travelling elsewhere
in truth`'s service) from the Province and Quarterly meetings,
until disabled by infirmity of body.

He was a man of good understanding, though but little school-learning; of a sweet temper;
in conversation pleasant and affable; an affectionate husband and father;
a tender and sympathizing visitor of the sick: he was a diligent and faithful minister,
and his labours were often crowned with success, to the convincement of several,
who proved eminent and serviceable men in the church,
and the edification and establishment of others.
In the exercise of his gift he was clear, solid, and lively, even unto extreme old age;
in prayer, living, reverent, weighty, and concise.
In his deportment meek and humble, not elevated by his gifts and good services;
far from being desirous of exercising lordship over God`'s heritage,
frequently declaring, that he did not judge ministers to be of an order above other men,
and that he and all others in the ministry,
ought willingly to refer their doctrines to the divine
witness in the consciences of their hearers.
He was a diligent reader of the holy Scriptures,
and in his preaching a faithful quoter of them.
He retained his integrity, as well as understanding and memory to his end,
and departed this life in the ninety first year of his age,
and about the sixty-seventh of his ministry,
and appears be the most ancient minister mentioned in these records.

This year, there being apprehensions of an in tended invasion of England from France,
Friends drew up an address to the king,
signifying their fidelity and good affection to his person and government,
which was as follows:

[.embedded-content-document.address]
--

[.blurb]
=== To George the Second, King of Great Britain and the Dominions Thereunto Belonging. The humble Address of his Protestant Subjects, the People called Quakers, in the Kingdom of Ireland.

We your dutiful and peaceable subjects,
with hearts truly sensible of the many blessings and privileges
we enjoy under your paternal care and protection,
beg leave at this critical conjuncture,
when your dominions are threatened with an invasion in favour of a popish pretender,
to express our sincere and hearty abhorrence of all plots
and conspiracies against your person and government.

Duty, gratitude, and interest,
unite to engage us in a firm attachment to your royal person,
and the Protestant succession in the illustrious house; and we are determined,
by divine assistance, to continue unshaken in these sentiments,
and conformable to our known principles to do the utmost in our
power for promoting the peace and welfare of this nation.

The kind indulgence granted us by the legislature in our religious scruples,
the free access we have had to the several chief governors
of this kingdom since your accession to the throne,
and the readiness shown for our relief,
whereof we retain the most grateful and lively sense,
lay us under additional obligations of duty and fidelity.

May the same divine Providence that defeated the attempts of the enemies of our constitution,
in the rebellion against your royal father,
and which has lately protected you in imminent danger,
preserve you and your royal family from the wicked designs of all your enemies,
whether foreign or domestic.
May the Almighty guide your counsels by his wisdom,
and render them effectual for the reestablishment of peace and tranquillity,
and grant you a long and prosperous reign over us.
May the British throne be always filled with one of your royal offspring,
to transmit the blessings we enjoy to future ages.

Signed in Dublin, in behalf of the said people, the 31st of the First month,
called March, 1744, by

[.signed-section-signature]
John Barclay, Peter Judd, Henry Pemberton, Daniel Bewley, Edward Fawcett, Joseph Fade,
James Johnston, John Rutty, Samuel Judd, Benjamin Dawson, Paul Johnson, Robert Clibborn,
Francis Russell, Thomas Strettell, jr., Robert Unthank, Jacob Ford, Robert Jaffray,
Joseph Barcroft, John Goulbee, Robert Gill, Jonathan Strettell, John Dawson,
Ambrose Barcroft, Samuel Sharpley, William Greenhow, Thomas Chandley, John Barclay,
jr., Joshua Clibborn, Edward Stephens, Lancelot Whitehead, John Powel, Aaron Atkinson,
Isaac Ashton, Thomas Handy, Issachar Willcocks, Joseph Willcocks, Gherret Hassen,
Henry Aflie, John Willcocks, Samuel Russel, Thomas Goulbee, Samuel Morton,
Samuel Summers, John Beetham, Jonathan Fletcher, Joseph Green, Abraham Robinson,
William Willan, Isaac Jackson, Richard Pearce, John Pim, Jacob Goff, William Richardson,
James Forbes

--

It is worthy of observation,
that while the neighbouring kingdom of Great Britain
was disturbed both with a foreign war,
and a rebellion at home, this nation,
under the prudent administration of our chief governor, enjoyed a profound peace;
and at the same time we were favoured with the visits
of several worthy brethren and sisters in the ministry,
some from Great Britain and others from America,
who crossed the seas in this service at the hazard of their lives.

Also, whereas the act of parliament for granting Friends an affirmation in all,
except criminal cases, and for qualifying for places of profit and trust,
and serving on juries, which was passed in the year 1736, was only temporary,
and to expire at the end of the ensuing session of parliament,
the present time was thought convenient to make early application
for a renewal of the said act without limitation of time,
in the same manner as Friends elsewhere enjoy it.
Therefore the Friends who attended the last Yearly meeting at London,
did there wait on the earl of Chesterfield, the lord lieutenant,
requesting his advice and friendship in our intended solicitation,
which he with great cheerfulness granted them, and on his arrival here,
encouraged Friends to petition the House of Commons this session,
for such an act as aforesaid, which they accordingly did with good success,
for it passed both houses, _nemine contradicente,_ and obtained the royal assent.^
footnote:[See the Year 1721.]

Besides other ministering Friends at home,
who visited Friends this year (1744) Gherret Hassen
performed a visit to them in each province,
not only in their public meetings, but in their families, having in this service visited,
by estimation, three thousand families and upwards, exclusive of those in Dublin,
where he had resided some years.

This year died Mungo Bewley, son of Thomas and Margaret Bewley,
of Woodhall in Cumberland, from which place he came over to this kingdom,
and settled at Edenderry, in the King`'s County.
He was favoured in his youth with a tender visitation of the love of God,
and manifested early a fervent zeal for divine worship in the following instance:
among his papers was found one which he wrote during the time of his apprenticeship,
requesting of his master either to have his work previously allotted to him,
in order that he might make preparation against the time of the week-day
meeting or that he might be allowed when his apprenticeship expired,
to pay for so much time as he should have spent at meetings:
and he grew and prospered in the saving knowledge of the truth accordingly,
and not long after his coming over to Ireland,
a dispensation of the gospel was committed unto him, whereof he became an eminent minister,
freely devoting himself to spend and be spent for the promotion of piety in the earth,
being diligent in the exercise of his gift both at home and abroad,
having visited Friends in the service of the gospel in England, Scotland, Wales, Holland,
and America.

He adorned his ministry by a grave and solid behaviour;
he was also a man of good understanding,
zealous in Christian discipline and serviceable in visiting the families of Friends;
a man of integrity and firmness, industrious in business, upright in his dealings,
and careful in the religious education of his children;
cheerful and edifying in his conversation; compassionate and liberal to the afflicted;
a nursing father to young travellers in the way to Zion;
yet not hasty to lay hands suddenly on such as were more in show than substance,
being of a discerning spirit; and not withstanding these good qualifications,
he was very humble-minded with respect to himself.

He continued lively in the exercise of his gift to the last,
finishing his Christian course in the seventieth year of his age,
and about the fortieth of his ministry.

This year died at Cork, George Bewley, a faithful minister and elder,
his conduct and conversation having been agreeable to his doctrine.
He was careful to keep free from the encumbrances of this life,
and zealous for the support of good order and discipline in the church.
A narrative of his life was published, by the approbation of the National meeting,
in the year 1750.
